### ISSUE TITLE
[Feature Request] Import cert from tls.secretName into ACM

### ISSUE THREAD

**Issue by tcolgate** [kubernetes-sigs/aws-load-balancer-controller#1084]
Hi,
  It looks like ACM now permits importing certificates via the API, I'm pretty sure this has been missing previously.
  Would you be interested in a PR to sync secrets to ACM? I've started working on it under the assumption that you would (didn't see any existing PRs).
  My current plan is:
- if tls.secretName is set, try and pull a cert, key and certchain from the secret, following format of the secrets used by CertificateManager.
- if all are good, import that cert, if that works, add an annotation to the secret to indicate the ARN
- keep a cache of hashes of some of the cert info (isuer, issued at and issued by), and compare those with the related info from ACM, use those to indicate if an update is needed.

**Comment by tcolgate** [comment]
I've started digging around the code a little. It's a bit more heavy going than expected. I'm going to have a poke at it, but it's not going to be quite as quick as expected (may not be able to give it high priority as we can, for now, manage with manually managed ACM certs)

**Comment by M00nF1sh** [comment]
@tcolgate 
Actually i had an [PR](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/836) for this but closed it.
The main reason is ACM only allows u to import like 10 certs per year(total imports instead of active imported cert), which basically makes it an unusable feature.

seems they changed to 1000 now....

**Comment by gmauleon** [comment]
Nice!
FYI, related issue on the certmanager side https://github.com/jetstack/cert-manager/issues/2302

**Comment by alejandrox1** [comment]
adding some labels to make this more discoverable to others -the idea sounds good
also, here are the docs I could find regarding the limit of 1000 https://docs.aws.amazon.com/acm/latest/userguide/acm-limits.html

/kind feature
/priority important-longterm

**Comment by tcolgate** [comment]
A lot of the AWS limits can be raised with service requests, though I've not looked at cert limits I must admit.

**Comment by tcolgate** [comment]
@M00nF1sh that looks very promising.

**Comment by Morriz** [comment]
@M00nF1sh can you maybe pick up that closed PR? Would be awesome to just mention a list of secrets in an ingress annotation so that they get synced with ACM, and their ARNs added to the `alb.ingress.kubernetes.io/certificate-arn` list.

**Comment by vainkop** [comment]
Any updates on using cert-manager let's encrypt certs + alb + eks?

**Comment by marcellodesales** [comment]
Looking for the same here... Any progress with `lestencrypt` + `cert-manager`

**Comment by M00nF1sh** [comment]
@marcellodesales 
I'll put this into our backlog, we should be able to work on this post reinvent.

**Comment by vainkop** [comment]
Sharing my not very elegant but working hack for Cert-Manager Let's Encrypt certs + ALB + EKS using a combination of kubectl & aws cli:

1) Use the following cluster issuer to get the certificate into the k8s secret:
ClusterIssuer.yml:
```
kind: ClusterIssuer
apiVersion: cert-manager.io/v1
metadata:
  name: prod-clusterissuer
spec:
  acme:
    privateKeySecretRef:
      name: prod-clusterissuer
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    solvers:
      - http01:
          ingress:
            class: alb
            ingressTemplate:
              metadata:
                annotations:
                  alb.ingress.kubernetes.io/scheme: "internet-facing"
                  alb.ingress.kubernetes.io/listen-ports : '[{"HTTP": 80}]'
                  alb.ingress.kubernetes.io/group.name: "group1"
```
2) Deploy the app using Helm:
app-helm-values.yml (only relevant part):
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/listen-ports : '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/group.name: "group1"
    external-dns.alpha.kubernetes.io/hostname: $HOST
    kubernetes.io/tls-acme: "true"
    alb.ingress.kubernetes.io/certificate-arn: ""
  hosts:
    - host: $HOST
      paths:
        path: /
  tls:
    - secretName: $HOST-tls
      hosts:
        - $HOST
```
3) Wait for the certificate to be created in the K8s secret by cert-manager & then import it into the ACM using aws cli:
```
kubectl get secret $HOST-tls -o yaml | yq r - data.[tls.crt] | base64 -d | sed -e '/-----END CERTIFICATE-----/q' > $CI_PROJECT_DIR/Certificate.pem

kubectl get secret $HOST-tls -o yaml | yq r - data.[tls.crt] | base64 -d > $CI_PROJECT_DIR/CertificateChain.pem

kubectl get secret $HOST-tls -o yaml | yq r - data.[tls.key] | base64 -d > $CI_PROJECT_DIR/PrivateKey.pem

aws acm import-certificate \
  --certificate fileb://Certificate.pem \
  --certificate-chain fileb://CertificateChain.pem \
  --private-key fileb://PrivateKey.pem

export CERTIFICATE_ARN=$(aws acm list-certificates --query CertificateSummaryList[].[CertificateArn,DomainName] --output text | grep "$HOST" | cut -f1 | head -n 1)

kubectl annotate --overwrite ingress app alb.ingress.kubernetes.io/certificate-arn=$CERTIFICATE_ARN
```

In my case `head -n 1` always shows the certificate which is in use by ALB & to verify it I'm using the following query expecting a non empty output:
`aws acm describe-certificate --certificate-arn $(aws acm list-certificates --query CertificateSummaryList[].[CertificateArn,DomainName] --output text | grep "$HOST" | cut -f1 | head -n 1) --query Certificate.InUseBy --output text`

You can use it without `head -n 1` & loop over the output ARNs to find which certificate ARN is in use & use exactly it (in case the behavior of the aws cli `list-certificates` output changes.
