### ISSUE TITLE
Endless loop when reconciling security group rules in dualstack mode

### ISSUE THREAD

**Issue by acobaugh** [kubernetes-sigs/aws-load-balancer-controller#1094]
We're running aws-alb-ingress-controller v1.1.3.

We have an ingress with the following annotations:
```
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:REDACTED:certificate/1caae96a-ce38-49df-8449-b140f6411551,arn:aws:acm:us-east-1:REDACTED:certificate/5fd29d94-bac3-4e82-989d-fbea7a43c577
    alb.ingress.kubernetes.io/ip-address-type: dualstack
    alb.ingress.kubernetes.io/inbound-cidrs: 0.0.0.0/0,::/0
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: '32080'
    alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
    external-dns.alpha.kubernetes.io/hostname: lb.eks-dev2.swe-dev.aws.cloud.REDACTED
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
```

Every time the reconciliation runs, the controller thinks there are differences between desired and actual sg rules, and therefor removes then adds rules:

```
alb-controller-aws-alb-ingress-controller-5b97bc4dbc-7xlgq aws-alb-ingress-controller I1205 19:46:29.529824       1 security_group.go:64] ingress/alb-ingress: revoking inbound permissions from securityGroup sg-0c68410f9eeb20856: [{    FromPort: 80,    IpProtocol: "tcp",    IpRanges: [{        CidrIp: "0.0.0.0/0",        Description: "Allow ingress on port 80 from 0.0.0.0/0"      }],    Ipv6Ranges: [{        CidrIpv6: "::/0",        Description: "Allow ingress on port 80 from ::/0"      }],    ToPort: 80  },{    FromPort: 443,    IpProtocol: "tcp",    IpRanges: [{        CidrIp: "0.0.0.0/0",        Description: "Allow ingress on port 443 from 0.0.0.0/0"      }],    Ipv6Ranges: [{        CidrIpv6: "::/0",        Description: "Allow ingress on port 443 from ::/0"      }],    ToPort: 443  }]

alb-controller-aws-alb-ingress-controller-5b97bc4dbc-7xlgq aws-alb-ingress-controller I1205 19:46:29.637477       1 security_group.go:75] ingress/alb-ingress: granting inbound permissions to securityGroup sg-0c68410f9eeb20856: [  {    FromPort: 80,    IpProtocol: "tcp",    IpRanges: [{        CidrIp: "0.0.0.0/0",        Description: "Allow ingress on port 80 from 0.0.0.0/0"      }],    ToPort: 80  },  {    FromPort: 80,    IpProtocol: "tcp",    Ipv6Ranges: [{        CidrIpv6: "::/0",        Description: "Allow ingress on port 80 from ::/0"      }],    ToPort: 80  },  {    FromPort: 443,    IpProtocol: "tcp",    IpRanges: [{        CidrIp: "0.0.0.0/0",        Description: "Allow ingress on port 443 from 0.0.0.0/0"      }],    ToPort: 443  },  {    FromPort: 443,    IpProtocol: "tcp",    Ipv6Ranges: [{        CidrIpv6: "::/0",        Description: "Allow ingress on port 443 from ::/0"      }],    ToPort: 443  }]
```

This is, of course, causing an outage every time. Judging from the logs, it looks like the rules that the controller is putting in place are being mutated by AWS upon receipt, and so look different when being read on the next loop. Specifically, the controller is creating one rule per-port per-family, then AWS is returning one rule per-port, with both a v4 and v6 cidr range.

It looks like this was done intentionally in #991 to fix the e2e tests. I don't see any indication in the API reference that an IpPermission can't contain both ipRanges and ipv6Ranges, contrary to what was stated in that PR.

In fact, security_group_test.go does the Right Thing by mixing ipRanges and ipv6Ranges when exercising diffIpPermissions().
