### ISSUE TITLE
Ability to configure the default action on a listener?

### ISSUE THREAD

**Issue by ccampo133** [kubernetes-sigs/aws-load-balancer-controller#1264]
Hello @M00nF1sh 

Is it possible to configure the default action for a listener, or all listeners? Currently it seems to just seems to set the default to 404. What if I wanted this to redirect to a specific target group, or even static URL?

I've been able to create specific actions using https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#actions however I can't seem to find out how to specify a default action.

**Comment by waynewong-ascenda** [comment]
+1

**Comment by ismailyenigul** [comment]
Having default  action `Return fixed response 404` in HTTP 80 listener causes failure on AWS Security Hub's  AWS Foundational Security Best Practices for `Application Load Balancer should be configured to redirect all HTTP requests to HTTPS check fails if`   check
I am not sure this is SecurityHub bug or not.

**Comment by ishaannarang** [comment]
+1

**Comment by vhbfernandes** [comment]
+1

**Comment by thucnd55** [comment]
Is there the solution for this issue guy?
Current I have to use rule "Path is/*"  for default action ...

**Comment by annakulakrishna** [comment]
Any update on this ?

**Comment by pavan2004it** [comment]
+1

**Comment by M00nF1sh** [comment]
Hi all,
You should be able configure the default action by the IngressSpec. (spec.backend). It's supported in all version, but please try out our v2.0.0 instead.
`use-annotation` is also supported for `spec.backend`
e.g.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: game-2048
  name: ingress-2048
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  backend:
   serviceName: xxxx
   servicePort: xxx
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: service-2048
              servicePort: 80
```

feel free to reopen if above didn't help.

**Comment by thucnd55** [comment]
You can try : 
```
alb.ingress.kubernetes.io/actions.default: |
      {"Type":"fixed-response","FixedResponseConfig":{"ContentType":"application/json","StatusCode":"403","MessageBody":"{ \"code\" : 403, \"message\" : \"The requested URI is forbidden, please use the correct URI\"  }"}}
```

**Comment by yyurov** [comment]
Any updates ?
I'm using last version "amazon/aws-alb-ingress-controller:v2.1.0" and still have same issue.
When I'm creating **ingress** in ALB I see same default actions with _return fixed response 404_.
This is reason why I can't use CNAME's in R53 with "A" records associated with ALB.

I'm making ALB thru **ingress** + I'm using external-dns-controller which create **A** records in R53 when ALB is appear.

After I want to make R53 DNS Policy with Failover for point **CNAME** to these **A** records. But this is not works cuz we have default actions with _return fixed response_.
After modify this _default actions_, **CNAME** is works good. This is reason why I can't use AWS DNS policy (each 50$ p/month).

**Comment by jbenoit2011** [comment]
Here is how to configure the default rule with a 403 response for example:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: events-api-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: /ping
    alb.ingress.kubernetes.io/actions.default-rule: >
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"403","messageBody":"Forbidden"}}
    alb.ingress.kubernetes.io/actions.forward-rule: >
      {"type":"forward","forwardConfig":{"targetGroups":[{"serviceName":"my-service","servicePort":"80"}]}}
spec:
  backend:
    serviceName: default-rule
    servicePort: use-annotation
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: forward-rule
              servicePort: use-annotation
```
To work, you have to defined your default rule with an annotation then reference it in `spec.backend.serviceName` and add set `spec.backend.servicePort` to `use-annotation`.

**Comment by dewe** [comment]
Suggested solution with 

```yaml
annotations:
  alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
...
spec:
  backend:
   serviceName: ssl-redirect
   servicePort: use-annotation
```

Does not work with **AWS ALB Ingress Controller v1.1**. When listening on both 80 and 443 this config would create a loop. 

This is the this error:

```text
E0527 07:55:52.208613       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile listeners due to failed to reconcile listener due to InvalidLoadBalancerAction: The redirect configuration is not valid because it creates a loop.\n\tstatus code: 400, request id: 6bc25f8e-8e03-495d-b720-40ab8e12cfd4"  "controller"="alb-ingress-controller" "request"={"Namespace":"xxx","Name":"xxx"} 
```

Does this setup work with **AWS Load Balancer Controller v2.x**?

**Comment by vumdao** [comment]
`aws-load-balancer-controller:v2.2.0` still not solve the problem 
![image](https://user-images.githubusercontent.com/37215642/121351681-3e07c880-c956-11eb-856b-69b151029e23.png)

**Comment by azelezni** [comment]
I managed to set the default action using this config:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: public-alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-name: public-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: public-alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: ""
    alb.ingress.kubernetes.io/listen-ports: |-
      [
        {"HTTP": 80},
        {"HTTPS": 443}
      ]
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/actions.ssl-redirect: |-
      {
        "Type": "redirect",
        "RedirectConfig": {
          "Protocol": "HTTPS",
          "Port": "443",
          "StatusCode": "HTTP_301"
        }
      }
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
```
Without the `alb.ingress.kubernetes.io/ssl-redirect: '443'` annotation, the default rules doesn't change and the redirect is added as another rule, by combining the ssl-redirect annotation and action it seems to work:
![Screenshot from 2021-07-29 19-19-26](https://user-images.githubusercontent.com/37799469/127529429-d1962e96-7dc7-484e-a2c0-4ea23513dc96.png)

**Comment by xuanhai266** [comment]
> I managed to set the default action using this config:
> 
> ```
> apiVersion: networking.k8s.io/v1beta1
> kind: Ingress
> metadata:
>   name: public-alb
>   annotations:
>     kubernetes.io/ingress.class: alb
>     alb.ingress.kubernetes.io/load-balancer-name: public-alb
>     alb.ingress.kubernetes.io/scheme: internet-facing
>     alb.ingress.kubernetes.io/group.name: public-alb
>     alb.ingress.kubernetes.io/target-type: ip
>     alb.ingress.kubernetes.io/certificate-arn: ""
>     alb.ingress.kubernetes.io/listen-ports: |-
>       [
>         {"HTTP": 80},
>         {"HTTPS": 443}
>       ]
>     alb.ingress.kubernetes.io/ssl-redirect: '443'
>     alb.ingress.kubernetes.io/actions.ssl-redirect: |-
>       {
>         "Type": "redirect",
>         "RedirectConfig": {
>           "Protocol": "HTTPS",
>           "Port": "443",
>           "StatusCode": "HTTP_301"
>         }
>       }
> spec:
>   rules:
>     - http:
>         paths:
>           - backend:
>               serviceName: ssl-redirect
>               servicePort: use-annotation
> ```
> 
> Without the `alb.ingress.kubernetes.io/ssl-redirect: '443'` annotation, the default rules doesn't change and the redirect is added as another rule, by combining the ssl-redirect annotation and action it seems to work: ![Screenshot from 2021-07-29 19-19-26](https://user-images.githubusercontent.com/37799469/127529429-d1962e96-7dc7-484e-a2c0-4ea23513dc96.png)

I confirmed that it works well.
Many thanks.

**Comment by MaxFlandersLaerdal** [comment]
What if I would like to set the default action to a forward action, that forwards *to the target group created by the controller*. There are examples of how to forward to TG's created manually, but if I want to use the default action to forward to the controller-created TG, I would need to know the name of the group ahead of time in order to put it in the annotation, which doesn't work out exactly :/

**Comment by MaxFlandersLaerdal** [comment]
Hi there, I was able to find that you can also set the default action via the [defaultBackend](https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressSpec) configuration of the ingress resource, rather than using the AWS ALB annotations to do so.

**Comment by deenMuhammad** [comment]
> Hi there, I was able to find that you can also set the default action via the [defaultBackend](https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressSpec) configuration of the ingress resource, rather than using the AWS ALB annotations to do so.

Above workarounds are great, but this way us right in target, solves the problem in the most correct way.

**Comment by khosro-copper** [comment]
> Hi all You should be able configure the default action by the IngressSpec. (spec.backend). It's supported in all version, but please try out our v2.0.0 instead. `use-annotation` is also supported for `spec.backend` e.g.
> 
> ```
> apiVersion: extensions/v1beta1
> kind: Ingress
> metadata:
>   namespace: game-2048
>   name: ingress-2048
>   annotations:
>     kubernetes.io/ingress.class: alb
>     alb.ingress.kubernetes.io/scheme: internet-facing
>     alb.ingress.kubernetes.io/target-type: ip
> spec:
>   backend:
>    serviceName: xxxx
>    servicePort: xxx
>   rules:
>     - http:
>         paths:
>           - path: /*
>             backend:
>               serviceName: service-2048
>               servicePort: 80
> ```
> 
> feel free to reopen if above didn't help.



For those of you that are using kubernetes 1.22+, these are the changes:

`Ingress` and `IngressClass` resources have graduated to `networking.k8s.io/v1`. Ingress and IngressClass types in the `extensions/v1beta1` and `networking.k8s.io/v1beta1` API versions are deprecated and will no longer be served in 1.22+. Persisted objects can be accessed via the `networking.k8s.io/v1` API. Notable changes in v1 Ingress objects (v1beta1 field names are unchanged):
  - `spec.backend` -> `spec.defaultBackend`
  - `serviceName` -> `service.name`
  - `servicePort` -> `service.port.name` (for string values)
  - `servicePort` -> `service.port.number` (for numeric values)
  - `pathType` no longer has a default value in v1; "Exact", "Prefix", or "ImplementationSpecific" must be specified

So, for example, this worked for me and tested:
```
defaultBackend:
    service:
      name: name-of-service
      port:
        number: 80
```
This will change default rule (last rule if anything else doesn't match) to use k8s service.

**Comment by fernandomullerjr** [comment]
+1

**Comment by mafeifan** [comment]
this example was successful in k8s 1.29
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "300"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/load-balancer-name: alb-demo
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/actions.rule-kone: >
      {"type":"forward","forwardConfig":{"targetGroups":[{"serviceName":"svc-nginx","servicePort":"80"}]}}
    alb.ingress.kubernetes.io/conditions.rule-kone: >
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "X-DEMO-Header", "values":["1234567"]}}]
    alb.ingress.kubernetes.io/actions.default: |
      {"Type":"fixed-response","FixedResponseConfig":{"ContentType":"application/json","StatusCode":"403","MessageBody":"{ \"code\" : 403, \"message\" : \"Access deny, please contact to cndevops@demo.com\"  }"}}
  name: alb-demo
  namespace: demo
spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: default
      port:
        name: use-annotation
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: rule-kone
                port:
                  name: use-annotation
```

**Comment by segoja7** [comment]
Hello everyone,

Could we explain me what is the annotation for obtain an listener rule how the following image, I was trying many things but the result is always the same.

![image](https://github.com/user-attachments/assets/2892648c-0ff0-4811-9fb1-978d44d40bf7)

This is my .yaml and I make tests with this annotations but not work for me.

forward-single-tg: forward to a single targetGroup [simplified schema]

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: alb.${subdomain}.<domain>
    alb.ingress.kubernetes.io/load-balancer-name: visionamos-${env}
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/certificate-arn: ${acm_arn}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: ${security_group_id}
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2019-08
    alb.ingress.kubernetes.io/success-codes: 200-404
    alb.ingress.kubernetes.io/target-type: ip
  name: ingress-visionamos
  namespace: visionamos
spec:
  ingressClassName: alb
  rules:
  - host: ${subdomain}.<domain>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: istio-ingressgateway
            port:
              number: 15021
      - path: /
        pathType: Prefix
        backend:
          service:
            name: <myservice>
            port:
              number: 443
```

And this the final result.

![image](https://github.com/user-attachments/assets/ce30e110-1ae2-457e-8c31-902eaa9e50fb)
