### ISSUE TITLE
URL rewrite?

### ISSUE THREAD

**Issue by nowfox** [kubernetes-sigs/aws-load-balancer-controller#1268]
I found this issues https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/835.
But the reply didn't solve the problem. The reply is to use redirect instead of rewrite.
In nginx ingress controller, the corresponding configuration is
`nginx.ingress.kubernetes .io/rewrite-target: /`

Assume the configuration is as follows
```
spec:
  rules:
    - http:
        paths:
          - path: /path1
            backend:
              serviceName: "service1"
              servicePort: 80
          - path: /paht2
            backend:
              serviceName: "service2"
              servicePort: 80
```
If the request URL is http://*.com/path1/abc.html , the expected result is that the backend service receives the request at abc.html Not path1/abc.html .
Do you have any idea?Thank you.
