### ISSUE TITLE
Resticting permissions in iam policy

### ISSUE THREAD

**Issue by dudicoco** [kubernetes-sigs/aws-load-balancer-controller#1302]
Hi,

We would like to restrict the permissions of the controller to only modify resources in a specific vpc in which the cluster is deployed.

The best I could come up with is the following:
```
  - Effect: Allow
    Action:
    - ec2:DescribeAccountAttributes
    - ec2:DescribeAddresses
    - ec2:DescribeInstances
    - ec2:DescribeInstanceStatus
    - ec2:DescribeInternetGateways
    - ec2:DescribeNetworkInterfaces
    - ec2:DescribeSecurityGroups
    - ec2:DescribeSubnets
    - ec2:DescribeTags
    - ec2:DescribeVpcs
    Resource:
    - "*"
  - Effect: Allow
    Action:
    - ec2:CreateTags
    - ec2:DeleteTags
    - ec2:ModifyInstanceAttribute
    - ec2:ModifyNetworkInterfaceAttribute
    Resource:
    - "*"
    Condition:
      StringEquals:
        ec2:Vpc: <VPC_ARN>
  - Effect: Allow
    Action:
    - elasticloadbalancing:DescribeListenerCertificates
    - elasticloadbalancing:DescribeListeners
    - elasticloadbalancing:DescribeLoadBalancers
    - elasticloadbalancing:DescribeLoadBalancerAttributes
    - elasticloadbalancing:DescribeRules
    - elasticloadbalancing:DescribeSSLPolicies
    - elasticloadbalancing:DescribeTags
    - elasticloadbalancing:DescribeTargetGroups
    - elasticloadbalancing:DescribeTargetGroupAttributes
    - elasticloadbalancing:DescribeTargetHealth
    Resource:
    - "*"
  - Effect: Allow
    Action:
    - elasticloadbalancing:AddTags
    - elasticloadbalancing:CreateLoadBalancer
    - elasticloadbalancing:CreateTargetGroup
    Resource:
    - "*"
  - Effect: Allow
    Action:
    - elasticloadbalancing:AddListenerCertificates
    - elasticloadbalancing:CreateListener
    - elasticloadbalancing:CreateRule
    - elasticloadbalancing:DeleteListener
    - elasticloadbalancing:DeleteLoadBalancer
    - elasticloadbalancing:DeleteRule
    - elasticloadbalancing:DeleteTargetGroup
    - elasticloadbalancing:DeregisterTargets
    - elasticloadbalancing:ModifyListener
    - elasticloadbalancing:ModifyLoadBalancerAttributes
    - elasticloadbalancing:ModifyRule
    - elasticloadbalancing:ModifyTargetGroup
    - elasticloadbalancing:ModifyTargetGroupAttributes
    - elasticloadbalancing:RegisterTargets
    - elasticloadbalancing:RemoveListenerCertificates
    - elasticloadbalancing:RemoveTags
    - elasticloadbalancing:SetIpAddressType
    - elasticloadbalancing:SetSecurityGroups
    - elasticloadbalancing:SetSubnets
    - elasticloadbalancing:SetWebACL
    Resource:
    - "*"
    Condition:
      StringEquals:
        elasticloadbalancing:ResourceTag/ingress.k8s.aws/cluster: <CLUSTER_NAME>
```

The above policy doesn't work as we get errors from the controller such as:
```
"error"="failed to reconcile listeners due to failed to reconcile rules due to failed creating rule 1 on xxx due to AccessDenied: User: xxx is not authorized to perform: elasticloadbalancing:CreateRule on resource: xxx"
```

In addition, even if this policy would work, the controller has permissions to add tags to all load balancers so it could basically escalate its own permissions by adding tags to a load balancer.

Can anyone please advise on how to restrict the controller's permissions?

Thanks
