### ISSUE TITLE
Adding a health-check path annotation leads to service being timed out

### ISSUE THREAD

**Issue by hjpotter92** [kubernetes-sigs/aws-load-balancer-controller#1303]
We have setup the ALB controller 1.1.8 for our EKS cluster. Our API services do not respond to `/`, but we do mount a `/health` route for successful deployments.

On configuring the annotation:

``` yaml
metadata:
  annotations:
    # custom health check route
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/ip-address-type: dualstack
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=4000
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=60
    alb.ingress.kubernetes.io/target-type: ip
```

we start receiving a 502 errors on all the mounted hosts of the ALB.
