### ISSUE TITLE
Failure to configure whole ALB if a kubernetes Service resource is missing

### ISSUE THREAD

**Issue by omninonsense** [kubernetes-sigs/aws-load-balancer-controller#1304]
Hello!

If the ALB IC gets a rule that points to a non-existent k8s Service resource, the ALB fails to configure. As far as I could tell, there are no bugs for this. I'm not sure whether this is a bug in ALB or a bug in [`amazon-vpc-cni-k8s`](https://github.com/aws/amazon-vpc-cni-k8s). Here's how to reproduce it:

```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: faulty-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: oops/*
            backend:
              serviceName: typo
              servicePort: 80
          - path: /*
            backend:
              serviceName: web
              servicePort: 80
```

There ate two things that happen:

  1. **On first/initial configuration**: The ALB IC accepts the configuration, but something refuses _all_ connections.
  2. **Applying the erroneous config on top of a valid one**: The ALB IC will accept the config, but it won't actually do anything, the previous config will remain in effect.

I can't get any verbose logging, so I'm not sure what, where or how things go wrong exactly. After some experimentation, I definitely narrowed it down to the culprit being a missing k8s Service resource, though.

I think what should happen is that the IC would accept the Ingress resource, but warn that the k8s Service doesn't exist in the event log (ie when doing `kubectl describe ingress faulty-ingress`) , and return 503 for the misconfigured paths/rules. But, it should continue to work for the other paths.

Alternatively, it could also refuse the ingress resource with an error. But, I guess there are cases where someone might create the ingress before they create the resource, depending on how their deployment pipeline works.
