### ISSUE TITLE
Guidance: controller ignores HTTP IP whitelisting rule?

### ISSUE THREAD

**Issue by crawforde** [kubernetes-sigs/aws-load-balancer-controller#1307]
I set up an ALB with a Cognito Auth listener and the recommended http -> https ssl-redirect rule:
```
rules:
    - host: {{ .Values.alb.hostname }}
      http:
        paths:
          - path: /*
            backend:
              # Configured via the redirect settings in the annotations
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: {{ .Chart.Name }}
              servicePort: 80
```

The app works as expected. However, I want to be able to whitelist HTTP traffic from specific CIDR ranges and not redirect to port 443, but instead forward directly to the target group. I was able to achieve this manually by adding a conditional rule just to the HTTP listener on port 80, but I can't figure out how to update the helm chart to achieve this. I tried adding the following annotations:
```
alb.ingress.kubernetes.io/actions.whitelist-http-by-source-ip: >
    {"Type":"forward","ForwardConfig":{"TargetGroups":[{"ServiceName":"{{ .Chart.Name }}","ServicePort":"80","Weight":100}]}}
alb.ingress.kubernetes.io/conditions.whitelist-http-by-source-ip: >
    [{"Field":"source-ip","SourceIpConfig":{"Values":["172.16.0.0/12"]}}]
```
Then I modified the rules to the following:
```
rules:
    - host: {{ .Values.alb.hostname }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: whitelist-http-by-source-ip
              servicePort: use-annotation
          - path: /*
            backend:
              # Configured via the redirect settings in the annotations
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: {{ .Chart.Name }}
              servicePort: 80
```

When I run `helm upgrade`, the ingress controller says "successfully reconciled" but completely ignores the new rule and adds no new listeners to either of the ports. Any guidance? (I'm using helm 12.16)
