### ISSUE TITLE
how to map host path with service path in ingress

### ISSUE THREAD

**Issue by vrathore18** [kubernetes-sigs/aws-load-balancer-controller#1326]
How to create an alb ingress such that only "/" will redirect to a service that shows static files in service-1. all other paths should redirect to service 2. it will host something like this

```
spec:
  rules:
    - host: a.abc.com
      http:
        paths:
          - path: /
            backend:
              serviceName: service-1
              servicePort: 80
          - path: /v1
            backend:
              serviceName: service-2/v1
              servicePort: 9090
```

I know I can't have service-2/v1 on serviceName but I want to map /v1 to service-2:9090/v1.
I am hosting some static files in service-1(nginx) which I want to show on "/" and then /v1 and /admin is on my another service :service-2

**Comment by vrathore18** [comment]
@M00nF1sh : Could you please help with this issue?

**Comment by M00nF1sh** [comment]
i believe below will work :D 
```
spec:
  rules:
    - host: a.abc.com
      http:
        paths:
          - path: /
            backend:
              serviceName: service-1
              servicePort: 80
          - path: /*
            backend:
              serviceName: service-2
              servicePort: 9090
```
