### ISSUE TITLE
Service annotation (tags) causes target group and rule not be be created.

### ISSUE THREAD

**Issue by joneal** [kubernetes-sigs/aws-load-balancer-controller#1380]
Tried to specify a user-friendly name of the target group that gets created from the ingress instead of the cryptic hash.  In this example, the desired target name if 'tg-foo-dev'.

```
apiVersion: v1
kind: Service
metadata:
  name: foo-dev
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: '/v1/diagnostics/healthcheck'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '3'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '10'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/tags: 'Name:tg-foo-dev'
spec:
  ports:
    - port: 80
      targetPort: 9999
      protocol: TCP
  type: NodePort
  selector:
    run: foo-dev
```

When the ingress is applied, the new ALB is created, but the target group is NOT created nor is the associated rule created.  Removing the 'Name' tag does not cause the target group and rule to get created unless the ingress is recreated.

The expected behavior would be the target group to get the friendly name, or the Name tag is ignored and the hash is used, but instead got no target group nor rule created.
