### ISSUE TITLE
ALB  with Nginx controller deployment

### ISSUE THREAD

**Issue by newtoworld999** [kubernetes-sigs/aws-load-balancer-controller#1384]
Hi Everyone
Is there any documentation on how to implement the ALB with nginx ingress controller in EKS? As single ALB ingress controller cannot be used to expose services accross namespaces, while looking at documentation found that NLB with Nginx ingress controller can do that, but if i want to expose the services after authenticating with cognito i cannot use NLB and need to use ALB with nginx ingress controller so looking for documentation on how to implement ALB with nginx ingress controller.

**Comment by kishorj** [comment]
There is a blog post on this  - 
https://aws.amazon.com/blogs/opensource/network-load-balancer-nginx-ingress-controller-eks/

Please check if this helps.

**Comment by M00nF1sh** [comment]
@newtoworld999 
You can refers the nlb + nginx doc @kishorj shared above.
To use ALB, you should create a Ingress targeting the NginxController service(change it's type from LoadBalancer to NodePort). with routing path "/*"

**Comment by vitali-zevako** [comment]
@M00nF1sh could please share more details how to use alb with nginx ingress helm chart?

**Comment by newtoworld999** [comment]
Hi Kishorj, 
I tried deploying the nginix ingress controller with ALB seeing that documentation but it didnt deploy the ALB, seems only load balancer that can be deployed with nginx ingress controller is either classic or NLB.

**Comment by raunyoliveira-hotmart** [comment]
@newtoworld999 here is the configuration that worked for me:

**ingress-nginx**

The important part here is the **service.type: NodePort**, this config will disable the Nginx ELB creation.

```
controller:
  replicaCount: 1
  publishService:
    enabled: false
  ingressClass: nginx
  service:
    type: NodePort
    targetPorts:
      http: http
      https: http
```

**aws-alb-ingress**

```
scope:
  ingressClass: alb
  singleNamespace: true
  watchNamespace: your-namespace
```

And finally you have to create an Ingress that will create the ALB and send the traffic to the Nginx pods:

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: aws-alb-ingress-controller
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: "your-certificate-arn"
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/success-codes: "200,404"
spec:
  rules:
  - host: "*.yourhost.com"
    http:
      paths:
      - backend:
          serviceName: ingress-nginx-service
          servicePort: http
        path: "/*"
```

**Comment by M00nF1sh** [comment]
@raunyoliveira-hotmart 
feel free to reopen if above instructions didn't help :D

**Comment by dignajar** [comment]
Hi @raunyoliveira-hotmart how do you manage the DNS records with Nginx and Route53 ?

For example, if I have an application `echo` and I want to expose it to `echo.yourhost.com` the ingress for that app should be pointing to the `nginx` ingress class to generate the backend config in `nginx.conf`, but not sure how to manage the DNS to point to the ALB.

**Comment by ectogon** [comment]
@dignajar I think you'll need something like: https://github.com/kubernetes-sigs/external-dns

**Comment by nirsv** [comment]
@ectogon external-dns is not working properly when you use nginx as alb.
All any other inress controles behind tgat nginx, will refer to the nginx' IP instead of the DNS of the ALB.
This is nginx isuue (not external-dns)

**Comment by sapna-dentsu** [comment]
> "/*"

@raunyoliveira-hotmart I tried this approach and I'm getting permanent redirect

**Comment by y0zg** [comment]
@M00nF1sh where is TLS terminated if we use ALB controller in conjunction with nginx controller? Tried to run some tcpdumps but would like double check here as well

**Comment by timothyclarke** [comment]
@y0zg TLS is terminated on ALB

**Comment by y0zg** [comment]
Do you mean AWS ALB or ALB controller? If it's AWS ALB, what is needed in order to ensure TLS is terminated within k8s cluster?

**Comment by timothyclarke** [comment]
@y0zg On the AWS ALB. That's the thing that handles the traffic. The ALB controller "manages" the AWS ALB by watching for annotations within the cluster and then making API calls to AWS to create or modify an ALB.

>what is needed in order to ensure TLS is terminated within k8s cluster?

**I'm not sure I completely understand what you're asking, hopefully the following with give enough of an answer.**

AWS ALB operates on the HTTP level. All HTTP (and HTTPS) connections terminate at the AWS ALB. That's why you use an ALB instead of a NLB or Classic LB. The ALB has access to AWS ACM to obtain / use SSL certificates (so you can terminate HTTPS connections), aka Browser -> ALB. 
If you want TLS connections from ALB to the thing behind, then the thing behind needs certificates. If we're talking Nginx-ingress within Kubernetes then you would typically have cert-manager to obtain certs from lets-encrypt. 
IIRC AWS ALB can be configured to ignore the validity of a cert (eg the self signed ones) if you don't want cert-manager.

I'm still trying to understand why ALB -> Nginx -> App, more so if you're talking ALB (TLS) -> Nginx (TLS) -> App rather than ALB -> App or NLB/ELB -> Nginx (TLS) -> App.
I get that ALB doesn't support CORS, and you may not want to put it in the App, but if you're adding Nginx for CORS and wanting TLS between ALB and Nginx why not just go for Network or Classic LB. If someone can tell me what I'm missing I'd appreciate it. Perhaps CloudFront with WAF and some paths served from S3 while others come from EKS?

**Comment by y0zg** [comment]
@timothyclarke  Thanks for sharing your thoughts and for provided an extended answer.
I'd prefer to use ACM against let's encrypt just because it looks more resilient. I have experience to use these options 
1) NLB+certmanager+external dns+let's encrypt or 
2) ALB+ACM

For me option 2) looks a bit more resilient (less dependency on k8s)
That's the reason I raised the question regarding TLS termination with ALB

**Comment by gitmaniak** [comment]
@raunyoliveira-hotmart so we need to install both nginx and alb ingress controllers? I am looking for a solution to resolve CORS issues with my ALB using Aws Load Balancer controller.

**Comment by SAURABH110894** [comment]
@gitmaniak did you got any solution for CORS with ALB ?

**Comment by alon-cheq** [comment]
@rauny-brandao - I have tryed your set up and all my requests are reaching default backend service with 404.
I have each serivce has 2 ingress: one for the route53 + public ALB withroutes poiting to nginx-internal:
`backend:
              service:
                name: nginx-ingress-controller-internal 
`
and the second ingress using the internal nginx to route traffic to the backend service:
`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helloworld.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "helloworld.name" . }}
    helm.sh/chart: {{ include "helloworld.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Release.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx-internal
spec:
  rules:
    {{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $.Values.service.port }}
        path: {{ $.Values.ingress.path }}
        pathType: {{ $.Values.ingress.pathType }}
    {{- end }}
{{- end }}
`
Any advice on this? 
I am not sure the internal nxing has an updated config toroute the traffic to the dedicated pods.

**Comment by emwalker** [comment]
It took me a little while to track down what [this was referring to](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1384#issuecomment-698591561):
```
scope:
  ingressClass: alb
  singleNamespace: true
  watchNamespace: your-namespace
```

It looks like these are [values](https://github.com/kubernetes-sigs/aws-load-balancer-controller/tree/main/helm/aws-load-balancer-controller) passed to the AWS Load Balancer Controller helm chart.

**Comment by midu-git** [comment]
I had exactly the same requirement and it took me some time to figure out the whole chain. In my case, I had an additional constraint. In the Kubernetes cluster, we used external-dns to create and update DNS entries for the particular application pointed to by `Ingress` resource.
When you create a Kubernetes `Service` of type `NodePort` or `ClusterIP`, as described above, nginx-controller will put the IP of the node or the service as the address field on the application ingresses, and thus external-dns will put these values in the DNS record, and not the value for the ALB.

To overcome this problem, define `ExternalName` as the type of `Service` and source `externalName` from the `status.loadBalancer.ingress.hostname` field of the `Ingress` resource created for nginx-controller.
Moreover, set the argument `--publish-service` to the name of `Service` created. Basically

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    ...
spec:
  rules:
  - host: "*.yourhost.com"
    http:
      paths:
      - backend:
          serviceName: ingress-nginx-controller
          servicePort: http
        path: "/*"
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: SOURCE_FROM_INGRESS (status.loadBalancer.ingress.hostname)
  selector:
      app.kubernetes.io/component: controller"
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
  ...
---
```
and set `--publish-service=nginx/ingress-nginx-controller`. As the value for `externalName` can't be passed into the helm chart, you need to set `service.enabled=false` as a helm value, and pass `publish-service` as `extraArgs` to helm.
