### ISSUE TITLE
How can i set the alb target to "Other private IP address"

### ISSUE THREAD

**Issue by eph6666** [kubernetes-sigs/aws-load-balancer-controller#1405]
When I use alb ingree with following yaml
```
apiVersion: v1
kind: Service
metadata:
  name: external-ip
spec:
  ports:
  - name: app
    port: 12345
    protocol: TCP
    targetPort: 12345
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-ip
subsets:
- addresses:
  # list all external ips for this service
  - ip: 192.168.64.88
  ports:
  - name: app
    port: 12345
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /test/
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 10080}]'
spec:
  backend:
    serviceName: external-ip
    servicePort: 12345
```
I want to set the target to a ip in another VPC.
I can do this in aws console with following config: "Other private ip address"
![image](https://user-images.githubusercontent.com/9880709/92863258-4ca86a00-f42e-11ea-8bf2-dfc274b33c01.png)
How can i set this with alb?
