### ISSUE TITLE
[Feature Request] Support for IngressClassName

### ISSUE THREAD

**Issue by rdubya16** [kubernetes-sigs/aws-load-balancer-controller#1439]
We are using CI to validate our manifests and came across a depreciation warning for our ingress objects for alb-ingress-controller. 

`FAIL - Ingress/alb-ingress: Ingress annotation kubernetes.io/ingress.class has been deprecated in 1.18, use spec.IngressClassName instead.`

Are there plans to support IngressClassName? I searched the codebase and didnt see the changes required for this yet but I could be missing something. It also appears that all the documentation references ingress.class

**Comment by M00nF1sh** [comment]
Hi, 
we'll support IngressClass in the new versions. 
We can leverage the parameters in IngressClass for setting common LoadBalancer settings.

**Comment by maxbraun** [comment]
Hey,

since EKS 1.18 is GA, can you give any ETA when this will arrive?

Cheers, Max

**Comment by M00nF1sh** [comment]
@maxbraun we'll add support use IngressClass's controller field before reinvent2020. And post reinvent2020, we'll add configurations via CRD.

**Comment by M00nF1sh** [comment]
it's supported in v2.1.0 😄

**Comment by michalpacholczyk** [comment]
Supercool! Can you please tell how to properly set `spec.controller` value in `IngressClassResource` ?

**Comment by zmarouf** [comment]
Define the `IngressClass`
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: aws-load-balancer
spec:
  controller: ingress.k8s.aws/alb
  ```
Reference it like so
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-alb-ingress
spec:
  ingressClassName: aws-load-balancer
```
