### ISSUE TITLE
Exposing multiple services with https and ACM is throwing error 

### ISSUE THREAD

**Issue by madhu131313** [kubernetes-sigs/aws-load-balancer-controller#1455]
**What do I want to create**
I want to expose multiple services via alb ingress by exposing each kubernetes service via a  subdomain like appname.example.com

**What have I done**
I am able to replicate the alb ingress by [basic example given](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html) and when I go to my alb url I can see the app. After that I have added ACM certificate annotation, listen-ports annotation, ssl-redirect annoation ( http to https redirection) and used host  header configuration from the documentation.
The alb got created with http listener (with https redirection rule), acm certificate attached to https lisetner and there was https listener _without any rules_

Basically the rules are not created in https listener. On seeing the logs with 

`kubectl logs -n kube-system   deployment.apps/alb-ingress-controller`

I got the error **Condition values must be unique**

`E0929 08:15:03.586482       1 rules.go:75] default/stage-alb-ingress: failed creating rule 1 on arn:aws:elasticloadbalancing:ap-south-1:x:listener/app/xx-default-stagealbi-7f34/d6a64c59c40b48xx/8f598a310f6ed0xx due to ValidationError: Condition values must be unique
`
Here is a simplified  yaml for alb ingress 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "stage-alb-ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:xxxxxxxx:certificate/xxxxx-7e14-4cd4-87ff-xxx
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/conditions.service-2048: >
      [{"Field":"host-header","HostHeaderConfig":{"Values":["2048.example.com"]}}]
  labels:
    app: stage-alb-ingress
spec:
  rules:
    - host: "2048.example.com"
      http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /test
            backend:
              serviceName: service-2048
              servicePort: 80
```

The issue is freshly replicated in another cluster with similar configuration and having the same results. 

**Why is this important to solve?** 
I haven't found this use case anywhere in the web and documentation and this will help all the future engineers who will build similar system

**Comment by madhu131313** [comment]
I got solved from Amazon support, basically one should not use both annotation and service rule together. 

Here is the updated version of yaml file

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "stage-alb-ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:789919094586:certificate/ab003070-7e14-4cd4-87ff-4223275c26cd
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/conditions.service-2048: >
      [{"Field":"host-header","HostHeaderConfig":{"Values":["2048.awigntest.com"]}}]
  labels:
    app: stage-alb-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: service-2048
              servicePort: 80
```

I am not closing this so that the admins can close this after improving the documentation.
