### ISSUE TITLE
Conditional cognito usage

### ISSUE THREAD

**Issue by ghost** [kubernetes-sigs/aws-load-balancer-controller#1465]
Hello everyone,

I was wondering if it was possible to have certain rules with conditions (e.g. a special route, or a special method) where I can disable the authentication with cognito.
In my case, I have a health check method and would like this to be accessible without being authenticated.

```yaml
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: "/api/healthcheck"
            backend:
              serviceName: {{ .Release.Name }}-backend
              servicePort: 80
              useAuthentication: false
          - path: "/api*"
            backend:
              serviceName: {{ .Release.Name }}-backend
              servicePort: 80
              useAuthentication: true
          - path: /*
            backend:
              serviceName: {{ .Release.Name }}-frontend
              servicePort: 80
              useAuthentication: true
```

When I manually create an ALB, I can define for each rule whether it uses authentication.

Thank you for your help,
Philipp

**Comment by philippwostry** [comment]
I think I figured it out.

**Comment by philippwostry** [comment]
Unfortunately, acutall I havent figured it out,

I thought I could work with actions and type forward but this still puts the cognito inbetween.
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    external-dns.alpha.kubernetes.io/hostname: {{ required "FQDN to be created on Route53 is required. please fill R53DnsName in values.yaml" .Values.R53DnsName }}
    alb.ingress.kubernetes.io/certificate-arn: {{ required "ACM certificate arn is required . please fill AcmCertArn in values.yaml" .Values.AcmCertArn }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/auth-scope: openid
    alb.ingress.kubernetes.io/auth-session-timeout: '3600'
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/security-groups: {{ required "Frontend securitygroups  to be used is required. please fill ALBFrontendSecurityGroup in values.yaml" .Values.ALBFrontendSecurityGroup }},{{ required "Backend securitygroups  to be used is required. please fill ALBBackendSecurityGroup in values.yaml" .Values.ALBBackendSecurityGroup }}
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn": "{{ required "Cognito user pool to be used is required. please fill UserPoolArn in values.yaml" .Values.UserPoolArn }}","UserPoolClientId":"{{ required "Client id is required . please fill UserPoolClientId in values.yaml" .Values.UserPoolClientId }}","UserPoolDomain":"{{ required "Cognito user pool domain to be used is required. please fill UserPoolDomain in values.yaml" .Values.UserPoolDomain }}"}'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    # alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    # alb.ingress.kubernetes.io/healthcheck-port: '80'
    # alb.ingress.kubernetes.io/healthcheck-path: /api/health-check
    # alb.ingress.kubernetes.io/healthcheck-interval-seconds: '10'
    # alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '8'
    # alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=1200
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true
    alb.ingress.kubernetes.io/actions.apikey: >
      {"Type":"forward","ForwardConfig":{"TargetGroups":[{"ServiceName":"repository","ServicePort":"80","Weight":1}]}}
    alb.ingress.kubernetes.io/conditions.apikey: >
      [{"Field":"path-pattern","PathPatternConfig":{"Values":["/2l46/*"]}},{"Field":"http-header","HttpHeaderConfig":{"HttpHeaderName": "authorization", "Values":["*"]}}]
    # alb.ingress.kubernetes.io/conditions.repository: >
      # [{"Field":"path-pattern","PathPatternConfig":{"Values":["/2l46/*","/api/*"]}}]
  labels:
    app: {{ .Release.Name }}
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /api/*
            backend:
              serviceName: apikey
              servicePort: use-annotation
          - path: "/api*"
            backend:
              serviceName: repository
              servicePort: 80
          - path: /*
            backend:
              serviceName: pert
              servicePort: 80
```

In case a http header with name authorization is present, I want cognito to be skipped.
any idea? :/
