### ISSUE TITLE
[V2] Support different strategies for ordering ingresses within a group

### ISSUE THREAD

**Issue by AndrewBoklashko** [kubernetes-sigs/aws-load-balancer-controller#1513]
Hi and thanks for releasing v2 version of the controller!

We have a bunch of ingresses in our cluster which look similar to this:
```YAML
host: example.com
http:
  paths:
    - path: /foo/a*
      backend:
        serviceName: foo-a-service
        servicePort: 80
    - path: /foo/b*
      backend:
        serviceName: foo-b-service
        servicePort: 80
    - path: /bar/a*
      backend:
        serviceName: bar-a-service
        servicePort: 80
    - path: /foo*
      backend:
        serviceName: foo-service
        servicePort: 80
    - path: /bar*
      backend:
        serviceName: bar-service
        servicePort: 80
    - path: /*
      backend:
        serviceName: catch-all-service
        servicePort: 80
```

Note that an order of rules is important here, `foo-service` must go after `foo-{a,b}-service`, `bar-service` must be after `bar-a-service` and `catch-all-service` must be the last one. Each backend service here is a separate application(deployment). We use a central Helm chart for managing these ingress objects, which is disconnected from the application charts. This is needed with v1 version of the controller to be able to put as much services into single ingress for reusing ALBs and to get ingress rules in correct order.

With v2 and ingress grouping there is no need in having a single ingress for reusing ALBs, so we would really like to deploy ingresses as a part of application charts to manage everything in a single place. This means that each rule from the ingress above will become a separate ingress object. However by doing that it will be hard to get the order right, even if we use ingress group order annotations, we will have to manually figure them out, which is tedious and error-prone. It's even worse if you want to combine ingresses not only by application(service), but also within many environments(namespaces).

So my suggestion is to provide different strategy for ordering of ingress rules when combining them. Like in this case simple reverse sorting by path would work really well, however I'm not sure if there are any corner cases here(the point is that more specific rule must win). Although there are open questions, for example it's not clear what do if ingress has multiple rules which order conflicts with the order after combining. But in general providing different strategies of ordering seems reasonable to me and it will not be a breaking change if user can set it using the group-exclusive ingress annotation.

Let me know about your thoughts on this problem.
