### ISSUE TITLE
add option for specifying target group port to support Istio

### ISSUE THREAD

**Issue by jbilliau-rcd** [kubernetes-sigs/aws-load-balancer-controller#1521]
We currently use Istio 1.6.9 as a service mesh on top of Kubernetes EKS 1.17 (going to 1.18 shortly). We currently create `Ingress` objects per namespace/application, which our Zalando ingress controller is hardset to just create ALB/TG's for us based off arguments passed in:

```
    spec:
      containers:
      - args:
        - --health-check-path=/healthz/ready
        - --health-check-port=31370
        - --target-port=31380
        - --ingress-class-filter=alb-istio
        - --controller-id=istio-gw
```

We are trying to migrate to this aws-alb-ingress-controller but are stuck on one thing: there is no way to specify a target group port, only the health check port. Problem is, the controller does a lookup of the `Service` NodePort to create the target group, but I'm not routing directly to the service; i'm routing to the Istio ingress-gateway. 

Normally, if Kubernetes supported cross-namespace routing, I would just route across the namespaces, forwarding every single `Ingress` to istio-ingressgateway, but that doesn't work. Thus, even though my `Ingress` looks like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rhino
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: shared
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-port: "31370"
    alb.ingress.kubernetes.io/healthcheck-path: "/healthz/ready"
    alb.ingress.kubernetes.io/security-groups: sg-01d80853eb787088d
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
spec:
  rules:
  - host: rhino.jasoneks.foc.zone
    http:
      paths:
      - backend:
          serviceName: rhino
          servicePort: 80
```

I don't actually want it to look up the NodePort of the `Service` rhino: i want it to create a TG that is hardset to go to 31380, which is the Nodeport of istio-ingressgateway.

This controller supports custom healthcheck-port's......can we get it to support custom targetgroup ports as well for this use-case?
