### ISSUE TITLE
Unable to configure default listener rule in ALB-Ingress-Controller

### ISSUE THREAD

**Issue by pavan2004it** [kubernetes-sigs/aws-load-balancer-controller#1533]
I am trying to setup the alb with https listener , but i am unable to configure default rule to forward the traffic to one of the services, below is my config file for ingress and services
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: xyz
  namespace: xyz
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: <Certificate-ARn>
    alb.ingress.kubernetes.io/subnets: <Subnet-Id>
spec:
  rules:

    - http:
        paths:

          - path: /*
            backend:
              serviceName: service a
              servicePort: xyz

          - path: /api/service b*
            backend:
              serviceName: service b
              servicePort: xyz


apiVersion: v1
kind: Service
metadata:
  name: service a
  namespace: <App Name>
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/health"
    alb.ingress.kubernetes.io/successCodes: "200"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '60'
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '30'
    alb.ingress.kubernetes.io/healthy-threshold-count: '5'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '3'
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=300

spec:
  ports:
    - port: 80
      targetPort:  5000
      protocol: TCP
  type: NodePort
  selector:
    app: feedservice


apiVersion: v1
kind: Service
metadata:
  name: service b
  namespace: <app name>
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/health"
    alb.ingress.kubernetes.io/successCodes: "200-401"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '60'
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '30'
    alb.ingress.kubernetes.io/healthy-threshold-count: '5'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '3'
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=300

spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: service b

```

When i create the alb using the above config , the alb gets created but the default listener is not mapped to any service but rather 404 error is reported, i can manually set it up to the target group which is not desirable , hence wanted to know if there is a way to do it via config file
