### ISSUE TITLE
[v2] AWS Load Balancer is trying to add target groups from a different load balancer

### ISSUE THREAD

**Issue by avasquez614** [kubernetes-sigs/aws-load-balancer-controller#1566]
Recently, I tried to update the 1.1.8 ALB Ingress Controller of our QA environment to AWS Load Balancer. We have also a production environment that's still using the 1.1.8 ALB Ingress Controller. I followed the migration steps:

1. Create the IAM service account with the IAM role/policy in https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json and the additional IAM permissions https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy_v1_to_v2_additional.json
2. Deleted the ALB Ingress Controller Helm
3. Installed the AWS Load Balancer Controller Helm

Checking the logs of the controller pod, I'm seeing this error:

```
 {"level":"error","ts":1603756088.3558407,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"authoring-ingress","namespace":"craftercms","error":"ValidationError: The followi 
 ng target groups are in a different VPC than load balancer 'arn:aws:elasticloadbalancing:us-east-1:436619279051:loadbalancer/app/60e3284a-craftercms-author-fcfd/2b6ae5420278244e': arn:aws:elasticloadb 
 alancing:us-east-1:436619279051:targetgroup/k8s-crafterc-authorin-a2dac88502/e4ebcf36edb1a5ac\n\tstatus code: 400, request id: df304992-fb4a-42f1-b026-fb5270c91227"}
```

Which seems to indicate that the AWS Load Balancer is trying to somehow add the target groups of the Production environment into the LB of the QA environment. I tried specifying the `vpcId` and the `region` parameters of the Helm but still, it's showing that error. Any ideas?

**Comment by M00nF1sh** [comment]
@avasquez614 Did you specify the cluster-name correctly?
The controller find resource by cluster-name/ingressName. Make sure you are using different clusterName for different clusters

**Comment by avasquez614** [comment]
@M00nF1sh  Yes, I'm specifying cluster name. These are the Helm parameters:

```
  nodeSelector:
    node-type: k8s-support

  clusterName: craftersoftware-cc-v2

  serviceAccount:
    create: false
    name: aws-load-balancer-controller
```

And the controller pod running has these:

```
 spec:                                                                                                                                                                                                    
   containers:                                                                                                                                                                                            
   - args:                                                                                                                                                                                                
     - --cluster-name=<HIDDING CLUSTER NAME>                                                                                                                                                          
     - --ingress-class=alb 
```

**Comment by avasquez614** [comment]
@M00nF1sh Yes, I'm specifying cluster name. These are the Helm parameters:

```
  nodeSelector:
    node-type: k8s-support

  clusterName: <HIDDING CLUSTER NAME>

  serviceAccount:
    create: false
    name: aws-load-balancer-controller
```

And the controller pod running has these:

```
 spec:                                                                                                                                                                                                    
   containers:                                                                                                                                                                                            
   - args:                                                                                                                                                                                                
     - --cluster-name=<HIDDING CLUSTER NAME>                                                                                                                                                          
     - --ingress-class=alb 
```
