### ISSUE TITLE
Redirect from HTTP to HTTPS gives "ssl-redirect" not found

### ISSUE THREAD

**Issue by d3v2null** [kubernetes-sigs/aws-load-balancer-controller#1626]
Hello,

I setup an Ingress using v2 to redirect http traffic into https from one of my app, however despite seeing no issues on the Ingress and resources provisioned by the AWS load balancer controller, I see the following error upon describing my Ingress object;

```sh
Rules:
  Host        Path  Backends
  ----        ----  --------
  *           
              /*   ssl-redirect:use-annotation (<error: endpoints "ssl-redirect" not found>)
              /*   mytestapp:80 (192.168.86.120:8082)
```

My Ingress object is as follows:

```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mytestapp-ingress
  labels:
    helm.sh/chart: mytestapp-0.3.29
    app.kubernetes.io/name: mytestapp
    app.kubernetes.io/instance: mytestapp
    app.kubernetes.io/version: "mytestapp-804cdc03"
    app.kubernetes.io/managed-by: Helm
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:111222333:certificate/****
    alb.ingress.kubernetes.io/group.name: backend-ingress
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/success-codes: 301,302,200
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: mytestapp
              servicePort: 80
```
any hint or suggestion why this error shows up?
