### ISSUE TITLE
separate yaml per ingress path

### ISSUE THREAD

**Issue by Tarang** [kubernetes-sigs/aws-load-balancer-controller#1643]
Is it possible to split this yaml into 2 pieces so each path has its own yaml file. Subsequently this would allow each application to be deployed independently as well.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bechoserver
  namespace: bechoserver
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
spec:
  tls:
  - hosts:
    - b8s.biz
  rules:
    - host: b8s.biz
      http:
        paths:
          - path: /abc
            backend:
              serviceName: echoserver
              servicePort: 80
          - path: /test
            backend:
              serviceName: bechoserver
              servicePort: 80
```
