### ISSUE TITLE
Security group rules not being created for ingress traffic

### ISSUE THREAD

**Issue by sidprak** [kubernetes-sigs/aws-load-balancer-controller#1649]
I've tried creating a NLB using the yaml below. When I create this, security group rules are added for health checks from the load balancer but nothing is added for ingressing traffic. I would expect to see a rule for `1.2.3.4/32`, or at least if i remove this range, I'd expect a rule for `0.0.0.0/`, but neither of them seem to work. Looking in the code, it seems that this might only work for UDP? Is there a reason for this or a workaround? https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/service/nlb/builder.go#L536

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
  name: test
spec:
  externalTrafficPolicy: Local
  healthCheckNodePort: 31135
  loadBalancerSourceRanges:
  - 1.2.3.4/32
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: foo
  type: LoadBalancer
```
