### ISSUE TITLE
NLB service + external-dns: Not properly assigning NLB service address to A record

### ISSUE THREAD

**Issue by Gowiem** [kubernetes-sigs/aws-load-balancer-controller#1652]
Hey folks, 

I've upgraded to using the aws-load-balancer-controller over v1. As part of that, I've gotten rid of using nginx-ingress for our single service that needs an NLB. Since migrating, our external-dns usage is not working properly. I've applied what I would believe are the correct annotations to the Service:

```yaml
    helm.fluxcd.io/antecedent: 'REDACTED'
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: >-
      eipalloc-REDACTED,eipalloc-REDACTED,eipalloc-REDACTED
    service.beta.kubernetes.io/aws-load-balancer-subnets: 'subnet-REDACTED,subnet-REDACTED,subnet-REDACTED'
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    external-dns.alpha.kubernetes.io/hostname=REDACTED
```

With the above, external-dns does run and creates an A record for the given annotation's hostname, but the value of that A record is not the hostname of the NLB or the EIPs that are associated with the NLB. The value is 2 external IP addresses that I've never seen before and cannot find in my cluster.

Our Service is type NodePort. [I've tried using LoadBalancer as suggested by the AWS Documentation](https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html#deploy-lb-controller:~:text=Create%20a%20service%20of%20type%20LoadBalancer), but it seems that is v1.20 K8s feature which we're not on. 

What am I doing wrong here? Any direction anyone can give me would be much appreciated as I'd like to know how I can / should debug this further.
