### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by yspreen** [kubernetes-sigs/aws-load-balancer-controller#1654]
I'm using the following ingress config: ( heavily inspired by @d3v2null )

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "nginx-ingress"
  namespace: "default"
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect:
      '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:00xxx9:certificate/faaxxxfe
    alb.ingress.kubernetes.io/group.name: backend-ingress
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/success-codes: 301,302,200
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: nginx-service
              servicePort: 82
```

The Nginx service simply returns "hi" on port 82. If I curl the server (CNAME from our domain to ALB domain name), I get back the right result. However, on chrome and any other browser I tested, it results in a NET::ERR_CERT_AUTHORITY_INVALID error.

I really have no clue what's wrong though.

---

edit: Starting to think this has something to do with the self-signed certificates that the controller mounts and which are usually created by cert-manager. Because I'm running on fargate, I skipped that step and tried to create my own certs. Apparently something went wrong there and causes issues way down the line now?
