### ISSUE TITLE
NLB deployment failing to run

### ISSUE THREAD

**Issue by laxathom** [kubernetes-sigs/aws-load-balancer-controller#1659]
Hey folks,

I currently am having some issues with having a running aws-load-balancer-controller.
I'm running a fargate cluster located in **ap-southweast-1** where I was able to deploy an ALB controller w/o issue. I needed to migrate to an NLB + ALB setup and followed this [guideline](https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html).
Unfortunetaly, the container keeps failing with the following error
```
{"level":"info","ts":1605561917.746771,"msg":"version","GitVersion":"v2.0.1","GitCommit":"b28cc08c5451da98383b345592c4d8cd57da2afb","BuildDate":"2020-11-11T18:57:40+0000"}
{"level":"error","ts":1605561924.0503578,"logger":"setup","msg":"unable to initialize AWS cloud","error":"failed to introspect region from EC2Metadata, specify --aws-region instead if EC2Metadata is unavailable: EC2MetadataRequestError: failed to get EC2 instance identity document\ncaused by: RequestError: send request failed\ncaused by: Get \"http://169.254.169.254/latest/dynamic/instance-identity/document\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
```
One thing I noticed from the guideline is that the provided iam-policy at step 5.c doesn't seem right. When I look this policy up on the web console, it says that provided resources is unrecognize (I don't thinl this has somethign to do with the error).

So, I tried to build a new fargate cluster from scratch (same region) and proceed as the guideline suggested. I also checked this guideline [here](https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller) and still facing the same issue.

**Comment by kishorj** [comment]
If you are running the controller on Fargate, the EC2 metadata isn't available, so you will have to manually specify the region and the vpc id. For helm installation, you will need to specify additional parameters `--set region=<AWS_REGION> --set vpcId=<AWS_VPC_ID>`. This issue is similar to #1622

**Comment by kishorj** [comment]
If you are not installing the Helm chart, you will run into  issues similar to #1606. The workaround is to either run the cert manager in EC2, or manually modify the yaml manifest.

**Comment by laxathom** [comment]
Thanks, @kishorj, that actually was my first guess to look at but, the pod info was saying it was running w/ the right region.
```yaml
---
    Liveness:       http-get http://:61779/healthz delay=30s timeout=10s period=10s #success=1 #failure=2
    Environment:
      AWS_DEFAULT_REGION:           ap-southeast-1
      AWS_REGION:                   ap-southeast-1
      AWS_ROLE_ARN:                 arn:aws:iam::****:role/eksctl-stg-addon-iamserviceaccount-kub-Role1-*****
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
---
```
I guess the env is not that relevant for fargate. thanks for the info
