### ISSUE TITLE
How to makes changes to the default rule for a listener?

### ISSUE THREAD

**Issue by C2L2C** [kubernetes-sigs/aws-load-balancer-controller#1672]
My use case is to enable SSL redirection from port 80 to 443 The problem is, even after I use the `ssl-redirection` annotation, it works but creates the SSL redirection rules per host on the 80 listener, which is not efficient. Another way to do this would be to add a default SSL redirection rule to the listener on port 80 but I can't seem to find it in the docs. Please help!!

**Comment by M00nF1sh** [comment]
@C2L2C 
Currently, you can only achieve it using our IngressGroup feature.
I.e. Define two Ingress one for 80 and one for 443, and make them belong to same group. for the Ingress with port 80, use the ssl redirect action in its `Ingress.spec.backend`.
Will this suit your need?

Also, i think we should consider offer a easier way to configure HTTP_HTTPS redirect, something in my mind like 
```
alb.ingress.kubernetes.io/ssl-redirect: "443"
```
And the semantic of above annotation is redirect all HTTP port to this 443 port.

**Comment by C2L2C** [comment]
@M00nF1sh  I will try the ingress group method as you said. Is there a way to change the default rule for a listener through the controller?

**Comment by Hunter-Thompson** [comment]
> @C2L2C
> Currently, you can only achieve it using our IngressGroup feature.
> I.e. Define two Ingress one for 80 and one for 443, and make them belong to same group. for the Ingress with port 80, use the ssl redirect action in its `Ingress.spec.backend`.
> Will this suit your need?
> 
> Also, i think we should consider offer a easier way to configure HTTP_HTTPS redirect, something in my mind like
> 
> ```
> alb.ingress.kubernetes.io/ssl-redirect: "443"
> ```
> 
> And the semantic of above annotation is redirect all HTTP port to this 443 port.

Can confirm that it works using the `group.name` annotation, thanks, this freed up almost 40 rules on our ALB.

Port 80 ingress config : 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "nginx-p80"
  namespace: "default"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: >
     {"type": "redirect", "redirectconfig": { "protocol": "HTTPS", "port": "443", "statuscode": "HTTP_301"}}
    alb.ingress.kubernetes.io/group.name: nginx-ingress
spec:
  rules:
    - http:
        paths:
         - path: /*
           backend:
             serviceName: ssl-redirect
             servicePort: use-annotation
```
Port 443 ingress config : 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "nginx-p443"
  namespace: "default"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: xxxxxxxxxxxxxx
    alb.ingress.kubernetes.io/group.name: nginx-ingress
spec:
  rules:
    - host: nginx.example.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: "nginx-svc"
              servicePort: 80
```
Important thing to note above is that we have the same `alb.ingress.kubernetes.io/group.name: nginx-ingress` annotation for both ingress, this makes sure that we use the same ALB.
