### ISSUE TITLE
Error: InvalidParameter: 1 validation error(s) found.\n- minimum field value of 1, CreateTargetGroupInput.Port.\n

### ISSUE THREAD

**Issue by bugok** [kubernetes-sigs/aws-load-balancer-controller#1695]
Context: Running using helm, chart version 1.0.8, application version 2.0.1. 
I've applied the crds (using `kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"`) and installed alb ingress controller using helm. 

When deploying the following ingress (as part of my application packaged in a helm chart), I get the mentioned error: 

```
# Source: myapp/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myapp
  labels:
    helm.sh/chart: myapp-0.1.6
    app.kubernetes.io/name: myapp
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
    external-dns.alpha.kubernetes.io/hostname: "sub.mydomain.com"
spec:
  rules:
    - host: "*.sub.mydomain.com"
      http:
        paths:
          - path: "/"
            backend:
              serviceName: myapp
              servicePort: 80
```

I'd be happy to supply more information.
