### ISSUE TITLE
Paths of type "Prefix" do not work as expected

### ISSUE THREAD

**Issue by Nuru** [kubernetes-sigs/aws-load-balancer-controller#1702]
According to the [Kubernetes documentatio](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types), a `pathType` of `Prefix` and value `/` should match all paths, but with `aws-load-balancer-controller` v2.0.1 it only matches `/`

My ingress:

```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: echo-server
  namespace: echo
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  tls:
    - hosts:
        - echo.example.com
  rules:
    - host: echo.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: echo-server
              servicePort: http

```
gives me `404 Not Found` errors for all paths except exactly `/`:
```
HTTP/2 404 
server: awselb/2.0
```
It should behave exactly the same way as the implementation dependent `/*`. 

Having type `Prefix` work as expected is very important for portability.

**Comment by M00nF1sh** [comment]
@Nuru 
We only support ImplementationSpecific currently. Prefix PathType is planned.
/kind feature

**Comment by kishorj** [comment]
PR #1772

**Comment by kishorj** [comment]
Feature supported in v2.2.0 release

**Comment by youzipi** [comment]
> Feature supported in v2.2.0 release

@kishorj 
is there any way to achieve the `prefix` rule in before version?
we use `v1.1.5` ☹️

**Comment by youzipi** [comment]
> > Feature supported in v2.2.0 release
> 
> @kishorj is there any way to achieve the `prefix` rule in before version? we use `v1.1.5` ☹️

is these two configuration can achieve the same effect?
if so, why we need the prefix config? it provide better performance with limited scenario?
```yaml
      - path: /actuator*
        pathType: ImplementationSpecific

      - path: /actuator
        pathType: Prefix
```
