### ISSUE TITLE
add gRPC ingress example

### ISSUE THREAD

**Issue by tdyas** [kubernetes-sigs/aws-load-balancer-controller#1706]
Are there any available examples of how to enable a GRPC-only endpoint?

I'm trying to use v2.1.0 of the controller on EKS and the controller reports the following error:

```
{"level":"error","ts":1606949022.5301569,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"prod-buildgrid-frontend2","namespace":"prod","error":"InvalidParameter: 1 validation error(s) found.\n- minimum field value of 1, CreateTargetGroupInput.Port.\n"}
```

I can supply the annotations I'm using and the Ingress resource, but would rather first try and use a known-good example of how to use gRPC, and then see if the issue still persists.

(As for the error at issue, looking at the resource model output to the controller's log, the `Port` attribute for the `AWS::ElasticLoadBalancingV2::TargetGroup` resource is set to `0` instead of being set to the port on which the service is listening.)

**Comment by kishorj** [comment]
This issue is similar to #1656.

For instance mode, you'd need to use service of type NodePort instead of the default type ClusterIP.

**Comment by tdyas** [comment]
Using NodePort mode fixed the issue for me. Thanks!

Also, what is the right place to document this? (I can submit a PR.)

**Comment by kishorj** [comment]
It is documented in these places - 
https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/spec/
https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/annotations/#target-type

Let us know if it is not clear, or feel free to raise a docs PR.

**Comment by kishorj** [comment]
We will add a walkthrough example for gRPC.

**Comment by dschunack** [comment]
Hi,

we use the following code example for gRPC with ingress and ALB.
Maybe it helps.
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"RedirectConfig":{"Port":"443","Protocol":"HTTPS","StatusCode":"HTTP_301"},"Type":"redirect"}'
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: CERTIFICATES_ARN
    alb.ingress.kubernetes.io/group.name: GROUPING_NAME
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=600
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  name: ALB-NAME
  namespace: NAMESPACE
spec:
  rules:
  - host: FQDN
    http:
      paths:
      - backend:
          serviceName: NODEPORT_SERVICE
          servicePort: PORT OR PROTOCOL (GRPC Port)
        path: /*
```
