### ISSUE TITLE
wrong SG port for TargetGroupBindings in instance mode

### ISSUE THREAD

**Issue by MartinEmrich** [kubernetes-sigs/aws-load-balancer-controller#1712]
Hello!

When configuring a targetGroupBinding for a Target Group in instance mode, it registers every K8s node with the service NodePort (31000 plus X).

But the security Groups generated are for the port of the service. Example:

````
apiVersion: v1
kind: Service
metadata:
  name: someservice
spec:
  selector:
    name: stateservice
  type: NodePort
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: someservice
spec:
  serviceRef:
    name: someservice
    port: 1883
  targetGroupARN: arn:aws:elasticloadbalancing:eu-central-1:xxx
  # targetType: instance # setting this makes no difference
  networking:
    ingress:
    - from:
      - ipBlock:
          cidr: 10.41.0.0/16
      ports:
      - port: 1883
        protocol: TCP
````

Indeed it creates a security group rule allowing port 1883 from 10.41.0.0/16. 
But K8s assigns e.g. a nodeport of 31252 to the service, so the security group rule should use that port... or am I missing something?

The documentation (https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/targetgroupbinding/spec/#elbv2.k8s.aws/v1beta1.NetworkingPort) states " if port is unspecified, it defaults to all ports.". But if I set

````
     ports: []
````
No security group rule is created at all.

**Comment by MartinEmrich** [comment]
FYI: as a workaround, I specified the `NodePort` in the service and added it to the ports list. But I'd prefer the automatic port assignment by K8s, to avoid conflicts.

**Comment by kishorj** [comment]
If you are using NLB, then we don't support instance mode yet. Did you create the targetgroupbinding manually?

If you want to allow all ports, you can specify the following for the ports,
```
      ports:
      - protocol: TCP
```
We recommend more restricted security group configuration.

**Comment by MartinEmrich** [comment]
Yes, I created the TargetGroupBinding manually... I did not know that Instance Mode ist not supported yet. But with my little workaround, it works fine... Are there any traps in front of me if I keep it that way? Will instance mode be supported in the future?

Until AWS EKS supports pod topology spread constraints, It's either instance mode or cross-zone load balancing to guarantee availability from every AZ....

Thanks,
Martin

**Comment by ranupratapsingh** [comment]
Hi all,
I am also facing the same issue. I am trying to follow this guide. https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/targetgroupbinding/targetgroupbinding/.

The targets are getting registered but the security group rules to accept the traffic from existing ALB is not getting added in the node's security group.

As a newbie to this, I figured that the work around is to have static NodePort in the service and open ingress rule on the basis of CIDR but this feels like hardcoding.

Is this still not supported in 2.4 ?

**Comment by ranupratapsingh** [comment]
Hi all,
I figured this out from [the spec doc section here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/targetgroupbinding/spec/#elbv2.k8s.aws/v1beta1.SecurityGroup).

We can specify networking to use source target group like this 

```
  serviceRef:
    name: auth-prod-service # route traffic to the auth-prod-service
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:ap-south-1:<your-tg-id>
  networking: 
    ingress:
      - from:
        - securityGroup: sg-<your-alb-sg-id>
```
