### ISSUE TITLE
[v2] ALB is deleted and recreated

### ISSUE THREAD

**Issue by tkms0106** [kubernetes-sigs/aws-load-balancer-controller#1717]
when running `kubectl apply -f ingresses.yaml` .

Is it intended behavior? (Perhaps yes, I guess)
If that's the case, what was wrong with me?

# Status before applying

- One Ingress resource in default Namespace
- One ALB (created by v1 controller)
- Migration of controller to v2(2.1.0) is completed

# What I applied

Two ingresses in one yaml

```yaml
# pseudo manifest
# existing default ingress
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/group.name: foo-group # changed from implicit IngressGroup
<some other annotations>
spec:
  rules:
<some rules A>
---
# newly added ingress in another namespace
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: bar-namespace
  annotations:
    alb.ingress.kubernetes.io/group.name: foo-group
<some other annotations same as above ingress>
spec:
  rules:
<some rules B>
```

# What I expected

`<some rules B>` are added to existing ALB
