### ISSUE TITLE
How to write IngressClass

### ISSUE THREAD

**Issue by cw-sakamoto** [kubernetes-sigs/aws-load-balancer-controller#1721]
Starting from 2.1.0, aws-load-balancer-controller supports for IngressClass, but is there any documentation on how to write `IngressClass`?

I would like to know what can be specified for `spec.controller` and what can be specified for `spec.parameter`.

https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#ingress-controller-support

**Comment by kishorj** [comment]
Example ingressclass 
```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: example-ingress-class
spec:
  controller: ingress.k8s.aws/alb
```

The `spec.controller` is string, and in the current version (v2.1.0) the supported value is  `ingress.k8s.aws/alb`. The `spec.parameter` is ignored in `v2.1.0`, it will be supported in future releases.
