### ISSUE TITLE
Ingress controller overwrites an existing load balancer

### ISSUE THREAD

**Issue by kdyakova** [kubernetes-sigs/aws-load-balancer-controller#1725]
I have two helm charts for two different services. Here is how the definition of the ingress controller looks like in both of them:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.deployment.container.liveness_probe_path }}
    alb.ingress.kubernetes.io/inbound-cidrs: {{ .Values.ingress.cidr_bastion }}, {{ .Values.ingress.cidr_kong }}, {{ .Values.ingress.cidr_vpn }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.alb_scheme }}
    alb.ingress.kubernetes.io/tags: "Name=CMP-{{ .Values.common.service_name }}-service,Environment={{ .Values.common.environment }},ServiceCatalogueId={{ .Values.common.service_catalogue_id }},ServiceName={{ .Values.common.service_name }}"
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.common.service_name }}{{ .Values.common.environment_suffix }}.{{ .Values.ingress.external_dns }}
    kubernetes.io/ingress.class: alb
  name: sun-savers-{{ .Values.common.service_name }}-ingress{{ .Values.common.environment_suffix }}
  namespace: sun-savers-{{ .Values.common.environment }}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ .Values.service.name }}{{ .Values.common.environment_suffix }}
          servicePort: 8080
        path: /*
```

Those charts are used for deploying PR and UAT environments in the same AWS EKS cluster. Usually, it works great, but on very rare occasions(I have seen this 2 times for 5 months) two deployments start using the same load balancer. 

Example: Service A has been deployed with ALB 1 and the corresponding tags. A few hours later service B is deployed and it starts using ALB 1 and overwrites its tags. When I list the ingresses in EKS I see they both have the same addresses.

I tried deleting the deployments. Deployed Service 1 with the same suffix - it created a new load balancer ALB 2. After that, I deployed Service 2 with the same suffix and the same happened.

here is the Kubernetes version I am on:
```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
