### ISSUE TITLE
BUG: Reconcile error InvalidIdentityToken due to use of regional STS endpoint

### ISSUE THREAD

**Issue by toytown** [kubernetes-sigs/aws-load-balancer-controller#1728]
I am using EKS v1.18 with Fargate profile in public +  private mode with IRSA enabled. The Fargate is deployed to a private cluster and Load balancer is internal. When I try to switch OIDC provider client or audience setting to use regional STS endpoint it gives InvalidIdentityToken error. But if switched to global STS endpoint works fine. I suppose this behaviour is a bug.

I configured  OIDC to use regional sts and this did NOT work. If I use global STS endpoint it works and the yaml file below gets deployed and LB gets created successfully. Due to customer'S network policy global STS endpoints are not allowed or blocked by firewall.

OIDC setting (NOT Working)
```
resource "aws_iam_openid_connect_provider" "oidc_provider" {
  client_id_list  = ["sts.eu-central-1.amazonaws.com"]
  thumbprint_list = [var.eks_oidc_root_ca_thumbprint]
  url             = module.eks.cluster_oidc_issuer_url
}

variable "eks_oidc_root_ca_thumbprint" {
  type        = string
  default     = "9ab2f38d7bbd0ef68a5b82ab84b56508fe2a6632"
  
}
```

OIDC Working with global STS endpoint
```
resource "aws_iam_openid_connect_provider" "oidc_provider" {
  client_id_list  = ["sts.amazonaws.com"]
  thumbprint_list = [var.eks_oidc_root_ca_thumbprint]
  url             = module.eks.cluster_oidc_issuer_url
}


```

EKS version = 1.18, Fargate
ALB version = 2.1.0 . I also activated target bindings
Deployment : public endpoint + private (Fargate cluster) 

I even setup the ALB container with environment variable **AWS_STS_REGIONAL_ENDPOINTS=regional**
Also this did not help and still getting error "failed to retrieve credentials"

```
{"level":"info","ts":1608017225.6562812,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"kube-system/ex-nginx-ingress\",\"resources\":{}}"}
{"level":"error","ts":1608017325.0324068,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ex-nginx-ingress","namespace":"kube-system","error":"WebIdentityErr: failed to retrieve credentials\ncaused by: InvalidIdentityToken: Incorrect token audience\n\tstatus code: 400, request id: df2bcf28-74b8-475f-9d09-0a10906be05f"}
{"level":"info","ts":1608017325.0328588,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"kube-system/ex-nginx-ingress\",\"resources\":{}}"}
{"level":"error","ts":1608017420.7906892,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ex-nginx-ingress","namespace":"kube-system","error":"WebIdentityErr: failed to retrieve credentials\ncaused by: InvalidIdentityToken: Incorrect token audience\n\tstatus code: 400, request id: a6bf46bd-1b7f-47c9-9eb8-11263891f8ab"}
{"level":"info","ts":1608017420.7909899,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"kube-system/ex-nginx-ingress\",\"resources\":{}}"}
```

OIDC STS setting (NOT working)

![image](https://user-images.githubusercontent.com/535868/102195369-c7b26e00-3ebe-11eb-951b-425038a3a6d5.png)

**ngix-deployment yaml**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex-nginx
  namespace: kube-system
  labels:
    app: ex-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex-nginx
  template:
    metadata:
      labels:
        app: ex-nginx
    spec:
      containers:
      - name: ex-nginx
        image: nginx:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ex-nginx-service
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: ex-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ex-nginx-ingress
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internal
spec:
  rules: 
    - host: internal-example-test.ossca.cloud
    - http: 
        paths: 
          - backend: 
              serviceName: ex-nginx-service
              servicePort: 80 
            path: /* 


```
