### ISSUE TITLE
Security Group ports attached to node security group are overly broad

### ISSUE THREAD

**Issue by chrisleck** [kubernetes-sigs/aws-load-balancer-controller#1731]
I have three ingresses, one each with a different port set via `alb.ingress.kubernetes.io/listen-ports`: (80, 443, 8081) which route to various pods (via named ports) all serving on port 80.

Example of one of these: 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: <redacted>
    alb.ingress.kubernetes.io/group.name: public
    alb.ingress.kubernetes.io/group.order: "2"
    alb.ingress.kubernetes.io/healthcheck-path: <redacted>
    alb.ingress.kubernetes.io/healthcheck-port: "12345"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: <redacted>
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/target-type: ip
  finalizers:
  - group.ingress.k8s.aws/public
  generation: 1
  labels:
    name: ingress-https
  name: ingress-https
  namespace: passthrough
spec:
  rules:
  - host: <redacted>.io
    http:
      paths:
      - backend:
          serviceName: router
          servicePort: app
        path: /*
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - <redacted>.io
```

This results in three targetGroupBindings being autogenerated, none of which specify a port number?
```
spec:
  networking:
    ingress:
    - from:
      - securityGroup:
          groupID: sg-0a5925f1b155aa9ac
      ports:
      - protocol: TCP
  serviceRef:
    name: router
    port: app
  targetGroupARN: <redacted>
  targetType: ip
```

The resulting inbound SG rule attached to the node SG has all TCP ports open, but should only open specific ports - I would imagine just the ports the pod services are running on?  In this case, just port 80.
