### ISSUE TITLE
[v2] Wildcard in host

### ISSUE THREAD

**Issue by jtprom** [kubernetes-sigs/aws-load-balancer-controller#1739]
With the release of v2 and the introduction of `alb.ingress.kubernetes.io/group.name` the suggested workaround in a similar ticket [#987](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/987) does not work when using multiple ingresses with the same `group.name`.

Is there a new workaround in v2 or plans to support this in the next few releases? 

**I would like to be able to do this**
```
---
kind: Ingress
metadata:
  name: login
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports:  [{"HTTPS":443}]
    alb.ingress.kubernetes.io/success-codes: 200
    alb.ingress.kubernetes.io/group.name: ui-dev

spec:
  rules:
    - host: login-*.dev.sample.com
      http:
        paths:
          - backend:
              serviceName: login
              servicePort: 8080
---
kind: Ingress
metadata:
  name: signup
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports:  [{"HTTPS":443}]
    alb.ingress.kubernetes.io/success-codes: 200
    alb.ingress.kubernetes.io/group.name: ui-dev

spec:
  rules:
    - host: signup-*.dev.sample.com
      http:
        paths:
          - backend:
              serviceName: signup
              servicePort: 8080
```

**Comment by M00nF1sh** [comment]
Hi @jtprom,
The Ingress spec in k8s<1.18 doesn't allow wildcard in host. and in k8s>=1.18, Ingress allow a single wildcard in host, e.g.(*.signup.dev.example.com).

For your case, the same workaround also works with IngressGroup :D, e.g. to achieve the desired effect, your Ingresses should look like below:
```
kind: Ingress
metadata:
  name: login
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports:  [{"HTTPS":443}]
    alb.ingress.kubernetes.io/success-codes: 200
    alb.ingress.kubernetes.io/group.name: ui-dev
    alb.ingress.kubernetes.io/conditions.login: >
      [{"Field":"host-header","HostHeaderConfig":{"Values":["login-*.dev.sample.com"]}}]
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: login
              servicePort: 8080
---
kind: Ingress
metadata:
  name: signup
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports:  [{"HTTPS":443}]
    alb.ingress.kubernetes.io/success-codes: 200
    alb.ingress.kubernetes.io/group.name: ui-dev
    alb.ingress.kubernetes.io/conditions.signup: >
      [{"Field":"host-header","HostHeaderConfig":{"Values":["signup-*.dev.sample.com"]}}]
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: signup
              servicePort: 8080
```

**Comment by jtprom** [comment]
Thanks!

**Comment by ob-uk** [comment]
I'm trying something very similar but it does not work. Here is my Ingress object: 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    <some auth related annotations>
    alb.ingress.kubernetes.io/group.name: ui
    alb.ingress.kubernetes.io/group.order: "305"
    alb.ingress.kubernetes.io/healthcheck-path: /ping
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=300
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/conditions.test: >
      [{"field":"host-header","hostHeaderConfig":{"values":["test-*.trial.abcd.xyz"]}}]
  labels:
    app: test-wildcard
  name: test-wildcard
  namespace: tester
spec:
  ingressClassName: alb
  rules:
  - host: test.trial.abcd.xyz
     http:
       paths:
       - backend:
            service:
              name: test
              port:
                number: 80
          path: /
          pathType: Prefix
```

What am I doing wrong here? Going to https://test.trial.abcd.xyz/ works but doing something like https://test-abcd123.trial.abcd.xyz does not. 

I also looked at the documentation for the [conditions annotation](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#conditions) here but it does not mention any wildcards. Am I just understanding this functionality wrong or is something off with my configuration? 

Thanks!
