### ISSUE TITLE
Loop when defining custom ssl redirect

### ISSUE THREAD

**Issue by apolegoshko** [kubernetes-sigs/aws-load-balancer-controller#1752]
Hey there,

I'm using snippet below, to satisfy ([ELBv2.1] Application Load Balancer should be configured to redirect all HTTP requests to HTTPS)[https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html]. Unfortunately, I'm getting an error in logs:

```txt
{"level":"error","ts":1609676859.1565235,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"my-app","namespace":"default","error":"InvalidLoadBalancerAction: The redirect configuration is not valid because it creates a loop.\n\tstatus code: 400, request id: XXXXX-XXXXX-XXXX-XXX-XXXX"}
```

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-app
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: /stress/health
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: "80"
    alb.ingress.kubernetes.io/certificate-arn: XXXXXXXXXXXXXXXXXXXXX
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: >-
      {   
        "Type": "redirect",
        "RedirectConfig": {
          "URI": "https://#{host}/#{path}?#{query}",
          "StatusCode": "HTTP_301"
        }   
      } 
spec:
  backend:
      serviceName: ssl-redirect
      servicePort: use-annotation
  rules:
    - host: my-app.example.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: "my-app-service"
              servicePort: 80
```

Setup:
- aws lb controller installed via latest helm chart with latest image

```yaml
k get deploy aws-lb-controller-aws-load-balancer-controller -oyaml | grep image
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.1.0
```

**Comment by M00nF1sh** [comment]
Hi @apolegoshko 
The HTTP->SSL redirect trick don't work for the default Ingress rule(Ingress.spec.backend). The HTTPS port also need a default rule, and it cannot be a redirect.

The correct way to implement HTTP->SSL redirect without using IngressGroup for your example is.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-app
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: /stress/health
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: "80"
    alb.ingress.kubernetes.io/certificate-arn: XXXXXXXXXXXXXXXXXXXXX
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: >-
      {   
        "Type": "redirect",
        "RedirectConfig": {
          "URI": "https://#{host}/#{path}?#{query}",
          "StatusCode": "HTTP_301"
        }   
      } 
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
    - host: my-app.example.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: "my-app-service"
              servicePort: 80
``` 
Alternatively, with IngressGroup feature, you can define two Ingress one for HTTP port, another one for HTTPS port. and use the `Ingress.spec.backend` with a ssl-redirect action annotation for the Ingress with HTTP port only.

BTW, we'll provide a dedicated annotation to configure HTTP->HTTPS redirect easier in next minor release.

**Comment by apolegoshko** [comment]
Hey @M00nF1sh, thanks for quick response. I've already tried example you've provided above before opening issue here, http -> https redirect works as expected, but it's not accepted by AWS SecurityHub standards. That the main reason to clarify things.

Thanks for letting us know about upcoming release feature to implement this.

**Comment by apolegoshko** [comment]
Thanks @M00nF1sh for your suggestion with ingressGroup feature (Please note that ssl-redirect action is actually a bit different as in example above). 

Posting an example, which works for me and it's compliant according [AWS Foundational Security Best Practices controls](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html) ([ELBv2.1] Application Load Balancer should be configured to redirect all HTTP requests to HTTPS)

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-app-http
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: my-app
    alb.ingress.kubernetes.io/group.order: '1'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: >-
        {
            "Type": "redirect",
            "RedirectConfig": {
                "Protocol": "HTTPS",
                "Port": "443",
                "Host": "#{host}",
                "Path": "/#{path}",
                "Query": "#{query}",
                "StatusCode": "HTTP_301"
            }
        }
spec:
  backend:
    serviceName: ssl-redirect
    servicePort: use-annotation
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-app-https
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: my-app
    alb.ingress.kubernetes.io/group.order: '2'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: "80"
    alb.ingress.kubernetes.io/certificate-arn: <arn:aws:acm:us-east-1:XXXXXXXXXXXXXX:certificate/XXXXXXXXXXXXXXXXXXXXX >
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
spec:
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: "my-app-service"
              servicePort: 80
```

![Screenshot 2021-01-05 at 09 19 55](https://user-images.githubusercontent.com/19555411/103623592-9a466680-4f38-11eb-84ff-6b0c1b35b907.png)
