### ISSUE TITLE
Using ingressClass, the status section is updated with the IP of the node

### ISSUE THREAD

**Issue by genehand** [kubernetes-sigs/aws-load-balancer-controller#1755]
After upgrading to EKS 1.18, I'm trying out v2.1.0 for the new `IngressClass` support.  It's mostly working but I'm seeing odd behavior in the status section.  When an ingress is first created I see the standard output:

```
status:
  loadBalancer:
    ingress:
    - hostname: k8s-ingresss-ambassad-<unique id>.us-east-1.elb.amazonaws.com
```

However after ~30s, it's updated to:

```
status:
  loadBalancer:
    ingress:
    - ip: 10.8.29.186
```

This IP is for the node where the aws-load-balancer-controller is running (not the pod IP).  external-dns then uses this field to update Route53 with the internal IP.  Turning on debug logging, I don't see anything additional logged when this field changes.

If I remove the `ingressClassName` field and go back to the `kubernetes.io/ingress.class` annotation, the status remains with the public hostname as expected.  Here are my test resources:

```
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: aws-load-balancer
spec:
  controller: ingress.k8s.aws/alb
```

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  name: ambassador
  namespace: ingress-system
spec:
  ingressClassName: aws-load-balancer
  rules:
  - host: '*.example.com'
    http:
      paths:
      - backend:
          serviceName: ambassador
          servicePort: 80
        path: /*
```
