### ISSUE TITLE
Missing validation when using Annotation

### ISSUE THREAD

**Issue by ozaditya** [kubernetes-sigs/aws-load-balancer-controller#1756]
While using creating service with target type set as IP in case NLB. I have noted that calls goes via Load balancer controller but there is no validation when using annotations.

Example to configure backend target group protocol to TLS value should be passed as ssl because service accept parameter value as http,https,tcp,ssl only but in all NLB documentation its referred as TLS everywhere so I believe this annotation field should be updated to TLS
-------
service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
-------
Also, NLB don't except http and https as backend protocol but neither service through any error in events nor any validation is in place and default protocol is set as TCP 

It will be good to have some validations in place.

**Comment by M00nF1sh** [comment]
/kind feature
we currently don't have any webhooks for service/ingress, so there isn't validation in place. we'll add them in future releases

**Comment by ArchiFleKs** [comment]
It seems this `service.beta.kubernetes.io/aws-load-balancer-backend-protocol` is not implemented ? I cannot find it in the code

**Comment by mlazowik** [comment]
@ArchiFleKs  see here:
* https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/da8951f80521651e0a1ffe1361c011d6baad7706/pkg/annotations/constants.go#L65
* https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/8d7b991af8297ff2a35b0d67b04088c568dfef11/pkg/service/model_build_listener.go#L123
* https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/8d7b991af8297ff2a35b0d67b04088c568dfef11/pkg/service/model_build_listener.go#L164
* https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/8d7b991af8297ff2a35b0d67b04088c568dfef11/pkg/service/model_build_listener.go#L41

**Comment by ArchiFleKs** [comment]
@mlazowik thanks, does setting `aws-load-balancer-backend-protocol` influence the listener ?  My end goal is to have a listener with   `TCP_UDP` so I can get source IP working with NLB-IP

**Comment by ArchiFleKs** [comment]
I have just tested with a service with the following annotation:
```
# Source: pocket-full-meta/charts/pocket-full-4/templates/service.yaml                                                                                                                                                                                                                                                                                                                                                                 
apiVersion: v1                                                                                                                                                                                                                                                                                                                                                                                                                         
kind: Service                                                                                                                                                                                                                                                                                                                                                                                                                          
metadata:                                                                                                                                                                                                                                                                                                                                                                                                                              
  name: RELEASE-NAME                                                                                                                                                                                                                                                                                                                                                                             
  annotations:                                                                                                                                                                                                                                                                                                                                                                                                                         
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"                                                                                                                                                                                                                                                                                                                                                                        
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "TCP_UDP"                                                                                                                                                                                                                                                                                                                                                           
    external-dns.alpha.kubernetes.io/hostname: "4.pocket-full.demo.io"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
spec:                                                                                                                                                                                                                                                                                                                                                                                                                                  
  publishNotReadyAddresses: true                                                                                                                                                                                                                                                                                                                                                                                                       
  type: LoadBalancer                                                                                                                                                                                                                                                                                                                                                                                                                   
  ports:                                                                                                                                                                                                                                                                                                                                                                                                                               
    - port: 26656                                                                                                                                                                                                                                                                                                                                                                                                                      
      targetPort: tendermint-p2p                                                                                                                                                                                                                                                                                                                                                                                                       
      protocol: TCP                                                                                                                                                                                                                                                                                                                                                                                                                    
      name: tendermint-p2p                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  selector:                                                                                                                                                                                                                                                                                                                                                                                                                            
    app.kubernetes.io/name: pocket-full-4                                                                                                                                                                                                                                                                                                                                                                                              
    app.kubernetes.io/instance: RELEASE-NAME                       
```

I'm still getting a TCP listener and not a TCP_UDP
