### ISSUE TITLE
FailedUpdateStatus keeps being reported continuously.

### ISSUE THREAD

**Issue by nanasi880** [kubernetes-sigs/aws-load-balancer-controller#1765]
I am using TargetGroupBinding in EKS.
TargetGroupBinding is working and the request is reaching the Pod, but it keeps reporting the following error continuously.
```
FailedUpdateStatus: Failed update status due to failed to update targetGroupBinding status: default/administrator: targetgroupbindings.elbv2.k8s.aws "administrator" not found
```
Which specific resources are missing in this error?

--- Information about EKS and installation ---

EKS Cluster Version: 1.18

I installed aws-load-balancer-controller in the following way.
```
helm upgrade --install aws-load-balancer-controller \
    eks/aws-load-balancer-controller \
    --version 1.1.1 \
    -n kube-system \
    --set clusterName=my-cluster-name \
    --set serviceAccount.create=false \
    --set serviceAccount.name=aws-load-balancer-controller \
    --set replicaCount=1 \
    --set image.repository=602401143452.dkr.ecr.ap-northeast-1.amazonaws.com/amazon/aws-load-balancer-controller \
    --set resources.limits.cpu="100m" \
    --set resources.limits.memory="128Mi"
```

Then, I bound the service named administrator and the target group in the default namespace with the following yaml.
```
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: administrator
  namespace: default
spec:
  targetGroupARN: ***my-target-group-arn***
  targetType: "ip"
  serviceRef:
    name: administrator-service
    port: 80
  networking:
    ingress:
      - from:
        - securityGroup:
            groupID: ***my-security-group-id***
        ports:
          - protocol: TCP
            port: 80
```
