### ISSUE TITLE
Specifying attributes for a group load balancer only once

### ISSUE THREAD

**Issue by betabandido** [kubernetes-sigs/aws-load-balancer-controller#1768]
We are trying to move from using an NLB + nginx ingress controller to using the AWS Load Balancer Controller. We want to share a single controller among multiple applications. We have managed to do so by using the alb.ingress.kubernetes.io/group.name annotation.

This shared controller will also share the same configuration for all the applications it serves traffic to (e.g., the SSL certificate as we use a wildcard one, the port where traffic is served, whether access logs are enabled, etc.). Right now we add that configuration to every single ingress resource we create in the cluster, but we would like to add it only once.

For instance, in the case of the nginx ingress controller, it is possible to add annotations to the service resource, then all the ingress resources created would inherit that configuration. Is this possible in any way with the AWS Load Balancer Controller?

Another consequence we are facing is the fact the shared load balancer is not created right away. Instead we need to wait for an application that has an ingress resource to be created on the cluster. This makes it impossible for us to create a Route 53 entry that points to the load balancer or create a WAF for the ALB as part of the cluster setup.

If there is no way to do this, would you consider adding such a feature? I think it would greatly simplify managing configuration related to the load balancer.

**Comment by betabandido** [comment]
As an update, we tried creating an ALB beforehand and later use target group bindings (as instructed here: https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/targetgroupbinding/targetgroupbinding/).

While it worked, it turns out there is quite a bit on overhead when going down that route. For instance, in order to have the ALB send traffic to different services based on the host name, we would need to manually modify the listeners' rules associated to the ALB. We would rather have the AWS Load Balancer Controller do that work for us.

In my mind, it should be possible to have some form of CRD that would create the ALB, and later ingress resources would use that ALB instead of creating one. While I'm not familiar with the LB controller, this might be a relatively easy thing to do. If you think this is a good idea, I would be glad to help with this, but I might need some direction.

**Comment by hazim1093** [comment]
Having a custom resource for creating the ingress seems like a good idea. 

As a workaround for now, I have created a "default" ingress that has all common annotations and handles ssl redirects for all incoming traffic instead of specifying that in each ingress. 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-loadbalancer-default
  namespace: 1-ns
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: "dev"
    alb.ingress.kubernetes.io/tags: Environment=dev,Name=dev
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
```

I had to place this ingress in a namespace named `1-ns` (for details see #1875 ). 
If you don't need the SSL redirection, and just want an ingress for common annotations, you can create a similar one and use the `actions` annotations to return a 200 or a 404 and specify a high group order e.g. 1000

**Comment by cloudlady911** [comment]
I have a similar issue.  I like this idea so I am going to test it.

Question: 

Different containers might have different success codes.  Would you put those in the "default" one leave them in the individual ingresses for each application?

`alb.ingress.kubernetes.io/success-codes: 200,303`

Also I noticed that your example starts with: 
`apiVersion: networking.k8s.io/v1`

The example on the the AWS LoadBalancer Controller [website](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/tasks/ssl_redirect/) starts with this:

`apiVersion: extensions/v1beta1`

Also your spec rule are formatted differently:

```
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
```

Their example is like this:
```
spec:
  rules:
    - http:
        paths:
         - path: /*
           backend:
             serviceName: ssl-redirect
             servicePort: use-annotation
```
It seems like the instructions are incorrect on the website.  Is there a better place where I should be looking for examples?  i am looking under v2.1 which is the version I am using.
