### ISSUE TITLE
Creating TargetGroupBinding without specifying Ingress

### ISSUE THREAD

**Issue by rswail** [kubernetes-sigs/aws-load-balancer-controller#1778]
We have a number of services that are configured with type: ClusterIP.

What we want to do is bind these to a known target group that is already existing.

Created the ALB and the target group as type IP and mapped to port 8080.

Do I need to do something weird with the ALB's routing to be able to see the cluster IPs?

Or should I be creating the target group as type instance and somehow specifying the service with a NodePort?

VPC CIDR: 192.168.32.0/20
Cluster CIDR: 10.100.0.0/16

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
  - port: 8080
    name: http 
```

and the targetgroupbinding is:

```
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: my-service-binding
spec:
  serviceRef:
    name: my-service
    port: 8080
  targetGroupARN: arn:aws:elasticloadbalancing:<redacted>
  networking:
    ingress:
    - from:
      - ipBlock:
        cidr: 192.168.32.0/20
      ports:
      - port: 8080
        protocol: TCP
```
