### ISSUE TITLE
Ingress ALB not created subnet count 1 < 2

### ISSUE THREAD

**Issue by rlanore** [kubernetes-sigs/aws-load-balancer-controller#1783]
Hi i following this doc to create an ALB from my EKS.
I was searching since two days now but unable to find anything that help full
https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/installation/
But i receive this error message. All subnet are correctly tagged i think

```
 Warning  FailedBuildModel  2m50s (x22 over 58m)  ingress  Failed build model due to couldn't auto-discover subnets: subnets count less than minimal required count: 1 < 2
```
To check my subnet tagg i use awscli like

```
aws ec2 describe-subnets  --filters "Name=tag:kubernetes.io/cluster/eksrla1,Values=shared"
{
    "Subnets": [
        {
            "AvailabilityZone": "eu-west-1a",
            "State": "available",
            "SubnetId": "subnet-0hhhhhh59141b",
            "Tags": [
                {
                    "Key": "kubernetes.io/role/internal-elb",
                    "Value": "1"
                },
                {
                    "Key": "kubernetes.io/cluster/eksrla1",
                    "Value": "shared"
                }
            ]
        },
        {
            "AvailabilityZone": "eu-west-1a",
            "State": "available",
            "SubnetId": "subnet-0b4JJJJJJJJced7b8",
            "Tags": [
                {
                    "Key": "kubernetes.io/role/elb",
                    "Value": "1"
                },
                {
                    "Key": "kubernetes.io/cluster/eksrla1",
                    "Value": "shared"
                }
            ]
        },
        {
            "AvailabilityZone": "eu-west-1b",
            "State": "available",
            "SubnetId": "subnet-01BBBBBBB41c9b",
            "Tags": [
                {
                    "Key": "kubernetes.io/cluster/eksrla1",
                    "Value": "shared"
                },
                {
                    "Key": "kubernetes.io/role/internal-elb",
                    "Value": "1"
                }
            ]
        }
    ]
}
```

The route table of one of this subnet is correctly connected to IGW.

aws-load-controller version is
```
helm list
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
awselb  kube-system     1               2021-01-28 16:21:51.015626364 +0000 UTC deployed        aws-load-balancer-controller-1.1.3      v2.1.1 
```

eks version is
```
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
My service echo server is 

```
apiVersion: v1
kind: Service
metadata:
  name: meow-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: NodePort
  selector:
    app: meow
```
and ingress look like

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: echo-server
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: meow-svc
              servicePort: 80
```
Debug message from controller not fully help full

```
{"level":"debug","ts":1611914435.3809292,"logger":"controller-runtime.manager.events","msg":"Warning","object":{"kind":"Ingress","namespace":"default","name":"echo-server","uid":"5572f9a4-ab1f-479f-b8c3-bd0948265758","apiVersion":"networking.k8s.io/v1beta1","resourceVersion":"285295"},"reason":"FailedBuildModel","message":"Failed build model due to couldn't auto-discover subnets: subnets count less than minimal required count: 1 < 2"}
```
I don't understand what i missing.
Note that if i create a service with type of loadbalancer everything works but it's not what a want.

thanks
