### ISSUE TITLE
no matches for kind "Certificate" in version "cert-manager.io/v1alpha2"

### ISSUE THREAD

**Issue by ghostsquad** [kubernetes-sigs/aws-load-balancer-controller#1787]
the latest example docs point to requiring cert-manager installed, which apparently has graduated to `v1`, so the manifests don't match in the instructions.

**Comment by kishorj** [comment]
@ghostsquad, could you confirm your kubernetes version and the cert-manager manifests you applied? I'm not aware of any recent changes to the cert-manager manifests based on the links we documented.

**Comment by ghostsquad** [comment]
per: https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/installation/

> in instructions
```
wget https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.1.0/docs/install/v2_1_0_full.yaml
```

> file contents include:
```
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
```

> in instructions
```
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.2/cert-manager-legacy.yaml
```

> file contents include:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from-secret: cert-manager/cert-manager-webhook-ca
  labels:
    app: cert-manager
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
  name: certificates.cert-manager.io
...
kind: Certificate
```

as you can see, cert-manager has graduated to `v1beta1` and aws-load-balancer-controller is still referring the `v1alpha2` apiVersion.
