### ISSUE TITLE
Controller can't attach ALB security group to eks cluster security group

### ISSUE THREAD

**Issue by skerava** [kubernetes-sigs/aws-load-balancer-controller#1791]
Hi,
The alb controller provides two ingress annotations to work with AWS security groups to restrict traffic access.
```
alb.ingress.kubernetes.io/security-groups

alb.ingress.kubernetes.io/inbound-cidrs 
```

In my scenario, `alb.ingress.kubernetes.io/security-groups` is applied.

![image](https://user-images.githubusercontent.com/50441394/106543614-08cf1200-6541-11eb-9756-0cc88c251a57.png)

However, while trying to navigate to the ingress URL, the website application was not accessible with a 504 error. So I checked the target group health check and found that all the backend were in unhealthy status.

![image](https://user-images.githubusercontent.com/50441394/106548612-45ebd200-654a-11eb-9c15-8f40e595f8ae.png)

I noticed that the cause of those phenomena is that the security group of the EKS cluster did not include the alb security group so that the health check was unable to work normally.

On the other hand, if applying `alb.ingress.kubernetes.io/inbound-cidrs`, ALB would work well since the alb security is covered by the security group of the EKS cluster.

Is there any roadmap for our ALB controller project to fix the problem?

**Comment by schollii** [comment]
I have same issue. The docs provide an explanation for this: 

> When this annotation is **not** present, the controller will automatically create one security groups: the security group will be attached to the LoadBalancer and allow access from inbound-cidrs to the listen-ports. Also, the securityGroups for _Node/Pod will be modified to allow inbound traffic from this securityGroup_. 

The annotation supports multiple security groups being on ALB, so I can see why the controller does not automatically apply them to the nodes' security group. However the controller should automatically add the specified SG if there is only one in the annotation, AND it should support having some SG that are added automatically, and some that are not. This could be done with a second annotation such as 

```
alb.ingress.kubernetes.io/security-groups-manual: [list]
```
(I don't like this second annotation's name but I'm lacking inspiration at the moment). Then the following annotations on an ingress would cause ALB to have SG A, B, C, but only B and C to be added. Ingress groups still work with this approach. 
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: your-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: group-name
    alb.ingress.kubernetes.io/security-groups: sg-123456789, sg-987654321
    alb.ingress.kubernetes.io/security-groups-not-nodes: sg-123456789
```
For now it seems that the workaround is to manually (or via terraform or such automation tool) add the ALB SG to the cluster SG.
