### ISSUE TITLE
AWS Internal ALB unreachable 

### ISSUE THREAD

**Issue by Ph4rell** [kubernetes-sigs/aws-load-balancer-controller#1794]
Hello guys,

I'm facing some difficulties when i want to setup an Ingress ressource with scheme internal. When i setup this same config in internet-facing everything works fine.

If someone got an idea of where it fail, i would appreciate :)

Below my ingress configuration:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/inbound-cidrs: 0.0.0.0/0
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: polyaxon.xxx
    external-dns.alpha.kubernetes.io/internal-hostname: polyaxon.xxx
    kubernetes.io/ingress.class: alb
  finalizers:
  - ingress.k8s.aws/resources
  name: polyaxon-polyaxon-ingress
  namespace: polyaxon
spec:
  rules:
  - host: polyaxon.xxx
    http:
      paths:
      - backend:
          serviceName: polyaxon-polyaxon-gateway
          servicePort: 80
        path: /*
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - hostname: internal-k8s-polyaxon-polyaxon-b4ec570d59-129169640.eu-central-1.elb.amazonaws.com
```
Below my service configuration:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: polyaxon
    meta.helm.sh/release-namespace: polyaxon
  name: polyaxon-polyaxon-gateway
  namespace: polyaxon
spec:
  clusterIP: 172.20.118.150
  ports:
  - name: gateway
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: polyaxon-polyaxon-gateway
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
My External-DNS configuration:
The records are well created in private and public hosted zones.
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxxxxx:role/polyaxon-externalDNS-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.7.3
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=xxx.yyy
        - --provider=aws
        - --registry=txt
        - --txt-owner-id=xxxxxxxx
      securityContext:
        fsGroup: 65534
```
DNS resolution looks good:

```
; ANSWER SECTION:
internal-k8s-polyaxon-polyaxon-b4ec570d59-129169640.eu-central-1.elb.amazonaws.com. 60 IN A 10.67.3.206
internal-k8s-polyaxon-polyaxon-b4ec570d59-129169640.eu-central-1.elb.amazonaws.com. 60 IN A 10.67.2.179
```
Result:
`curl: (7) Failed to connect to polyaxon.xxx port 80: Operation timed out`

Regards,
Pierre

### Environment
AWS EKS version 1.18
External-DNS version 0.7.3
aws-alb-ingress-controller version 2.1.0
