### ISSUE TITLE
nlb-ip mode with externalTrafficPolicy: Local not using HTTP health check against healthCheckNodePort 

### ISSUE THREAD

**Issue by chancez** [kubernetes-sigs/aws-load-balancer-controller#1813]
When creating a `type: LoadBalancer` service with `externalTrafficPolicy: Local`, the service creates a separate health check port (healthCheckNodePort) that is used to determine which hosts actually have a pod for the service in question.

Normally, it fails the health check if the pod is not on a given host, and that causes the cloud loadbalancer to not send traffic to that node, which does not have the pod behind the service.

When using aws-load-balancer-controller and a service with `service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip` this behavior is not retained. Instead, the health check uses the traffic port.

This is unexpected, and for us a problem since one of our NLB loadbalancers is for an NLB service; and the health check is TCP based; meaning it does not work with this setup.

I can probably work-around this by specifying `service.beta.kubernetes.io/aws-load-balancer-healthcheck-port` but this is undesirable as I also have to map that to the  healthCheckNodePort which is allocated dynamically, and I'd rather not be in charge of manually maintaining and allocating nodePorts.

**Comment by kishorj** [comment]
@chancez, for IP mode, the node port and the healthCheckNodePort gets ignored since NLB will target traffic directly to the pods, not the instances. You can override the health check configurations via annotations, however, you need to make sure it is the pods that have the ports open, not the nodes.

**Comment by chancez** [comment]
Right, does this also mean the healthCheckNodePort wouldn't even be reachable on the podIP since the nodePort is bound to the instance's IP? What can I do to make it so I can use UDP with nlb-ip such that the health check passes?

**Comment by M00nF1sh** [comment]
@chancez 
NLB currently don't support health check with UDP. if your pods only have UDP, the workaround should be add a sidecar container to your pod which merely listens for tcp traffic. (a simple shell script can work)

**Comment by kishorj** [comment]
Here are couple of options in this case
- Leave as is and rely on the fail-open mode if health check fails for all of the targets
- Modify your application to listen on a TCP port as well to respond to the health check queries
- Add a sidecar to your deployment, this sidecar will open up a TCP port to perform the health check and respond to the queries. You should be able to use HTTP/HTTPS for health check as well if required. 

For the third option, here is a sample manifest that I use to test -
```
kind: Service
apiVersion: v1
metadata:
  name: udp-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8080"
spec:
  ports:
    - name: port
      port: 53
      targetPort: 10000
      protocol: UDP
    - name: port80
      port: 80
      targetPort: 10000
      protocol: UDP
  type: LoadBalancer
  selector:
    app: udp-hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udp-hello
  template:
    metadata:
      labels:
        app: udp-hello
    spec:
      containers:
        - name: udp-hello
          image: "kishorj/udp-hello:v1"
          ports:
            - protocol: UDP
              containerPort: 10000
        - name: tcp-multi
          image: "kishorj/hello-multi:v1"
          ports:
            - name: http-alt 
              containerPort: 8080
```
