### ISSUE TITLE
Document advised resource 'request' and 'limit' settings

### ISSUE THREAD

**Issue by qoobic** [kubernetes-sigs/aws-load-balancer-controller#1817]
We're using the Ingress controller and wondering what constraints (request and limit) we can apply.

We only have one ingress point currently but it might extend to two or more in the near future.

What values should we be using here?

**Comment by kishorj** [comment]
If you install the v2.1.2 yaml manifests, here are the resource limitations currently used
```
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
```

If you use the helm chart, you can specify similar limits.
