### ISSUE TITLE
Lack of logging settings

### ISSUE THREAD

**Issue by mikalai-t** [kubernetes-sigs/aws-load-balancer-controller#1820]
Hello.

**What happened**:
It seems AWS LB controller only have 2 options for `--log-level` setting because despite `--log-level=error` it keeps recording messages with `info` and even `debug` severity:
```
kubectl logs pod/aws-load-balancer-controller-7b8679bb6b-vtkk

# ...
{"level":"info","ts":1613117211.6421442,"msg":"registering targets","arn":"arn:aws:elasticloadbalancing:eu-west-1:604075052855:targetgroup/k8s-monitori-grafana-64518712aa/f6416c1843ea075e","targets":[{"AvailabilityZone":null,"Id":"10.7.50.63","Port":3000}]}
{"level":"info","ts":1613117211.9982367,"msg":"registered targets","arn":"arn:aws:elasticloadbalancing:eu-west-1:604075052855:targetgroup/k8s-monitori-grafana-64518712aa/f6416c1843ea075e"}
{"level":"debug","ts":1613117211.9982986,"logger":"controller","msg":"Successfully Reconciled","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-monitori-grafana-64518712aa","namespace":"monitoring"}
# ...
```

**Expected behavior**
Logger must show messages with severity equal or lower than configured only.

**Environment**
* AWS EKS
```
kubectl version

Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
* Installed from the Helm repo `https://aws.github.io/eks-charts` using chart `aws-load-balancer-controller` version `1.1.2` with value:
```yaml
# ...
logLevel: error
# ...
```
* `kubectl get pod/aws-load-balancer-controller-7b8679bb6b-vtkkq -o yaml`
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/instance: kube-system-aws-load-balancer-controller
    app.kubernetes.io/name: aws-load-balancer-controller
  name: aws-load-balancer-controller-7b8679bb6b-vtkkq
  namespace: kube-system
spec:
  containers:
  - args:
    - --cluster-name=eks007
    - --ingress-class=alb
    - --aws-region=eu-west-1
    - --enable-shield=false
    - --enable-waf=false
    - --enable-wafv2=false
    - --log-level=error
    command:
    - /controller
    env:
    - name: AWS_DEFAULT_REGION
      value: eu-west-1
    - name: AWS_REGION
      value: eu-west-1
    - name: AWS_ROLE_ARN
      value: arn:aws:iam::XXXXXXXXXXXX:role/eks007-kube-system-aws-lb-controller
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.1.1
# ...
```
