### ISSUE TITLE
annotation "aws-load-balancer-subnets" not taken into account

### ISSUE THREAD

**Issue by leandro-loos** [kubernetes-sigs/aws-load-balancer-controller#1821]
According to the documentation (https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/guide/service/annotations.md):

> service.beta.kubernetes.io/aws-load-balancer-subnets specifies the Availability Zone the NLB will route traffic to. See Network Load Balancers for more details.

> !!!tip Subnets are auto-discovered if this annotation is not specified, see Subnet Discovery for further details.

I have a `v1.18.15` and a `v1.16.15` kubernetes clusters created with `kops` on top of EC2 instantes. 

Deploying the following service as part of a nginx-controller-deployment:
```
---
kind: Service
apiVersion: v1
metadata:
  name: ingress-oso
  namespace: ingress-oso
  labels:
    app.kubernetes.io/name: ingress-oso
    app.kubernetes.io/part-of: ingress-oso
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-XXXX,subnet-YYYY,subnet-ZZZZ"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 172.16.0.0/12
  selector:
    app.kubernetes.io/name: ingress-oso
    app.kubernetes.io/part-of: ingress-oso
  ports:
    - name: http
      port: 80
      targetPort: http
```
Where `subnet-XXXX, subnet-YYYY, subnet-ZZZZ` are valid subnets on the VPC from different AZs (a, b, and c).

The `aws-load-balancer-subnets` annotation is being ignored and the NLB is created on the auto discovered subnets.

(note that the whole lot of combinations like using `"`,`'`,` `, etc were tested)
