### ISSUE TITLE
Support for exposing private hostnames / IP addresses outside of Kubernetes

### ISSUE THREAD

**Issue by viorelvintan** [kubernetes-sigs/aws-load-balancer-controller#1826]
We have to expose an AWS Elasticsearch domain with advanced security enabled, deployed in a VPC (whose endpoint hostname resolves into a private IP address) and we couldn't find a way of doing it by creating Ingress / Service / Endpoints objects with annotations supported by aws-load-balancer-controller.

There was a [similar issue](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1223) but it does not seem to provide a solution for this specific use case.

Our attempt was to create an ingress object pointing to a service without a selector and then creating an endpoint manually to the Elasticsearch domain's private IP address. The outcome was that the following AWS resources were deployed:
- the expected ALB with a listener and a rule for our desired host HTTP header pointing to a target group
- the expected  target group but with no registered targets whatsoever (despite having the IP address mentioned in the manual endpoint)

We would have expected that the IP address specified by the endpoint would be added as a registered target, but this did not happen (it is most likely not currently supported).

Here are the three Kubernetes objects (we run version 1.17):
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/group.name: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/success-codes: '401'
    kubernetes.io/ingress.class: alb
  finalizers:
  - group.ingress.k8s.aws/alb
  name: elasticsearch
  namespace: logging
spec:
  rules:
  - host: elasticsearch.my.domain
    http:
      paths:
      - backend:
          serviceName: elasticsearch
          servicePort: 443
  tls:
  - hosts:
    - elasticsearch.my.domain
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: logging
spec:
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: elasticsearch
  namespace: logging
subsets:
- addresses:
  - ip: 192.168.22.122
  ports:
  - port: 443
```
Please implement a feature which would make this possible.
Many thanks in advance!
