### ISSUE TITLE
Certificate rotation expected?

### ISSUE THREAD

**Issue by johnjeffers** [kubernetes-sigs/aws-load-balancer-controller#1828]
I've deployed the Helm chart with ArgoCD, and it Argo keeps marking it out of sync because certificates for the webhooks are changing. This seems to happen about once per day. Is this expected?

![Screen Shot 2021-02-16 at 8 51 15 PM](https://user-images.githubusercontent.com/11821214/108153747-06b89780-7099-11eb-97f5-14020abf64d5.png)

**Comment by kishorj** [comment]
@johnjeffers, the keys are generated when the helm template gets rendered. The controller doesn't modify the keys/secret. If your CD workflow involves rendeering a new helm template for the aws-load-balancer-controller chart then the new keys will generated every time the template gets rendered. You can use the cert-manager to manage the keys/certificates instead.

**Comment by johnjeffers** [comment]
Got it. Thank you for the quick reply!

**Comment by johnjeffers** [comment]
For anyone else who runs across this, the solution is to add the following to the ArgoCD `Application` object. This will tell Argo to ignore when the certificates change.

```
kind: Application
spec:
  ignoreDifferences:
  - kind: Secret
    name: aws-load-balancer-tls
    jsonPointers:
    - /data/ca.crt
    - /data/tls.crt
    - /data/tls.key
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: aws-load-balancer-webhook
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
    - /webhooks/1/clientConfig/caBundle
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: aws-load-balancer-webhook
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
```
