### ISSUE TITLE
NLB IP Target registration is extremely slow

### ISSUE THREAD

**Issue by abatilo** [kubernetes-sigs/aws-load-balancer-controller#1834]
I've configured an NLB with IP targets to point to an instance of Traefik 2 and noticed that when I have pod readiness gates enabled, it might take upwards of 5 minutes for a single target to register and be considered healthy. Is this normal/expected?

**Comment by kishorj** [comment]
The NLB target registration can take from 90 to 180 seconds to complete. After registration, the targets are marked healthy only after the configured health check passes. This delay is from the AWS NLB and is currently expected. It is not due to the pod readiness gate configuration. 

In case of rolling updates to your application, the pod readiness gate helps mitigate the effects of this delay by making sure the existing pods will not be terminated until the newly registered targets show up as healthy.

**Comment by abatilo** [comment]
Ah, thank you. Is there anything at all I can do to help speed that up?

**Comment by M00nF1sh** [comment]
@abatilo 
You can contact NLB team via support ticket to accelerate it. 

From the controller's perspective, we will add some docs to note this limitation on our docs. 

/kind documentation

**Comment by keperry** [comment]
@abatilo  - I would encourage anyone encountering this issue to reach out to AWS support.  They are aware of the issue.  AFAIK, it has been an issue for 3+ years (per stackoverflow).  The more people that contact them, the more likely it will get fixed.  ;)

**Comment by juozasget** [comment]
Can confirm that I've observed the same behaviour when testing NLB ingress with IP targets @abatilo.
The controller registers a new pod with the target group within few seconds. I'd expect the NLB health check to kick in and register the service in 20-30s (2 or 3 health cheks, 10s interval). Instead of 20-30s, it's 3-5minutes.

**Comment by paul-lupu** [comment]
I can confirm this is still present... feels a bit like AWS is letting people down by delaying a fix for it for so long...

**Comment by jbg** [comment]
I don't think they see it as a bug :) This is not related to k8s or the load balancer controller and probably doesn't belong here. If you want NLB to take less than 3 minutes to register targets, tell your AWS support rep!

**Comment by paul-lupu** [comment]
@jbg I did, they mentioned this thread in their response... 
"Mom, can I go out?" 
"Ask your dad!"
"Dad?"
"Ask your mom!" XD

**Comment by jbg** [comment]
If you're contacting AWS support about this, it's probably advisable to demonstrate the issue with an NLB provisioned manually or via CloudFormation, so that first-level support can't point the finger at aws-load-balancer-controller or k8s as the source of the delay.

**Comment by paul-lupu** [comment]
@jbg  I did, they mentioned they will add a note with my case to the existing issue on the NLB.

**Comment by M00nF1sh** [comment]
@paul-lupu 
NLB team is already aware of this issue and have fixes in progress. 
They already rolled out a HC system to slightly improve the registration time and plan to improve it to be <=60sec(I don't have an ETA on this).

From the controller's point of view, we cannot do much until NLB improves it. If the registration time is a concern, we can use NLB instance mode(supported by newer version of this controller as well). If spot instances is been used, we can use nodeSelectors(service.beta.kubernetes.io/aws-load-balancer-target-node-labels) to use no-spot instances as NLB backend.

**Comment by bennettellis** [comment]
I have same issue with NLB fronting ECS containers. Very frustrating. The container is up and receives and responds to healthchecks in seconds, yet the TG takes minutes to recognize a container has healthy. If containers go down for some reason and need to be re-run this could potentially leave a major gap in service availability. Makes the NLB problematic to use, but I have to use it in order to do the TCP passthrough I need to the ECS container so that we can implement mTLS at the container. Very frustrating delay. Is there a general NLB ticket/issue that anyone might have a link to that I can help pile on with?

**Comment by jbg** [comment]
@bennettellis since it is a problem with AWS internal implementation rather than any open-source component, the best place to "pile on" is your AWS support

**Comment by rayjanoka** [comment]
I worked around this with traefik by setting the nlb deregistration timeout, deployment grace period, and container grace period to 5 minutes. I also needed to ensure the container health-check continued to report success during this inbetween time with traefik's `--ping.terminatingStatusCode=204`. This leaves the old pod in a "Terminating" but still running state for 5 minutes to give the nlb time to complete the registration process.

```
NAME                                      READY   STATUS        RESTARTS   AGE
traefik-5fc5468b49-7htxk                  1/1     Terminating   0          6m10s
traefik-5fc5468b49-hgdll                  1/1     Terminating   0          5m50s
traefik-5fc5468b49-t2qk7                  1/1     Terminating   0          6m31s
traefik-f5c4b56fb-478hc                   1/1     Running       0          29s
traefik-f5c4b56fb-7858g                   1/1     Running       0          49s
traefik-f5c4b56fb-czqbj                   1/1     Running       0          69s
```

NLB Service
```yaml
      service:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: external
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
          service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
          service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: deregistration_delay.timeout_seconds=300
```

k8s deployment
```
      deployment:
        terminationGracePeriodSeconds: 315
```

traefik container settings
```
      --ping.terminatingStatusCode=204
      --entrypoints.metrics.transport.lifecycle.requestacceptgracetimeout=5m
      --entrypoints.traefik.transport.lifecycle.requestacceptgracetimeout=5m
      --entrypoints.web.transport.lifecycle.requestacceptgracetimeout=5m
      --entrypoints.websecure.transport.lifecycle.requestacceptgracetimeout=5m
```

I think the container settings could also be accomplished with container lifecycle wait
```yaml
          lifecycle:
            preStop:
              exec:
                command: [
                    "sh", "-c",
                  # Introduce a delay to the shutdown sequence to wait for the
                  # pod eviction event to propagate. Then, gracefully shutdown
                    "sleep 300 && killall -SIGTERM application",
                ]
```

**Comment by ldemailly** [comment]
Unfortunately 5 minutes is too long for when using spot

**Comment by nbourdeau** [comment]
Anyone has any update on this ? Do we have a way to determine when the registration is actually completed and pod start receiving requests from the NLB ?

**Comment by keperry** [comment]
@nbourdeau - use pod readiness gates. They are super easy to setup and essentially your pod will not be considered ready until the LB sees the target as healthy. Unfortunately, deployments are slow, but at least with pod readiness gates they are stable.

**Comment by nbourdeau** [comment]
> @nbourdeau - use pod readiness gates. They are super easy to setup and essentially your pod will not be considered ready until the LB sees the target as healthy. Unfortunately, deployments are slow, but at least with pod readiness gates they are stable.

Well in my use case this is not really usable because it is a singleton deployment with an EBS volume mounted and I cannot have 2 pods with same volume running at the same time ...

But the strange thing is the NLB target is marked healthy in the target group but there is still a delay before the pod actually start receiving requests ... will that even work with pod readiness gates ?

**Comment by nbourdeau** [comment]
> There is a way to improve this time? Its taking more than 5 min when I use NLB with TCP protocol.

seems like the answer is no ... I contacted AWS support and the answer is: we are working on improving the delay ...
use pod readiness gates if you can ...

**Comment by ldemailly** [comment]
I will comment with more details but note you can reduce de-registration to around 45s using http(s) instead of tcp healthchecks. which help a lot for spot.

**Comment by ldemailly** [comment]
@roimor 

```yaml
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
      service.beta.kubernetes.io/aws-load-balancer-name: {{ $AwsLbName }}
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-internal: {{ $AwsLbInt }}
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: true
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: HTTPS
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8443"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /ready
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
```

combined with, istio/envoy wise:

```yaml
            containers:
              - name: istio-proxy
                lifecycle:
                  preStop:
                    exec:
                      command:
                        - "/bin/bash"
                        - "-c"
                        - curl -XPOST http://localhost:15000/healthcheck/fail && sleep 45 &&
                          curl -XPOST http://localhost:15000/drain_listeners?graceful && sleep 5
```


to reach the envoy internal health endpoint:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: localhost-service-entry
  namespace: istio-system
spec:
  hosts:
    - localhost.service.entry
  ports:
    - number: 15099
      name: http-port
      protocol: HTTP
      targetPort: 15000
  location: MESH_INTERNAL
  resolution: STATIC
  endpoints:
    - address: 127.0.0.1
```
and

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: external-virtualservice
  namespace: istio-system
spec:
  hosts:
    - '*'
  gateways:
    - ...
  http:
    - name: http-hc-route
      match:
        - uri:
            exact: /ready
      route:
        - destination:
            host: localhost.service.entry
            port:
              number: 15099
```
and because the hc will come with IP as target you need to serve certs on *
```yaml
    - port:
        number: 443
        name: https-no-sni
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: your-cert
      hosts:
      - "*" 
```

**Comment by youwalther65** [comment]
Out of curiosity: Is this an issue for ALB IP target mode as well?

**Comment by kishorj** [comment]
@youwalther65, ALB IP target registration is faster than NLB.

**Comment by bennettellis** [comment]
the issue being discussed is precisely NLBs, not ALBs. There are many cases where an ALB is not an appropriate solution.

**Comment by ldemailly** [comment]
>  Out of curiosity: Is this an issue for ALB IP target mode as well?

ALB is a lot faster yes, which is puzzling - but as mentioned above this is about NLB which is what is needed for many cases, using ALB isn't an option for us

**Comment by bennettellis** [comment]
I've been trying to put some pressure on the services team through tickets, and the AWS teams I work with to get this fixed for some time now. No movement yet. Also FWIW, this is not specific to k8s. In my situation, I'm actually deploying Fargate ECS containers into a standard TargetGroup for my NLB. The contianers come up in 4+ seconds and respond to healthcheck requests they're receiving pretty much right away. The TargetGroup sees them pretty much immediately and puts them in the initial state. But for whatever reason, it takes up-to (not always) 5 minutes of regular healthcheck calls for the TargetGroup to decide that they're healthy. My healthcheck endpoint does nothing but return 200, immediately.

**Comment by sosheskaz** [comment]
@ldemailly was able to use your solution as a basis for my own (but via sidecar instead of operator). Thank you for putting your info here.

I do have a thought though. I don't think this works because it is HTTP instead of TCP, but instead because the health check starts failing artificially. The NLB responds to failed health checks (~45s in my experiments) faster than it responds to target deregistration (~90s-4m).

Envoy is a nice solution for this, because of the ability to manipulate health checks, as was shown earlier. I think this could be done much more simply with a TCP health check. One could imagine:
* a sidecar container, dumbly running a TCP listener like `netcat -l` (or... anything really). 
* When a pod goes down, we use two different `preStop` hooks for the application container, and the sidecar container:
  * For the sidecar, we terminate the listener and exit immediately.
  * For the pod, we delay by about a minute (and drain connections if appropriate).
* The NLB health check should be configured to health check the TCP listener sidecar, instead of the application itself.

As a result, when a pod transitions to state `TERMINATING`:
* The application container continues running for a while (and passing health checks)
* The TCP listener sidecar starts refusing connections and exits.
* The NLB detects that health checks are failing, and stops sending new traffic.
* The application container finally shuts down.

NOTE: This idea has shortcomings. For example, genuine application healthcheck failures may not be reflected in NLB's target group in a timely fashion, because the TCP proxy may still be working even if the application is failing health checks.

That said, even though this is a viable workaround... this still feels like a genuine problem with the NLB/NLB controller.

/remove-lifecycle stale

**Comment by hitsub2** [comment]
Any Updates on this?

**Comment by matti** [comment]
I wrote a generic sidecar for this which works ~like @sosheskaz described above https://github.com/matti/k8s-prestop-sidecar

**Comment by dorsegal** [comment]
Anyone knows other places to do followup? I will read any change log but I don't know which one...

**Comment by eth-limo** [comment]
`/bump`. This basically renders autoscaling useless. We've noticed that there is no way to accommodate surge loads due to the slow provisioning/registration times. Pods will OOM/kill 4-5x in the window it takes for a single pod to successfully register. Looks like we'll be migrating off to ECS as EKS is half-baked at best. Super disappointed in this being a known issue for over 2 years without any commentary.

**Comment by bbdimitriu** [comment]
> `/bump`. This basically renders autoscaling useless. We've noticed that there is no way to accommodate surge loads due to the slow provisioning/registration times. Pods will OOM/kill 4-5x in the window it takes for a single pod to successfully register. Looks like we'll be migrating off to ECS as EKS is half-baked at best. Super disappointed in this being a known issue for over 2 years without any commentary.

As mentioned above in the discussion, this isn't an issue with EKS, but with the NLB itself and you're most likely going to have the same problem with ECS too.

**Comment by abatilo** [comment]
Hi @nicc777, I just tried your changes and the registration doesn't appear to be any faster so to anyone else who tries it, YMMV.

I tested it on the v2.5.2 of the aws lb controller under chart version v1.5.3. And tried 2x and both times it still took about ~3 minutes for the readiness gate to pass.

**Comment by abatilo** [comment]
Thank you for sharing anyways!

**Comment by dorsegal** [comment]
> @abatilo - yes, I was afraid it may have been something specific to just our environment. We are on controller v2.4.6 with Helm chart version 1.4.8 (Kubernetes/EKS v1.24)

I am using the same stack but chaning those settings didn't help. Are you sure you use NLB and not ALB?

**Comment by nicc777** [comment]
@dorsegal Yes NLB - I have about 150 of them at peak loads (EKS), each with between 3 and 9 target groups.

It seems after further analysis our problem was resolved because we were in a private VPC and there was therefore no comms to the WAF API. So it appears our problem was not related at all to what this problem is describing. Provisioning from EKS AWS Load Balancer Controller is done in roughly 3 seconds (on average) per target group - so it's now blistering fast for us. The actual registration of the targets is obviously dependent on the service itself, but it's acceptable for us (couple of seconds).

**Comment by nicc777** [comment]
@dorsegal - here is the annotation we use (service type is `LoadBalancer`, obviously):

```yaml
service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: namespace=REDACTED,desiredHostName=REDACTED
service.beta.kubernetes.io/aws-load-balancer-internal: "true"
service.beta.kubernetes.io/aws-load-balancer-name: REDACTED
service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
service.beta.kubernetes.io/aws-load-balancer-type: external
service.beta.kubernetes.io/load-balancer-source-ranges: REDACTED
```

**Comment by studzien** [comment]
We're also experiencing unexpectedly long deregistration delays.
From a few experiments I was able to run I noticed that deregistration is very fast (a few seconds) if there are no active connections, with deregistration delay set to 0.

We have also noticed that the deregistration time depends on how many targets are deregistered concurrently.

If we deregister 4 targets at the same time, it takes approximately 2 minutes to complete the deregistration.
If we deregister just once target at once, it takes approximately 30 seconds.

**Comment by stefkkkk** [comment]
any ETA about progress or fix?! It's horrible

**Comment by kovaxur** [comment]
I just contacted support, we are the helicopters, this is not a bug, it's a feature :D:D

> "Thank you for contacting Elastic Load Balancing about the length of time taken for a target registration and deregistration in Target Groups on your Network Load Balancer. When you register a new target to your Network Load Balancer, it is expected to take between 3-5 minutes (180 and 300 seconds) to complete the registration process. After registration is complete, the Network Load Balancer health check systems will begin to send health checks to the target. A newly registered target must pass health checks for the configured interval to enter service and receive traffic. For example, if you configure your health check for a 30 second interval, and require 3 health checks to become healthy, the minimum time a newly registered target could enter service is 270 seconds (180 seconds for registration, and another 90 (3*30) seconds for passing health checks) after a new target passes its first health check.
> 
> Similarly, when you deregister a target from your Network Load Balancer, it is expected to take 3-5 minutes (180-300 seconds) to process the requested deregistration, after which it will no longer receive new connections. During this time the Elastic Load  Balancing API will report the target in 'draining' state. The target will continue to receive new connections until the deregistration processing has completed. At the end of the configured deregistration delay, the target will not be included in the describe-target-health response for the Target Group, and will return 'unused' with reason 'Target.NotRegistered' when querying for the specific target.
> 
> We have added information about your questions and use case to a feature request to reduce the time taken to register, deregister, and health check Network Load Balancer targets."
> 
> As nothing can be done on the NLB to reduce this, I suggest taking a look at EKS best practices guide[1] to workaround the delay induced by the NLB. The guide does cover the exact scenario you're facing and includes supporting recommendations. 
> 
> Please ket me know if you have any questions. 
> 
> Resources:
> [1] https://aws.github.io/aws-eks-best-practices/networking/loadbalancing/loadbalancing/ 

Our solution is to put a stable loadbalancer (eg: HAProxy) in front of our pods and use dns service discovery. It also has many feature, which NLB lacks of.

**Comment by nicc777** [comment]
Thanks for the feedback @kovaxur 

We have also now rolled out our own load balancer.  The moment you need more then a 120 or so Load Balancers from EKS (using AWS Load Balancer Controller) the wheels really start to come of. ELBv2 API Calls go through the roof - so much so that API calls start to time out or be throttled. Our own load balancer turned out to be the path of least resistance. 

AWS really tripped on this one.

**Comment by ldemailly** [comment]
Having nodes with public IPs to do one own's load balancing is really not a good solution (imo) - ditto reinventing a wheel.

So we need this addressed, specially considering spot termination notice. I have yet to hear a technical explanation for why it takes that long.

**Comment by paymog** [comment]
It seems that NLB doesn't start registering new pods until they pass the kubernetes level pod readiness check. If I set a pod readiness check of 300 seconds, new pods don't seem start the NLB registration process until after kubernetes has declared them ready.

Is there a way to get NLB to start registering new pods in a deployment *before* the kubernetes pod readiness check passes?

**Comment by sylr** [comment]
> It seems that NLB doesn't start registering new pods until they pass the kubernetes level pod readiness check. If I set a pod readiness check of 300 seconds, new pods don't seem start the NLB registration process until after kubernetes has declared them ready.
> 
> Is there a way to get NLB to start registering new pods in a deployment _before_ the kubernetes pod readiness check passes?

No, it makes no sense, your pods should not receive traffic unless it is ready.

**Comment by paymog** [comment]
> No, it makes no sense, your pods should not receive traffic unless they are ready.

yeah, now that you mention it that totally makes sense. I just spent hours trying to figure out how to spin up all the new pods right away so they can start the registration process while also keeping the old pods around. I played with `terminationGracePeriodSeconds`, `maxSurge`, `maxUnavailable`, and the `preStop` lifecycle hook. Could not figure it out.

**Comment by oliviassss** [comment]
hi @nicc777 and @abatilo, we made some improvement on podReadinessGate since v2.6.1 as mentioned in the [release note](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.6.1), would you be able to help verify if the newer version has improvement in your use cases? Thanks

**Comment by js-9** [comment]
I still get pretty slow initialization times for the nlb and pod readyness gate, just over 3 minutes with v2.6.2

**Comment by stefkkkk** [comment]
> hi @nicc777 and @abatilo, we made some improvement on podReadinessGate since v2.6.1 as mentioned in the [release note](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.6.1), would you be able to help verify if the newer version has improvement in your use cases? Thanks

still the same

**Comment by stefkkkk** [comment]
> The Kubernetes project currently lacks enough contributors to adequately respond to all issues.
> 
> This bot triages un-triaged issues according to the following rules:
> 
> * After 90d of inactivity, `lifecycle/stale` is applied
> * After 30d of inactivity since `lifecycle/stale` was applied, `lifecycle/rotten` is applied
> * After 30d of inactivity since `lifecycle/rotten` was applied, the issue is closed
> 
> You can:
> 
> * Mark this issue as fresh with `/remove-lifecycle stale`
> * Close this issue with `/close`
> * Offer to help out with [Issue Triage](https://www.kubernetes.dev/docs/guide/issue-triage/)
> 
> Please send feedback to sig-contributor-experience at [kubernetes/community](https://github.com/kubernetes/community).
> 
> /lifecycle stale
/remove-lifecycle stale

**Comment by cyrus-mc** [comment]
I came across this issue after noticing the long registration delays in my own environment. I wanted to add a few additional pieces of information and see if others are seeing the same.

1) ALB vs NLB

If I use an ALB the target group shows healthy immediately once the readiness check of the POD passes. Since the POD is never added to the target group until the POD is ready, this means that from a k8s perspective, once the POD is ready to receive traffic the ALB will show it as healthy and it begins to receive traffic

2) Healthy vs Initial state

Regardless of ALB vs NLB, what I see is that once the POD is added to the target group (and even if in initial state for a NLB target group) the POD receives new traffic immediately. In this situation I am not sure what POD readiness gates would serve, other than to hold up deployment rollout until the target goes to healthy in the TG.

**Comment by youwalther65** [comment]
Please check NLB target registration delay now, should be much faster.

**Comment by frittentheke** [comment]
> Please check NLB target registration delay now, should be much faster.

@youwalther65 that sound promising, thank you.

Could you kindly elaborate this a little more? What registration times can be expected now?
Is this change something that happened within the NLB control plane? Is a certain version or setting of the https://github.com/kubernetes-sigs/aws-load-balancer-controller/ required? 

Any other best-practices in regards to the various annotations / settings ?
`service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold`, `service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval`, `service.beta.kubernetes.io/aws-load-balancer-target-group-attributes`, ....

**Comment by youwalther65** [comment]
@frittentheke  NLB has a good amount of improvement in target registration now. I tested the following in eu-west-1 region on 2024-09-16: AWS Load Balancer Ctlr 2.8.3 provisioning NLB with NGINX Ingress Ctlr pods as IP targets (in my test just 2 replica pods). This is a very common setup I 've seen a lot in various user setups (sometimes they just use other Ingress Ctlr like Traefik, Kong Gateway or Istio Gateway). I used AWS Load Balancer Ctlr "pod readiness gate" so pods become fully K8s ready when they are "Healthy" targets on NLB. I just did a `kubectl rollout restart ...`of the NGINX deployment to force creation of new pods/NLB target IP. Instead of 4-5 minutes for for NLB "Healthy" pods which I have seen in the past before the latest NLB changes, now it takes just 90s for Healthy IP targets/Ready pods. I used 10s health check interval and healthy threshold count of 3 for the target health checks which are the defaults when using  AWS Load Balancer Ctlr.
You can verify the time it takes or full readiness (Note: There are 2 conditions because NGINX Ingress Ctlr uses 2 targets groups for HTTP and HTTPS respectively:
```yaml
$ k get po -n ingress-nginx ingress-nginx-controller-<redacted> -o yaml
…
status:
 conditions:
 - lastProbeTime: null
   lastTransitionTime: "2024-09-16T06:22:53Z"
   status: "True"
   type: target-health.elbv2.k8s.aws/k8s-ingressn-ingressn-<redacted-1>
 - lastProbeTime: null
   lastTransitionTime: "2024-09-16T06:22:53Z"
   status: "True"
   type: target-health.elbv2.k8s.aws/k8s-ingressn-ingressn-<redacted-2>
 - lastProbeTime: null
   lastTransitionTime: "2024-09-16T06:21:31Z"
   status: "True"
   type: PodReadyToStartContainers
 - lastProbeTime: null
   lastTransitionTime: "2024-09-16T06:21:25Z"
   status: "True"
   type: Initialized
 - lastProbeTime: null
   lastTransitionTime: "2024-09-16T06:22:53Z"
   status: "True"
   type: Ready
 - lastProbeTime: null
   lastTransitionTime: "2024-09-16T06:21:45Z"
   status: "True"
   type: ContainersReady
 - lastProbeTime: null
   lastTransitionTime: "2024-09-16T06:21:25Z"
   status: "True"
   type: PodScheduled
…
```
