### ISSUE TITLE
Failed build model due to conflicting loadBalancerAttribute idle_timeout.timeout_seconds: 900 | 1200

### ISSUE THREAD

**Issue by dsaydon90** [kubernetes-sigs/aws-load-balancer-controller#1839]
I'm getting the following error
```
kubectl -n mynamespace describe ingress myservice
Failed build model due to conflicting loadBalancerAttribute idle_timeout.timeout_seconds: 900 | 1200
```
relevant logs from `kubectl -n kube-system logs -f system-alb-ingress-controller-56d67bcb8b-txwwm`
```
{"level":"error","ts":1614013025.184384,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"dev-internal","namespace":"","error":"conflicting loadBalancerAttribute idle_timeout.timeout_seconds: 900 | 1200"}
```

ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/group.name: dev-internal
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=600
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/subnets: subnet-0efdf79e923sdfg86b, subnet-0bddffdfdfa0ef299,
      subnet-01fdf4c3ec20fdf
    alb.ingress.kubernetes.io/tags: env=dev
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  labels:
    app: myservice
  name: myservice
  namespace: mynamespace
spec:
  rules:
  - host: myservice.internal.local
    http:
      paths:
      - backend:
          serviceName: myservice
          servicePort: 80
        path: /*
        pathType: Prefix
```

ingress details:
```
    - args:
        - --cluster-name=my-eks
        - --ingress-class=alb
        command:
        - /controller
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.1.3
```

I have other `ingress` resources with the annotation `alb.ingress.kubernetes.io/load-balancer-attributes` with different values. Is that can be an issue?

workaround:
remove the annotation `alb.ingress.kubernetes.io/load-balancer-attributes`
