### ISSUE TITLE
Migrating from networking.k8s.io/v1beta1 to networking.k8s.io/v1

### ISSUE THREAD

**Issue by Kunamatata** [kubernetes-sigs/aws-load-balancer-controller#1846]
I was wondering if it was possible to migrate to the new apiVersion for networking.k8s.io
Some of the changes involve `serivceName` and `servicePort` as well as the annotations deprecating `kubernetes.io/ingress.class: alb` from what I understand. Does this also mean that we must use `kind: IngressClass` with a `metadata.name: alb` ?

The examples on the live documentation still use the `v1beta1` apiVersion:
https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/ingress/annotations/

**Comment by M00nF1sh** [comment]
@Kunamatata 
We'll keep support `kubernetes.io/ingress.class` annotation and it takes priority than spec.ingressClassName.
In the next release, we'll offer a flag called "--disable-ingress-class-annotation", where we have a  webhook for Ingress will prevent new Ingress creation(or updates) that have `kubernetes.io/ingress.class: alb` annotation(which basically enforce the adoption of IngressClass resource). However, it will be an optional flag, and default to false. (we might change the default value after a few versions).

**Comment by antweiss** [comment]
I have a question about this. The [ssl-redirect example](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/tasks/ssl_redirect/) features old style ingress backend definitions:
```
  - path: /*
           backend:
             serviceName: ssl-redirect
             servicePort: use-annotation
 ```
 
 how is this configured in the networking.k8s.io/v1 ingresses?

**Comment by antweiss** [comment]
Never mind - this worked:
```
     - path: /*
        pathType: Prefix
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
```

**Comment by guidoffm** [comment]
Yes, this works. But describing the ingress says:

```
/*   ssl-redirect:use-annotation (<error: endpoints "ssl-redirect" not found>)
```

**Comment by mylespollie** [comment]
> Yes, this works. But describing the ingress says:
> 
> ```
> /*   ssl-redirect:use-annotation (<error: endpoints "ssl-redirect" not found>)
> ```

Do you know of a way to fix this?

**Comment by TheBaus** [comment]
> > Yes, this works. But describing the ingress says:
> > ```
> > /*   ssl-redirect:use-annotation (<error: endpoints "ssl-redirect" not found>)
> > ```
> 
> Do you know of a way to fix this?

@mylespollie and @guidoffm 
The error is due to the missing annotation containing `actions.ssl-redirect`

Does this fix it for you? When you define the annotations this way? 

`  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    extraLabels: {}
    hosts:
        - example.com
    extraPaths:
      - path: /*
        backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
      - backend:
          serviceName: example-service-name
          servicePort: 80
        path: /*
        pathType: ImplementationSpecific
    tls:
        - secretName: example-tls
          hosts:
            - example.com`

**Comment by TheBaus** [comment]
The above is actually out of a helm charts ingress, if you require the raw K8s Manifests do let me know. I just used it as an example to show that you need an annotation with actions.ssl-redirect to match the service name.

**Comment by ArjunBhushan** [comment]
Hi, the next minor release is v1.22 in which networking.k8s.io/v1beta1 will be unavailable. Are there any working examples on how to use ssl-redirect with networking.k8s.io/v1? Thanks!

**Comment by antweiss** [comment]
@ArjunBhushan correct me if I'm wrong but I don't think there's any change to the API - it's just going out of beta.

**Comment by vedarths** [comment]
Hello @TheBaus 

Thanks for your comment that surely helps.

However, in spite of having the annotations that you have mentioned, it still does not seem to work and I get the error

```
 /*                         ssl-redirect:use-annotation (<error: endpoints "ssl-redirect" not found>)
```

Please could you let me know what I might be missing? Thanks for your time!

Here is my CRD

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alb-dev-ssl-ingress
  labels:
    app: alb-dev-ssl-ingress
  annotations:
    # Ingress Core Settings
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Redirect setting
    alb.ingress.kubernetes.io/listen-ports: '[ { "HTTPS":443 }, { "HTTP":80 } ]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    # External DNS - For creating a Record Set in Route53
    external-dns.alpha.kubernetes.io/hostname: dev.mydomain.blah
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          - path: /my-service/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: my-nodeport-service
                port:
                  number: 3000
                  - path: /*
          - path: /*
              pathType: ImplementationSpecific
              backend:
                service:
                  name: nginx-nodeport-service
                  port:
                    number: 80

```

**Comment by TheBaus** [comment]
> Hello @TheBaus
> 
> Thanks for your comment that surely helps.
> 
> However, in spite of having the annotations that you have mentioned, it still does not seem to work and I get the error
> 
> ```
>  /*                         ssl-redirect:use-annotation (<error: endpoints "ssl-redirect" not found>)
> ```
> 
> Please could you let me know what I might be missing? Thanks for your time!
> 
> Here is my CRD
> 
> ```
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   name: alb-dev-ssl-ingress
>   labels:
>     app: alb-dev-ssl-ingress
>   annotations:
>     # Ingress Core Settings
>     kubernetes.io/ingress.class: "alb"
>     alb.ingress.kubernetes.io/scheme: internet-facing
>     # Redirect setting
>     alb.ingress.kubernetes.io/listen-ports: '[ { "HTTPS":443 }, { "HTTP":80 } ]'
>     alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
>     # External DNS - For creating a Record Set in Route53
>     external-dns.alpha.kubernetes.io/hostname: dev.mydomain.blah
> spec:
>   rules:
>     - http:
>         paths:
>           - path: /*
>             pathType: ImplementationSpecific
>             backend:
>               service:
>                 name: ssl-redirect
>                 port:
>                   name: use-annotation
>           - path: /my-service/*
>             pathType: ImplementationSpecific
>             backend:
>               service:
>                 name: my-nodeport-service
>                 port:
>                   number: 3000
>                   - path: /*
>           - path: /*
>               pathType: ImplementationSpecific
>               backend:
>                 service:
>                   name: nginx-nodeport-service
>                   port:
>                     number: 80
> ```
@vedarths 
Here is my raw manifest, sanitised of course, Not sure if it helps?

`apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: >-
      {"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port":
      "443", "StatusCode": "HTTP_301"}}
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=10
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  labels:
    app.kubernetes.io/instance: web-proxies
  name: web-proxies
  namespace: web-proxies
spec:
  rules:
    - host: my-host.example.com
      http:
        paths:
          - backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
            path: /*
          - backend:
              serviceName: web-proxies
              servicePort: 80
            path: /*
  tls:
    - hosts:
        - my-host.example.com
`

I've not yet moved off the beta api, will give that a test and see if it makes a difference.

**Comment by natsumemaya** [comment]
In my case cant use-annotation it require number not string...
```
- host: '*.example.io'
    http:
      paths:
      - pathType: Prefix
        path: "/*"
        backend:
          service:
            name: ssl-redirect
            port:
              number: use-annotation
      - pathType: Prefix
        path: "/*"
        backend:
          service:
            name: example
            port: 
              number: 80
```

error: error validating "../ingress/......": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend.service.port.number): invalid type for io.k8s.api.networking.v1.ServiceBackendPort.number: got "string", expected "integer"; if you choose to ignore these errors, turn validation off with --validate=false`

**Comment by saasglue** [comment]
> alb.ingress.kubernetes.io/target-type: ip

This didn't work for me.

**Comment by MatviyivR** [comment]
for 2.3 alb ingress controller version >, here is new annotation:

**Comment by drop-rahul** [comment]
Has anyone got weighted routing working? Still getting /   weighted-routing:use-annotation (<error: endpoints "weighted-routing" not found>) Below is my manifest - > 
`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "proxy-ingress-multi-tg"
  namespace: dev
  annotations:
    alb.ingress.kubernetes.io/group.name: aws-registry-proxy-multi
    external-dns.alpha.kubernetes.io/hostname: "ecrmulti.mydev.com"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:12345678:certificate/abcd-efg-hijk
    alb.ingress.kubernetes.io/subnets: subnet-1234,subnet-5678
    alb.ingress.kubernetes.io/security-groups: sg-12345678, sg-87654321
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "20"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/actions.weighted-routing: '{"Type":"forward","ForwardConfig":{"TargetGroupStickinessConfig":{"Enabled": true,"DurationSeconds":100},"TargetGroups":[{"Weight":100,"ServiceName":"aws-registry-proxy-svc","ServicePort":"8080"},{"Weight":0,"ServiceName":"webservice","ServicePort":"80"}]}}'
  labels:
    app: proxy-ingress-multi-tg
spec:
  rules:
    - host: "ecrmulti.mydev.com"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
              service:
                name: weighted-routing
                port:
                  name: use-annotation`

**Comment by mkatychev** [comment]
`kubernetes.io/ingress.class` is replaced by `spec.ingressClass` in v1, this is a working solution I did for GRPC with TLS termination at the ingress:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: "{{ .Values.subnets }}"
    alb.ingress.kubernetes.io/security-groups: "{{ .Values.security_groups }}"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.certificate_arn }}"
  labels:
    app: "{{ .Chart.Name }}"
    environment: "{{ .Values.environment }}"
  name: "{{ .Chart.Name }}"
  namespace: "{{ .Chart.Name }}"
spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: "{{ .Chart.Name }}"
      port:
        number: {{ .Values.grpc.port }}
  rules:
    - host: "{{ .Values.domain.sub }}.{{ .Values.domain.root }}"
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: "{{ .Chart.Name }}"
                port:
                  number: {{ .Values.grpc.port }}
```
