### ISSUE TITLE
x-forwarded-proto been reset by alb 

### ISSUE THREAD

**Issue by jerry153fish** [kubernetes-sigs/aws-load-balancer-controller#1852]
Hi all, we have an ingress using 

user -> (https ) -> alb ->(http) pod

We can get the correctly x-forwarded-for header but the x-forward-proto one has been reseted. We had similar ingress but using inginx-ingress which can disable the proxy-proto.

Is it possible to do the same for alb ?

**Comment by M00nF1sh** [comment]
@jerry153fish 
What do you mean by `x-forward-proto one has been reseted`. from the [documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/how-elastic-load-balancing-works.html), ALB supports X-Forwarded-Proto. currently ALB didn't have any knobs to adjust the behavior.

**Comment by jerry153fish** [comment]
@M00nF1sh 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: debug
  name: alb-ingress
  labels:
    app: ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: xxx
    alb.ingress.kubernetes.io/inbound-cidrs: xxxx
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
    - host: xxx.xxx.org
      http:
        paths:
          - path: /*
            backend:
              serviceName: http-echo
              servicePort: 8080
```

This is how the ingress looks like, I was expecting that x-forward-proto should be https but it is HTTP. The echo outputs

```
{
  "path": "/",
  "headers": {
    "host": "xxx",
    "x-request-id": "d450649ba4b969aab735dd8a3d96b843",
    "x-real-ip": "xxx",
    "x-forwarded-for": "xxx",
    "x-forwarded-host": "xxx",
    "x-forwarded-port": "80",
    "x-forwarded-proto": "http",
    "x-scheme": "http",
    "cache-control": "max-age=0",
    "sec-ch-ua": "\"Google Chrome\";v=\"87\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"87\"",
    "sec-ch-ua-mobile": "?0",
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "sec-fetch-site": "none",
    "sec-fetch-mode": "navigate",
    "sec-fetch-user": "?1",
    "sec-fetch-dest": "document",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en,zh-CN;q=0.9,zh;q=0.8,ja;q=0.7",
    "cookie": "_ga=GA1.2.35614456.1597129335",
    "if-none-match": "W/\"5db-Qrm5DqofEdWiRXT57c8ihoQln7Q\""
  },
  "method": "GET",
  "body": "",
  "fresh": false,
  "hostname": "xxx",
  "ip": "xxx",
  "ips": [
    "xxx"
  ],
  "protocol": "http",
  "query": {},
  "subdomains": [
    "k8s",
    "echo"
  ],
  "xhr": false,
  "os": {
    "hostname": "http-echo-6d5cf94d45-z46mn"
  },
  "connection": {}
}
```

**Comment by M00nF1sh** [comment]
@jerry153fish 
Since the "x-forwarded-port" is 80, did you accessed the ALB through port 80? if so, the x-forwarded-proto should be HTTP.

**Comment by jerry153fish** [comment]
@M00nF1sh thanks for that. I did have a HTTP to HTTPS redirect setup on the ingress
```    
     - http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
```

**Comment by M00nF1sh** [comment]
@jerry153fish 
So you accessed with HTTP first and get redirected to HTTPS? From the ALB's point of view, it would be two request(one http and one HTTPs).
That didn't explain why your backend is getting `x-forwarded-port: 80`. Is there something i'm missing or you figured out the issue ?

**Comment by jerry153fish** [comment]
@M00nF1sh no, we had to force set the header in app or proxy layer to bypass. I assume this is irrelevant that from alb -> targetgroup -> service is using the HTTP. 

```
    - host: xxx.xxx.org
      http:
        paths:
          - path: /*
            backend:
              serviceName: http-echo
              servicePort: 8080
```

But we are using the target type as `ip`, which I think is working in ECS.
