### ISSUE TITLE
SSL redirect ingress format in k8s 1.19

### ISSUE THREAD

**Issue by BanutC** [kubernetes-sigs/aws-load-balancer-controller#1873]
I updated my cluster from 1.18 to 1.19. After that i started to get the following error:

> Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

So I decided to update the ingress rules following the new format.
Before, my ingress rules will look like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "att-igs-api-discovery.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  {{- if not (regexMatch "local.*" .Values.global.cluster) }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: {{ include "->" (list . .Values.sslCertArn) }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/web-acl-id: {{ include "->" (list . .Values.webAcl) }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ include "->" (list . .Values.WAFv2AclArn) }}
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-Ext-2018-06"
    alb.ingress.kubernetes.io/healthcheck-path: /healthCheck/v1
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "10"
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled={{ include "->" (list . .Values.S3AccessLogEnable) }},access_logs.s3.bucket={{ include "->" (list . .Values.S3AccessLog) }},access_logs.s3.prefix=elb,deletion_protection.enabled=true
    alb.ingress.kubernetes.io/tags: Environment={{ include "->" (list . .Values.tagEnv) }},Inventory={{ include "->" (list . .Values.tagInv) }},Owner={{ include "->" (list . .Values.tagOwn) }},Name={{ include "->" (list . .Values.tagName) }}
   {{- end }}
  labels:
    app: {{ include "att-igs-api-discovery.fullname" . }}
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: "att-svc-np-api-discovery"
              servicePort: 30280
```
After that, the ingress looks like this:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "att-igs-api-discovery.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  {{- if not (regexMatch "local.*" .Values.global.cluster) }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: {{ include "->" (list . .Values.sslCertArn) }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/web-acl-id: {{ include "->" (list . .Values.webAcl) }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ include "->" (list . .Values.WAFv2AclArn) }}
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-FS-1-2-Res-2020-10"
    alb.ingress.kubernetes.io/healthcheck-path: /healthCheck/v1
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "10"
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled={{ include "->" (list . .Values.S3AccessLogEnable) }},access_logs.s3.bucket={{ include "->" (list . .Values.S3AccessLog) }},access_logs.s3.prefix=elb,deletion_protection.enabled=true,routing.http.drop_invalid_header_fields.enabled=true
    alb.ingress.kubernetes.io/tags: Environment={{ include "->" (list . .Values.tagEnv) }},Inventory={{ include "->" (list . .Values.tagInv) }},Owner={{ include "->" (list . .Values.tagOwn) }},Name={{ include "->" (list . .Values.tagName) }}
   {{- end }}
  labels:
    app: {{ include "att-igs-api-discovery.fullname" . }}
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              service:
                name: ssl-redirect
                port:
                  number: use-annotation
          - path: /*
            backend:
              service:
                name: "att-svc-np-api-discovery"
                port:
                  number: 30280
```

My problem is at service `ssl-redirect`. Before that i used `use-annotation` at `servicePort` to redirect my traffic. Now `number` doesn't support that syntax used in the previous example.
I tried to find anything in docs, but all information i found use the old `apiVersion: extensions/v1beta1` and the old styling for ingress rules.
