### ISSUE TITLE
Specifying group order smaller than the default (i.e. 0)

### ISSUE THREAD

**Issue by hazim1093** [kubernetes-sigs/aws-load-balancer-controller#1875]
## Problem
I have an ingress with a rule that needs to be evaluated first in the ALB. 
In order to ensure that, I would have to assign group orders to all other ingresses, so that this particular ingress has the smallest order which is "0". 
It would be convenient if we could set the order such that one ingress has the smallest order instead of specifying the order for all other present and future ingresses.

I faced this issue while creating a common ingress for redirecting HTTP to HTTPS for all routes, and some common annotations instead of adding boilerplate config to each ingress. ( This request/issue is already tracked in #1768 ) 

## Proposed Solution
If a new order is introduced which is smaller than the default, it would solve the problem. 
e.g. order `-1`, the default would still be `0` so all rules will be added after that. 

## Current Solution / Workaround
By default the rules are ordered based on the lexical order of Ingress’s namespace/name.
I created a dummy namespace (e.g. `1-ns`) such that this ingress rule is always evaluated first and created this ingress in that namespace. 

## Example Ingress
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-loadbalancer-default
  namespace: 1-ns
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: "dev"
    alb.ingress.kubernetes.io/tags: Environment=dev,Name=dev
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
```
