### ISSUE TITLE
EKS Fargate 1.19: Created load balancer has no targets

### ISSUE THREAD

**Issue by vorti2** [kubernetes-sigs/aws-load-balancer-controller#1884]
Hi devs,

I deploy AWS load balancer controller via helm in my EKS 1.19 fargate cluster:

```
helm upgrade -i aws-load-balancer-controller \
                                           eks/aws-load-balancer-controller \
                                           -n kube-system \
                                           --set clusterName=$EKS_CLUSTER_NAME \
                                           --set serviceAccount.create=false \
                                           --set serviceAccount.name=aws-load-balancer-controller \
                                           --set region=$AWS_REGION --set vpcId=$EKS_VPC
```

If I deploy a service to this cluster the resulting load balancer (which was created correctly IMHO) has __no__ targets.

How can I equip the load balancer with more rights so that it can also attach targets?

Regards,
Wilhelm

**Comment by kishorj** [comment]
@vorti2, what does your service spec look like? Did you specify `nlb-ip` for the annotation `service.beta.kubernetes.io/aws-load-balancer-type`?

**Comment by vorti2** [comment]
@kishorj thanks for the fast reply, the service has the following ingress (helm):

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.libretta.serviceName }}.{{ .Values.libretta.serviceDomain }}
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.libretta.certificateArn }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
  name: {{ .Values.appName }}-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.appName }}-service
            port:
              number: {{ .Values.libretta.port }}
```

(I use `external-dns` annotation and that part works now ...).

Should I add the annotation `service.beta.kubernetes.io/aws-load-balancer-type`?
