### ISSUE TITLE
502 Error for mutual TLS with istio ingress

### ISSUE THREAD

**Issue by apryiomka** [kubernetes-sigs/aws-load-balancer-controller#1892]
We use ALB controller to forward traffic to our `istio-ingressgateway` service that routes the internal traffic. We currently have configured mutual TLS as per [istio documentation](https://istio.io/v1.7/docs/tasks/traffic-management/ingress/secure-ingress/#configure-a-mutual-tls-ingress-gateway).

We were able to get isiot working for both mutual TLS and simple TLS. I can hit the services with istio NodePort from within the pod in the cluster as per example:
```
curl -v -HHost:httpbin.example.com --resolve "httpbin.example.com:31047:10.0.17.158" "https://httpbin.example.com:31047/status/418" -k --cert httpbin.example.com.crt --key httpbin.example.com.key
```
where `31047` port is listed below and `10.0.17.158` is the Node's IP address - `istio-ingressgateway` is a `NodePort`:
```
apiVersion: v1
kind: Service
metadata:
    app: istio-ingressgateway
  name: istio-ingressgateway
  namespace: istio-system
spec:
  ports:
  - name: http2
    nodePort: 30481
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 31047
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  type: NodePort
```

This is our Ingress configuration:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
    alb.ingress.kubernetes.io/healthcheck-port: "31562"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    kubernetes.io/ingress.class: alb
  labels:
    app: tls
  name: tls
  namespace: istio-system
spec:
  rules:
  - host: '*.example.com'
    http:
      paths:
      - path: /*
        backend:
          serviceName: istio-ingressgateway
          servicePort: https
```
I also tried to set ports explicitly like so:
```
  http:
    paths:
    - path: /*
      backend:
        serviceName: istio-ingressgateway
        servicePort: 443
```
and
```
  http:
    paths:
    - path: /*
      backend:
        serviceName: istio-ingressgateway
        servicePort: 31047
```
I constantly get 502 when Istio gateway is set to mutual TLS:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tls-default
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: MUTUAL
      credentialName: tls-certificate-other
    hosts:
    - '*'
```
I can get ALB to pass through when the gateway is set to SIMPLE TLS

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tls-default
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-certificate-other
    hosts:
    - '*'
```

Note, that istio works when traffic is internal, that includes both SIMPLE TLS and MUTUAL TLS, MUTUAL TLS doesn't work then traffic goes through ALB.
