### ISSUE TITLE
One instance of the NLB times out in one of the us-east-1 AZ

### ISSUE THREAD

**Issue by apryiomka** [kubernetes-sigs/aws-load-balancer-controller#1895]
We created istio ingress gateway with NLB that looks like so:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: tls-ingressgateway
    istio: tls-ingressgateway
  name: tls-ingressgateway
  namespace: istio-system
spec:
  ports:
  - name: status-port
    nodePort: 32150
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    nodePort: 30408
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 32381
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: tls
    nodePort: 30943
    port: 15443
    protocol: TCP
    targetPort: 15443
  selector:
    app: tls-ingressgateway
    istio: tls-ingressgateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: *******.elb.us-east-1.amazonaws.com
```

As the result, the `*******.elb.us-east-1.amazonaws.com` NLB is created in three availability zones resulting in 3 IPs the host resolves to. Now two IPs seems to be routing traffic just fine to the EKS LoadBalancer service, but one of the three for some reason doesn't route any traffic and constantly times out. I tried to delete the istio ingress LoadBalancer service and re-create, I get the same result back. Two out of three work, one doesn't. 

```
curl -v -HHost:httpbin.example.com "https://*******.elb.us-east-1.amazonaws.com/status/418" -k
*   Trying XXX.XXX.XXX.96...
* TCP_NODELAY set
* Connection failed
* connect to XXX.XXX.XXX.96 port 443 failed: Operation timed out
*   Trying XXX.XXX.XXX.27...
* TCP_NODELAY set
* Connected to *******.elb.us-east-1.amazonaws.com (XXX.XXX.XXX.27) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
```

Whenever NLB resolves to XXX.XXX.XXX.96 above, it would time out. If it resolves to the other two - XXX.XXX.XXX.27 or XXX.XXX.XXX.156, it works just fine. The IP addresses are set by AWS, not US, the AZs are also picked based on the subnets public subnets
