### ISSUE TITLE
Redirect port 80 to 443

### ISSUE THREAD

**Issue by aswanevelder** [kubernetes-sigs/aws-load-balancer-controller#1914]
Can an annotation be created to redirect port 80 to 443? 

`alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'`

![Image 2021-04-05 at 08 37](https://user-images.githubusercontent.com/10231700/113545388-5839c900-95ea-11eb-94e7-26923ba244b0.jpg)

**Comment by cloudlady911** [comment]
@aswanevelder I saw that you closed this.  I have been trying to do this too.  But have been unable to get his to work.  Did you find a solution?

**Comment by mylifelineio** [comment]
Yes, just add the RedirectConfig to your annotations

```
annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
```
