### ISSUE TITLE
Tags not being applied to the ALB

### ISSUE THREAD

**Issue by lpossamai** [kubernetes-sigs/aws-load-balancer-controller#1921]
Even if I delete the load balancer and re-create it, the tags are not being applied:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: envoy
  namespace: envoy-proxy
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test,App=envoy
```

Is this a known issue? Any work arounds?
