### ISSUE TITLE
SSL-Redirect not working

### ISSUE THREAD

**Issue by cloudlady911** [kubernetes-sigs/aws-load-balancer-controller#1936]
I am using kubernetes 1.18 on AWS EKS.
I have deployed aws load balancer version 2.1
I attempted to follow the instructions here: [link](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/tasks/ssl_redirect/)

This is my ingress yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: testredirect
  namespace: 1-ns
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/group.name: testredirect
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:725680032710:certificate/xxxxx-xxxxx-xxxxx
    alb.ingress.kubernetes.io/success-codes: 200,303,404,301
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'

spec:
  rules:
    - http:
        paths:
        - path: /*
          backend:
            serviceName: ssl-redirect
            servicePort: use-annotation
```

Ultimately I want to do this to create a basic shared elb that other apps will use. (similar to what was described in this [post](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1768)) Hence I have added the group.name annotation.

The resulting ALB created by this yaml has both listeners, but the http listener is set to "Default: returning fixed response 404"  instead of redirecting to 443.

I have tried removing the group.name annotation but that did not make a difference.
