### ISSUE TITLE
How to set different rules for HTTP and HTTPS?

### ISSUE THREAD

**Issue by jinzishuai** [kubernetes-sigs/aws-load-balancer-controller#1937]
So far, I got my alb-ingress working pretty nicely with

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: ac-dev
  name: ingress-ac-example-dev
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: web-sites.example.farm
    alb.ingress.kubernetes.io/group.order: "1000"
    alb.ingress.kubernetes.io/subnets: ac-example-dev-private-ap-southeast-1a, ac-example-dev-private-ap-southeast-1b, ac-example-dev-private-ap-southeast-1c
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: example-service
              servicePort: 8080

```

However, I am struggle to find a way to have the HTTP listener to have different rules from the HTTPS listerners.
For example
* I would like to have only a single redirect from HTTP to HTTPS rule as the default rule for the HTTP listener
* On the other hand, we wish to have multiple rules in HTTPS that send to different services for different host/path combinations.

I am not sure how to do this in a clean way. I ended up creating multiple ssl-redirect rules that look identical for the same hots/path combinations which is not looking nice to the least. Is there a best practice for my use case? Thank you very much.

**Comment by M00nF1sh** [comment]
@jinzishuai 
we have a upcoming release that supports a feature for this exact use case: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1837

In the meanwhile, with current version, you need to use IngressGroups feature and create two Ingress(one for HTTP listener) another for HTTPS listener and group them together on a single ALB.

**Comment by kishorj** [comment]
simplified ssl-redirect configuration support is available in v2.2.0 release. Closing the issue.

**Comment by jinzishuai** [comment]
For people's reference, this is how the new configuration works:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: ac-dev
  name: ingress-ac-example-dev
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: web-sites.example.farm
    alb.ingress.kubernetes.io/group.order: "1000"
    alb.ingress.kubernetes.io/subnets: ac-example-dev-private-ap-southeast-1a, ac-example-dev-private-ap-southeast-1b, ac-example-dev-private-ap-southeast-1c
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: example-service
              servicePort: 8080
```
The code is much simpler and the resulting HTTP listener would have a single redirect rule as
![image](https://user-images.githubusercontent.com/1074685/122812251-b17ed380-d28e-11eb-8dc3-588b3e37b686.png)

This is perfect!
