### ISSUE TITLE
How to point to a service in a different ns than the ingress

### ISSUE THREAD

**Issue by kaykhancheckpoint** [kubernetes-sigs/aws-load-balancer-controller#1951]
Hi friends, i am looking at creating an alb

Lets say i have two namespaces `kubernetes-dashboard` and `otherns`. 

In the first namespace i have a service called `kubernetes-dashboard` and in the second namespace i have a service called `otherservice`

Would the below ingress work?

**ingress.yml**

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: general-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: <redacted>
    alb.ingress.kubernetes.io/tags: Environment=staging,Team=dev
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '300'
spec:
  rules:
    - host: k8s.acme.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: kubernetes-dashboard.kubernetes-dashboard
              servicePort: 8080
    - host: otherservice.acme.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: otherservice.otherns
              servicePort: 80
```
