### ISSUE TITLE
How to find/generate TLS secret

### ISSUE THREAD

**Issue by kaykhancheckpoint** [kubernetes-sigs/aws-load-balancer-controller#1954]
Hi friends,

I am new to this library, I have a service i have installed on my k8s cluster that requires me to setup a certificate and specify a secret with the certificate details (ca.crt, tls.crt, tls.key). https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-tls-certificates.html#k8s-setting-up-your-own-certificate

This service is a NodePort which i expose externally using this ingress controller.

Where do i find these 3 variables  `ca.crt, tls.crt, tls.key`, Or how do i create them? Is it related to this library?

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elastic-ingress
  namespace: elastic-system
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: "<redacted>"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: <redacted>
    alb.ingress.kubernetes.io/tags: Environment=prod,Team=dev
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '300'
spec:
  rules:
    - host: kibana.dev.<redacted>.com
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: kibana-prod-kb-http
                port:
                  number: 5601

```

Right now i use ACM to create a certificate arn for that sub domain and i apply the arn to the field     alb.ingress.kubernetes.io/certificate-arn. How is this related? if at all?
