### ISSUE TITLE
SSL certificate and policy are not getting attached when `alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":443}]'` annotation is set

### ISSUE THREAD

**Issue by alexmnyc** [kubernetes-sigs/aws-load-balancer-controller#1957]
Hi,

I have successfully provisioned ALB with the SSL previously but it doesn't work after adding `alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":443}]'` annotation as such

```
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:iam::XXX:server-certificate/cert-xx20210422202846575100000001"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-2016-08
```

![image](https://user-images.githubusercontent.com/1847565/116282500-d9ebc500-a758-11eb-91f8-e615a1eaf195.png)

I am using v2.1.3 on EKS

### complete example

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: poc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: poc
  name: deployment-2048
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048
    spec:
      containers:
        - image: alexwhen/docker-2048
          imagePullPolicy: Always
          name: app-2048
          ports:
            - containerPort: 80
      nodeSelector:
        instance-type: m5a.large
---
apiVersion: v1
kind: Service
metadata:
  namespace: poc
  name: service-2048
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-2048
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: poc
  name: ingress-2048
  annotations:
    alb.ingress.kubernetes.io/target-type: instance
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/group.name: "poc"
    alb.ingress.kubernetes.io/group.order: "1"
    alb.ingress.kubernetes.io/tags: "AppName=poc"
    alb.ingress.kubernetes.io/subnets: subnet-XXX, subnet-XX2
    alb.ingress.kubernetes.io/security-groups: sg-XXX
    alb.ingress.kubernetes.io/load-balancer-attributes: "idle_timeout.timeout_seconds=60"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:iam::XXXX:server-certificate/poc20210422202846575100000001"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-2016-08

spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: service-2048
              servicePort: 80
```

certificate arn arn:aws:iam::XXXX:server-certificate/poc20210422202846575100000001 does exist and IAM role for aws lb controller has access to it 

After poking around at it and trying different permutations of Ingress I found the cause. If I comment out `    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":443}]'` all gets created perfectly well as follows:

![image](https://user-images.githubusercontent.com/1847565/116287017-e6265100-a75d-11eb-8b0b-3f62a2f6b00e.png)

If I enable `alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":443}]'` annotation SSL is not getting attached
