### ISSUE TITLE
Separate annotations under a single Ingress

### ISSUE THREAD

**Issue by yuzhouliu-solace** [kubernetes-sigs/aws-load-balancer-controller#1981]
I have one application using HTTPS, and another using gRPC.
Is it possible to merge them under one Ingress? Or specifically have a single Load Balancer to handle both (to save money)?

Would the `alb.ingress.kubernetes.io/backend-protocol-version: GRPC` of the gRPC ingress cause trouble for the HTTPS ingress?

Thanks!

Ingress of HTTPS app:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nexus-ingress
  namespace: nexus
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: <>
    alb.ingress.kubernetes.io/subnets: <>
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}, {"HTTPS": 18444}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
spec:
  rules:
    - host: nexus.abcd.net
      http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: nexus-service
              servicePort: 80
    - host: docker.abcd.net
      http:
        paths:
          - path: /*
            backend:
              serviceName: nexus-service
              servicePort: 18444
```

Ingress of gRPC app:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: artifact-inventory
  labels:
    app: artifact-inventory
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: <>
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 50051}]'
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
spec:
  rules:
  - host: artifact-inventory.abcd.net
    http:
      paths:
        - path: /*
          backend:
            serviceName: artifact-inventory
            servicePort: 50051
```
