### ISSUE TITLE
use multiple 'host' at once

### ISSUE THREAD

**Issue by DevOpJadeja** [kubernetes-sigs/aws-load-balancer-controller#1984]
```yaml
...
...
spec:
  rules:
  - host: 
    - admin.example.com
    - team.example.com
    - customer.example.com
    http:
      paths:
        - pathType: Prefix
          path: "/*"
...
...
```
something like this.
