### ISSUE TITLE
TargetGroupBinding stuck in FailedCleanup loop (Failed cleanup due to ValidationError) when created without a targetGroupARN

### ISSUE THREAD

**Issue by wjrogers** [kubernetes-sigs/aws-load-balancer-controller#1997]
I accidentally created a TargetGroupBinding without a `targetGroupARN`. I misspelled the key, and I explicitly included `targetType: ip`, so the resource was successfully created missing the ARN:

```yaml
spec:
  serviceRef:
    name: beanstalkd
    port: 11300
  targetGroupARN: ""
  targetType: ip
```

I subsequently tried to delete it, and now the resource seems permanently stuck in this event loop:

> Warning  FailedCleanup  80s (x8 over 6m45s)  targetGroupBinding  (combined from similar events): Failed cleanup due to ValidationError: A target group ARN must be specified
>           status code: 400, request id: 4c885c04-894f-4f40-930b-0fb62e96ede1

Workaround: remove the finalizer from the broken TargetGroupBinding (e.g. `kubectl edit`) so it can be deleted.
