### ISSUE TITLE
ALB cognito config not created

### ISSUE THREAD

**Issue by thomashoefkens-vw** [kubernetes-sigs/aws-load-balancer-controller#1998]
Hi everyone,

I am using aws-load-balancer-controller v2.1.3 and am facing the same issue as #1382 which is marked as closed.

I have the following annotations on my ingress:

```
ingress:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/auth-scope: openid
    alb.ingress.kubernetes.io/auth-session-timeout: '3600'
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn": "arn:aws:cognito-idp:eu-central-1:xxx:userpool/eu-central-1_abc","UserPoolClientId":"xxxxx","UserPoolDomain":"my-cognito-domain"}'
```
The ALB is created, pods are included in the target group, yet the cognito config is not in place..
Also, there is no error in the aws-lbc pod logs.

What could be causing this?

Thanks
