### ISSUE TITLE
Ingressclassparams don't take effect.

### ISSUE THREAD

**Issue by b0nete** [kubernetes-sigs/aws-load-balancer-controller#2025]
Hi again!, i have a new doubt.

I tried to create two differents ingressclass (public and internal) associating this with two ingressclassparams. 
The problem is when deploy my application using specs instead of annotations, this don't take effect, this follow using internal scheme.
But when i add annotation this work correctly.

What is the problem? The only difference between documentation is the apiVersion used in ingressclass, i had to change to 
**v1beta1** because **v1** don't work for me. 

This are my manifests.
```
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: ingressclass-public
spec:
  controller: ingress.k8s.aws/alb
  parameters:
    apiGroup: elbv2.k8s.aws
    kind: IngressClassParams
    name: public-param
```
```
apiVersion: elbv2.k8s.aws/v1beta1
kind: IngressClassParams
metadata:
  name: public-param
  namespace: alb-ingress-controller
spec:
  scheme: internet-facing
```

In the deployment add this spec.
```
spec:
  ingressClassName: ingressclass-public
```

What is the problem here? thanks!

**Comment by M00nF1sh** [comment]
@b0nete 
What's your controller version? it needs to be v2.2.0 to support IngressClassParams

**Comment by kishorj** [comment]
@b0nete, closing the issue for now. If you still have issues, feel free to reopen or create a new one.

**Comment by zachfeldman-koneksahealth** [comment]
@M00nF1sh @kishorj I seem to be having the same issue here.

After switching to IngressClass and IngressClassParams my internet-facing alb's are coming up as internal. Running v1.2.0 of the helm chart which should be v2.2.0+ of the controller.

```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: ext-alb-class
spec:
  controller: ingress.k8s.aws/alb
  parameters:
    apiGroup: elbv2.k8s.aws
    kind: IngressClassParams
    name: ext-alb-class
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: IngressClassParams
metadata:
  name: ext-alb-class
spec:
  scheme: internet-facing
  tags:
  - key: ingress-class
    value: ext-alb-class
```

my deployments have:
```
spec:
  ingressClassName: ext-alb-class
```

I don't see anything unusual in the logs, the load balancers reconcile it just looks like the Params that deem the LB internet-facing aren't taking.
