### ISSUE TITLE
defaultMetricsAddr port is fixed to 8080 and might cause crashloopback in some cases

### ISSUE THREAD

**Issue by ybialik** [kubernetes-sigs/aws-load-balancer-controller#2027]
the defaultMetricsAddr is fixed to 8080 and in some cases, if the pod is created on a node with kube-state-metric that is also using 8080 by default - the pod will be in a crashloopback 

{"level":"error","ts":1621765581.0182273,"logger":"controller-runtime.metrics","msg":"metrics server failed to listen. You may want to disable the metrics server or use another port if it is due to conflicts","error":"error listening on :8080: listen tcp :8080: bind: address already in use"}
{"level":"error","ts":1621765581.0182464,"logger":"setup","msg":"unable to start manager","error":"error listening on :8080: listen tcp :8080: bind: address already in use"}

please add an option to pass defaultMetricsAddr as an external argument.

**Comment by kishorj** [comment]
@ybialik, you can specify the controller flag `--metrics-bind-addr`. If you installed the helm chart, you can also set the `metricsBindAddr` value during chart installation. Did this option not help in your case?

As for `address already in use` error, did you enable host networking on the lb controller pods?

**Comment by ybialik** [comment]
@kishorj I followed this manual:
https://aws.amazon.com/premiumsupport/knowledge-center/eks-alb-ingress-controller-setup/
so we did not install the controller with helm..

regrading the second question - yes, hostNetwork is true in our deployments as we are using a custom CNI (cilium)

**Comment by kishorj** [comment]
were you able to specify the `--metrics-bind-addr` flag and see if you are able to get past the crash? You will have to edit the deployment spec. For example, If you want to use port 8081 - 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: aws-load-balancer-controller
  name: aws-load-balancer-controller
...
    spec:
      containers:
      - args:
        - --cluster-name=your-cluster-name
        - --ingress-class=alb
        - --metrics-bind-addr=:8081
        image: amazon/aws-alb-ingress-controller:v2.2.0
        livenessProbe:
---
```
