### ISSUE TITLE
Internal load balancer throws curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by saranyaeu2987** [kubernetes-sigs/aws-load-balancer-controller#2032]
I exposed a k8s service using internal load balancer using annotation
`kubectl patch svc argo-server -n argo -p '{"metadata": {"annotations": {"service.beta.kubernetes.io/aws-load-balancer-internal": "true"}}}'`

It stopped working and started giving me **(52) Empty reply from server** for curl.

I tried 
`service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"`
and 
`service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"`
both gives same error.

I see external ip is exposed with `service.beta.kubernetes.io/aws-load-balancer-internal: "true"` but unable to access it

```
kubectl get svc argo-server -n argo                                                                                                          
NAME          TYPE           CLUSTER-IP       EXTERNAL-IP                                                                        PORT(S)          AGE
argo-server   LoadBalancer   172.20.135.242   internal-ae99b272671214b38bba978529ccc81f-1242061336.us-east-1.elb.amazonaws.com   2746:32105/TCP   11h
```
P.S - EKS k8s version - 1.19

Any suggestion?

**Comment by kishorj** [comment]
@saranyaeu2987, for some reason your backend application pods are honoring http requests. Could you verify the following -

- the instance targets in the NLB target groups are all healthy
- your backend pods are setup to accept plain http. Check if the application does not expect https(TLS) or proxy protocol v2 connections

Based on load balancer name, your service is reconciled by the kubernetes in-tree controller and not by the controller from this project. Most of the new features documented in this project would not be available in the in-tree controller.

**Comment by saranyaeu2987** [comment]
@kishorj 
All instances are healthy. 
 I am unable to create an internal load balancer in private subnet just by using **type: LoadBalancer** and **service.beta.kubernetes.io/aws-load-balancer-scheme: internal** 
ref: https://docs.aws.amazon.com/eks/latest/userguide/network-load-balancing.html

Only with annotation **service.beta.kubernetes.io/aws-load-balancer-scheme**
`kubectl describe svc argo-server -n argo                                                  
Name:                     argo-server
Namespace:                argo
Labels:                   <none>
Annotations:              kubectl.kubernetes.io/last-applied-configuration:
                            {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-nlb-target-type":"instance","...
                          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
                          service.beta.kubernetes.io/aws-load-balancer-scheme: internal
                          service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
Selector:                 app=argo-server
Type:                     LoadBalancer
IP:                       172.20.55.207
Port:                     web  2746/TCP
TargetPort:               2746/TCP
NodePort:                 web  30185/TCP
Endpoints:                10.207.195.15:2746
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age   From                Message
  ----    ------                ----  ----                -------
  Normal  EnsuringLoadBalancer  5m3s  service-controller  Ensuring load balancer`
 
 Only 
` service.beta.kubernetes.io/aws-load-balancer-internal: "true"` creates a classic internal load balancer for a service. but gives Empty reply error

`kubectl describe svc argo-server -n argo        
Name:           argo-server
Namespace:        argo
Labels:          <none>
Annotations:       kubectl.kubernetes.io/last-applied-configuration:
              {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-internal":"0.0.0.0/0"},"creat...
             service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
             service.beta.kubernetes.io/aws-load-balancer-scheme: internal
Selector:         app=argo-server
Type:           LoadBalancer
IP:            172.20.135.242
LoadBalancer Ingress:   internal-ae99b272671214b38bba978529ccc81f-1242061336.us-east-1.elb.amazonaws.com
Port:           web 2746/TCP
TargetPort:        2746/TCP
NodePort:         web 32105/TCP
Endpoints:        10.207.195.92:2746
Session Affinity:     None
External Traffic Policy: Cluster
Events:          <none>`
 
Can you please guide what annotation am I missing here

**Comment by kishorj** [comment]
Did you install the AWS Load Balancer controller? You can find the installation instructions at the live docs https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/installation. This controller is different from the kubernetes in-tree controller available with kubernetes.

The annotation you've specified will create NLB with IP targets -
```
service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
service.beta.kubernetes.io/aws-load-balancer-scheme: internal
service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
```

For instance targets, you will have to specify
```
service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
service.beta.kubernetes.io/aws-load-balancer-type: external
```

You see the `Normal EnsuringLoadBalancer...` event and no other events mean you don't have the AWS Load balancer controller installed.

In your second example, you haven't specified the `service.beta.kubernetes.io/aws-load-balancer-type` annotation. So the in-tree controller provisions CLB.

**Comment by saranyaeu2987** [comment]
@kishorj 

I have very minimal requirement of exposing EKS k8s service to users within team. So, a classic load balancer is suffice. 
So, as in second example - it create a CLB(like you mentioned), but unable to access it ((52) Empty reply from server).

1. I dont see error logged anywhere for that service, nor host down. Any guidance on debugging this CLB and make the service reachable using CLB (This CLB solution was working fine for past 6 months, until couple of days)

2. If AWS Load Balancer is only option then, my EKS cluster has only private subnets. So I can have only internal LB.
is this annotation relevant for internal Load Balancer
`service.beta.kubernetes.io/aws-load-balancer-type: external`

**Comment by kishorj** [comment]
@saranyaeu2987,
CLB should work just fine. As I mentioned previously, the empty reply error has something to do with your application pods. For some reason, your application pods are not sending http responses. 

The annotation `service.beta.kubernetes.io/aws-load-balancer-type: external` is for the in-tree controller to pass on the service to an external component for provisioning the load balancer.

**Comment by tonisojandu** [comment]
@kishorj @saranyaeu2987 , this might me totally unrelated. I stumbled on this thread when I was researching our own problem. 

Symptoms are really similar. System that was working for some time suddenly started causing problems couple of days ago. We are not on AWS, but we that this problem specifically is with our nginx proxy and TLS. When the HTTP header is larger than 5476 bytes then we encounter similar error. Non-TLS responds correctly.

This is just a hint. You may be using nginx somewhere internally and may want to test with different header sizes. But again, might be totally unrelated.

We are internally trying to pinpoint the package upgrade that may have cause this. No info currently. But if they are related then I would be thankful for the information, if you pinpoint the issue before us.

**Comment by mikeinton** [comment]
We might be experiencing the same issue.

**AWS LB Controller Version:**
v2.2.0 installed via static manifests over an older v2.1.3 install (updated new CRD's and IAM permissions as well)

**Kubernetes Version:**
v1.21.1 installed via Kops 1.21.0-beta2

We've been waiting for v.2.2.0 of the AWS LB Controller so that we can test dual stack internal-facing NLB's running in instance mode since we are using Cilium instead of AWS's CNI.

```
❯ curl -k https://k8s-demo-nlb-4175996729-e7f7db43b44a43e8.elb.us-east-2.amazonaws.com
curl: (52) Empty reply from server
```

Here are the annotations we used for this NLB.  Logs from the aws-lb-controller confirm that it deployed this NLB after specs were applied.
```
annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <redacted>
    external-dns.alpha.kubernetes.io/hostname: <redacted>
```

When switching back to use the in-tree kube-controller-manager NLB spec, everything works again.  Here's an example of what we were previously using.
```
annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <redacted>
    external-dns.alpha.kubernetes.io/hostname: <redacted>
```

Target Groups registered instances in the AWS console all show healthy with the correct backing node ports so we're not really sure what's going on here.

Our example service is just a simple echo server `gcr.io/google_containers/echoserver:1.8` exposed on 8080 which works fine if I kubectl port forward to it and connect to it via normal http.
```
spec:
  selector:
    app: nlb
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
  type: LoadBalancer
```

**Comment by saranyaeu2987** [comment]
@mikeinton 
I was having this issue because I didnt properly configure the SSL certificate and k8s service was not responding because communication was not TLS enabled.

Below are the set of annotation that worked for me

`  service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert:  arn:aws:acm:us-east-1:******
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"`

**Comment by mikeinton** [comment]
Hi @saranyaeu2987 thanks for the reply.

As @kishorj mentioned earlier using `service.beta.kubernetes.io/aws-load-balancer-type: nlb` results in the in-tree kube-controller-manager creating the NLB, not the AWS LB Controller.

We have no issues with our NLB's when using that annotation.

Our issue is specifically with NLB's reconciled by the new AWS LB Controller v2.2.0 using these new annotations as per - https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/nlb/#configuration

```
annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
```

**Comment by kishorj** [comment]
@mikeinton, the in-tree controller doesn't support proxy protocol v2, i.e it ignores the annotation `service.beta.kubernetes.io/aws-load-balancer-proxy-protocol`. However, the AWS LB controller will honor this annotation and configure proxy protocol on the target groups. The `gcr.io/google_containers/echoserver:1.8` does not support proxy protocol. You'd either need an app that has support for proxy protocol v2, for example nginx, and configure appropriately, or remove the annotation `service.beta.kubernetes.io/aws-load-balancer-proxy-protocol` from your service.

**Comment by mikeinton** [comment]
Thanks @kishorj, I removed `service.beta.kubernetes.io/aws-load-balancer-proxy-protocol` and I'm seeing the same results.

```
annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
```
