### ISSUE TITLE
Upgrade from v2.1.3 to v2.2 Failing problem running manager

### ISSUE THREAD

**Issue by kaykhancheckpoint** [kubernetes-sigs/aws-load-balancer-controller#2036]
Hi friends,

I wanted to upgrade from v2.1.3 to v2.2 .

However after upgrading i am now recieving an error and the pod crashes. 

**kubectl logs -f aws-load-balancer-controller-kube-system-54fb558d8f-q6vkv -n kube-system**

> {"level":"info","ts":1622205184.4700763,"msg":"version","GitVersion":"v2.2.0","GitCommit":"68c417a7ea37ff153f053d9ffef1cc5c70d7e211","BuildDate":"2021-05-14T21:49:05+0000"}
> {"level":"info","ts":1622205187.6245296,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
> {"level":"info","ts":1622205187.6266322,"logger":"setup","msg":"adding health check for controller"}
> {"level":"info","ts":1622205187.6266942,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-v1-pod"}
> {"level":"info","ts":1622205187.6267304,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
> {"level":"info","ts":1622205187.626755,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
> {"level":"info","ts":1622205187.6267757,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-networking-v1beta1-ingress"}
> {"level":"info","ts":1622205187.6269166,"logger":"setup","msg":"starting podInfo repo"}
> I0528 12:33:09.627008       1 leaderelection.go:242] attempting to acquire leader lease  kube-system/aws-load-balancer-controller-leader...
> {"level":"info","ts":1622205189.7272909,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
> {"level":"info","ts":1622205189.7273088,"logger":"controller-runtime.webhook.webhooks","msg":"starting webhook server"}
> {"level":"info","ts":1622205189.7277226,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
> {"level":"info","ts":1622205189.7278209,"logger":"controller-runtime.webhook","msg":"serving webhook server","host":"","port":9443}
> {"level":"info","ts":1622205189.7278821,"logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
> I0528 12:33:24.677745       1 leaderelection.go:252] successfully acquired lease kube-system/aws-load-balancer-controller-leader
> {"level":"info","ts":1622205204.6779692,"logger":"controller","msg":"Starting EventSource","controller":"service","source":"kind source: /, Kind="}
> {"level":"info","ts":1622205204.6780825,"logger":"controller","msg":"Starting Controller","controller":"service"}
> {"level":"info","ts":1622205204.6779726,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"channel source: 0xc000090690"}
> {"level":"info","ts":1622205204.6781013,"logger":"controller","msg":"Starting workers","controller":"service","worker count":3}
> {"level":"info","ts":1622205204.6781425,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"channel source: 0xc0000906e0"}
> {"level":"info","ts":1622205204.678204,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"kind source: /, Kind="}
> {"level":"info","ts":1622205204.6782513,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"kind source: /, Kind="}
> {"level":"info","ts":1622205204.6783605,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"kind source: /, Kind="}
> {"level":"info","ts":1622205204.6783473,"logger":"controller","msg":"Starting EventSource","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","source":"kind source: /, Kind="}
> {"level":"info","ts":1622205204.6785593,"logger":"controller","msg":"Starting EventSource","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","source":"kind source: /, Kind="}
> {"level":"info","ts":1622205204.6786187,"logger":"controller","msg":"Starting EventSource","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","source":"kind source: /, Kind="}
> {"level":"info","ts":1622205204.7788537,"logger":"controller","msg":"Starting EventSource","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","source":"kind source: /, Kind="}
> {"level":"info","ts":1622205204.8791637,"logger":"controller","msg":"Starting Controller","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding"}
> {"level":"info","ts":1622205204.9787166,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"channel source: 0xc000090960"}
> {"level":"info","ts":1622205204.9788074,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"kind source: /, Kind="}
> {"level":"error","ts":1622205204.9930644,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"IngressClassParams.elbv2.k8s.aws","error":"no matches for kind \"IngressClassParams\" in version \"elbv2.k8s.aws/v1beta1\""}
> {"level":"error","ts":1622205204.9931467,"logger":"controller","msg":"Could not wait for Cache to sync","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","error":"failed to wait for targetGroupBinding caches to sync: cache did not sync"}
> {"level":"info","ts":1622205204.993222,"logger":"controller","msg":"Stopping workers","controller":"service"}
> {"level":"info","ts":1622205204.9932265,"logger":"controller-runtime.webhook","msg":"shutting down webhook server"}
> {"level":"error","ts":1622205204.993333,"logger":"controller-runtime.manager","msg":"error received after stop sequence was engaged","error":"failed to wait for targetGroupBinding caches to sync: cache did not sync"}
> {"level":"error","ts":1622205205.4933515,"logger":"setup","msg":"problem running manager","error":"no matches for kind \"IngressClassParams\" in version \"elbv2.k8s.aws/v1beta1\""}
> {"level":"error","ts":1622205205.4934142,"logger":"controller-runtime.manager","msg":"error received after stop sequence was engaged","error":"leader election lost"}
> 

values.yml

```
# Default values for aws-load-balancer-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller
  tag: v2.2.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: "kube-system"
fullnameOverride: ""

# The name of the Kubernetes cluster. A non-empty value is required
clusterName: "geeiq-prod-k8s"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<redacted>:role/AWSLoadBalancerControllerIAMRole
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "aws-load-balancer-controller"
  # Automount API credentials for a Service Account.
  automountServiceAccountToken: true

rbac:
  # Specifies whether rbac resources should be created
  create: true

podSecurityContext:
  fsGroup: 65534

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  allowPrivilegeEscalation: false

# Time period for the controller pod to do a graceful shutdown
terminationGracePeriodSeconds: 10

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# priorityClassName specifies the PriorityClass to indicate the importance of controller pods
# ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass
priorityClassName: system-cluster-critical

nodeSelector:
  geeiq/node-type: worker

tolerations: []

affinity: {}

podAnnotations: {}

podLabels: {}

# Enable cert-manager
enableCertManager: false

# The ingress class this controller will satisfy. If not specified, controller will match all
# ingresses without ingress class annotation and ingresses of type alb
ingressClass: alb

# The AWS region for the kubernetes cluster. Set to use KIAM or kube2iam for example.
region:

# The VPC ID for the Kubernetes cluster. Set this manually when your pods are unable to use the metadata service to determine this automatically
vpcId:

# Maximum retries for AWS APIs (default 10)
awsMaxRetries:

# If enabled, targetHealth readiness gate will get injected to the pod spec for the matching endpoint pods (default true)
enablePodReadinessGateInject:

# Enable Shield addon for ALB (default true)
enableShield:

# Enable WAF addon for ALB (default true)
enableWaf:

# Enable WAF V2 addon for ALB (default true)
enableWafv2:

# Maximum number of concurrently running reconcile loops for ingress (default 3)
ingressMaxConcurrentReconciles:

# Set the controller log level - info(default), debug (default "info")
logLevel:

# The address the metric endpoint binds to. (default ":8080")
metricsBindAddr: ""

# The TCP port the Webhook server binds to. (default 9443)
webhookBindPort:

# Maximum number of concurrently running reconcile loops for service (default 3)
serviceMaxConcurrentReconciles:

# Maximum number of concurrently running reconcile loops for targetGroupBinding
targetgroupbindingMaxConcurrentReconciles:

# Period at which the controller forces the repopulation of its local object stores. (default 1h0m0s)
syncPeriod:

# Namespace the controller watches for updates to Kubernetes objects, If empty, all namespaces are watched.
watchNamespace:

# Liveness probe configuration for the controller
livenessProbe:
  failureThreshold: 2
  httpGet:
    path: /healthz
    port: 61779
    scheme: HTTP
  initialDelaySeconds: 30
  timeoutSeconds: 10

# Environment variables to set for aws-load-balancer-controller pod.
# We strongly discourage programming access credentials in the controller environment. You should setup IRSA or
# comparable solutions like kube2iam, kiam etc instead.
env:
  # ENV_1: ""
  # ENV_2: ""

# Specifies if aws-load-balancer-controller should be started in hostNetwork mode.
#
# This is required if using a custom CNI where the managed control plane nodes are unable to initiate
# network connections to the pods, for example using Calico CNI plugin on EKS. This is not required or
# recommended if using the Amazon VPC CNI plugin.
hostNetwork: false

# extraVolumeMounts are the additional volume mounts. This enables setting up IRSA on non-EKS Kubernetes cluster
extraVolumeMounts:
  # - name: aws-iam-token
  #   mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
  #   readOnly: true

# extraVolumes for the extraVolumeMounts. Useful to mount a projected service account token for example.
extraVolumes:
  # - name: aws-iam-token
  #   projected:
  #     defaultMode: 420
  #     sources:
  #     - serviceAccountToken:
  #         audience: sts.amazonaws.com
  #         expirationSeconds: 86400
  #         path: token

# defaultTags are the tags to apply to all AWS resources managed by this controller
defaultTags: {}
  # default_tag1: value1
  # default_tag2: value2

# podDisruptionBudget specifies the disruption budget for the controller pods.
# Disruption budget will be configured only when the replicaCount is greater than 1
podDisruptionBudget: {}
#  maxUnavailable: 1
```
