### ISSUE TITLE
Annotations not working

### ISSUE THREAD

**Issue by EKami** [kubernetes-sigs/aws-load-balancer-controller#2037]
I'm trying to automatically start an ALB in my EKS cluster by using the [aws-load-balancer-controller](https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller)

This is what the logs of my deployment look like:
```
$ kubectl logs -n kube-system deployment.apps/aws-load-balancer-controller
{"level":"info","ts":1622297350.5886948,"msg":"version","GitVersion":"v2.2.0","GitCommit":"68c417a7ea37ff153f053d9ffef1cc5c70d7e211","BuildDate":"2021-05-14T21:49:05+0000"}
{"level":"info","ts":1622297353.7576282,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1622297353.7667196,"logger":"setup","msg":"adding health check for controller"}
{"level":"info","ts":1622297353.766923,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-v1-pod"}
{"level":"info","ts":1622297353.7670138,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
{"level":"info","ts":1622297353.7670481,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
{"level":"info","ts":1622297353.7670848,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-networking-v1beta1-ingress"}
{"level":"info","ts":1622297353.7672708,"logger":"setup","msg":"starting podInfo repo"}
I0529 14:09:15.767379       1 leaderelection.go:242] attempting to acquire leader lease  kube-system/aws-load-balancer-controller-leader...
{"level":"info","ts":1622297355.767861,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1622297355.8680398,"logger":"controller-runtime.webhook.webhooks","msg":"starting webhook server"}
{"level":"info","ts":1622297355.868631,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":1622297355.8688757,"logger":"controller-runtime.webhook","msg":"serving webhook server","host":"","port":9443}
{"level":"info","ts":1622297355.8690248,"logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
```

And the annotations in my kustomize ingress config (I'm patching the [Kubeflow 1.3](https://www.kubeflow.org/) config):
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: istio-ingress
  namespace: istio-system
  annotations:
    # create AWS Application LoadBalancer
    kubernetes.io/ingress.class: alb
    # external type
    alb.ingress.kubernetes.io/scheme: internet-facing
    # AWS Certificate Manager certificate's ARN
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-2:1111111:certificate/xxx-xxx-xxx"
    # open ports 80 and 443 
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    # ExternalDNS settings: https://rtfm.co.ua/en/kubernetes-update-aws-route53-dns-from-an-ingress/
    external-dns.alpha.kubernetes.io/hostname: kubeflow.my-domain.com
    # redirect all HTTP to HTTPS
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'

```

But so far nothing happens, no alb is being created.

```
$ kubectl get services -n istio-system
NAME                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                      AGE
authservice             ClusterIP   172.20.17.19     <none>        8080/TCP                                                                     39m
cluster-local-gateway   ClusterIP   172.20.0.189     <none>        15020/TCP,80/TCP                                                             39m
istio-ingressgateway    NodePort    172.20.81.219    <none>        15021:31033/TCP,80:31875/TCP,443:31517/TCP,31400:32737/TCP,15443:32018/TCP   39m
istiod                  ClusterIP   172.20.186.197   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP                                        39m
```

(The NodePort is supposed to be replaced by an ALB here I believe).
I'm out of idea on how to debug this. Any help would be greatly appreciated, Thank you.
