### ISSUE TITLE
alb.ingress.kubernetes.io/ssl-redirect ingress annotation broken

### ISSUE THREAD

**Issue by dallasmarlow** [kubernetes-sigs/aws-load-balancer-controller#2052]
According to the following documentation, setting the `alb.ingress.kubernetes.io/ssl-redirect` ingress annotation is supposed to configure a default listener action to redirect to the configured port. In my testing I have not seen any situation where setting this annotation has any effect.

https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#ssl-redirect

Example manifest:
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: test
  name: test
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:xxx
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: test
              servicePort: 80
```

Given that there are examples for setting a custom action for SSL redirection in the documentation, maybe it makes sense to remove this annotation from the documentation and service code.
