### ISSUE TITLE
The spec for Ingress resource is incorrect

### ISSUE THREAD

**Issue by tlliddle** [kubernetes-sigs/aws-load-balancer-controller#2066]
The manifest for `apiVersion: networking.k8s.io/v1` has the incorrect specs.
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/3a6ba6a7c16e5fe9f63949381b24cebadd7e8c9f/docs/examples/2048/2048_full.yaml#L52-L59

The spec should conform to the spec referenced here:
https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
```yaml
spec:
  rules:
    - http:
        paths:
        - path: /*
          pathType: Prefix
          backend:
             service:
               name:  service-2048
               port:
                 number: 80
```
