### ISSUE TITLE
IP whitelisting SHARED aws-load-balancer-controller

### ISSUE THREAD

**Issue by cloudlady911** [kubernetes-sigs/aws-load-balancer-controller#2076]
There was a question similar to this before.  But in my case I am using a SHARED ALB.
I have a question related to this. I am using a shared ALB. I have many apps using the same alb. I would like to be able to whitelist certain CIDR's to certain apps. 

I know about this annotation: `alb.ingress.kubernetes.io/inbound-cidrs`

How can I use this setting for a shared ALB? For instance, AppA should be accessible from 123.345.23.45/24 and AppB should be accessible from 456.567.89.76/24.  But I don't want 123.345.23.45/24 to access AppB.  And all apps should be accessible from my company's ip address, 987.98.98.98/32.

Below is an example of a current Ingress for one of my apps.  I added the line for the cidr.  But if this is set at the ALB listener level, wont the next app I launch over write it?

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress-pub
  namespace: snapdrop-service
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: public
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:725680032710:certificate/d947a8e3-06d9-4786-8994-92be48202c24
    alb.ingress.kubernetes.io/success-codes: 200,303,301
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '60'
    alb.ingress.kubernetes.io/healthcheck-path: /
    **alb.ingress.kubernetes.io/inbound-cidrs: 456.567.89.76/24, 987.98.98.98/32**

spec:
  rules:
  - host: example.vetpro.us
    http:
      paths:
      - path: /*
        backend:
          serviceName: example
          servicePort: 80
```
