### ISSUE TITLE
Path / with Kind Prefix does not work

### ISSUE THREAD

**Issue by Mattie112** [kubernetes-sigs/aws-load-balancer-controller#2081]
When looking at the spec of the ingress (https://kubernetes.io/docs/concepts/services-networking/ingress/#examples) I see the following:

Kind: Prefix
Path: /
Matches: ' all paths' 

I have something like:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sites-xx-xx-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: xxx-io
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ip-address-type: dualstack
    alb.ingress.kubernetes.io/load-balancer-name: xxx-io
    alb.ingress.kubernetes.io/success-codes: 200-499
    alb.ingress.kubernetes.io/ssl-redirect: '443'

    external-dns.alpha.kubernetes.io/hostname: xx.xx.io
spec:
  rules:
    - host: xx.xx.io
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: sites-xx-xx
                port:
                  number: 80
```
The resulting rule in the loadbalancer is:
![image](https://user-images.githubusercontent.com/662896/122369059-2932c280-cf5e-11eb-893f-7b229577ec4c.png)

The following url works `xx.xx.io` but `xx.xx.io/js/somefile.js` does not. Because the spec lists that 'all patch' should match I am confused why this doesn't work.

Changing it to `/*` does work but I cannot find anything on https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/ explaining why does should/shouldn't work.

Is this a bug? Or some missing documentation?
