### ISSUE TITLE
Support for URL rewite annotation

### ISSUE THREAD

**Issue by igoratencompass** [kubernetes-sigs/aws-load-balancer-controller#2082]
Please provide support for `ingress.kubernetes.io/rewrite-target` annotation as provided by all other ingress controllers. Example usage stripping leading part of the URL before sending upstream:

```
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: name
  annotations:
    [...]
    ingress.kubernetes.io/rewrite-target: /$1
  rules:
  - host: my.domain.tld
    http:
      paths:
      - backend:
          serviceName: svc1
          servicePort: 80
        path: /svc1/(.*)
```
I found similar issue from like two and a half years ago https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/835 that was just closed without any action.
