### ISSUE TITLE
Unable to use cert-manager generated TLS certificate for ALB TLS Termination

### ISSUE THREAD

**Issue by MuriukiPM** [kubernetes-sigs/aws-load-balancer-controller#2107]
**Ingress resource not able to use TLS certificate**
We have AWS Load Balancer Controller installed for a test EKS set up and paired with cert-manager for ingress TLS management. We are able to generate valid TLS certificates, but attaching them to the ingress resource does not work as expected. From the documentation [here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/ingress/cert_discovery/#discover-via-ingress-tls) certificate discovery can be done via Ingress TLS, just not sure if this allows for attaching certificates as k8s secrets for discovery. Please let me know if there is something done wrong.

**Steps to reproduce**
We followed these [steps](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/deploy/installation.md)  to install the controller and exposed an nginx service. Once HTTP connections worked, we installed cert-manager using these [steps](https://cert-manager.io/docs/installation/kubernetes/) and generated ACME certificates using these [steps](https://cert-manager.io/docs/tutorials/acme/http-validation/). 
This is the updated ingress resource description with some sensitive fields replaced:
```yaml
Name:             test-ingress
Namespace:        development
Address:          <alb address id>.eu-west-1.elb.amazonaws.com
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
  test-tls terminates example.com
Rules:
  Host        Path  Backends
  ----        ----  --------
  *           
              /*   test-nginx:8080 (10.0.102.41:8080)
Annotations:  alb.ingress.kubernetes.io/listen-ports: [{"HTTP": 80}, {"HTTPS":443}]
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: ip
              ingress.annotations.certmanager.k8s.io/cluster-issuer: letsencrypt-prod
              kubernetes.io/ingress.class: alb
Events:
  Type     Reason            Age                    From     Message
  ----     ------            ----                   ----     -------
  Warning  FailedBuildModel  14m (x317 over 3d10h)  ingress  Failed build model due to ingress: development/test-ingress: none certificate found for host: example.com
```
The domain used is being replaced here with `example.com` for illustration purposes. We created a CNAME record for pointing to the ALB address and used that for certificate creation.

**Expected outcome**
As can be seen, the TLS certificate is attached but ingress fails to build for HTTPS. 

**Environment**

* AWS Load Balancer controller version: 2.2.0
* Kubernetes version: 1.20.4
* Using EKS (yes), if so version: eks.1

**Additional Context**:
