### ISSUE TITLE
Unable to create non-OIDC listener rule condition when IDP configured

### ISSUE THREAD

**Issue by rossigee** [kubernetes-sigs/aws-load-balancer-controller#2109]
**Describe the bug**

We have an ALB with IDP enabled.

```
        alb.ingress.kubernetes.io/auth-type: oidc
        alb.ingress.kubernetes.io/auth-idp-oidc: '{"issuer":"https://accounts.google.com","authorizationEndpoint":"https://accounts.google.com/o/oauth2/auth","tokenEndpoint":"https://oauth2.googleapis.com/token","userInfoEndpoint":"https://openidconnect.googleapis.com/v1/userinfo","secretName":"netbox-oidc"}'
        alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
        alb.ingress.kubernetes.io/auth-scope: 'openid profile email'
        alb.ingress.kubernetes.io/auth-session-cookie: netbox-oidc-session
        alb.ingress.kubernetes.io/auth-session-timeout: '86400'
```

This works fine. However, the application also serves as a REST API endpoint, and the REST clients are not OIDC-capable. So, we need an extra listener condition rule (before the OIDC one) that allows requests through if the 'Authorization' header is set.

I can add annotations to the Ingress which creates the listener:

```
        alb.ingress.kubernetes.io/actions.api-auth: '{
                    "Type": "forward",
                    "Order": 1,
                    "ForwardConfig": {
                        "TargetGroups": [
                            {
                                "ServiceName": "netbox",
                                "ServicePort": "80",
                                "Weight": 1
                            }
                        ],
                        "TargetGroupStickinessConfig": {
                            "Enabled": false
                        }
                    }
                }'
        alb.ingress.kubernetes.io/conditions.api-auth: '[
                {
                    "Field": "http-header",
                    "HttpHeaderConfig": {
                        "HttpHeaderName": "Authorization",
                        "Values": [
                            "*"
                        ]
                  }
                }
            ]'
```

However, it results in a listener rule that *also* includes the OIDC conditions 👎 

![Screen Shot 2564-06-29 at 10 13 11](https://user-images.githubusercontent.com/5194485/123731613-acd7a200-d8c2-11eb-930b-5d8d093b4559.png)

As a workaround I have to go into the management console and edit the first rule manually to remove the OIDC condition. Then, our REST clients work as expected.

So, the desired outcome is possible, but it doesn't seem to be achievable using annotations only, without the manual step?!

**Steps to reproduce**

Create an Ingress with IDP annotations. Add a 'conditions' and 'actions' annotations as above.

**Expected outcome**

The 'api-auth' condition should be created on the ALB as specified, without erroneously merging the OIDC conditions.

**Environment**

* AWS Load Balancer controller version: 2.2.0
* Kubernetes version: 1.18
* Using EKS (yes/no), if so version? yes, 1.18

**Additional Context**:

**Comment by M00nF1sh** [comment]
@rossigee 
Currently we don't offer a way to enable/disable auth per rule basis. you can only enable/disable auth per entire Ingress or per Service. In your case, since you applied the auth rule on the Service, it will be merged even you used actions/conditions annotations.

The current way to achieve it is to leverage the [IngressGroup](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#group.name) feature, where you can create two Ingress(one with auth while another one don't) and group them on a single ALB.

**Comment by rossigee** [comment]
@M00nF1sh - Thank you very much for the explanation.

Based on your suggestion I was able to get it to work by using two Ingress resources.

Here's a cut-down version in case it helps anyone else in a similar situation...

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.api-auth: '{ "Type": "forward", "ForwardConfig": {"TargetGroups": [{"ServiceName":"netbox","ServicePort":"http","Weight":1}]}}'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/conditions.api-auth: '[ { "Field": "http-header", "HttpHeaderConfig": { "HttpHeaderName": "Authorization", "Values": [ "*" ] } } ]'
    alb.ingress.kubernetes.io/group.name: netbox
    alb.ingress.kubernetes.io/group.order: "1"
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/inbound-cidrs: ...
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-2019-08
    alb.ingress.kubernetes.io/target-group-attributes: load_balancing.algorithm.type=least_outstanding_requests
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  name: netbox-apiauth
  namespace: netbox
spec:
  rules:
  - host: netbox.yourdomain.com
    http:
      paths:
      - backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
        path: /*
        pathType: ImplementationSpecific
      - backend:
          serviceName: api-auth
          servicePort: use-annotation
        path: /*
        pathType: ImplementationSpecific

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/auth-idp-oidc: '{"issuer":"https://accounts.google.com","authorizationEndpoint":"https://accounts.google.com/o/oauth2/auth","tokenEndpoint":"https://oauth2.googleapis.com/token","userInfoEndpoint":"https://openidconnect.googleapis.com/v1/userinfo","secretName":"netbox-oidc"}'
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-scope: openid profile email
    alb.ingress.kubernetes.io/auth-session-cookie: netbox-oidc-session
    alb.ingress.kubernetes.io/auth-session-timeout: "86400"
    alb.ingress.kubernetes.io/auth-type: oidc
    alb.ingress.kubernetes.io/group.name: netbox
    alb.ingress.kubernetes.io/group.order: "2"
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/inbound-cidrs: ...
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-2019-08
    alb.ingress.kubernetes.io/target-group-attributes: load_balancing.algorithm.type=least_outstanding_requests
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  name: netbox-oidc
  namespace: netbox
spec:
  rules:
  - host: netbox.yourdomain.com
    http:
      paths:
      - backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
        path: /*
        pathType: ImplementationSpecific
      - backend:
          serviceName: netbox
          servicePort: http
        path: /*
        pathType: ImplementationSpecific
```
