### ISSUE TITLE
Path patterns & rewrite

### ISSUE THREAD

**Issue by ashokspeelyaal** [kubernetes-sigs/aws-load-balancer-controller#2128]
**Describe the bug**
when we use `/*` for our vue web app, the subpaths are showing `404`. However the root path is working fine. 

**Steps to reproduce**

We have this ingress in place: 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  namespace: dev-env
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: myhostname.com
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: ---our certificate arn---

spec:

  rules:
    - http:
        paths:
          - backend:
              service:
                name: my-web-app
                port:
                  number: 30001
            path: /*
            pathType: Prefix
```

**Expected outcome**
when I access https://myhostname.com/login or https://myhostname.com/clients 
It should redirect me to specific page. (but now it shows 404. However, if I access https://myhostname.com there is no problem) 

**Environment**

* AWS Load Balancer controller version
v1.1.9

* Kubernetes version

* Using EKS (yes/no), if so version?

Yes, EKS.   v1.19.6-eks-49a6c0

**Additional Context**:

It is a single page app (vue). When we access subpaths from the nav bars of the application, there is no issue. The issue comes only when we try to directly access the sub-path, or refresh a non-root page. 
I assume the rewrite is not possible with ALB ingress like we do in nginx-controller.  In this case, what could be the solution?
