### ISSUE TITLE
503 response from AWS

### ISSUE THREAD

**Issue by hinewwiner** [kubernetes-sigs/aws-load-balancer-controller#2132]
I followed the 'EchoServer' example in https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/examples/echo_server/

When I try to access the service, I get 503 error from AWS.  I see that no target is registered in the alb.  I am not sure what I missed.

This is the ingress controller.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver
  namespace: echoserver
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
spec:
  rules:
    - host: v2.domain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: echoserver
              servicePort: 80
```
 
And I verified that the subnets have 'kubernetes.io/role/internal-elb'=1 for private subnets and ' kubernetes.io/role/elb'=1 for public subnets.

EKS cluster is created using eksctl with version 1.20 and fargate.

I am running aws-load-balancer-controller version v2.2.1.
