### ISSUE TITLE
alb.ingress.kubernetes.io/target-type=instance :: Not registering target group

### ISSUE THREAD

**Issue by hinewwiner** [kubernetes-sigs/aws-load-balancer-controller#2133]
**Describe the bug**
When 'alb.ingress.kubernetes.io/target-type: instance' is set, no target group is registered in AWS.

**Steps to reproduce**
Followed the example 'echoserver' in https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/examples/echo_server/

When the following ingress is applied, no target group is registered.  I verified type=ip works correctly but not 'instance'.  I also verified that the 'Service' is type of 'NodePort'.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver
  namespace: echoserver
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
spec:
  rules:
    - host: v2.domain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: echoserver
              servicePort: 80
```

**Expected outcome**
A concise description of what you expected to happen.
Target group is registered in AWS.

**Environment**

* AWS Load Balancer controller version : v2.2.1
* Kubernetes version : v1.20
* Using EKS (yes/no), if so version? : yes
* Also used fargate to create nodes

**Additional Context**:
