### ISSUE TITLE
Unable to find ACM through auto discovery and receiving ValidationError when passing in ARN

### ISSUE THREAD

**Issue by davidvuong** [kubernetes-sigs/aws-load-balancer-controller#2134]
**Environment**

* AWS Load Balancer controller version: 2.2.1
* Kubernetes version 1.20
* Using EKS (yes/no), if so version? Yes. eks.1 (?)

**Additional Context**:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: '/.well-known/apollo/server-health'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.certificateArn }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    external-dns.alpha.kubernetes.io/hostname: api.example.com
spec:
  tls:
  - hosts:
    - dev.example.com
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: {{ .Values.name }}
          servicePort: {{ .Values.port }}
```

Passing the ARN directly gives:

```
ValidationError: Certificate ARN 'xxx' is not valid
    status code: 400, request id: yyy
```

Omitting `alb.ingress.kubernetes.io/certificate-arn` gives:

```
ingress: xxx: none certificate found for host: dev.example.com
```

ACM is in a different region if that makes a difference: `us-east-1` (ACM) `ap-southeast-2` (EKS). Any help would be appreciated.
