### ISSUE TITLE
alb groups not managed as expected (alb rules not deleted, security group already exists exception)

### ISSUE THREAD

**Issue by jkornblum** [kubernetes-sigs/aws-load-balancer-controller#2138]
**Describe the bug**
My use case is managing access to development environments for git branches. 
Each branch environment is deployed in its own namespace.
I am looking for a way to manage access to all these environments with ingress and ingress controller. 

I think this project can help but I might be approaching my problem fundamentally incorrectly because I seem to be running into a lot of issues
- Cannot create new (2+) ingresses because of security group conflicts
- Cannot delete ingresses because of finalizer on ingress 2+
- ALB rules not updated when ingress deleted

ingress1
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver
  namespace: echoserver
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/inbound-cidrs: 10.0.0.0/8, 146.61.0.0/16, 172.16.0.0/12
    alb.ingress.kubernetes.io/group.name: development-alb
    external-dns.alpha.kubernetes.io/hostname: "echoserver.eap-np.net"
spec:
  rules:
    - host: echoserver.eap-np.tceh.net
      http:
        paths:
          - path: /
            backend:
              serviceName: echoserver
              servicePort: 80
```

ingress2
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver2
  namespace: echoserver2
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: development-alb
    external-dns.alpha.kubernetes.io/hostname: "echoserver2.eap-np.net"
spec:
  rules:
    - host: echoserver2.eap-np.tceh.net
      http:
        paths:
          - path: /
            backend:
              serviceName: echoserver2
              servicePort: 80
```

The security group works for the first ingress created but all subsequent creations give me `The security group 'k8s-developmentalb-5c8268b161' already exists for VPC` error. I know I can use my own sg but then I have to manage the inbound rules on nodes, I think this library handles that for us with managed sg so I prefer to use managed sg. I this note in the documentation `if same listen-port is defined by multiple Ingress within IngressGroup, inbound-cidrs should only be defined on one of the Ingress.` however if I leave of security group and inbound cidrs annotation I get th same duplicate sg error.

If I want to delete an ingress (when I have more than one) I cannot because finalizer is placed on ingress. I do not want
to delete the ALB just the ingress (because other ingresses reference the same alb). The only method I found is to manually patch the ingress and remove the finalizer.

After a patch and delete the ALB routing rules are not deleted. For instance one ingress is for host `echoserver.com` and another for `echoserver2.com` and if I delete ingress for `echoserver2` than I still see the rule on the AWS ALB, its not being deleted by deleting the ingress definition. I see it also leaves the associated target group but deleted all the targets in the group.

**Environment**

* AWS Load Balancer controller version: `2.1.3`
* Kubernetes version: `1.17.x`
* Using EKS (yes/no), if so version? yes
