### ISSUE TITLE
defaultTags not parsing correctly - aws-load-balancer-controller

### ISSUE THREAD

**Issue by LevonBecker** [kubernetes-sigs/aws-load-balancer-controller#2143]
## Describe the bug
I've tried normous ways to feed the set value defaultTags with Terraform helm_release and Helm CLI. I'm not a Go expert so can't pinpoint exactly what's wrong, but it seems to be something to do with the aws-load-balancer-controller.convert-map-to-csv method.

#### Helm Template Debug
```bash
helm template --debug eks-charts/aws-load-balancer-controller -n kube-system --set clusterName=MyEksCluster --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller --set installCRDs=true --set replicaCount=1 --set defaultTags="{\"StackName\":\"MyStack\",\"Terraform_Workspace\":\"MyWorkspace\"}"
```

## Generated Yaml Section
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-aws-load-balancer-controller
  namespace: kube-system
  labels:
    helm.sh/chart: aws-load-balancer-controller-1.2.3
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v2.2.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-load-balancer-controller
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aws-load-balancer-controller
        app.kubernetes.io/instance: RELEASE-NAME
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: aws-load-balancer-controller
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: aws-load-balancer-tls
      securityContext:
        fsGroup: 65534
      containers:
      - name: aws-load-balancer-controller
        args:
        - --cluster-name=MyEksCluster
        - --ingress-class=alb
        - --default-tags=0="StackName":"MyStack",1="Terraform_Workspace":"MyWorkspace"
```
It should be taking the map (in this case a json map) and iterating a key value. What it does and set a key of 0 and the value to the key:value. As you can see above 0="StackName":"MyStack"

So when it sets the tags on an AWS object such as an ALB. You get:

| Key | Value |
| :--- | :--- |
| ingress.k8s.aws/stack       | *** |
| ingress.k8s.aws/resource       | LoadBalancer|
| elbv2.k8s.aws/cluster      | ***|
| 0        | StackName:MyStack |
| 1        | Terraform_Workspace:MyWorkspace |

## Expected outcome
First off it would be amazing if there was an example somewhere in the documentation instead of just **{}** as the description.

or this in values.yml doesn't help much either... like what is a one-liner supposed to look like. What format are you expecting? It seems to like JSON, Not much else from my stabs at it.
```yaml
# defaultTags are the tags to apply to all AWS resources managed by this controller
defaultTags: {}
  # default_tag1: value1
  # default_tag2: value2
```

It should be something like:

```
--default-tags="StackName"="MyStack","Terraform_Workspace"="MyWorkspace"
```

| Key | Value |
| :--- | :--- |
| ingress.k8s.aws/stack       | *** |
| ingress.k8s.aws/resource       | LoadBalancer|
| elbv2.k8s.aws/cluster      | ***|
| StackName        | MyStack |
| Terraform_Workspace        | MyWorkspace |

## Environment
* Helm: v3.6.3
* Terraform Helm Provider: 2.2
* helm.sh/chart: aws-load-balancer-controller-1.2.3
* AWS Load Balancer controller version: v2.2.1
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version? 1.21/eks.1

## Additional Context
I think this is where the issue is in 
#### templates/deployment.yaml
```golang
{{- if .Values.defaultTags }}
- --default-tags={{ include "aws-load-balancer-controller.convert-map-to-csv" .Values.defaultTags | trimSuffix "," }}
{{- end }}
```
#### _helpers.tpl
```golang
{{- define "aws-load-balancer-controller.convert-map-to-csv" -}}
{{- range $key, $value := . -}} {{ $key }}={{ $value }}, {{- end -}}
{{- end -}}
```

Looking on golang docs for map they state:
If the requested key doesn't exist, we get the value type's zero value. In this case the value type is int, so the zero value is 0:

So I'm guessing it's not getting the key right and setting it incrementally to an int starting at 0.

Seems like something wrong in the range iteration and string generation syntax.

**Comment by kishorj** [comment]
@LevonBecker, there are two ways to specify the default tags 
- edit the helm values.yaml file and specify the defaultTags map, for example
```
# defaultTags are the tags to apply to all AWS resources managed by this controller
defaultTags:
  k1: v1
  k2: v2
```
- Specify the default tags from the helm install/upgrade command, for example
```
--set defaultTags.k1=v1,defaultTags.k2="v2"
```

**Comment by LevonBecker** [comment]
Awesome thanks for the help! Although, I still can't get it to work with terraform/helm_release. I've tried all kinds of combos syntax wise and it just insists on parsing incorrectly.

## CLI Example (works!)
```bash
helm template --debug eks-charts/aws-load-balancer-controller -n kube-system --set clusterName=gs-p1-use2 --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller --set installCRDs=true --set replicaCount=1 --set defaultTags.StackName=\"MyStack\",defaultTags.Terraform_Workspace=\"MyWorkspace\"
```

## Terraform / helm_release (fails)
```hcl
resource "helm_release" "aws_load_balancer_controller" {
  chart                         = "aws-load-balancer-controller"
  create_namespace              = false
  depends_on                    = [aws_iam_role.service_account, module.k8s_service_account]
  name                          = "aws-load-balancer-controller"
  namespace                     = "kube-system"
  repository                    = "https://aws.github.io/eks-charts"
  version                       = var.parameters.chart_version
  cleanup_on_fail               = true

  set {
    name  = "clusterName"
    value = var.eks_cluster.name
  }

  set {
    name  = "installCRDs"
    value = true
  }

  set {
    name  = "replicaCount"
    value = var.parameters.replicas
  }

  set {
    name  = "serviceAccount.create"
    value = false
  }

  set {
    name  = "serviceAccount.name"
    value = "aws-load-balancer-controller"
  }

  set {
    name = "defaultTags"
    value = jsonencode({
      StackName           = "MyStack"
      Terraform_Workspace = terraform.workspace
    })
  }
}
```

Generated yaml section example:
Note it sets key of 0 and the key:value as value.
```yaml
containers:
      - name: aws-load-balancer-controller
        args:
        - --cluster-name=MyEksCluster
        - --ingress-class=alb
        - --default-tags=0="StackName":"MyStack",1="Terraform_Workspace":"MyWorkspace"
```
