### ISSUE TITLE
Need to have a single ingress with both OIDC-Auth protected paths and open paths

### ISSUE THREAD

**Issue by LynnOwens** [kubernetes-sigs/aws-load-balancer-controller#2151]
I'm able to create an ingress with the OIDC auth annotations so that it's paths are protected, and I'm able to create an ingress that is unprotected.  But, I need both for a single hostname and therefore a single ingress (because one ingress creates one route53 record).  

```
Example:  (the OIDC auth annotations should apply only to the protected service)
    - host: www.example.com
      http:
        paths:
          - path: /protected
            backend:
              serviceName: protected
              servicePort: 8080
          - path: /public
            backend:
              serviceName: public
              servicePort: 8080
```

Is this possible with conditions?  I don't see any examples of how to do this.
