### ISSUE TITLE
Target-Type IP Scenario - NLB Performs HealtChecks on Node IPs (rather than Pod IP)

### ISSUE THREAD

**Issue by dumlutimuralp** [kubernetes-sigs/aws-load-balancer-controller#2165]
I am using the below manifest for NLB. Once I deploy this, I can see that the AWS NLB still performs the health checks against the Node IP/Ports. Why is this the case ? 

```
apiVersion: v1
kind: Service
metadata:
  name: testwpservice
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: testwp
```

**Steps to reproduce**

**Expected outcome**

When the load balancer type is ALB and the annotation target-type ip is used hen the health checks are  performed against the Pod IP (as expected).  Why is this behaviour different with NLB ? 

**Environment**

* AWS Load Balancer controller version 2.2.0
* Kubernetes version 1.20.0 
* Using EKS (yes/no), if so version? Yes, eks.2
