### ISSUE TITLE
Feature Request: Specify Managed Prefix Lists for access control

### ISSUE THREAD

**Issue by patrickpierson** [kubernetes-sigs/aws-load-balancer-controller#2167]
**Is your feature request related to a problem?**
AWS provides a method to create a list of IPs in a Managed Prefix List. This Managed Prefix List allows a user to specify a list of IPs that can be shared between accounts. It also allows for IP lists to be managed by another team as a list of pre-approved list. A Managed Prefix List looks like:

`pl-123456abcde123456`

**Describe the solution you'd like**

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: testing
  name: testing
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: testing
  type: LoadBalancer
  loadBalancerSourceRanges:
  - "pl-123456abcde123456"
```

**Describe alternatives you've considered**
Have not considered any alternatives but I am open to ideas.
