### ISSUE TITLE
Documentation actions and conditions example update

### ISSUE THREAD

**Issue by tomiszili** [kubernetes-sigs/aws-load-balancer-controller#2182]
Hia all!

Please update the documentation examples in the section of actions and the conditions.
I want to define a default HTTP 403 response for those loadbalancer rule paths which are not defined.

**Environment**

* AWS Load Balancer controller version: v2.2.1
* Kubernetes version: 1.19
* Using EKS (yes/no), if so version? EKS 1.19

**Comment by ameeet** [comment]
Hello, I would like to help.

**Comment by mason-liu** [comment]
> Hello, I would like to help.

Thanks @ameeet, are you going to upgrade the sample apiVersion to networking.k8s.io/v1 at the same time?

**Comment by tomiszili** [comment]
Hello,
Any updates on this?

I want to use this configuration in eks 1.19 or later.

in 1.18 i use the following:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: <hidden_cert_arn>
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/actions.response-403: >
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"403","messageBody":"Forbidden"}}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/success-codes: 200
  labels:
    run: test-ingress-hu
  name: test-ingress-hu
  namespace: default
spec:
  backend:
    serviceName: response-403
    servicePort: use-annotation
  rules:
    - http:
        paths:
        - backend:
            serviceName: ssl-redirect
            servicePort: use-annotation
          path: /*
    - host: admin-demo.test.example.hu
      http:
        paths:
        - backend:
            serviceName: admin
            servicePort: 80
          path: /*
```

**Comment by gangstead** [comment]
> Hello, Any updates on this?
> 
> I want to use this configuration in eks 1.19 or later.
> 
> in 1.18 i use the following:
> 
> ```
> apiVersion: extensions/v1beta1
> kind: Ingress
> metadata:
>   annotations:
>     kubernetes.io/ingress.class: alb
>     alb.ingress.kubernetes.io/certificate-arn: <hidden_cert_arn>
>     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
>     alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
>     alb.ingress.kubernetes.io/actions.response-403: >
>       {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"403","messageBody":"Forbidden"}}
>     alb.ingress.kubernetes.io/scheme: internet-facing
>     alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
>     alb.ingress.kubernetes.io/success-codes: 200
>   labels:
>     run: test-ingress-hu
>   name: test-ingress-hu
>   namespace: default
> spec:
>   backend:
>     serviceName: response-403
>     servicePort: use-annotation
>   rules:
>     - http:
>         paths:
>         - backend:
>             serviceName: ssl-redirect
>             servicePort: use-annotation
>           path: /*
>     - host: admin-demo.test.example.hu
>       http:
>         paths:
>         - backend:
>             serviceName: admin
>             servicePort: 80
>           path: /*
> ```
> 
> How the above snippet would look like in kubernetes 1.19 or above?

Here's how I got it to work (from reading the networking.k8s.io/v1 Ingress spec)
 ```
 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   annotations:
     kubernetes.io/ingress.class: alb
     alb.ingress.kubernetes.io/certificate-arn: <hidden_cert_arn>
     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
     alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
     alb.ingress.kubernetes.io/actions.response-403: >
       {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"403","messageBody":"Forbidden"}}
     alb.ingress.kubernetes.io/scheme: internet-facing
     alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
     alb.ingress.kubernetes.io/success-codes: 200
   labels:
     run: test-ingress-hu
   name: test-ingress-hu
   namespace: default
 spec:
   backend:
     service:
       name: response-403
       port:
         name: use-annotation
   rules:
     - http:
         paths:
         - backend:
             service:
               name: ssl-redirect
               port:
                 name: use-annotation
           path: /*
     - host: admin-demo.test.example.hu
       http:
         paths:
         - backend:
             service:
               name: admin
               port:
                  number: 80
           path: /*
```

**Comment by tomiszili** [comment]
I successfully created what i want with the new synthax.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: <hidden_cert>
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/actions.response-403: >
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"403","messageBody":"Forbidden"}}
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=false
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10
    alb.ingress.kubernetes.io/success-codes: 200
  labels:
    run: test-ingress-hu
  name: test-ingress-hu
  namespace: default
spec:
  defaultBackend:
    service:
      name: response-403
      port:
        name: use-annotation
  rules:
  - http:
      paths:
      - backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
        path: /
        pathType: Prefix
  - host: admin-demo.test.example.hu
    http:
      paths:
      - backend:
          service:
            name: admin
            port:
              number: 80
        path: /
        pathType: Prefix
```
