### ISSUE TITLE
Service deleting get stuck

### ISSUE THREAD

**Issue by eliecer2323** [kubernetes-sigs/aws-load-balancer-controller#2200]
**Describe the bug**
I'm trying to delete a service with the `kubect delete service claims` but it never finish (I have had let it run by 12 hours) so I have to press `ctrl+c` but the service doesn't get eliminated

**Steps to reproduce**
I am using the AWS Load Balancer Controller to expose the deployment by a Network Load Balancer in AWS, so basically I ran the next config file to generate the deployment and its service, after making all my tests I was going to delete them so I tipped `kubectl delete deployment claims` and `kubectl delete service claims`, the first one finish successfully but the second one get stuck and never finishes.

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: claims
spec:
  replicas: 1
  selector:
    matchLabels:
      app: claims
  template:
    metadata:
      labels:
        app: claims
    spec:
      containers:
        - name: claims
          image: $AWS_REGISTRY_IMAGE:$CI_COMMIT_SHA
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: claims
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: NodePort
  ports:
    - name: claims
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: claims
```

**Expected outcome**
Write `kubect delete service claims` and get the service eliminated so I can write `kubectl get services` and don't see it them

**Environment**
* AWS Load Balancer controller version: v2.2.3
* Kubernetes version: 1.22.1
* Using EKS (yes/no), if so version?: eksctl v0.62.0

**Additional Context**:
I had to delete the Load Balancer manually in the AWS Console for stopping cost billing but the service is still present and stuck in kubernetes.

- OS: MacOS Big Sur version 11.5.2
- Kernel: Darwin Kernel Version 20.6.0
