### ISSUE TITLE
ingress rules gets random order / priority in load balancer listener rules

### ISSUE THREAD

**Issue by ThomasSteinbach** [kubernetes-sigs/aws-load-balancer-controller#2203]
/kind bug

**Describe the bug**

The aws-load-balancer-controller creates Load Balancer Listener Rules in the same order as K8s ingress rules are defined in the ingress object. This does NOT correctly implement the K8s ingress specification, as the ingress documentation says:

> In some cases, multiple paths within an Ingress will match a request. In those cases precedence will be given first to the longest matching path.
( https://kubernetes.io/docs/concepts/services-networking/ingress/#multiple-matches )

More worse - the order of rules within an ingress specification is not ensured, as those rules are just a YAML/JSON list with no defined order. When processing the specification, any tool could possibly "sort" the items or alter the order. This is for instance the case if you process your k8s yaml specifications with official kubernetes kustomize.

That means that the priority of load balancer listener is random. At least NOT ordered by the longest matching path.

**Steps to reproduce**

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: my-service
spec:
  rules:
  - host: my-service.hello.world
    http:
      paths:
      - backend:
          service:
            name: my-service
            port:
              name: application
        path: /
        pathType: Prefix
      - backend:
          service:
            name: my-service
            port:
              name: monitoring
        path: /actuator/
        pathType: Prefix
```

The AWS Load Balancer created will forward requests always to the `application` port. Even in the case of the request path `/actuator/` he will not forward to the `monitoring` port, as the rule with the path `/` get a higher priority in the Load Balancer Listener Rules.

**Expected outcome**

* The listener rule with the more specific path `/actuator` should get a higher priority in the Load Balancer Listener Rules.
* For the upper example requests to `my-service.hello.world/actuator` should be forwarded to the `monitoring` port.

**Environment**

* AWS Load Balancer controller version: helm chart versiono 1.2.3
