### ISSUE TITLE
Ingress with PathPrefix does not work as expected

### ISSUE THREAD

**Issue by tfn220189** [kubernetes-sigs/aws-load-balancer-controller#2207]
**Describe the bug**
When using AWS Load balancer controller with a path "/some-prefix" of type "Prefix", I would expect the Alb listener rule to be translated to the following path condition: 
```
Path is /some-prefix*
```
Instead the following is created:
```
Path is /some-prefix OR /some-prefix/*
```
which means a / is appended to the desired prefix. 

**Steps to reproduce**
Use an ingress as the example below, check the created Alb listener rule in AWS console

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
# ...
spec:
  rules:
  - host: some-host.com
    http:
      paths:
      - backend:
          serviceName: some-service
          servicePort: 80
        path: /some-prefix
        pathType: Prefix
```

**Environment**

* AWS Load Balancer controller version v2.2.4
* Kubernetes version 1.19
* Using EKS (yes/no), if so version? Yes, eks.6
