### ISSUE TITLE
ALB with backend protocol gRPC not working

### ISSUE THREAD

**Issue by L30Bola** [kubernetes-sigs/aws-load-balancer-controller#2214]
**Describe the bug**
We are trying to deploy an Ingress with backend protocol configured as gRPC. This is the Ingress definition:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/group.name: test-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
  labels:
    app: server
  name: ing
  namespace: ing-alb-test
spec:
  rules:
  - host: ing-alb-test.example.com
    http:
      paths:
      - backend:
          serviceName: svc
          servicePort: server
        pathType: ImplementationSpecific
```

But, we are facing this on the controller logs:

```
{"level":"error","ts":1630697843.0649042,"logger":"controller","msg":"Reconciler error","controller":"ingress",
"name":"test-alb","namespace":"","error":"failed to create listener rule: InvalidLoadBalancerAction: Listener
protocol 'HTTP' is not supported with a target group with the protocol-version 'GRPC'\n\tstatus code: 400,
request id: ********-****-****-****-************"}
```

Since there is that error, an ALB never gets attached to the Ingress resource.

Maybe we are missing something on our end.

**Steps to reproduce**
Add an Ingress with the above definition.

**Expected outcome**
An ALB get attached to the Ingress resource.

**Environment**
Kops-managed K8s cluster hosted on AWS.

* AWS Load Balancer controller version 2.2.4
* Kubernetes version 1.18.18
* Using EKS (yes/no), if so version? no

**Additional Context**:

**Comment by kishorj** [comment]
@L30Bola , for GRPC, you need to to configure an HTTPS listener. If you specify the certificate arn as follows, HTTPS:443 gets used as a default port instead of HTTP:80 - 
```
alb.ingress.kubernetes.io/certificate-arn: <your-cert-arns>
```

If you still encounter issues, you can share the model from the controller logs.

**Comment by L30Bola** [comment]
Hmm, I'll test and share here then. Thanks for the help :D

**Comment by L30Bola** [comment]
All working! Thanks!

**Comment by pen-pal** [comment]
Hi,

I am trying to carry out the same, however the connection fails with the following error
```Received RST_STREAM with code 2 triggered by internal client error: Protocol error```

Our dns is managed in cloudflare, with grpc support enabled.

the configuration for dns has been tested with both proxied and dns only.

while using the example provided, the grpc server works.
Also while carrying out portforward of the service after deployment, grpc connection works, however it fails for ingress.

Is there any thing to be taken care of on the alb ingress controller side.

this is the ingress.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":{
      "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:123124123123:certificate/4264-9fad-afb6d12a689a
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    meta.helm.sh/release-name: grpc
    meta.helm.sh/release-namespace: development
  finalizers:
  - ingress.k8s.aws/resources
  labels:
    app.kubernetes.io/instance: grpc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grpc
    helm.sh/chart: grpc-0.1.0
  name: grpc
  namespace: development
spec:
  ingressClassName: alb
  rules:
  - host: grpc.example.com
    http:
      paths:
      - backend:
          service:
            name: grpc
            port:
              number: 3002
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - hostname: k8s-developm--900c6e5ca4-1750334981.ap-southeast-1.elb.amazonaws.com
```
