### ISSUE TITLE
To support lambda as TargetGroup in alb controller

### ISSUE THREAD

**Issue by igrowheart** [kubernetes-sigs/aws-load-balancer-controller#2216]
**Describe the bug**
To support lambda as TargetGroup in alb controller.
If customer is already using ALB, they probably have rule based routing to lambda and different EC2 instances or EKS worker node groups.
For example, 
request against '/newCustomer' will trigger a lambda to do new customer provisioning job.
request against '/main' will forward the request to the major application, which sits in the EKS work node group.

Once they migrated to ALB controller, they will no longer be able to add lambda to the target of ALB.
Even if the target is manually added to ALB, it will be removed by ALB controller very soon.

---
The guide of adding lambda as ALB targets.
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html

**Steps to reproduce**
If the target is manually added to ALB, it will be removed depends on the schedule of ALB controller.

**Expected outcome**
To support lambda as TargetGroup in alb controller.

**Environment**

* AWS Load Balancer controller version: aws-alb-ingress-controller: v2.2.0
* Kubernetes version: 1.20
* Using EKS (yes/no), if so version? Yes. eks.2

**Additional Context**:

**Comment by cainzhong** [comment]
Great. We also need it very much!

**Comment by TonyHuaPei** [comment]
we really need this

**Comment by gareth-liu276** [comment]
Sounds good, we like it

**Comment by papigers** [comment]
I was planning to work on adding support for a lambda target but after thinking it through I'm not sure what kind of support is missing.
One could create a target group with a lambda target and add it as a rule to the ingress using the ingress annotations, for example:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/actions.forward-lambda-tg: >
      {"type":"forward","targetGroupARN": "arn-of-your-target-group"}
spec:
  rules:
    - http:
        paths:
          - path: /main
            backend:
              serviceName: k8s-service
              servicePort: 80
          - path: /newCustomer
            backend:
              serviceName: forward-lambda-tg
              servicePort: use-annotation
```

@igrowheart @kishorj is there something I'm missing?
