### ISSUE TITLE
redirect action not applying to all conditions

### ISSUE THREAD

**Issue by prowave** [kubernetes-sigs/aws-load-balancer-controller#2218]
**Describe the bug**
I have an ALB listening on 80 and 443, and I have applied the Redirect action to the Host in order to automatically redirect from 80 -> 443.  The host is "www.something.com".

I have a condition on the same annotation to support the host "something.com".

The ALB creates 2 rules on the port 80 listener:
If `path is /* and host is www.something.com` then it redirects to 443 as expected.
If `path is /* and host is www.something.com OR something.com` then it forwards to the backend service (This is not desirable).

**Steps to reproduce**
```
    alb.ingress.kubernetes.io/actions.prod-config: >
      [{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}},
      {"type":"forward","forwardConfig":{"targetGroups":[{"serviceName":"www-service","servicePort":"https","weight":1}]}}]
    alb.ingress.kubernetes.io/conditions.prod-config: >
      [{"field":"host-header","hostHeaderConfig":{"values":["something.com"]}}
```
along with
```
    - host: www.something.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prod-config
                port:
                  name: use-annotation
```
**Expected outcome**
I would expect to have 1 rule on the port 80 Rules:
If `path is /* and host is www.something.com OR something.com` then it redirects to 443.

**Environment**

* AWS Load Balancer controller version: `v2.2.3`
* Kubernetes version 
```
Client Version: v1.21.0
Server Version: v1.21.2-eks-0389ca3
```
* Using EKS (yes/no), if so version? Yes, `1.21`

**Additional Context**:
