### ISSUE TITLE
Security Group not getting deleted [ Ingress deletion getting stuck ]

### ISSUE THREAD

**Issue by chandankashyap19** [kubernetes-sigs/aws-load-balancer-controller#2220]
**Describe the bug**
Ingress is not getting deleted by running the command: kubectl delete ingress <ingress name>.  By describing the ingress got "finalizer" in spec so removed it and after its removal, Ingress got removed but still controller is giving error "failed to delete securityGroup: timed out waiting for the condition".

While checking controller logs in details seen that controller is looking to search those services which is not available in cluster. Please see below attached logs: 
```
{"level":"error","ts":1631533698.1557388,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"enforcement-sidecar-macc02yk0bfjgh5","namespace":"enforcement-sidecar-local","error":"ingress: enforcement-sidecar-local/enforcement-sidecar-macc02yk0bfjgh5: Service \"enforcement-sidecar-macc02yk0bfjgh5\" not found"}
{"level":"error","ts":1631533855.053329,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-enforcem-enforcem-ad6295feb0","namespace":"enforcement-sidecar-local","error":"Service \"enforcement-sidecar-macc02yk0bfjgh5\" not found"}
{"level":"error","ts":1631533862.3472788,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"enforcement-sidecar-macc02yk0bfjgh5","namespace":"enforcement-sidecar-local","error":"ingress: enforcement-sidecar-local/enforcement-sidecar-macc02yk0bfjgh5: Service \"enforcement-sidecar-macc02yk0bfjgh5\" not found"
```

Security deletion logs are coming like : `{"level":"error","ts":1631514920.5677116,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"referencek8-chore-use-v1-events","namespace":"reference-local","error":"failed to delete securityGroup: timed out waiting for the condition"}`

**Steps to reproduce**
1. Created a hollowworld deployment with deployment, service and ingress manifest file. 
2. Creation of all workload went well and ingress also got applied and ALB got provisioned .
3. Perform deletion of all the resources using by kubectl delete -f <maifest file>
4. Deployment got deleted, Service got deleted but ingress got stuck.
5.  Removed finalizer by editing the ingress and deleted ingress but at same time controller start giving me error like SG deletion failed and also start searching the service name which was already deleted.

**Expected outcome**
Everything should be cleaned up on deletion and Controller should not look for those services which is not available in cluster anymore.

**Environment**

* AWS Load Balancer controller version : v2.1.0 & v2.1.3
* Kubernetes version 1.19
* Using EKS (yes/no), if so version? Yes (EKS with Fargate type )

**Additional Context**:

**Comment by kishorj** [comment]
@chandankashyap19, if you manually remove the finalizer from ingress resources, the LB controller will not be able to cleanup the AWS resources it allocated. How long did the ingress deletion get stuck before you had to remove the finalizer? Also, were the ALB managed security groups referenced from outside of the controller managed rules?

**Comment by chandankashyap19** [comment]
@kishorj  It is getting stuck forever then I perform manual removal of finalizer.  We are not providing managed security groups from outside. Whatever SG is getting created it is by Controller Only.  Performing sample deployments. Mentioned below.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: dockercloud/hello-world
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081   
  type: NodePort
  
---
apiVersion:  networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  labels:
    app: helloworld
  name: helloworld
spec:
  rules:
  - host: abc.com
  - http:
      paths:
      - backend:
          service: 
            name: helloworld
            port:
              number: 80
        path: /*
        pathType: ImplementationSpecific

```
