### ISSUE TITLE
Installing multiple instances of the ALB controller with different configuration and ingress class into the same namespace (kube-system)

### ISSUE THREAD

**Issue by dnutels** [kubernetes-sigs/aws-load-balancer-controller#2233]
**Describe the bug**
I am trying to install multiple, differently configured instances of the ALB controller into `kube-system` namespace. It won't work because the first instance claims ownership of `aws-load-balancer-tls` in the target namespace via `meta.helm.sh/release-name` and prevents the second instance to do the same.

**Steps to reproduce**

`values.yml` for the **first** instance:

```yaml
clusterName: my-cluster

ingressClass: alb-a
watchNamespace: app

fullnameOverride: alb-a-controller

serviceAccount:
  create: false
  name: aws-load-balancer-controller

defaultTags:
  ingressClass: alb-a
```

`values.yml` for the **second** instance:

```yaml
clusterName: my-cluster

ingressClass: alb-b
watchNamespace: app

fullnameOverride: alb-b-controller

serviceAccount:
  create: false
  name: aws-load-balancer-controller

defaultTags:
  ingressClass: alb-b
```

Then the instances are deployed using:

```bash
helm upgrade -i alb-a-controller eks/aws-load-balancer-controller -n kube-system -f alb-a/values.yml
helm upgrade -i alb-b-controller eks/aws-load-balancer-controller -n kube-system -f alb-b/values.yml
```

**Expected outcome**

Both controller instances are deployed and each handles separate ingress class.

**Actual outcome**

```
Error: rendered manifests contain a resource that already exists. 
Unable to continue with install: Secret "aws-load-balancer-tls" in 
namespace "kube-system" exists and cannot be imported into 
the current release: invalid ownership metadata; annotation 
validation error: key "meta.helm.sh/release-name" must equal 
"alb-b-controller": current value is "alb-a-controller"
```

**Environment**

* AWS Load Balancer controller version: 2.2
* Kubernetes version 1.21
* Using EKS (yes/no), if so version? 1.21 eks.2

**Additional Context**:
