### ISSUE TITLE
Proxy protocol v2 not enabled for NLB

### ISSUE THREAD

**Issue by mprimeaux** [kubernetes-sigs/aws-load-balancer-controller#2238]
**Describe the bug**
I am attempting to create an NLB of target type 'instance' with proxy protocol v2 enabled but the proxy protocol v2 is still disabled on the target groups.

**Steps to reproduce**

Apply the following ingress controller values to an existing EKS cluster.

<details>
<summary>Values File</summary>
<p>

```yaml
controller:
  replicaCount: 2
  minAvailable: 1

  autoscaling:
    annotations: {}
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50

  # This section refers to the creation of the IngressClass resource
  # IngressClass resources are supported since k8s >= 1.18 and required since k8s >= 1.19
  ingressClassResource:
    name: ingress-external
    enabled: true
    # https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class
    default: true
    controllerValue: "k8s.io/ingress-nginx"

  # Will add custom configuration options to Nginx https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
  config:
    generate-request-id: true
    proxy-body-size: 512M
    proxy-buffer-size: 8k
    proxy-buffering: 'on'
    proxy-buffers-number: 8
    proxy-add-original-uri-header: true
    large-client-header-buffers: 8 8k
    enable-real-ip: true
    real-ip-recursive: 'on'
    use-proxy-protocol: true
    use-forwarded-headers: true
    compute-full-forwarded-for: true
    use-http2: true
    keepalive-timeout: 75
    proxy-real-ip-cidr: 172.31.0.0/16

  service:
    annotations:
      # See https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"      

      # See https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#modsecurity
      nginx.ingress.kubernetes.io/enable-modsecurity: "true"
      nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
      nginx.ingress.kubernetes.io/modsecurity-snippet: |
        SecRuleEngine On
        Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf

  metrics:
    enabled: true

    service:
      annotations: {}
      # prometheus.io/scrape: "true"
      # prometheus.io/port: "10254"
```

</p>
</details> 

**Expected outcome**
I would expect to see the target group attribute "Proxy protocol v2" set to "Enabled" but it is set to "Disabled".

**Environment**

* AWS Load Balancer controller version 2.2.4
* Kubernetes version 1.21
* Using EKS (yes/no), if so version? Yes, eks.2

**Additional Context**:

We are using the [Kubernetes Ingress NGINX](https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx) chart, which for AWS uses the AWS Load Balancer Controller from this repository.

**Comment by kishorj** [comment]
@mprimeaux, since you have set the service annotation  `service.beta.kubernetes.io/aws-load-balancer-type` to `"nlb"`, the service gets reconciled by the kubernetes in-tree controller, not the one from this project. The in-tree controller doesn't support proxy protocol v2.

If you prefer the external controller manage the NLB for your service, you can specify the following annotation instead 
```
service.beta.kubernetes.io/aws-load-balancer-type: external
service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
```
Both annotations are required, and the `service.beta.kubernetes.io/aws-load-balancer-type` annotation should not be modified after the service gets created.

**Comment by mprimeaux** [comment]
@kishorj Thanks for your reply. 

Why does the in-tree controller not support proxy protocol v2 for NLB? I ask because if I manually set the "Proxy protocol v2" attribute of the target group to "Enabled" then I can confirm that real client IP addresses are available to consumers. Here is an excerpt from the Ingress Controller k8s logs:

<details>
<summary>Ingress Controller Logs (Real-IP)</summary>
<p>

```shell
ingress-ingress-nginx-controller-d847df46-wpzr2 **66.182.200.104** - - [20/Sep/2021:18:01:10 +0000] "GET /auth/resources/qx2uj/login/keycloak/img/keycloak-bg.png HTTP/2.0" 200 81862 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15" 50 0.007 [observability-keycloak-http-http[] [] 172.31.59.167:8080 81913 0.008 200 2490e2eaf3c3932da2c2a2bb32ae0c91
ingress-ingress-nginx-controller-d847df46-wpzr2 **66.182.200.104** - - [20/Sep/2021:18:01:10 +0000] "GET /auth/resources/qx2uj/common/keycloak/web_modules/@patternfly/react-core/dist/styles/assets/fonts/overpass-webfont/overpass-regular.woff2 HTTP/2.0" 200 35161 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15" 107 0.010 [observability-keycloak-http-http[] [] 172.31.59.167:8080 35196 0.008 200 9cd3e03fa856a387208fd9e83cbb010e
ingress-ingress-nginx-controller-d847df46-wpzr2 **66.182.200.104** - - [20/Sep/2021:18:01:10 +0000] "GET /auth/resources/qx2uj/login/keycloak/img/favicon.ico HTTP/2.0" 200 650 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15" 46 0.003 [observability-keycloak-http-http[] [] 172.31.59.167:8080 650 0.004 200 d22fdd8d23b70d9e183bb060b3bf6d90
```
</p>
</details>

**Comment by mprimeaux** [comment]
@kishorj Thanks. 

I've opened [7675](https://github.com/kubernetes/ingress-nginx/issues/7675) in the [ingress-nginx](https://github.com/kubernetes/ingress-nginx) project.

**Comment by mprimeaux** [comment]
@kishorj  I attempted to set the annotations as recommended above.

```
service.beta.kubernetes.io/aws-load-balancer-type: external
service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
```

However, when doing so there is no NLB that is created. Is this the expected behavior?

**Comment by kishorj** [comment]
@mprimeaux,  If you did not install the aws-load-balancer-controller - https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/installation/, then there won't be any NLB created.

This is not an issue on the ingress-nginx.

**Comment by mprimeaux** [comment]
@kishorj Thanks again for your help. We will try this and reply back.

**Comment by mprimeaux** [comment]
@kishorj Thanks again for your help. We were able to get everything working using the AWS Load Balancer Controller combined with the NGINX Ingress Controller. Again, thanks.

**Comment by kishorj** [comment]
@mprimeaux, I'm closing the issue. If you encounter problems, feel free to reopen or create a new one.

**Comment by mprimeaux** [comment]
@mballoni To get proxy-protcol to work and to see the real IP addresses, we used both service annotations and config map settings on the [NGINX Ingress Controller](https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx) as follows:

```yaml
controller:
  # Ref https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
  config:
    generate-request-id: true
    proxy-body-size: 512M
    proxy-buffer-size: 8k
    proxy-buffering: 'on'
    proxy-buffers-number: 8
    proxy-add-original-uri-header: true
    large-client-header-buffers: 8 8k
    enable-real-ip: true
    real-ip-recursive: 'on'
    use-proxy-protocol: true
    use-forwarded-headers: true
    compute-full-forwarded-for: true
    use-http2: true
    keepalive-timeout: 75
    proxy-real-ip-cidr: 172.31.0.0/16

  service:
    annotations:
      # Ref https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/
      service.beta.kubernetes.io/aws-load-balancer-type: "external"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
```

You'll of course want to replace the `proxy-real-ip-cidr` with a value that is applicable to your VPC. Here is the full values file for reference.

<details>
<summary>values.yaml</summary>

```yaml
# See https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx
# NOTE: Execute the following command tTo see the available chart values.
#       helm show values ingress-nginx/ingress-nginx

controller:
  replicaCount: 2
  minAvailable: 1

  # Define requests resources to avoid probe issues due to CPU utilization in busy nodes
  # ref: https://github.com/kubernetes/ingress-nginx/issues/4735#issuecomment-551204903
  # Ideally, there should be no limits.
  # https://engineering.indeedblog.com/blog/2019/12/cpu-throttling-regression-fix/
  resources:
  #  limits:
  #    cpu: 100m
  #    memory: 90Mi
    requests:
      cpu: 100m
      memory: 150Mi

  autoscaling:
    annotations: {}
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 85

  # This section refers to the creation of the IngressClass resource
  # IngressClass resources are supported since k8s >= 1.18 and required since k8s >= 1.19
  ingressClassResource:
    name: ingress-external
    enabled: true
    # Ref https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class
    default: true
    controllerValue: "k8s.io/ingress-nginx"

  # Ref https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
  config:
    generate-request-id: true
    proxy-body-size: 512M
    proxy-buffer-size: 8k
    proxy-buffering: 'on'
    proxy-buffers-number: 8
    proxy-add-original-uri-header: true
    large-client-header-buffers: 8 8k
    enable-real-ip: true
    real-ip-recursive: 'on'
    use-proxy-protocol: true
    use-forwarded-headers: true
    compute-full-forwarded-for: true
    use-http2: true
    keepalive-timeout: 75
    proxy-real-ip-cidr: 172.31.0.0/16
    
    # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#enable-modsecurity
    # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#modsecurity
    enable-modsecurity: true
    enable-owasp-modsecurity-crs: true
    modsecurity-snippet: |
      SecRuleEngine On

  extraVolumeMounts:
    ## Additional volumeMounts to the controller main container.
      - name: modsecurity-config
        mountPath: /etc/nginx/owasp-modsecurity-crs/crs-setup.conf
        subPath: csr-setup.conf
        readOnly: true

  extraVolumes:
    ## Additional volumes to the controller pod.
    - name: modsecurity-config
      configMap:
        name: modsecurity

  service:
    annotations:
      # Ref https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/
      service.beta.kubernetes.io/aws-load-balancer-type: "external"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"

  metrics:
    enabled: true

    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"

```

</details>

Note that we also enable ModSecurity and the OWASP Core Ruleset using a separate ConfigMap, which is not shown.
