### ISSUE TITLE
UnauthorizedOperation: You are not authorized to perform this operation

### ISSUE THREAD

**Issue by mkasinat** [kubernetes-sigs/aws-load-balancer-controller#2240]
**Describe the bug**
A concise description of what the bug is.
I am trying to install the aws-load-balancer-controller V2.2.2 in my kubernetes cluster(v1.19) but after applied the kind ingress we are getting the below error message and it is not allowed to create an alb load balancer .
Events:
  Type     Reason            Age   From     Message
  ----     ------            ----  ----     -------
  Warning  FailedBuildModel  65s   ingress  Failed build model due to UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: bab9a6f3-88b9-4a70-a265-8c68d6a593d5
  Warning  FailedBuildModel  65s  ingress  Failed build model due to UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: b19e9271-2277-46d7-8ebe-9b7e8f73602d
**Steps to reproduce**
Please find the below links which we followed and trying to implement the alb ingress controller .
https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html
Private Repo which i was referred .
https://github.com/RobinNagpal/kubernetes-tutorials/tree/master/06_tools/007_alb_ingress/01_eks
**Expected outcome**
A concise description of what you expected to happen.
It should allow the create a alb load balancer to route the traffic .
**Environment**
All the Environment
* AWS Load Balancer controller version v2.2.2
* Kubernetes version v1.19
* Using EKS (yes/no), if so version? Yes . eks.6

**Additional Context**:

**Comment by thanhma** [comment]
@mkasinat 

Make sure the ServiceAccount used for aws-load-balancer-controller has correct IAM policy attached, and the policy has enough permissions.

I recommend you to double check this step from the Installation Guide:
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/installation/#setup-iam-role-for-service-accounts

**Comment by mkasinat** [comment]
@thanhma We have tried the same steps without changing any order but we got the below error mesage.

{"level":"error","ts":1632237330.6128585,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"simple-ingress-8","namespace":"default","error":"UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 2e212740-f1cb-492d-b23c-dd4a9e148896"}

we have created the kubernetes cluster via terraform include aws-alb-ingress-controller after that we followed the step which mentioned in the below url.

**Comment by kishorj** [comment]
@mkasinat, did you configure IRSA?

**Comment by mkasinat** [comment]
Hello, I am followed the below link and same step .

https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fkubernetes-sigs.github.io%2Faws-load-balancer-controller%2Fv2.2%2Fdeploy%2Finstallation%2F%23setup-iam-role-for-service-accounts&data=04%7C01%7Cmakeshkumar.kasinathan%40volvocars.com%7Cb327491176dc4ad675f308d97d118b8c%7C81fa766ea34948678bf4ab35e250a08f%7C0%7C0%7C637678336580880199%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BL3VJrxLfV%2BuT83W9MbEtl2HRrPGhKbUASqgrK2XrJM%3D&reserved=0

But I have provisions the cluster via terraform for alb-ingress-controller with irsa but not for aws-load-balancer-controller. Please let me the step
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dectl** [comment]
I'm having the same problem after updating to 2.2.4. Checked the IAM policy over and over, no luck.

**Comment by kishorj** [comment]
If you've set IRSA, please verify the following

- check if your serviceaccount has the annotation
```
eks.amazonaws.com/role-arn: arn:aws:iam::xxxx:role/eksctl-<cluster>-addon-iamserviceaccount-kube-Role1-xxxx
```
  
- controller pod has the aws-iam-token volume
```
  volumes:
  - name: aws-iam-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: sts.amazonaws.com
          expirationSeconds: 86400
          path: token
```

- and the mount
```
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      name: aws-iam-token
      readOnly: true
```

If you set IRSA after the controller pod, you will have to restart the lb controller deployment.

**Comment by apeschel** [comment]
@kishorj Just checked, and IRSA isn't mentioned anywhere in the documentation, but it seems like the `eksctl utils associate-iam-oidc-provider` command enables it. If that's the case then we definitely have IRSA enabled, but are getting this error.

**Comment by apeschel** [comment]
@kishorj  Following your guide, I see the following:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::XXX:role/eksctl-XXX
```

There are two controller pods running, is this correct?

Pod1

```
    volumes:
    - name: aws-iam-token
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            audience: sts.amazonaws.com
            expirationSeconds: 86400
            path: token
```
      - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
        name: aws-iam-token
        readOnly: true
```

Pod2:

```
    volumes:
    - name: aws-iam-token
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            audience: sts.amazonaws.com
            expirationSeconds: 86400
            path: token
```

```
      - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
        name: aws-iam-token
        readOnly: true
```

It seems like everything matches your description, yet the problem persists.
