### ISSUE TITLE
Load balancer not setting forward rule

### ISSUE THREAD

**Issue by TechnoChimp** [kubernetes-sigs/aws-load-balancer-controller#2244]
**Describe the bug**
When deploying an Ingress resource of type alb, the target group is not getting applied to the listener rule of the load balancer. Instead only a default rule with 404 is applied.

The target group is created correctly, but not applied to the load balancer listener rule. I can manually remove the default 404 rule and add the forward rule to the new target group.

**Steps to reproduce**
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lb-name
  namespace: my-namespace
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-name: lb-name
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 50051}]'
    alb.ingress.kubernetes.io/certificate-arn: my-cert-arn
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: service-name
          servicePort: grpc
    host: my-hostname
```

I can see from the logs:

```
{"level":"info","ts":1632427871.2902937,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"services/sample-service\",\"resources\":{\"AWS::EC2::SecurityGroup\":{\"ManagedLBSecurityGroup\":{\"spec\":{\"groupName\":\"<generated_group_name>\",\"description\":\"[k8s] Managed SecurityGroup for LoadBalancer\",\"ingress\":[{\"ipProtocol\":\"tcp\",\"fromPort\":50051,\"toPort\":50051,\"ipRanges\":[{\"cidrIP\":\"0.0.0.0/0\"}]}]}}},\"AWS::ElasticLoadBalancingV2::Listener\":{\"50051\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":50051,\"protocol\":\"HTTPS\",\"defaultActions\":[{\"type\":\"fixed-response\",\"fixedResponseConfig\":{\"contentType\":\"text/plain\",\"statusCode\":\"404\"}}],\"certificates\":[{\"certificateARN\":\"<certificate_arn>\"}],\"sslPolicy\":\"ELBSecurityPolicy-2016-08\"}}},\"AWS::ElasticLoadBalancingV2::ListenerRule\":{\"50051:1\":{\"spec\":{\"listenerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::Listener/50051/status/listenerARN\"},\"priority\":1,\"actions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/services/<service_name>:grpc/status/targetGroupARN\"}}]}}],\"conditions\":[{\"field\":\"host-header\",\"hostHeaderConfig\":{\"values\":[\"sample-service-test.titan-dev.sds.systems\"]}}]}}},\"AWS::ElasticLoadBalancingV2::LoadBalancer\":{\"LoadBalancer\":{\"spec\":{\"name\":\"<load_balancer_name>\",\"type\":\"application\",\"scheme\":\"internet-facing\",\"ipAddressType\":\"ipv4\",\"subnetMapping\":[{\"subnetID\":\"<subnet_id>\"},{\"subnetID\":\"<subnet_id>\"},{\"subnetID\":\"<subnet_id>\"}],\"securityGroups\":[{\"$ref\":\"#/resources/AWS::EC2::SecurityGroup/ManagedLBSecurityGroup/status/groupID\"}]}}},\"AWS::El
asticLoadBalancingV2::TargetGroup\":{\"services/<service_name>:grpc\":{\"spec\":{\"name\":\"<generated_name>\",\"targetType\":\"instance\",\"port\":30914,\"protocol\":\"HTTP\",\"protocolVersion\":\"GRPC\",\"healthCheckConfig\":{\"port\":\"traffic-port\",\"protocol\":\"HTTP\",\"path\":\"/AWS.ALB/healthcheck\",\"matcher\":{\"grpcCode\":\"12\"},\"intervalSeconds\":15,\"timeoutSeconds\":5,\"healthyThresholdCount\":2,\"unhealthyThresholdCount\":2}}}},\"K8S::ElasticLoadBalancingV2::TargetGroupBinding\":{\"services/<service_name>:grpc\":{\"spec\":{\"template\":{\"metadata\":{\"name\":\"<generated_name>\",\"namespace\":\"services\",\"creationTimestamp\":null},\"spec\":{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/services/<service_name>:grpc/status/targetGroupARN\"},\"targetType\":\"instance\",\"serviceRef\":{\"name\":\"<service_name>\",\"port\":\"grpc\"},\"networking\":{\"ingress\":[{\"from\":[{\"securityGroup\":{\"groupID\":{\"$ref\":\"#/resources/AWS::EC2::SecurityGroup/ManagedLBSecurityGroup/status/groupID\"}}}],\"ports\":[{\"protocol\":\"TCP\"}]}]}}}}}}}}"}
```

**Expected outcome**
I expect the load balancer to have a listener rule applied which forwards the traffic to the target group that was created by the controller.

**Environment**

* AWS Load Balancer controller version: 2.2.3
* Kubernetes version: 1.18
* Using EKS (yes/no), if so version? Yes ~ eks.8

**Additional Context**:
