### ISSUE TITLE
Multiple ingress resources with multiple hosts base routing

### ISSUE THREAD

**Issue by patrykcloudmind** [kubernetes-sigs/aws-load-balancer-controller#2255]
I am not sure if that is a bug, but I have multiple ingress resources grouped under one ALB.

Example:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/group.name: my-group
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/whitelist-source-range: someIP
spec:
  rules:
    - host: host1.example.com
      http:
        paths:
          - path: /test/*
            backend:
              service:
                name: service1
                port: http
```
and another one:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:.........
    alb.ingress.kubernetes.io/group.name: my-group
    alb.ingress.kubernetes.io/inbound-cidrs: someIP
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-2016-08
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - host: host2.example.com
    http:
      paths:
      - backend:
          service:
            name: service2
            port:
              name: 4000
        path: /api/*
      - backend:
          service:
            name: service2
            port:
              name: 4001
        path: /api/v1/*
      - backend:
          service:
            name: service2
            port:
              name: 4002
        path: /api/somethingelse/*
```
If I go to ALB rules, I can see only rules for service2. 
Host1 and service1 rules are missing.
No errors on ALB controller or ingress resource.

I am not sure if that is bug or just not supported feature to have multiple hosts group together under one ALB.

**Expected outcome**
I would expect to see all the rules above on ALB 

**Environment**

* AWS Load Balancer controller version 2.2.3
* Kubernetes version 1.21.2
* Using EKS (yes/no), if so version? yes - 1.21.2
