### ISSUE TITLE
Question: traffic from Target group go to a service or a pod ?

### ISSUE THREAD

**Issue by przemolb** [kubernetes-sigs/aws-load-balancer-controller#2256]
We are using AWS Load Balancer controller 2.2.4 with the latest EKS 1.21. We create ALB using the following manifests:
```
apiVersion: v1
kind: Service
metadata:
  name: alb
spec:
  ports:
  - name: alb
    port: 8000
    targetPort: 8080
    protocol: TCP
  selector:
    app: alb
---  
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: alb-test
    alb.ingress.kubernetes.io/healthcheck-port: "8080"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alb
                port:
                  number: 8000

```
The pod behind this service is listening on port 8080. When we apply this configuration it is working correctly (from external IP through the ALB then to Service and then to pod) . Normally kubernetes `Service` (logically) is the "face" of a pod and all traffic to a pod(s) is supposed to go through the `Service`. In this case the Targets in the Target Groups have the healthcheck port of "8080" (which is the port of the pod and not the `Service`). Does that mean that helathcheck is not going through the Service port and directly to the pod ? Is the Service definition bypassed when it comes to a healthcheck ? How does that internally work ? Is there any documentation about it ?
