### ISSUE TITLE
Service healthcheck annotation not working

### ISSUE THREAD

**Issue by davidgiga1993** [kubernetes-sigs/aws-load-balancer-controller#2279]
**Describe the bug**
When using the `service.beta.kubernetes.io/aws-load-balancer-healthcheck-path` annotation on a service used by the ingress, the ALB target group doesn't get updated and still uses the default `/` path.

**Steps to reproduce**
```yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "tht-app"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/subnets: private-zone-subnet-1, private-zone-subnet-2
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-central-1:something:certificate/something"
    alb.ingress.kubernetes.io/load-balancer-attributes: "idle_timeout.timeout_seconds=300"
spec:
  defaultBackend:
    service:
      name: "my-app"
      port:
        name: http
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  name: http
---
apiVersion: v1
kind: Service
metadata:
  name: "backend"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/api/hello"
spec:
  type: NodePort
  selector:
    app: "backend"
  ports:
    - name: http
      protocol: TCP
      port: 7070
  externalTrafficPolicy: Local
```
![image](https://user-images.githubusercontent.com/3924958/136538225-2ed22043-6ff9-4ca9-be33-eef0bb9a985f.png)

This also happens when deleting the ALB and recreating everything

**Expected outcome**
The target group should use the specified health check path

**Environment**

* AWS Load Balancer controller version: 2.2.4
* Kubernetes version: v1.21.2-eks-0389ca3
* Using EKS (yes/no), if so version? yes, see above
