### ISSUE TITLE
Failed to initial the AWS credentials with ProcessProviderExecutionError

### ISSUE THREAD

**Issue by lxlxok** [kubernetes-sigs/aws-load-balancer-controller#2286]
**Describe the bug**
The v2.2.4 use a minimal base docker image, it failed to initial the AWS credentials mounted to the aws-load-balancer-controller, we mount the AWS credentials through a secret to the aws-load-balancer-controller pod.

Here is the error message. 
```
{"level":"error","ts":1633997929.374549,"logger":"controller","msg":"Reconciler error","controller":"service","name":"grafana","namespace":"sam-system","error":"ProcessProviderExecutionError: error in credential_process\ncaused by: exec: \"sh\": executable file not found in $PATH"}
{"level":"debug","ts":1633997929.3745863,"logger":"controller-runtime.manager.events","msg":"Warning","object":{"kind":"Service","namespace":"sam-system","name":"grafana","uid":"d4864e62-523d-408b-b22e-dca5e81475ea","apiVersion":"v1","resourceVersion":"1128614668"},"reason":"FailedBuildModel","message":"Failed build model due to ProcessProviderExecutionError: error in credential_process\ncaused by: exec: \"sh\": executable file not found in $PATH"}
{"level":"error","ts":1633997930.0756721,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-samsyste-grafana-87421bfb62","namespace":"sam-system","error":"ProcessProviderExecutionError: error in credential_process\ncaused by: exec: \"sh\": executable file not found in $PATH"}
```

**Steps to reproduce**

1. Create a secret file with AWS credentials
```
apiVersion: v1
data:
  credentials: ****
  credentials.json: ***
  credentials.process: ***
kind: Secret
```

2. Mount the secret and specify the location of access keys though env.
```
        env:
        - name: AWS_REGION
          value: us-east-2
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /meta/aws-iam/credentials.process
        volumeMounts:
        - mountPath: /meta/aws-iam
          name: iamcreds
          readOnly: true
```

3. Update the tag of image docker.io/amazon/aws-alb-ingress-controller from v2.2.3 to v2.2.4.

**Expected outcome**

We expect the log to be same as what we saw in v2.2.1/v2.2.2/v2.2.3. 
```
{"level":"debug","ts":1634000827.467217,"logger":"controller-runtime.manager.events","msg":"Normal","object":{"kind":"TargetGroupBinding","namespace":"sam-system","name":"k8s-samsyste-grafana-87421bfb62","uid":"7855c9f7-9b4d-4138-96ca-e97ba91f57e9","apiVersion":"elbv2.k8s.aws/v1beta1","resourceVersion":"1128614688"},"reason":"SuccessfullyReconciled","message":"Successfully reconciled"}
{"level":"info","ts":1634000877.883543,"logger":"controllers.service","msg":"successfully deployed model","service":{"namespace":"sam-system","name":"grafana"}}
{"level":"debug","ts":1634000877.8836043,"logger":"controller","msg":"Successfully Reconciled","controller":"service","name":"grafana","namespace":"sam-system"
```

**Environment**

* AWS Load Balancer controller version
v2.2.4

* Kubernetes version
v1.19.13-eks-8df270

* Using EKS (yes/no), if so version?
yes 1.19
**Additional Context**:
