### ISSUE TITLE
Document how to create internal nlb-ip which supports setting service.beta.kubernetes.io/aws-load-balancer-ssl-cert

### ISSUE THREAD

**Issue by vinayan3** [kubernetes-sigs/aws-load-balancer-controller#2318]
**Is your feature request related to a problem?**
I would like to be able to set a SSL cert the LB can do the TLS termination and then pass along the traffic to a pod using IP targeting.

I've tried to use this setup and the SSL cert never gets set on the LB:

```
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway-lb
  namespace: istio-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    external-dns.alpha.kubernetes.io/hostname: "[...]"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "[...]"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "*"
spec:
  type: LoadBalancer
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
      name: https
```
AWS LB Controller image:
`602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon/aws-load-balancer-controller:v2.2.1`

**Describe the solution you'd like**
I would like use `nlb-ip` with TLS termination. 

**Describe alternatives you've considered**
Setting `service.beta.kubernetes.io/aws-load-balancer-type: nlb` and the LB will come up with SSL but it doesn't have IP targetting. It's livable but if the cluster gets larger then all of the issues describe in why `nlb-ip` was created come up.
