### ISSUE TITLE
Cannot resolve private-ips for NLB when it uses annotation "service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses" 

### ISSUE THREAD

**Issue by blackdog0403** [kubernetes-sigs/aws-load-balancer-controller#2325]
AWS Load Balancer Controller Version: 2.2
Amazon EKS Version: 1.20

I'm trying to use internal NLB with AWS Load Balancer Controller and want it to have private-ip that I want to assign on NLB. And I found that annotation "service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses" does not work as I expected. 

It does not fix private-ips that are set with the annotation but NLB just get the random private ips from private ip pools in subnets

Here is my test yaml files

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: game-2048
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-2048
  name: deployment-2048
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048
    spec:
      containers:
      - image: alexwhen/docker-2048
        imagePullPolicy: Always
        name: app-2048
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: game-2048
  name: service-2048
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0f74fd7c09e68cba4,subnet-06c2f3d899873f949,subnet-057554902ae830a97"
    service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses: "192.168.96.100,192.168.128.100,192.168.160.100"
spec:
  ports:
    - port: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: app-2048
```

And I found that If I set just one subnet and one private ip with the annotation, after NLB is provisioned through AWS Load Balancer Controller, I can configure two subnets and two private-ips which I want

Any Idea for this? or Already reported Issue?

**Comment by lakshaygaur** [comment]
I am not able to assigne the private IPs either. I am using EKS version 1.22. Please help what I am missing here.
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses: 10.1.244.178, 10.1.178.87, 10.1.223.71
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-01, subnet-02, subnet-03
  name: "nginx-svc"
spec:
  type: LoadBalancer
  selector:
    app: nginx-sample
  ports:
  - name: internal-port
    protocol: TCP
    port: 80
    targetPort: 80
```
