### ISSUE TITLE
ALB controller with Godaddy is giving me too many redirects

### ISSUE THREAD

**Issue by genieai-vikas** [kubernetes-sigs/aws-load-balancer-controller#2334]
* AWS Load Balancer controller version: 1.0.2
* Using EKS (yes/no), if so version? 1.19

**Additional Context**: I am trying to use ALB ingress controller in my EKS cluster but my domain is in GoDaddy and currently I can't move it to route53.

So what I did is I created an ingress and when ALB is created I added its IP to the subdomain in GoDaddy but keep getting "Too Many redirect" error.

Could you please provide me with the correct way of implementing ALB ingress controller with GoDaddy?

My ingress file

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingressScheme }}
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.ingress.ACM_CERTIFICATE_ARN }}"
spec:
  rules:
  - host: test.abc.io
    http:
      paths:
        - path: /*
          backend:
            serviceName: ssl-redirect
            servicePort: use-annotation
        - path: /*
          backend:
            serviceName: nginx-ui-svc
            servicePort: 80
```
This is my conf file of nginx service, I am trying to access via domain:

```
server {
  listen 80;
  # listen 443 default_server ssl http2; 
  # listen 443 ssl http2 default_server;
  # listen [::]:443 ssl http2 default_server;
  listen [::]:443 http2 default_server;
  server_name ${APP_DOMAIN} ec2-3-12-202-220.us-east-2.compute.amazonaws.com;

  server_tokens off;

  # ssl_certificate /etc/ssl/keys/cert.pem;
  # ssl_certificate_key /etc/ssl/keys/key.pem;

  # ssl_protocols TLSv1.2;
  # ssl_prefer_server_ciphers on;
  # ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
  # ssl_ecdh_curve secp384r1; # Requires nginx >= 1.1.0
  # ssl_ecdh_curve prime256v1; # FIX: Android 7.0 bug
  # ssl_session_cache shared:SSL:10m;
  # ssl_session_tickets off; # Requires nginx >= 1.5.9
  # ssl_stapling on; # Requires nginx >= 1.3.7
  # ssl_stapling_verify on; # Requires nginx => 1.3.7
  resolver 8.8.8.8 8.8.4.4 valid=300s;
  resolver_timeout 5s;
  add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
  add_header X-Frame-Options DENY;
  add_header X-Content-Type-Options nosniff;
  add_header Access-Control-Allow_Credentials true;
  add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
  add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH';

  error_page 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 500 501 502 503 504 505 506 507 508 509 510 511 /error.html;

  proxy_cookie_path / "/; HttpOnly; Secure";

  location / {
    root   /usr/share/nginx/html;
  }

  location ^~ /_health {
    types { } default_type "text/plain; charset=utf-8";
    return 200 "UP";
  }

  location ^~ /self {
    root   /usr/share/nginx/html/self;
  }

  location ${APP_BASE_URL} {
    error_log /var/log/nginx/error.log error;
    access_log off;

    proxy_pass ${APP_PROXY_URL};
    proxy_http_version 1.1;
    # proxy_ssl_server_name on;
    proxy_read_timeout 600;
    proxy_set_header Upgrade ${DOLLAR}http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host ${DOLLAR}host;
    proxy_set_header X-Forwarded-Host ${DOLLAR}host:${DOLLAR}server_port;
    proxy_set_header X-Forwarded-Server ${DOLLAR}host;
    proxy_set_header X-Forwarded-Proto ${DOLLAR}scheme;
    proxy_set_header X-Forwarded-For ${DOLLAR}proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP ${DOLLAR}remote_addr;
    #proxy_pass_header X-XSRF-TOKEN;
  }
}
```
How to fix these "too many redirect" issues?
