### ISSUE TITLE
Controller not updating resource status if reconcile fails

### ISSUE THREAD

**Issue by tekenstam** [kubernetes-sigs/aws-load-balancer-controller#2338]
**Describe the bug**
We have observed several cases where the reconcile of an `Ingress` object failed. For example:
```
Failed deploy model due to ValidationError: Health check interval must be greater than the timeout. status code: 400, request id: 998877ff-0000-1111-2a2a-aabbcc112233
```

We also observed reconciliation failures when a non-existent SG was specified in the `alb.ingress.kubernetes.io/security-groups` annotation.

An event for the resource is generated, but the status of the resource does not indicate any error. Currently the only values in status are:
```
status:
  loadBalancer:
    ingress:
      - hostname: >-
          myalb-1a2b3c4d5e-1234567890.us-west-2.elb.amazonaws.com
```

We are deploying this Ingress object using Argo CD. Current Argo CD considers the resource "healthy" if the "`status.loadBalancer.ingress` list is non-empty, with at least one value for hostname or IP", which is the case in this example. We would like some additional feedback that the reconciliation for this resource has failed so we can create a [custom resource health check for Argo CD](https://argo-cd.readthedocs.io/en/stable/operator-manual/health/).

Could some additional fields be added to `status` that would indicate when a reconcile error occurred? For example:
```
status:
  loadBalancer:
    ingress:
      - hostname: >-
          myalb-1a2b3c4d5e-1234567890.us-west-2.elb.amazonaws.com
  state: invalid
  reason: ValidationError
  message: Failed deploy model due to ValidationError: Health check interval must be greater than the timeout. status code: 400, request id: 998877ff-0000-1111-2a2a-aabbcc112233
```

Status:
  Message:  Configuration for default/dns-tcp was added or updated
  Reason:   AddedOrUpdated
  State:    Valid

**Steps to reproduce**

1. Deploy an ALB Ingress with default annotations.
2. Update the Ingress spec and add the `alb.ingress.kubernetes.io/healthcheck-interval-seconds: 3` annotation.
3. Reconcile of the resource will start failing.
4. Run `kubectl get ingress <name> -o yaml` and check the `status`. There is nothing to indicate there is a problem with the deployed spec.
5. BONUS: Do the above using GitOps and Argo CD.

**Expected outcome**
The `status` of an `Ingress` resource should have some indication of a reconciliation failure.

**Environment**

* AWS Load Balancer controller version: `v2.2.1`
* Kubernetes version: `v1.20`
* Using EKS: Yes, 1.20 eks.2

**Additional Context**:
