### ISSUE TITLE
Target Groups always unhealthy

### ISSUE THREAD

**Issue by kferrone** [kubernetes-sigs/aws-load-balancer-controller#2340]
**Describe the bug**
The target groups for the ALB are always unhealthy. 

**Steps to reproduce**

Here are the values I used with the helm chart:
```yaml
clusterName: MyCluster
region: us-west-2
vpcId: myvpcsid
serviceAccount: 
  create: false
  name: aws-load-balancer-controller
nodeSelector:
  eks.amazonaws.com/nodegroup: Main
enableCertManager: true
enablePodReadinessGateInject: true
enableShield: true
enableWaf: true
enableWafv2: true
createIngressClassResource: false
```
The service account is using irsa with this policy: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json

**Expected outcome**
Healthy target groups

**Environment**

* AWS Load Balancer controller version
helm  `1.3.1`
app: `v2.3.0`
* Kubernetes version
* Using EKS (yes/no), if so version?
yes `v1.21.2-eks-0389ca3`

**Additional Context**:
