### ISSUE TITLE
My controller pod is unable to reconcile even when I have type: NodePort

### ISSUE THREAD

**Issue by jayeshnazre** [kubernetes-sigs/aws-load-balancer-controller#2345]
**Describe the bug**
I have ingress defined for a service with type: nodeport and for some reason its logging an error  - 
Error: InvalidParameter: 1 validation error(s) found.\n- minimum field value of 1, CreateTargetGroupInput.Port.\n
**NOTE: This is not the same as what others have reported, I do have the service exposed as NodePort type.**
So its not the same as below
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1695

**Steps to reproduce**
Just deploy an ingress to the EKS cluster and this error occurs

**Expected outcome**
The error log should not happen as I have already checked the following
a) Service is NodePort type
b) The ingress details are correct as shown below
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      alb.ingress.kubernetes.io/group.name: XXXX
      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      alb.ingress.kubernetes.io/scheme: internal
      kubernetes.io/ingress.class: alb

**Environment**

- EKS
- kubernetes version: 1.19
- AWS ingress controller version 2.2.1 

**Additional Context**:

**Comment by jayeshnazre** [comment]
@kishorj  Kishore can you take a look at this for me? Its not the same issue as discussed before where the service type was incorrectly defined

**Comment by M00nF1sh** [comment]
@jayeshnazre 
Would mind post your full Service & IngressSpec here.
Also, from the controller logs, there should be a log like "Successfully built model: <someJson>", would you help post it here as well. (you can redact sensitive fields such as domain name)

**Comment by kishorj** [comment]
@jayeshnazre, you can email the specs and the controller logs to **k8s-alb-controller-triage AT amazon.com**

**Comment by kishorj** [comment]
@jayeshnazre, I'm closing the issue. If problem persists, feel free to reopen or create a new one.

**Comment by kasvith** [comment]
Hi, Im having the same issue. My Service is exposed as `NodePort` and im getting exactly the same issue

**Comment by kasvith** [comment]
My Ingress is for argocd

```yml
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP2 #This tells AWS to send traffic from the ALB using HTTP2. Can use GRPC as well if you want to leverage GRPC specific features
  labels:
    app: argogrpc
  name: argogrpc
  namespace: argocd
spec:
  ports:
    - name: "443"
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    # Use this annotation (which must match a service name) to route traffic to HTTP2 backends.
    alb.ingress.kubernetes.io/conditions.argogrpc: |
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "Content-Type", "values":["application/grpc"]}}]
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: apps
    alb.ingress.kubernetes.io/certificate-arn: <<redacted>>
    alb.ingress.kubernetes.io/target-type: instance
  name: argocd
  namespace: argocd
spec:
  ingressClassName: alb
  rules:
    - host: argocd.analystbuilder.com
      http:
        paths:
          - path: /
            backend:
              service:
                name: argogrpc
                port:
                  number: 443
            pathType: Prefix
          - path: /
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
            pathType: Prefix
  tls:
    - hosts:
        - argocd.example.com
```

Logs

```json
{
  "id": "apps",
  "resources": {
    "AWS::EC2::SecurityGroup": {
      "ManagedLBSecurityGroup": {
        "spec": {
          "groupName": "k8s-apps-53be320dfa",
          "description": "[k8s] Managed SecurityGroup for LoadBalancer",
          "ingress": [
            {
              "ipProtocol": "tcp",
              "fromPort": 443,
              "toPort": 443,
              "ipRanges": [
                {
                  "cidrIP": "0.0.0.0/0"
                }
              ]
            }
          ]
        }
      }
    },
    "AWS::ElasticLoadBalancingV2::Listener": {
      "443": {
        "spec": {
          "loadBalancerARN": {
            "$ref": "#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN"
          },
          "port": 443,
          "protocol": "HTTPS",
          "defaultActions": [
            {
              "type": "fixed-response",
              "fixedResponseConfig": {
                "contentType": "text/plain",
                "statusCode": "404"
              }
            }
          ],
          "certificates": [
            {
              "certificateARN": "<<redacted>>"
            }
          ],
          "sslPolicy": "ELBSecurityPolicy-2016-08"
        }
      }
    },
    "AWS::ElasticLoadBalancingV2::ListenerRule": {
      "443:1": {
        "spec": {
          "listenerARN": {
            "$ref": "#/resources/AWS::ElasticLoadBalancingV2::Listener/443/status/listenerARN"
          },
          "priority": 1,
          "actions": [
            {
              "type": "forward",
              "forwardConfig": {
                "targetGroups": [
                  {
                    "targetGroupARN": {
                      "$ref": "#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/argocd/argocd-argogrpc:443/status/targetGroupARN"
                    }
                  }
                ]
              }
            }
          ],
          "conditions": [
            {
              "field": "http-header",
              "httpHeaderConfig": {
                "httpHeaderName": "Content-Type",
                "values": [
                  "application/grpc"
                ]
              }
            },
            {
              "field": "host-header",
              "hostHeaderConfig": {
                "values": [
                  "argocd.example.com"
                ]
              }
            },
            {
              "field": "path-pattern",
              "pathPatternConfig": {
                "values": [
                  "/*"
                ]
              }
            }
          ]
        }
      },
      "443:2": {
        "spec": {
          "listenerARN": {
            "$ref": "#/resources/AWS::ElasticLoadBalancingV2::Listener/443/status/listenerARN"
          },
          "priority": 2,
          "actions": [
            {
              "type": "forward",
              "forwardConfig": {
                "targetGroups": [
                  {
                    "targetGroupARN": {
                      "$ref": "#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/argocd/argocd-argocd-server:443/status/targetGroupARN"
                    }
                  }
                ]
              }
            }
          ],
          "conditions": [
            {
              "field": "host-header",
              "hostHeaderConfig": {
                "values": [
                  "argocd.example.com"
                ]
              }
            },
            {
              "field": "path-pattern",
              "pathPatternConfig": {
                "values": [
                  "/*"
                ]
              }
            }
          ]
        }
      }
    },
    "AWS::ElasticLoadBalancingV2::LoadBalancer": {
      "LoadBalancer": {
        "spec": {
          "name": "k8s-apps-70e984890c",
          "type": "application",
          "scheme": "internet-facing",
          "ipAddressType": "ipv4",
          "subnetMapping": [
            {
              "subnetID": "subnet-033a262bc3f7df933"
            },
            {
              "subnetID": "subnet-068b5178b17c1a6d6"
            }
          ],
          "securityGroups": [
            {
              "$ref": "#/resources/AWS::EC2::SecurityGroup/ManagedLBSecurityGroup/status/groupID"
            },
            "sg-06f80ede99f54cc68"
          ]
        }
      }
    },
    "AWS::ElasticLoadBalancingV2::TargetGroup": {
      "argocd/argocd-argocd-server:443": {
        "spec": {
          "name": "k8s-argocd-argocdse-8bf850292e",
          "targetType": "instance",
          "port": 0,
          "protocol": "HTTPS",
          "protocolVersion": "HTTP1",
          "ipAddressType": "ipv4",
          "healthCheckConfig": {
            "port": "traffic-port",
            "protocol": "HTTPS",
            "path": "/",
            "matcher": {
              "httpCode": "200"
            },
            "intervalSeconds": 15,
            "timeoutSeconds": 5,
            "healthyThresholdCount": 2,
            "unhealthyThresholdCount": 2
          }
        }
      },
      "argocd/argocd-argogrpc:443": {
        "spec": {
          "name": "k8s-argocd-argogrpc-a536bf3a0d",
          "targetType": "instance",
          "port": 32010,
          "protocol": "HTTPS",
          "protocolVersion": "HTTP2",
          "ipAddressType": "ipv4",
          "healthCheckConfig": {
            "port": "traffic-port",
            "protocol": "HTTPS",
            "path": "/",
            "matcher": {
              "httpCode": "200"
            },
            "intervalSeconds": 15,
            "timeoutSeconds": 5,
            "healthyThresholdCount": 2,
            "unhealthyThresholdCount": 2
          }
        }
      }
    },
    "K8S::ElasticLoadBalancingV2::TargetGroupBinding": {
      "argocd/argocd-argocd-server:443": {
        "spec": {
          "template": {
            "metadata": {
              "name": "k8s-argocd-argocdse-8bf850292e",
              "namespace": "argocd",
              "creationTimestamp": null
            },
            "spec": {
              "targetGroupARN": {
                "$ref": "#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/argocd/argocd-argocd-server:443/status/targetGroupARN"
              },
              "targetType": "instance",
              "serviceRef": {
                "name": "argocd-server",
                "port": 443
              },
              "networking": {
                "ingress": [
                  {
                    "from": [
                      {
                        "securityGroup": {
                          "groupID": "sg-06f80ede99f54cc68"
                        }
                      }
                    ],
                    "ports": [
                      {
                        "protocol": "TCP",
                        "port": 0
                      }
                    ]
                  }
                ]
              },
              "ipAddressType": "ipv4"
            }
          }
        }
      },
      "argocd/argocd-argogrpc:443": {
        "spec": {
          "template": {
            "metadata": {
              "name": "k8s-argocd-argogrpc-a536bf3a0d",
              "namespace": "argocd",
              "creationTimestamp": null
            },
            "spec": {
              "targetGroupARN": {
                "$ref": "#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/argocd/argocd-argogrpc:443/status/targetGroupARN"
              },
              "targetType": "instance",
              "serviceRef": {
                "name": "argogrpc",
                "port": 443
              },
              "networking": {
                "ingress": [
                  {
                    "from": [
                      {
                        "securityGroup": {
                          "groupID": "sg-06f80ede99f54cc68"
                        }
                      }
                    ],
                    "ports": [
                      {
                        "protocol": "TCP",
                        "port": 32010
                      }
                    ]
                  }
                ]
              },
              "ipAddressType": "ipv4"
            }
          }
        }
      }
    }
  }
}
```
