### ISSUE TITLE
Unable create ingress to gRPC service running on EKS

### ISSUE THREAD

**Issue by FelipeLujan** [kubernetes-sigs/aws-load-balancer-controller#2346]
**Describe the bug**
In a properly tagged subnet I can create http-based Ingresses and access my applications from the internet
I am experiencing issues exposing the thanos-sidecar gRPC endpoint using the example labels

**Steps to reproduce**
*  installed the prometheus-operator and thanos sidecar.
*  created a service to expose the thanos sidecar port 10901. This port is accessible and works as expected within the EKS cluster

service definition
```
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
  name: thanos-sidecar-svc
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: grpc
      port: 10901
      targetPort: 10901
  selector:
    app: prometheus
    prometheus: k8s
````
ingress definition

````
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thanos-sidecar-ingress
  namespace: monitoring
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:a..."

    external-dns.alpha.kubernetes.io/hostname: "coupon.default.couponlm.net"
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=600

    alb.ingress.kubernetes.io/actions.ssl-redirect:
      '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'

    alb.ingress.kubernetes.io/target-type: instance
    kubernetes.io/ingress.class: alb

spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: thanos-sidecar-svc
                port:
                  number: 10901
````

The service running in port 10901 can't be accessed through the DNS name indicated by AWS
The following error is returned when `k describe ingress thanos-sidecar-ingress -n monitoring`
```
Warning  FailedDeployModel  2m  ingress  Failed deploy model due to failed to create listener rule: InvalidLoadBalancerAction: Listener protocol 'HTTP' is not supported with a target group with the protocol-version 'GRPC'
           status code: 400, request id: 01096c50-9ed2-4f80-9d72-4ef823cdc2e1
  Warning  FailedDeployModel  34s (x6 over 118s)  ingress  (combined from similar events): Failed deploy model due to failed to create listener rule: InvalidLoadBalancerAction: Listener protocol 'HTTP' is not supported with a target group with the protocol-version 'GRPC'
           status code: 400, request id: 63b839fc-5493-4e31-b2d6-752afcc85552
```

**Expected outcome**

The thanos sidecar service works from the outer internet as it does from within the EKS cluster

**Environment**

* Kubernetes version 1.21
* Using EKS (yes)

**Additional Context**:
[kube-prometheus](https://github.com/prometheus-operator/kube-prometheus)

edit: additional context and typo
