### ISSUE TITLE
Failures to handle a specific Ingress resource prevent other Ingress resources to be handled.

### ISSUE THREAD

**Issue by Dohbedoh** [kubernetes-sigs/aws-load-balancer-controller#2349]
**Describe the bug**

A bad Ingress resource should not prevent other Ingresses to be handled by the controller. I believe that this should not happen. A single "bad" ingress should not prevent other "good" ingress to be processed.

**Steps to reproduce**

* Deploy EKS 1.19+ the AWS Load Balancer Controller 2.3.0 (reproduced also in 2.2.4)
* Create an app with a broken Ingress, like for example:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-2048
  name: bad-2048
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bad-2048
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bad-2048
    spec:
      containers:
      - image: alexwhen/docker-2048
        imagePullPolicy: Always
        name: bad-2048
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: game-2048
  name: bad-2048
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: bad-2048
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: game-2048
  name: bad-2048
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: "game-2048"
spec:
  rules:
    - host: "core-eks.aburdajewicz.support.beescloud.com"
      http:
        paths:
        - backend:
            service:
              name: bad-2048
              port:
                number: 80
          path: "/bad/"
          pathType: "Prefix"
        - backend:
            service:
              name: bad-2048
              port:
                number: 80
          path: "/bad/*"
          pathType: "Prefix"
```

* Create an App with a proper Ingress for the same group:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-2048
  name: good-2048
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: good-2048
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: good-2048
    spec:
      containers:
      - image: alexwhen/docker-2048
        imagePullPolicy: Always
        name: good-2048
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: game-2048
  name: good-2048
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: good-2048
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: game-2048
  name: good-2048
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: "game-2048"
spec:
  rules:
    - host: "core-eks.aburdajewicz.support.beescloud.com"
      http:
        paths:
        - backend:
            service:
              name: good-2048
              port:
                number: 80
          path: "/good/"
          pathType: "Prefix"
```

**Expected outcome**

* the bad ingress is not processes and the respective app not accessible through ALB
* the good ingress is processed and the respective app accessible through ALB

**Environment**

* AWS Load Balancer controller version 2.3.0 (also reproduced with 2.2.4)
* Kubernetes version 1.19.13
* Using EKS (yes/no), if so version? 1.19.13-eks-8df270

**Additional Context**:

The load balancer controller continuously shows that the bad ingress is a problem. But we never see anything about the good one:

```
{"level":"info","ts":1636511590.5186014,"logger":"controllers.ingress","msg":"Auto Create SG","LB SGs":[{"$ref":"#/resources/AWS::EC2::SecurityGroup/ManagedLBSecurityGroup/status/groupID"},"sg-031403dd542bca665"],"backend SG":"sg-031403dd542bca665"}
{"level":"error","ts":1636511590.518824,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"game-2048","namespace":"","error":"ingress: game-2048/ingress-2048: prefix path shouldn't contain wildcards: /bad/*"}
```

If we delete the bad ingress:

```
kubectl -n aburdajewicz delete ingress bad
```

Once the bad ingress is deleted, the controller finally process the other ingresses:

```
{"level":"info","ts":1636511819.469284,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048\",\"resources\":{\"AWS::EC2::SecurityGroup\":{\"ManagedLBSecurityGroup\":{\"spec\":{\"groupName\":\"k8s-game2048-a45d26ea19\",\"description\":\"[k8s] Managed SecurityGroup for LoadBalancer\",\"ingress\":[{\"ipProtocol\":\"tcp\",\"fromPort\":80,\"toPort\":80,\"ipRanges\":[{\"cidrIP\":\"0.0.0.0/0\"}]}]}}},\"AWS::ElasticLoadBalancingV2::Listener\":{\"80\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":80,\"protocol\":\"HTTP\",\"defaultActions\":[{\"type\":\"fixed-response\",\"fixedResponseConfig\":{\"contentType\":\"text/plain\",\"statusCode\":\"404\"}}]}}},\"AWS::ElasticLoadBalancingV2::ListenerRule\":{\"80:1\":{\"spec\":{\"listenerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::Listener/80/status/listenerARN\"},\"priority\":1,\"actions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/game-2048/good-2048-good-2048:80/status/targetGroupARN\"}}]}}],\"conditions\":[{\"field\":\"host-header\",\"hostHeaderConfig\":{\"values\":[\"core-eks.aburdajewicz.support.beescloud.com\"]}},{\"field\":\"path-pattern\",\"pathPatternConfig\":{\"values\":[\"/good\",\"/good/*\"]}}]}}},\"AWS::ElasticLoadBalancingV2::LoadBalancer\":{\"LoadBalancer\":{\"spec\":{\"name\":\"k8s-game2048-e747fac4b0\",\"type\":\"application\",\"scheme\":\"internet-facing\",\"ipAddressType\":\"ipv4\",\"subnetMapping\":[{\"subnetID\":\"subnet-0230b07cf9c3ef4b9\"},{\"subnetID\":\"subnet-0527dfd8a1c6fa004\"},{\"subnetID\":\"subnet-06cd5c927fc4f33d4\"}],\"securityGroups\":[{\"$ref\":\"#/resources/AWS::EC2::SecurityGroup/ManagedLBSecurityGroup/status/groupID\"},\"sg-031403dd542bca665\"]}}},\"AWS::ElasticLoadBalancingV2::TargetGroup\":{\"game-2048/good-2048-good-2048:80\":{\"spec\":{\"name\":\"k8s-game2048-good2048-caa366868d\",\"targetType\":\"ip\",\"port\":80,\"protocol\":\"HTTP\",\"protocolVersion\":\"HTTP1\",\"ipAddressType\":\"ipv4\",\"healthCheckConfig\":{\"port\":\"traffic-port\",\"protocol\":\"HTTP\",\"path\":\"/\",\"matcher\":{\"httpCode\":\"200\"},\"intervalSeconds\":15,\"timeoutSeconds\":5,\"healthyThresholdCount\":2,\"unhealthyThresholdCount\":2}}}},\"K8S::ElasticLoadBalancingV2::TargetGroupBinding\":{\"game-2048/good-2048-good-2048:80\":{\"spec\":{\"template\":{\"metadata\":{\"name\":\"k8s-game2048-good2048-caa366868d\",\"namespace\":\"game-2048\",\"creationTimestamp\":null},\"spec\":{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/game-2048/good-2048-good-2048:80/status/targetGroupARN\"},\"targetType\":\"ip\",\"serviceRef\":{\"name\":\"good-2048\",\"port\":80},\"networking\":{\"ingress\":[{\"from\":[{\"securityGroup\":{\"groupID\":\"sg-031403dd542bca665\"}}],\"ports\":[{\"protocol\":\"TCP\"}]}]},\"ipAddressType\":\"ipv4\"}}}}}}}"}
{"level":"info","ts":1636511819.7015443,"logger":"controllers.ingress","msg":"creating securityGroup","resourceID":"ManagedLBSecurityGroup"}
{"level":"info","ts":1636511819.872457,"logger":"controllers.ingress","msg":"created securityGroup","resourceID":"ManagedLBSecurityGroup","securityGroupID":"sg-013e985c3c80b11bf"}
{"level":"info","ts":1636511820.115932,"msg":"authorizing securityGroup ingress","securityGroupID":"sg-013e985c3c80b11bf","permission":[{"FromPort":80,"IpProtocol":"tcp","IpRanges":[{"CidrIp":"0.0.0.0/0","Description":""}],"Ipv6Ranges":null,"PrefixListIds":null,"ToPort":80,"UserIdGroupPairs":null}]}
{"level":"info","ts":1636511820.3501003,"msg":"authorized securityGroup ingress","securityGroupID":"sg-013e985c3c80b11bf"}
{"level":"info","ts":1636511820.4180794,"logger":"controllers.ingress","msg":"creating targetGroup","stackID":"game-2048","resourceID":"game-2048/good-2048-good-2048:80"}
{"level":"info","ts":1636511820.933209,"logger":"controllers.ingress","msg":"created targetGroup","stackID":"game-2048","resourceID":"game-2048/good-2048-good-2048:80","arn":"arn:aws:elasticloadbalancing:us-east-1:123456789123:targetgroup/k8s-game2048-good2048-caa366868d/1e1b3dc6abdd9702"}
{"level":"info","ts":1636511821.0080144,"logger":"controllers.ingress","msg":"creating loadBalancer","stackID":"game-2048","resourceID":"LoadBalancer"}
{"level":"info","ts":1636511821.6949315,"logger":"controllers.ingress","msg":"created loadBalancer","stackID":"game-2048","resourceID":"LoadBalancer","arn":"arn:aws:elasticloadbalancing:us-east-1:123456789123:loadbalancer/app/k8s-game2048-e747fac4b0/2ccf54915c873aec"}
{"level":"info","ts":1636511821.7394106,"logger":"controllers.ingress","msg":"creating listener","stackID":"game-2048","resourceID":"80"}
{"level":"info","ts":1636511821.8082771,"logger":"controllers.ingress","msg":"created listener","stackID":"game-2048","resourceID":"80","arn":"arn:aws:elasticloadbalancing:us-east-1:123456789123:listener/app/k8s-game2048-e747fac4b0/2ccf54915c873aec/6e21f3f8b7382771"}
{"level":"info","ts":1636511821.8457499,"logger":"controllers.ingress","msg":"creating listener rule","stackID":"game-2048","resourceID":"80:1"}
{"level":"info","ts":1636511821.9592113,"logger":"controllers.ingress","msg":"created listener rule","stackID":"game-2048","resourceID":"80:1","arn":"arn:aws:elasticloadbalancing:us-east-1:123456789123:listener-rule/app/k8s-game2048-e747fac4b0/2ccf54915c873aec/6e21f3f8b7382771/7d0c4695d8975c7f"}
{"level":"info","ts":1636511821.959493,"logger":"controllers.ingress","msg":"creating targetGroupBinding","stackID":"game-2048","resourceID":"game-2048/good-2048-good-2048:80"}
{"level":"info","ts":1636511822.0012984,"logger":"controllers.ingress","msg":"created targetGroupBinding","stackID":"game-2048","resourceID":"game-2048/good-2048-good-2048:80","targetGroupBinding":{"namespace":"game-2048","name":"k8s-game2048-good2048-caa366868d"}}
{"level":"info","ts":1636511822.0423431,"msg":"registering targets","arn":"arn:aws:elasticloadbalancing:us-east-1:123456789123:targetgroup/k8s-game2048-good2048-caa366868d/1e1b3dc6abdd9702","targets":[{"AvailabilityZone":null,"Id":"10.240.0.122","Port":80},{"AvailabilityZone":null,"Id":"10.240.0.144","Port":80},{"AvailabilityZone":null,"Id":"10.240.0.15","Port":80},{"AvailabilityZone":null,"Id":"10.240.0.61","Port":80},{"AvailabilityZone":null,"Id":"10.240.0.91","Port":80}]}
{"level":"info","ts":1636511822.1611001,"logger":"controllers.ingress","msg":"successfully deployed model","ingressGroup":"game-2048"}
{"level":"info","ts":1636511822.4437633,"msg":"registered targets","arn":"arn:aws:elasticloadbalancing:us-east-1:123456789123:targetgroup/k8s-game2048-good2048-caa366868d/1e1b3dc6abdd9702"}
```

Note: To be able to delete the bad ingress, **we sometimes need to remove the finlizers** first - I believe this is necessary if resources have already been created / managed for the same group. For example if you create the good ingress first, then the bad one, then you will not be able to delete the good ingress because it has finalizers and the Controller does not process its removal...

```
kubectl -n aburdajewicz patch ingress bad -p '{"metadata":{"finalizers":[]}}' --type=merge
```
