### ISSUE TITLE
Models being built but then the controller stops

### ISSUE THREAD

**Issue by kevin-lindsay-1** [kubernetes-sigs/aws-load-balancer-controller#2355]
**Describe the bug**

I'm creating an ingress gateway via istio's ingress gateway helm chart v1.10.3 with a container image of 1.10.3, which shouldn't really matter, but my issue that I discovered is that if I create the service with the following settings:
```yaml
api: v1
kind: Service
metadata:
  name: istio-ingressgateway 
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
```

Which appears to be the preferred way according to the docs, it literally doesn't do anything at all.

However, if I take that config and simply change the following line:
```yaml
service.beta.kubernetes.io/aws-load-balancer-type: nlb
```

It immediately spins up an NLB for me, even though I don't see a line of docs stating that I should do that.

This is pretty frustrating. I'm using EKS, on latest everything, using an AWS toolchain, following the official docs, and it doesn't work if I follow the instructions, but if I don't, it seems to. 🤦 

**Steps to reproduce**

Try to follow the docs?

**Expected outcome**

I expect an NLB to be created per the docs.

**Environment**

* AWS Load Balancer controller version
helm chart: v1.3.2
image: v2.3.0, and tried 2.2.4

* Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Using EKS (yes/no), if so version?
yes, 1.21

**Additional Context**:

This was working in the past, and after deleting and recreating the same resources in helm, it stopped working, and required this alternate syntax. I can only imagine that the `nlb` annotation is picked up by EKS or something, but at this point I'm unsure, and the logs are pretty sparse, even on debug mode.
