### ISSUE TITLE
Not able to override NLB healthcheck port

### ISSUE THREAD

**Issue by Yitaek** [kubernetes-sigs/aws-load-balancer-controller#2372]
**Describe the bug**
Specifying the healthcheck port in the annotations of the LB svc type does not override the healthcheck port (always defaults to "target-port")

**Steps to reproduce**

Create a svc and set healthcheck port:

```
apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: test
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "31002"
...
```

**Expected outcome**
I expect the healthcheck port to be set to 31002 instead of target port. Port 31002 is a nodeport that is open. 

**Environment**

* AWS Load Balancer controller version: 2.3.0 (helm chart 1.3.2) 
* Kubernetes version: 1.19
* Using EKS (yes/no), if so version?: yes, 1.19

**Comment by kishorj** [comment]
@Yitaek, could you share the complete list of annotations you've specified on the service?

**Comment by Yitaek** [comment]
@kishorj yup here's the entire file: i have nodeport 31002 open in another service (i want to expose port 21000 but have healthcheck ping on port 31002) 

```
apiVersion: v1
kind: Service
metadata:
  name: test
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "31002"
spec:
  type: LoadBalancer
  ports:
    - port: 21000
      targetPort: 21000
      name: test-port
  selector:
    app: my-app
```
