### ISSUE TITLE
Cannot assign ELBSEcurityPolicy-TLS13-1-2-2021-06 to TLS Listener on NLB

### ISSUE THREAD

**Issue by kbelosevic** [kubernetes-sigs/aws-load-balancer-controller#2384]
**Describe the bug**
aws-load-balancer-controller cannot assign `ELBSEcurityPolicy-TLS13-1-2-2021-06` to the listener:
(needed for compliance reasons)

```
{"level":"error","ts":1638124275.2637324,"logger":"controller-runtime.manager.controller.service","msg":"Reconciler error","name":"ingress-nginx-controller","namespace":"ingress-nginx","error":"SSLPolicyNotFound: SSL policy 'ELBSEcurityPolicy-TLS13-1-2-2021-06' not found\n\tstatus code: 400, request id: c36ab801-2694-43e7-8b87-6b78ee1bbbfe"}
```

While when I go to AWS Console, I can change/create same listener, with same target group with `ELBSEcurityPolicy-TLS13-1-2-2021-06`

If this is left empty, or older TLS12 policy used, all works well.
Also, above will partially deploy resources, only TLS listener won't get deployed.

**Steps to reproduce**
aws-load-balancer-controller + ingress-nginx

Configuration:

ingress-nginx:
```
        annotations:
          # AWS resource configs
          service.beta.kubernetes.io/aws-load-balancer-name: "nlb-name"
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Some=tags,SomeOther=tags"
          # LB configs
          service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
          service.beta.kubernetes.io/aws-load-balancer-type: "external" # nlb
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/load-balancer-source-ranges: "10.0.0.0/16"
          # Listeners config
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "${cert_arn}" # Issued by AWS
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
          service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSEcurityPolicy-TLS13-1-2-2021-06
          # Target-group configs - enable proxy protocol v2 & preserve IP
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
          service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
          service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: "preserve_client_ip.enabled=true"
```

aws-load-balancer-controller:
```
Helm chart version 1.3.2
controller version: 2.3.0

No specific config other than specifying VPC_ID, EKS Cluster name, region & IAM role to assume eks.amazonaws.com/role-arn: foo_arn
```

**Expected outcome**
aws-load-balancer-controller does not error out when trying to assigned TLS13 policy

**Environment**

* AWS Load Balancer controller version `v2.3.0`
* Kubernetes version `v1.21`
* Using EKS (yes/no), if so version? Yes `v1.21` (latest available at current date)
