### ISSUE TITLE
Annotations in values.yaml

### ISSUE THREAD

**Issue by csaba-g** [kubernetes-sigs/aws-load-balancer-controller#2399]
**Is your feature request related to a problem?**
We would like to define the alb.ingress.* annotations for the k8s Ingress as a variable in values.yaml. Is that possible?

**Describe the solution you'd like**
The **ingress.yaml** file will have variables, like:
``` yaml
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn }}
    alb.ingress.kubernetes.io/subnets: {{ .Values.ingress.subnet }}
```

**values.yaml**
``` yaml
ingress:
  certificateArn: arn:aws:iam::1234567890:server-certificate/myCertificate
  subnet: subnet-abcde123456789, subnet-xyz987654321
```

**Describe alternatives you've considered**
Or is there any other suggested way if we have a multi-cluster setup? How to define the Ingress annotations for different clusters in Helm chart?

Thank you
