### ISSUE TITLE
Is there a way to route same url but different port in the same alb by IngressGroup?

### ISSUE THREAD

**Issue by wttat** [kubernetes-sigs/aws-load-balancer-controller#2406]
For example, I got two apps deployed in eks.
use abc.com:8888 to access app1, abc.com:9999 to access app2. both needs https

By this document, only route by path like abc.com/v1 and abc.com/v2 is supported .
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/ingress/annotations/#traffic-listening

could you please give an example for my case?
or how should I do this gracefully ? create two alb by ingress and put a nlb behind them?

**Comment by kishorj** [comment]
@wttat, you could create two ingresses one ingress using port 8888 and another using 9999, then group them together into the same ingress group so that a single ALB gets provisioned.

**Comment by wttat** [comment]
> @wttat, you could create two ingresses one ingress using port 8888 and another using 9999, then group them together into the same ingress group so that a single ALB gets provisioned.

i am not familiar with ingress group setting , could you please give me a example for that , it would be really helpful, thanks

**Comment by wttat** [comment]
I tried like this 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-2048
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048
    spec:
      containers:
      - image: alexwhen/docker-2048
        imagePullPolicy: Always
        name: app-2048
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-2048
spec:
  ports:
    - port: 33333
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-2048
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-nginx
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-nginx
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.19.6
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  ports:
    - port: 44444
      targetPort: 8081
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "ingress-2048"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: "share-alb"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 33334}, {"HTTPS": 33335}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:xx:certificate/xx
  labels:
    app: 2048-ingress
spec:
  rules:
    - http:
        paths: 
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-2048
                port:
                  number: 33333
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "ingress-nginx"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: "share-alb"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 44445}, {"HTTPS": 44446}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:xx:certificate/xx
  labels:
    app: nginx-ingress
spec:
  rules:
    - http:
        paths: 
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-nginx
                port:
                  number: 44444
```

but all four ports return 502 bad gateway, could anyone check this for me please?

**Comment by wttat** [comment]
turns out the container port should be set in 80
fixed
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-2048
spec:
  selector:
    matchLabels:
      app: app-2048
  replicas: 3
  template:
    metadata:
      labels:
        app: app-2048
    spec:
      containers:
      - image: alexwhen/docker-2048
        imagePullPolicy: Always
        name: app-2048
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-2048
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: app-2048
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
spec:
  selector:
    matchLabels:
      app: app-nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.19.6
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: app-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "ingress-2048"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: "share-alb"
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 33333}, {"HTTPS": 33334}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:xx:certificate/xx
  labels:
    app: 2048-ingress
spec:
  rules:
    - http:
        paths: 
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-2048
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "ingress-nginx"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: "share-alb"
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 55555}, {"HTTPS": 55556}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:xx:certificate/xx
  labels:
    app: nginx-ingress
spec:
  rules:
    - http:
        paths: 
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-nginx
                port:
                  number: 80
```
