### ISSUE TITLE
nginx ingress controller type nlb with static ip giving error "AllocationIdNotFound"

### ISSUE THREAD

**Issue by mhamzarazzaq97** [kubernetes-sigs/aws-load-balancer-controller#2412]
Hi,
I am creating nginx ingress controller of type nlb with static ips, but for static ips I am getting this error **`AllocationIdNotFound`**. Although this allocation id is valid and eip with this id is present in the same region. Here are the annotations that I am using with nginx ingress controller service
```
annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-xxxxxxxxxx, subnet-xxxxxxxxxx"
      service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-xxxxxxxxxx, eipalloc-xxxxxxxxxx"

```
If I comment service.beta.kubernetes.io/aws-load-balancer-eip-allocations annotation, load balancer gets created successfully but without eips.

What am I doing wrong here ?
