### ISSUE TITLE
Not Working!! restrict CIDR IP addresses for a LoadBalancer type

### ISSUE THREAD

**Issue by vmasule** [kubernetes-sigs/aws-load-balancer-controller#2419]
**Describe the bug**
A concise description of what the bug is.
I am using NLB with `nlb-target-type: ip`, I want to whitelist IP using `loadBalancerSourceRanges` but it seems there some issue with the AWS Load Balancer Controller as this feature is not working but it works for `nlb-target-type: instance`.

Make no mistake, I am also setting `preserve_client_ip.enabled=true` as per documentations and I could see the it is enabled on target group and SG Rule with whitelist IP range gets added successfully but I failed to access the application. I am currently whitelisting my ISP's public IP for testing which works fine when `nlb-target-type: instance`.

**Steps to reproduce**
You can run the sample Windows Container based k8s config below.

**Expected outcome**
After successful apply, I should be only able to access the application from `110.226.221.152/32` IP. 

* AWS Load Balancer controller version: 2.3.0
* Kubernetes version 1.21
* Using EKS (yes/no), if so version? Yes 1.21

**Additional Context**:

````
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-server-iis
  namespace: default
spec:
  selector:
    matchLabels:
      app: windows-server-iis
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: windows-server-iis
        tier: backend
        track: stable
    spec:
      containers:
        - name: windows-server-iis
          image: mcr.microsoft.com/windows/servercore:1809
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: IfNotPresent
          command:
            - powershell.exe
            - -command
            - "Add-WindowsFeature Web-Server; Invoke-WebRequest -UseBasicParsing -Uri 'https://dotnetbinaries.blob.core.windows.net/servicemonitor/2.0.1.6/ServiceMonitor.exe' -OutFile 'C:\\ServiceMonitor.exe'; echo '<html><body><br/><br/><marquee><H1>Hello EKS!!!<H1><marquee></body><html>' > C:\\inetpub\\wwwroot\\default.html; C:\\ServiceMonitor.exe 'w3svc'; "
      nodeSelector:
        kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: windows-server-iis-service
  namespace: default
  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: "external"
#    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
#    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "80"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-name: test-iis-server-lb
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: windows-server-iis
    tier: backend
    track: stable
#  sessionAffinity: None
  loadBalancerSourceRanges:
    - "110.226.221.152/32"
  type: LoadBalancer
````

AWS Load Balancer Controller Config

````
Name:                   aws-load-balancer-controller
Namespace:              kube-system
CreationTimestamp:      Thu, 04 Nov 2021 12:31:15 +0000
Labels:                 app.kubernetes.io/instance=aws-load-balancer-controller
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=aws-load-balancer-controller
                        app.kubernetes.io/version=v2.3.0
                        helm.sh/chart=aws-load-balancer-controller-1.3.2
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: aws-load-balancer-controller
                        meta.helm.sh/release-namespace: kube-system
Selector:               app.kubernetes.io/instance=aws-load-balancer-controller,app.kubernetes.io/name=aws-load-balancer-controller
Replicas:               2 desired | 2 updated | 2 total | 2 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/instance=aws-load-balancer-controller
                    app.kubernetes.io/name=aws-load-balancer-controller
  Annotations:      prometheus.io/port: 8080
                    prometheus.io/scrape: true
  Service Account:  aws-load-balancer-controller
  Containers:
   aws-load-balancer-controller:
    Image:       602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.3.0
    Ports:       9443/TCP, 8080/TCP
    Host Ports:  0/TCP, 0/TCP
    Command:
      /controller
    Args:
      --cluster-name=my-test-cluster
      --ingress-class=alb
      --disable-restricted-sg-rules=true
    Liveness:     http-get http://:61779/healthz delay=30s timeout=10s period=10s #success=1 #failure=2
    Environment:  <none>
    Mounts:
      /tmp/k8s-webhook-server/serving-certs from cert (ro)
  Volumes:
   cert:
    Type:               Secret (a volume populated by a Secret)
    SecretName:         aws-load-balancer-tls
    Optional:           false
  Priority Class Name:  system-cluster-critical
````

Instructions followed from here : [https://aws.amazon.com/premiumsupport/knowledge-center/eks-cidr-ip-address-loadbalancer/](url)
Please confirm whether this is a bug or I am missing something here.
