### ISSUE TITLE
controller does not set clientSecret correctly for auth-idp-oidc

### ISSUE THREAD

**Issue by TobiasLierzer** [kubernetes-sigs/aws-load-balancer-controller#2422]
**Describe the bug**
The clientSecret from an ingress secret is not set correctly on the AWS ALB Listener Rule for OIDC Auth with external IDP

**Steps to reproduce**
Deploy an ingress for the alb controller like:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloalbworld
  namespace: test-namespace
  annotations:
    external-dns.alpha.kubernetes.io/hostname: helloalbworld.acme.com
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-<id>,subnet-<id>,subnet-<id>
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:<accountid>:certificate/<certid>
    alb.ingress.kubernetes.io/auth-type: oidc
    alb.ingress.kubernetes.io/auth-idp-oidc: '{"issuer":"https://<idp>/auth/realms/<realm>","authorizationEndpoint":"https://l<idp>/auth/realms/<realm>/protocol/openid-connect/auth","tokenEndpoint":"https://l<idp>/auth/realms/<realm>/protocol/openid-connect/token","userInfoEndpoint":"https://l<idp>/auth/realms/<realm>/protocol/openid-connect/userinfo","secretName":"alb-secret"}'
spec:
  ingressClassName: alb
  rules:
  - host: helloalbworld.acme.com
    http:
      paths:
      - backend:
          service:
            name: helloworld
            port:
              number: 8080
        path: /
        pathType: Prefix
```
Deploy a k8s secret with
```
apiVersion: v1
kind: Secret
metadata:
  namespace: test-namespace
  name: alb-secret
data:
  clientID: <base64 client_id>
  clientSecret: <base64 client_secret>
```
Try to access the application.
-> AWS ALB returns http 561. IDP logs error "invalid_client_credentials"

**Expected outcome**
The clientSecret is set correctly on the ALB to work

**Environment**

* AWS Load Balancer controller version: v2.3.0
* Kubernetes version: 1.21.7
* Using EKS (yes/no): no

**Additional Context**:
When I update the clientSecret through the AWS Console, the OIDC Flow works perfectly fine.
IDP is Keycloak.
