### ISSUE TITLE
NLB created without registered targets

### ISSUE THREAD

**Issue by Throckmortra** [kubernetes-sigs/aws-load-balancer-controller#2432]
**Describe the bug**
When deploying an NLB with this controller for my consul cluster, the NLB is created, the target group is created, but there are no registered targets in the target group

**Steps to reproduce**
deploy a consul server cluster with the following helm chart:
```
global:
  datacenter: test
  acls:
    manageSystemACLs: false
    createReplicationToken: false

ui:
  enabled: true
  service:
    type: NodePort

server:
  replicas: 2
  bootstrapExpect: 2
  exposeGossipAndRPCPorts: true
  ports:
    serflan:
      port: 9301

client:
  enabled: false

controller:
  enabled: true
```

and attempt add NLB for this service with this manifest:

```
apiVersion: v1
kind: Service
metadata:
  name: consul-dev-ingress-8301
  namespace: consul
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: consul-dev-ingress-8301-nlb
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: consul-consul-server
  ports:
    - port: 9301
      targetPort: 9301
      protocol: TCP
```      

**Expected outcome**
NLB deploys as expected and serves consul serflan port 9301 

**Environment**
* AWS Load Balancer controller version - 2.3
* Kubernetes version - 1.21
* Using EKS (yes/no), if so version? yes, 1.21 (eks.4)

I understand that this could very well be due to issues with the helm chart but I would like some direction how to properly debug something like this
