### ISSUE TITLE
Application unreachable

### ISSUE THREAD

**Issue by d3p4rt** [kubernetes-sigs/aws-load-balancer-controller#2434]
Good morning everyone.
I have a problem with the ingress controller.
Three days ago I installed the latest version of the controller following the instructions here:
https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html

Then I installed the amazon vpc-cni plugin:
https://github.com/aws/amazon-vpc-cni-k8s

The problem is that when I try to access the application in the browser it times out (I have set the DNS to route53).

The balancer is correctly created:

- The three correct subnets are set.
- There are the two listeners (443 and 80)
- There are the two security groups that the controller sets by default

I have also checked the target group and _the health check is healty, the ip of the pod is correct and also the port_.

From AWS point of view everything seems to be correct.

Below is the ingress.yaml file I use:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my_name
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:certificate
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: my_subnet1, my_subnet2, my_subnet3
    alb.ingress.kubernetes.io/healthcheck-path: /test
  namespace: my-namespace
spec:
  rules:
    - host: myhostname
      http:
        paths:
          - backend:
              serviceName: my_service_name
              servicePort: 4001
            path: /
```

Below is the service I use (ClusterIp):
```
  ports:
    - name: http
      protocol: TCP
      port: 4001
      targetPort: 4001

```

EKS version: 1.19 

Please can you help me to understand how mail the controller is not working?

Thank you very much!
