### ISSUE TITLE
Fargate: NoCredentialProviders: no valid providers in chain.

### ISSUE THREAD

**Issue by dj-wasabi** [kubernetes-sigs/aws-load-balancer-controller#2437]
**Describe the bug**

Keep getting the error:
```
{"level":"error","ts":1640792367.3152826,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"echoserver","namespace":"<_NAMESPACE_>","error":"NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"}
```

**Steps to reproduce**

Open the page: https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller

Copied the content of JSON on "Setup IAM manually" and deployed with Terraform a Policy and attached it to the Fargate Profiles (And even for the EKS Cluster).

Executed the command:
```
helm repo add eks https://aws.github.io/eks-charts
helm repo update
kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"
```

Install the AWS Load Balancer controller, if not using iamserviceaccount
```helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=<_CLUSTER_NAME_> --set ingressClass=alb --set region=eu-central-1 --set vpcId=vpc-ID```

As found on various issues here (and on ww) I had to apply the region and vpcid, because of Fargate.

Applied the following yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: <_NAMESPACE_>
spec:
  selector:
    matchLabels:
      app: echoserver
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: gcr.io/google_containers/echoserver:1.4
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: <_NAMESPACE_>
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: echoserver
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver
  namespace: <_NAMESPACE_>
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
spec:
  rules:
    - host: echoserver.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: echoserver
              servicePort: 80
```

**Expected outcome**
After deployment I would expect to have an ALB created.

**Environment**

* AWS Load Balancer controller version: 2.3.1
* Kubernetes version 1.21
* Using EKS (yes/no), if so version? Yes, 1.21 (Platform version eks.4)

**Additional Context**:
All infra deployed with Terraform.
