### ISSUE TITLE
ssl-redirect not found in alb ingress

### ISSUE THREAD

**Issue by rdeteix** [kubernetes-sigs/aws-load-balancer-controller#2439]
**Describe the bug**
I've created an ingress following the grpc example and I've got `error: endpoints "ssl-redirect" not found`

**Steps to reproduce**

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: *****
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=3600
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    meta.helm.sh/release-name: airflow-dev
    meta.helm.sh/release-namespace: dev
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
        path: /*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: airflow-dev-webserver
            port:
              name: airflow-ui
        path: /dev/*
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - hostname: *****
```

I've got :

```
Rules:
  Host        Path  Backends
  ----        ----  --------
  *
              /*       ssl-redirect:use-annotation (<error: endpoints "ssl-redirect" not found>)
              /dev/*   airflow-dev-webserver:airflow-ui (20.0.170.226:8080)
```

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version: v2.3.1
* Kubernetes version v1.21
* Using EKS (yes/no), if so version? yes

**Additional Context**:

**Comment by kishorj** [comment]
@rdeteix, we've simplified the ssl-redirect configuration via annotation `alb.ingress.kubernetes.io/ssl-redirect` since v2.2.0 release of the controller. For details, please refer to the live docs - https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/tasks/ssl_redirect/

**Comment by rdeteix** [comment]
@kishorj thx
I've made the change:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: ***
    alb.ingress.kubernetes.io/group.name: airflow
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    external-dns.alpha.kubernetes.io/hostname: ***    kubernetes.io/ingress.class: alb
  name: airflow-dev-airflow-ingress
  namespace: dev
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: airflow-dev-webserver
            port:
              name: airflow-ui
        path: /dev/*
        pathType: ImplementationSpecific
```
and my service looks like this :
```
Name:              airflow-dev-webserver
Namespace:         dev
Selector:          component=webserver,release=airflow-dev,tier=airflow
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.100.206.220
IPs:               10.100.206.220
Port:              airflow-ui  8080/TCP
TargetPort:        8080/TCP
Endpoints:         20.0.181.145:8080
Session Affinity:  None
Events:            <none>
```

The ingress doesn't give me any address.
Have the fields `alb.ingress.kubernetes.io/scheme` and `target-type` disappeared ?
Is it because of the port 8080 ?
