### ISSUE TITLE
Unable to discover at least one subnet error

### ISSUE THREAD

**Issue by dalgibbard** [kubernetes-sigs/aws-load-balancer-controller#2446]
**Describe the bug**
Running an EKS Cluster with Managed Node Groups, but a custom AMI. When attempting to deploy an NLB via a k8s Service with the AWS Load Balancer Controller, I'm getting the following error from the LBC:
```
{"level":"error","ts":1641491044.4881954,"logger":"controller-runtime.manager.controller.service","msg":"Reconciler error","name":"nginx","namespace":"myapp","error":"unable to discover at least one subnet"}
```

I'm passing both the ```vpcId``` and ```region``` params to the Helm deployment of LBC, and the VPC and Subnets are tagged appropriately:
```
$ aws ec2 describe-subnets --filters "Name=tag:kubernetes.io/cluster/myclustername,Values=shared" "Name=tag:kubernetes.io/role/internal-elb,Values=1" | jq '.Subnets | map(.SubnetId)'
[
  "subnet-09<SNIP>86",
  "subnet-0a<SNIP>f6",
  "subnet-0a<SNIP>82"
]
```

* Confirmed that this VPC, and subnets listed above are the same ones used by the EKS Nodes and the AWS LBC pods (host networking enabled due to Calico CNI usage for pods)
* Confirmed that the cluster name passed to the LBC deployment is the same as the EKS Cluster name, and tags on the VPC/Subnets

Example failing deployment below.

**Steps to reproduce**

* EKS Cluster with Managed Node Groups + Custom AMI (based off the Amazon-provided Ubuntu-20.04 with minor changes)
* One NodeGroup per-AZ, across three AZs (Three NodeGroups total)
* Deploy AWS LBC using Helm, passing the VPC ID and Region params in too.
* Deploy simple example failing deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: myapp
  labels:
    app: "nginx"
    version: "1"
spec:
  selector:
    matchLabels:
      app: "nginx"
      version: "1"
  replicas: 1
  template:
    metadata:
      labels:
        app: "nginx"
        version: "1"
    spec:
      containers:
      - name: "nginx"
        image: "public.ecr.aws/nginx/nginx:1.21"
        ports:
        - containerPort: 80
          name: nginxhttp
        resources:
          requests:
            memory: "0.1Gi"
            cpu: 0.5
          limits:
            memory: "0.5Gi"
            cpu: 1.0
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: myapp
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
    version: "1"
  type: LoadBalancer
```

**Expected outcome**
An NLB Loadbalancer should be deployed successfully, with auto-discovered subnet detection.

**Environment**

* AWS Load Balancer controller version: ```v2.3.0```
* Kubernetes version: ```v1.21.2-eks-06eac09```
* Using EKS (yes/no), if so version? Yes (above)

**Additional Context**:
I've tried tagging the Subnets/VPC with both the ```internal-elb``` and ```elb``` tags, but no effect. Removing the passed in ```vpcId``` has no effect either.
Service event logs are:
```
Events:
Type     Reason                Age                  From                Message
----     ------                ----                 ----                -------
Normal   EnsuringLoadBalancer  12m                  service-controller  Ensuring load balancer
Warning  FailedBuildModel      2m1s (x18 over 12m)  service             Failed build model due to unable to discover at least one subnet
```

Happy to assist with debugging this/providing more information as possible; and can also open a AWS Enterprise Support case to share more specific information securely etc
