### ISSUE TITLE
Certificate Default Listener is not matching the first host. 

### ISSUE THREAD

**Issue by abebars** [kubernetes-sigs/aws-load-balancer-controller#2451]
**Describe the bug**
I am not sure if this behavior is expected, However, if the `alb.ingress.kubernetes.io/certificate-arn` is not specified, I am assuming the first host that has a matched certificate will be the default one but this wasn't the case. It's usually the first however I ran into a couple of cases where the order wasn't accounted for 

**Steps to reproduce**
the ingress with annotation as the following 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: host1.example.com
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=logs_bucket,access_logs.s3.prefix=test
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/healthcheck-path: /healthcheck
spec:
  rules:
    - host: host1.example.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: ${SERVICE_NAME}
              servicePort: 80
    - host: host2.example.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: ${SERVICE_NAME}
              servicePort: 80              
```
**Expected outcome**
I am assuming the default certificate will be for host1.example.com because it's the first rule and it's also defined in the hostname alb annotation but that is not guaranteed.

**Environment**

* AWS Load Balancer controller version: 2.2
* Kubernetes version: 1.20
* Using EKS (yes/no), if so version? Yes, eks.2

**Additional Context**:
