### ISSUE TITLE
Ingress rules do not get sorted correctly

### ISSUE THREAD

**Issue by przemolb** [kubernetes-sigs/aws-load-balancer-controller#2458]
We are using LB controller 2.3 + the latest EKS (1.21) and the following LB definition to try to get our app's metrics:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metrics-test
  namespace: myns
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: metrics-test
    alb.ingress.kubernetes.io/group.name: metrics-test
    alb.ingress.kubernetes.io/tags: Name=ingress-for-metrics-test
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
    - http:
        paths:
         - path: /
           pathType: Prefix
           backend:
             service:
                name: metrics-service
                port:
                  number: 443
         - path: /some/path/
           pathType: Prefix
           backend:
             service:
                name: metrics-service
                port:
                  number: 443
```
The following works:
```
curl http://x.x.x.x/metrics
```
but this one doesn't
```
curl http://x.x.x.x/some/path/metrics
```
Our metrics app doesn't recognise the `/some/path` - is there any way I can get rid of it using LB controller annotations ? If not then would chaining LB controller + nginx controller help ?
