### ISSUE TITLE
Ingress group merging with ssl redirect

### ISSUE THREAD

**Issue by adriandeac** [kubernetes-sigs/aws-load-balancer-controller#2467]
**Describe the bug**
I'm trying to use the IngressGroup feature in order to support multiple ingresses in different namespaces serviced by the same ALB but it looks the merge does not work if I also use the SSL redirect feature.

**Steps to reproduce**
I have the following two ingress definitions that I deploy in two different namespaces (some parts redacted):
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xxx
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: <public subnets in vpc>
    alb.ingress.kubernetes.io/security-groups: <sg>
    alb.ingress.kubernetes.io/certificate-arn: <cert arn>
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=30
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/healthcheck-path: '/up'
    alb.ingress.kubernetes.io/group.name: group-name
    # make sure the '/' rule for webserver is the last rule
    alb.ingress.kubernetes.io/group.order: '500'
  labels:
    app: xxx
spec:
  rules:
  # SSL redirect
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation

  - http:
      paths:
      - path: /path1
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 80

  # Fall back to main webserver
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webserver
            port:
              number: 80
```
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xxxx
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=30
    alb.ingress.kubernetes.io/healthcheck-path: '/up'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/group.name: group-name
  labels:
    app: xxxx
spec:
  rules:
  # SSL redirect
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation

  - http:
      paths:
      - path: /path2
        pathType: Prefix
        backend:
          service:
            name: service2
            port:
              number: 80
```
After deployment I check the created ALB resource in the AWS console.
There is no rule created for `/path2` for the listener on port 443 (second ingress) only the ones from the first ingress.
If I omit the SSL rule from the second ingress then it creates an ALB listener rule for the second ingress path but I need SSL redirect for that one as well, and this would only create a rule for the listener on port 80.

**Expected outcome**
I expect a rule to be created for the listener on port 443 with `/path2`

**Environment**

* AWS Load Balancer controller version: 2.2.0
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version? yes, eks.2

**Additional Context**:
I looked at the controller logs and the resulting built model that is logged does not contain a listener entry for `/path2`.
The reconcile is successful.
