### ISSUE TITLE
controller silently ignores ingress merging if a listen port is not declared

### ISSUE THREAD

**Issue by zswanson** [kubernetes-sigs/aws-load-balancer-controller#2471]
**Describe the bug**
When using multiple ingresses with a shared `group.name` **and** the first ingress declares multiple listen-ports (ie, http:80 and https: 443), any subsequent ingress appears to need the listen-ports annotation as well, to specify which listener the rule should go on. That all seems logical once i figured it out, but the controller will **silently ignore** the ingress in question if that annotation is not present. The controller will see the new ingress and  'rebuild' the model but will not include it as a rule, will not create a TargetGroup, and will not log any sort of warning or error to the operator. 

**Steps to reproduce**
1. Deploy the controller and some notional deployment/service for an application
2. Create a 'base'  ingress with 2 listen-ports
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alb-ingress-demo-1
  annotations:
    # use declared ingress group.name
    alb.ingress.kubernetes.io/group.name: myorg-myteam
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: >
      '{"Type":"redirect", "RedirectConfig":{"Protocol":"HTTPS", "Port":"443", "StatusCode":"HTTP_301"}}'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/actions.default-404-rule: >
      {"type":"fixed-response", "fixedResponseConfig":{"contentType":"text/plain", "statusCode":"404", "messageBody":"404 not found"}}
spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: default-404-rule
      port:
        name: use-annotation
```
3. Observe that the controller creates an ALB and logs that it has reconciled the model with the default 404 rule and the http to https redirect rule.
4. Create a second ingress that adds a route to a service backend but does NOT specify listen-ports annotation
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alb-ingress-demo-2
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: myorg-myteam
    alb.ingress.kubernetes.io/group.order: '1'

spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /whatever/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: demo-service
                port:
                  number: 80
```
5. Observe the logs of the controller; it will log that it has reconciled the model again but there will be no change from the previous model output. If you inspect the ALB listeners, no rule is present for this new ingress, nor is there a target group.

**Expected outcome**
A concise description of what you expected to happen.

If the controller cannot reconcile an Ingress to a Listener it should log an error/warning.

Documentation should specify that the listen.port annotation is required for shared ingress groups that have multiple port listeners defined.

**Environment**

* AWS Load Balancer controller version 2.3.1
* Kubernetes version 1.21
* Using EKS (yes/no), if so version? 1.21

**Additional Context**:
