### ISSUE TITLE
error: ingress: unable to find port 8080 on service api

### ISSUE THREAD

**Issue by dsaydon90** [kubernetes-sigs/aws-load-balancer-controller#2474]
**Describe the bug**
I have a pod which listen to 8080 but my service is listen to 80

service:
```
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
    component: "api"
    release: RELEASE-NAME
    chart: "api-1.0.0"
spec:
  type: ClusterIP
  selector:
    app: api
    release: RELEASE-NAME
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: api
      appProtocol: "http"
```

ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  labels:
    app: api
    component: "api"
    release: RELEASE-NAME
    chart: "api-1.0.0"
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:##############:certificate/###########
    alb.ingress.kubernetes.io/group.name: prod-api
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "10"
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-port: "80"
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=1800
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: ##########
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/subnets: ##########
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "8"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=25,load_balancing.algorithm.type=least_outstanding_requests
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
spec:
  rules:
  - host: "api.bla.com"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: api
            port:
              number: 80
```

all of my targets are down
![image](https://user-images.githubusercontent.com/22152786/150762217-48632d84-f083-401f-85bb-f4a6d3bafd96.png)

![image](https://user-images.githubusercontent.com/22152786/150763019-5484c284-a2ca-4e49-bb52-55c08bd067b9.png)

If I'm changing the annotation
from: `alb.ingress.kubernetes.io/healthcheck-port: "80"`
to: `alb.ingress.kubernetes.io/healthcheck-port: "8080"`

I'm getting the error
```
{"level":"error","ts":1643017978.5487103,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"prod-api,"namespace":"","error":"ingress: api: unable to find port 8080 on service api"}

```
If I'm changing the port manually from the AWS web console, it will be become green & healthy again

![image](https://user-images.githubusercontent.com/22152786/150763095-ebb28980-c203-4990-9401-210383239179.png)

**Environment**
EKS: 1.21
aws-load-balancer-controller: `602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.3.1`

**Comment by kishorj** [comment]
@dsaydon90, what happens when you don't specify the `alb.ingress.kubernetes.io/healthcheck-port` annotation on the ingress? If possible, could you email your controller logs to k8s-alb-controller-triage AT amazon.com?

**Comment by dsaydon90** [comment]
Hi @kishorj , when I use the annotation `alb.ingress.kubernetes.io/healthcheck-port: traffic-port` (which is the default) it's working as expected, and it will use the right health check port (in my case `8080`)

**Comment by haouc** [comment]
Hi @dsaydon90, I was trying to reproduce the issue but my target health check didn't have problem with various settings in ingress annotations:
`alb.ingress.kubernetes.io/healthcheck-port: "traffic-port"`
`alb.ingress.kubernetes.io/healthcheck-port: "8080"`
My service has ports configured as:
```
ports:
    - port: 80
       targetPort: 8080
       protocol: TCP
type: NodePort
```
My containers have port opened as:
```
ports:
- containerPort: 8080
```
Can you please check if you can access the health-check endpoint when the port check fails? If you don't mind, you can also send related logs to the email that Kishor mentioned in [his comment](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2474#issuecomment-1020440547). Thanks.
