### ISSUE TITLE
HTTP and gRPC ingresses inside single ingress group

### ISSUE THREAD

**Issue by christopher-wong** [kubernetes-sigs/aws-load-balancer-controller#2485]
**Describe the bug**
Our understanding is that ingress groups can be used to expose multiple different services on different ports using the same ALB. We have two backend services, one HTTP,and one GRPC that we'd like to expose with a single ALB on different ports.

The GRPC ingress is created correctly, but when the HTTP ingress is created we get the following error:

```bash
{"level":"error","ts":1643385787.915583,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"myapi-alb-group","namespace":"","error":"ValidationError: Health check matcher GRPC code '200' must be within '0-99' inclusive\n\tstatus code: 400, request id: b99ee8c1-b788-4253-9712-0960cdbc9793"} 
```

This seems to indicate the second ingress is getting created with an incorrect `alb.ingress.kubernetes.io/backend-protocol-version:` even though we explicitly set it to HTTP and an HTTP status code (see below).

**Steps to reproduce**
See manifests below.

**Expected outcome**
We expect to be able to create an ingress group with ingresses that have different backend protocol versions.

**Environment**

* 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.3.1
* 1.21
* EKS 1.21

**Additional Context**:

ingress.yaml
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-port: "traffic-port"
    alb.ingress.kubernetes.io/healthcheck-path: "/grpc.health.v1.Health/Check"
    alb.ingress.kubernetes.io/success-codes: "0"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '10'
    alb.ingress.kubernetes.io/security-groups: sg-0ad9500bd21c1966b, api_public_main_sg, api_worker_side_sg
    alb.ingress.kubernetes.io/subnets: subnet-001084dcc1a63666f, subnet-07cdae5c6451bfdc1, subnet-0714483a6639e3270
    alb.ingress.kubernetes.io/group.name: myapi-alb-group
  labels:
    app: myapi
    release: alpha
  name: myapi-alpha-grpc
  namespace: myapi
spec:
  rules:
  - host: service.myapi.com
    http:
      paths:
      - backend:
          service:
            name: myapi-alpha
            port:
              number: 90
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":8443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/security-groups: sg-0ad9500bd21c1966b, api_public_main_sg, api_worker_side_sg
    alb.ingress.kubernetes.io/subnets: subnet-001084dcc1a63666f, subnet-07cdae5c6451bfdc1, subnet-0714483a6639e3270
    alb.ingress.kubernetes.io/group.name: myapi-alb-group
  labels:
    app: myapi
    release: alpha
  name: myapi-alpha-http
  namespace: myapi
spec:
  rules:
  - host: service.myapi.com
    http:
      paths:
      - backend:
          service:
            name: myapi-alpha
            port:
              number: 80
        path: /
        pathType: Prefix
```

service.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: myapi-alpha
  namespace: myapi
spec:
  ports:
  - name: grpc
    protocol: TCP
    port: 90
    targetPort: 9090
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: myapi
    release: alpha
```

**Comment by kishorj** [comment]
@christopher-wong, would you be able to share the model generated by the controller for your ingress group? You could email it to k8s-alb-controller-triage AT amazon.com, if you prefer.

**Comment by oliviassss** [comment]
@christopher-wong Hi, I was trying to reproduce this issue with v2.3.1 using your manifest, but I didn't see the error mentioned above. Can you please email your controller logs to  k8s-alb-controller-triage AT amazon.com for further investigation? Thanks

**Comment by kishorj** [comment]
@christopher-wong, I'm closing the issue for now. If you have further concerns, feel free to reopen or create a new issue.

**Comment by cove** [comment]
I'm seeing this issue with controller v2.4.3, @kishorj @oliviassss can we reopen? I'll email the logs over.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
    alb.ingress.kubernetes.io/healthcheck-port: status-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: xxx
    alb.ingress.kubernetes.io/certificate-arn: xxx
  name: online-services-ingress
  namespace: istio-system
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: istio-ingressgateway
                port:
                  name: http2
            path: /
            pathType: Prefix

```
