### ISSUE TITLE
502 Errors when deployment scales up

### ISSUE THREAD

**Issue by tobrien-endpoint** [kubernetes-sigs/aws-load-balancer-controller#2490]
**Describe the bug**

We are getting a few 502 errors from the ALB when our deployments scale up with HPA.

**Steps to reproduce**

We are leveraging `alb.ingress.kubernetes.io/target-type: ip`, auto-injecting the readinessGates into our pods (we labeled the namespace), have readinessProbess, and have `alb.ingress.kubernetes.io/healthcheck-path` enabled. Our nodes are only under about 30% load during this time, pods pass readiness checks, and the readinessGate conditions added by the webhook pass.

**Expected outcome**

It's my understanding that with all of these enabled, we should not experience any 502 errors when pods are added to the deployment and registered into the target groups. 

**Environment**

* AWS Load Balancer controller version 2.1.8
* Kubernetes version 1.18
* Using EKS (yes/no), if so version?

**Additional Context**:

Ingress annotations:
```
    alb.ingress.kubernetes.io/actions.ssl-redirect: >-
      {"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port":
      "443", "StatusCode": "HTTP_301"}}
    alb.ingress.kubernetes.io/group.name: internal
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: 'routing.http2.enabled=true,idle_timeout.timeout_seconds=121'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/target-type: ip
```

Deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: test
spec:
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test
    spec:
      containers:
          image: -----------
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /service-information
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
```
