### ISSUE TITLE
Cannot set `Deregistration Delay` for NLB in IP mode

### ISSUE THREAD

**Issue by maruina** [kubernetes-sigs/aws-load-balancer-controller#2504]
**Describe the bug**
I'm trying to change the Deregistration Delay for an NLB created by the controller with IP targets. The annotation
```
service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: deregistration_delay.timeout_seconds=100
``` 
doesn't work and I still have the default value of 300.
Looking at https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/8409bd52953c21d0d3f0603a05300e9ee6e134a6/test/e2e/service/nlb_instance_target_test.go#L195 it seems this is only supported with instance targets.

**Steps to reproduce**
1. Create a SVC with IP targets using the annotation `service.beta.kubernetes.io/aws-load-balancer-type: ip`
2. Ensure the LB is created and for the target groups the default Deregistration Delay is 300s.
3. Add an annotation to the service to change the Deregistration Delay to a different value using the annotation `service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: deregistration_delay.timeout_seconds=100`
4. Observe the Deregistration Delay is still 300s.

**Expected outcome**
The Deregistration Delay should change according to the annotation.

**Environment**

* AWS Load Balancer controller version: v2.3.1
* Kubernetes version: 1.19.15
* Using EKS (yes/no), if so version? Using EKS, `v1.19.15-eks-9c63c4`

**Additional Context**:
N/A

**Comment by kishorj** [comment]
@maruina, what does your service manifest look like?

**Comment by maruina** [comment]
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    dns.alpha.kubernetes.io/external: foo.example.com
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses: 1.2.3.4
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-xxxxxx
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
  labels:
    app: istio-defaultgateway
    argocd.argoproj.io/instance: istio-redacted
    chart: gateways
    heritage: Helm
    istio: defaultgateway
    release: istio
  name: default-gateway
  namespace: istio-system
spec:
  clusterIP: 10.100.106.236
  ports:
  - name: status-port
    nodePort: 30021
    port: 15020
  - name: https
    nodePort: 30444
    port: 443
  - name: https-grpc
    nodePort: 30052
    port: 50051
  selector:
    app: istio-defaultgateway
    istio: defaultgateway
    release: istio
  type: LoadBalancer
  ```
