### ISSUE TITLE
Update advanced routing (actions and conditions annotations) docs/examples to use networking.k8s.io/v1

### ISSUE THREAD

**Issue by christopher-wong** [kubernetes-sigs/aws-load-balancer-controller#2522]
**Describe the bug**
The advanced traffic routing docs found [here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#traffic-routing) still shows an example using `apiVersion: extensions/v1beta1`.

**Expected outcome**
Update the docs to use the newer `networking.k8s.io/v1` which changes the syntax of the routing rules in the `spec` section of the yaml manifest.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
...
spec:
  rules:
    - host: www.example.com
       http:
        paths:
        - path: /504
          pathType: Prefix
          backend:
            service:
              name: response-503
              port:
                name: use-annotation
...
```
