### ISSUE TITLE
Validation error with cognito auth annotations

### ISSUE THREAD

**Issue by kncesarini** [kubernetes-sigs/aws-load-balancer-controller#2534]
**Describe the bug**
Following the guide to set up an alb ingress with cognito (https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/tasks/cognito_authentication/) it fails at the final step with a seemingly cryptic error-

{"level":"error","ts":1646228989.3521035,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"test-cognito-1234","namespace":"test-cognito","error":"failed to create listener rule: ValidationError: Action type 'authenticate-cognito' must be one of 'redirect,fixed-response,forward,authenticate-oidc'\n\tstatus code: 400, request id: 7a08b961-ab6a-49b8-b5c6-579b923b7e79"}

Other than the "default action" and ssl redirect, no listener rules are created.

I found the same error in a previous issue (https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1165) which was caused by region-mismatch, which is not the case here. Cognito and EKS are in the same region and same account.

alb-ingresses that don't contain auth-related configuration are created and functional without any issues.

**Steps to reproduce**

Follow the steps provided here https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/tasks/cognito_authentication/

**Expected outcome**
1 - The AWS load balancer controller successfully provisions the ALB.
2 - a more clear error message that describes what potential error that has been made in the setup or configuration.

**Environment**

* AWS Load Balancer controller version- v2.4.0
* Kubernetes version v1.21.5
* Using EKS (yes/no), yes eks.4

**Additional Context**:
This is the full (scrubbed) ingress yaml i'm using

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-cognito-1234
  namespace: test-cognito
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=test,Owner=test
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/auth-scope: openid
    alb.ingress.kubernetes.io/auth-session-timeout: '3600'
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn": "arn:aws:cognito-idp:eu-north-1:<accountid>:userpool/eu-north-1_<xxx>","UserPoolClientId":"<yyy>","UserPoolDomain":"<zzz>"}'
    alb.ingress.kubernetes.io/certificate-arn: <certarn>
spec:
  ingressClassName: alb
  rules:
    - host: <myhost>
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: <xyz>
                port:
                  number: 80
```

Thanks for reading :)

**Comment by kristianpaynova** [comment]
After some more digging and trial and error it appears this could be because Cognito Authentication is not an available option in the Stockholm (eu-north-1) region. 

![image](https://user-images.githubusercontent.com/89450133/156383736-852e49d7-2652-490e-94c8-21e238caacb3.png)
(frankfurt on top, stockholm below)

I can't find any type of documentation regarding this, what regions are and are not supported etc. Is this the correct conclusion? Is there a timeline and list somewhere on what regions regions are and will be supported?


Thanks.

**Comment by M00nF1sh** [comment]
@kristianpaynova i think that's the case but i couldn't find a documentation on supported cognito region either.
Will forward this to ELB pm.

**Comment by kishorj** [comment]
@kristianpaynova, cotnito auth is not currently supported in eu-north-1 region. ELB team is currently working on the support.
I'm closing the issue for now. If you have further questions, feel free to reopen or create a new issue.

**Comment by lunderhage** [comment]
Hello,

I am facing this exact same problem. I am also in the same region (eu-north-1). But according to [List of AWS Services Available by Region](https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/), cognito is now available in eu-north-1.

My annotations are the following:
```yaml
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
    external-dns.alpha.kubernetes.io/hostname: <my-domain>
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '443'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/authenicate-cognito: authenticate-oidc
    alb.ingress.kubernetes.io/auth-scope: openid
    alb.ingress.kubernetes.io/auth-session-timeout: "3600"
    a: b
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn":"arn:aws:cognito-idp:eu-north-1:1234567890123:userpool/eu-north-1_xxYYXXxxYYxx","UserPoolClientId":"xxxxxxxxxxxxxxx","UserPoolDomain":"mydomain.auth.eu-north-1.amazoncognito.com"}'
```

I am using AWS Load Balancer Controller 2.6.2.
