### ISSUE TITLE
NLB Healthcheck rules in <cluster-name>-lb security group includes the whole NLB subnet instead of NLB IP

### ISSUE THREAD

**Issue by matlemb** [kubernetes-sigs/aws-load-balancer-controller#2535]
**Describe the bug**
[AWS Load Balancer Controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) modifies the `<cluster-name>-lb` security group to allow incoming traffic to the nodes when creating a `svc.spec.type.loadbalancer` and when annotations are set to create an `NLB` with enabled client ip preservation. The controller does create entries for CIDRs specified in `svc.spec.loadBalancerSourceRanges` as well as for health checks coming from the specified NLB subnets. The entries for the health checks should not be allowed on the subnet where the NLB was created but rather on the ENI ip addresses of the NLBs. The current filtering behavior for health checks based on NLB subnet basis exposes all NLB services to other clusters or EC2-instances using the same NLB subnets which could be a security risk.

The same behavior can be seen in [`in-tree`](https://github.com/kubernetes/legacy-cloud-providers/tree/master/aws) and [`out-of-tree`](https://github.com/kubernetes/cloud-provider-aws) controllers (cloud-controller-manager and kube-controller-manager - with different annotations in order to get the same NLB created at AWS).

**Steps to reproduce**
Create a service type loadbalancer and annotations to create an NLB:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
    service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=false
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-abc, subnet-def, subnet-xyz
  name: foobar
  namespace: foobar
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: foobar
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 1.2.3.4/32
```

**Expected outcome**
AWS Load Balancer Controller should not allow traffic from the subnet CIDRs of the NLBs but rather from the ENI IP addresses of the created NLBs.

**Environment**

* AWS Load Balancer controller version
  2.4
* Kubernetes version
  1.23.3
* Using EKS (yes/no), if so version?
  no

**Additional Context**

The call to [`getLoadBalancerSubnetsSourceRanges`](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/service/model_build_target_group.go#L445) ranges over the retrieved [ec2 subnets](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/7baec176ddbaed9d23f92ca9f77a658eed3cf3a3/pkg/service/model_build_target_group.go#L497) and builds corresponding [ingress rules for the health checks](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/7baec176ddbaed9d23f92ca9f77a658eed3cf3a3/pkg/service/model_build_target_group.go#L552). The `defaultModelBuildTask` also has the [`existingLoadBalancer`](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/service/model_builder.go#L141) key, which contains the [`PrivateIPv4Address`](https://github.com/aws/aws-sdk-go/blob/v1.42.47/service/elbv2/api.go#L7184) under `LoadBalancerWithTags.LoadBalancer.AvailabilityZones[].LoadBalancerAddresses[]`. Not sure if this is feasible, but might this field be used instead of the subnets? Or can the ENI IP address of the load balancer only be retrieved by a [call to the actual network interface description based on the name of the load balancer](https://aws.amazon.com/premiumsupport/knowledge-center/elb-find-load-balancer-IP/)?

<sub>Matthias Lembcke <[matthias.lembcke@mercedes-benz.com](mailto:matthias.lembcke@mercedes-benz.com)>, Daimler TSS GmbH ([Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))</sub>
