### ISSUE TITLE
NLB share when using service resources

### ISSUE THREAD

**Issue by rverma-nsl** [kubernetes-sigs/aws-load-balancer-controller#2536]
**Is your feature request related to a problem?**
We have 2 svc which we want to expose on different port. The controller should allow to bind both the svc to same nlb as it does for alb.
Tried & Failed:      service.beta.kubernetes.io/aws-load-balancer-name: nsl-default

For instance when create two svc

```
apiVersion: v1
kind: Service
metadata:
  name: api-stable
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
      service.beta.kubernetes.io/aws-load-balancer-name: nsl-default
spec:
  ports:
  - name: http
    port: 443
    targetPort: http
  type: ClusterIP
```
---
```
apiVersion: v1
kind: Service
metadata:
  name: api-socket
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
      service.beta.kubernetes.io/aws-load-balancer-name: nsl-default
spec:
  ports:
  - name: http
    port: 6329
    targetPort: http
  type: ClusterIP

```
I expect a way to merge them on same nlb.

**Describe the solution you'd like**
Provide annotation for nlb merge
