### ISSUE TITLE
Inbound cidrs not working with EKS 

### ISSUE THREAD

**Issue by pabrahamusa** [kubernetes-sigs/aws-load-balancer-controller#2537]
**Describe the bug**
I have an ALB Ingress defined as below and I specified  `alb.ingress.kubernetes.io/inbound-cidrs:  10.200.121.23/32` to only allow traffic from single IP Address i.e. 10.200.121.23 . I can see this annotation adds an inbound rule to the ALB Security group. However when I try to do a curl from 10.200.121.23 it is failing with connection timed out.  This IP is part of the same VPC where ALB is running and I am assuming this is happening because the ALB is seeing a different IP address rather than the actual source/client ip. So is there a way to make sure inboud cidrs work properly and enable ALB to see correct client IP. ? I tried `service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true`  however it is not working.
 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:us-east-1:xxxxxxxxxxx:certificate/df09xxxxxxxxxxx'
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    kubernetes.io/ingress.class: ingress-alb
    external-dns.alpha.kubernetes.io/hostname: mydomain.com
    alb.ingress.kubernetes.io/inbound-cidrs:  10.200.121.23/32
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
    external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
  name: alb-ingress-connect
spec:
  backend:
    serviceName: my-test-service
    servicePort: client-port
```

**Steps to reproduce**
Define Ingress as above and try to allow cidrs

**Expected outcome**
The traffic should be allowed from the cidr inbound ip address.

**Environment**

* AWS Load Balancer controller version - from helm Chart.yaml  apiVersion: v2 / appVersion: v2.3.0
* Kubernetes version - 1.21
* Using EKS (yes/no), if so version? yes - 1.21
