### ISSUE TITLE
Load balancer name vs group name

### ISSUE THREAD

**Issue by przemolb** [kubernetes-sigs/aws-load-balancer-controller#2544]
**Details**

LB version: applies to all versions

I am trying to understand the relationship between `load-balancer-name` vs `group.name`. Let's say we have two ingresses defined:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
  namespace: ns-1
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: lb-1
    alb.ingress.kubernetes.io/group.name: group-1

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
  namespace: ns-2
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: lb-2
    alb.ingress.kubernetes.io/group.name: group-1
```
According to the docs:
```
IngressGroup feature enables you to group multiple Ingress resources together.
The controller will automatically merge Ingress rules for all Ingresses within IngressGroup and support
them with a __single__ALB__         # <- single !!!
...
[alb.ingress.kubernetes.io/group.name]() specifies the group name that this Ingress belongs to
...
```
but also:
```
[alb.ingress.kubernetes.io/load-balancer-name]() specifies the custom name to use for the load balancer

```
In this case above we have the ssame `group.name` but different `load-balancer-names` - what will be the name of the LB and why ?
