### ISSUE TITLE
Error: INSTALLATION FAILED - Address is not allowed

### ISSUE THREAD

**Issue by sb-tmd-dev** [kubernetes-sigs/aws-load-balancer-controller#2549]
**Describe the bug**
`Error: INSTALLATION FAILED: Internal error occurred: failed calling webhook "vingress.elbv2.k8s.aws": Post "[https://aws-load-balancer-webhook-service.kube-system.svc:443/validate-networking-v1-ingress?timeout=10s](https://aws-load-balancer-webhook-service.kube-system.svc/validate-networking-v1-ingress?timeout=10s)": Address is not allowed`

1. I'm trying to install using helm chart version 1.4.0
2. subnets are tagged with correct naming conventions. 
3. IAM created and attached to worker nodes with policy  as mentioned here: `https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/main/docs/install/iam_policy.json`
4. kubeversion >=1.21
5. **I am using Calico as my CNI** 

```
# values.yaml
aws-load-balancer-controller:
  replicaCount: 1
  clusterName: cluster
  awsRegion: us-east-1
  awsVpcID: vpc-id 
  scope:
    ingressClass: alb
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: space
                operator: In
                values:
                  - app
  tolerations:
    - effect: NoSchedule
      key: space
      operator: Equal
      value: app
```

```
# Ingress

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.https_cert_aws }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: "internal"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-2019-08
    alb.ingress.kubernetes.io/success-codes: 200-301
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  name: ingress
  namespace: "default"
spec:
  rules:
    - http:
        paths:
        - backend:
            serviceName: nginx-internal-service
            servicePort: 443
          path: /
      host: "aaa.stage.company_name.com"
```
---
```
# Service

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-internal-service
  name: nginx-internal-service
  namespace: "default"
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: nginx
  sessionAffinity: None
  type: NodePort
```

**Steps to reproduce**
1. Apply the ingress & service

**Expected outcome**
internal ALB  created 

* AWS Load Balancer controller version - v2.4.0
* Kubernetes version - 1.21
