### ISSUE TITLE
Unable to group Ingress objects under one ALB (using `alb.ingress.kubernetes.io/group-name`)

### ISSUE THREAD

**Issue by rfc2119** [kubernetes-sigs/aws-load-balancer-controller#2564]
**Describe the bug**
I'm trying to simply group Ingress objects under one ALB as detailed [here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#group.name). I create two Ingress objects expecting them to live under one ALB but they don't

**Steps to reproduce**
Here's a simple manifest I actually use to test this. Both backend services do not exist, but this won't matter:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-test
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group-name: eth
spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: svc-hello
      port:
        number: 80
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: svc-not-found
              port:
                number: 80
      host: "test.me"
```
An ALB is created with the following tracking tags:

| Key | Value |  
|:-------:|:-------:|
| ingress.k8s.aws/resource | LoadBalancer |  
| ingress.k8s.aws/stack | default/ingress-test |  
| elbv2.k8s.aws/cluster | eks-cluster-test |

The same YAML spec file is copied and has its name changed to "ingress-test-2" and its rules section to:
```yaml
  rules:
  - host: test.host.com
    http:
      paths:
      - backend:
          service:
            name: non-existant-svc
            port:
              number: 8090
        path: /
        pathType: Prefix
```
Then created with kubectl. A second ALB is created with the following tracking tags:

| Key | Value |  
|:-------:|:-------:|
| ingress.k8s.aws/resource | LoadBalancer |  
| ingress.k8s.aws/stack | default/ingress-test-2 |  
| elbv2.k8s.aws/cluster | eks-cluster-test |

**Expected outcome**
As far as I understand it, second ALB should not be created

**Environment**

* **AWS Load Balancer controller version**: v2.4.0
* **Kubernetes version**: v1.21.5-eks-bc4871b
* **Using EKS (yes/no), if so version?** v1.21.5-eks-bc4871b
