### ISSUE TITLE
SG rules are not created for TargetGroupBinding

### ISSUE THREAD

**Issue by jbg** [kubernetes-sigs/aws-load-balancer-controller#2582]
**Describe the bug**
When creating a TargetGroupBinding manually, to link a k8s ClusterIP service to an existing NLB target group, rules are not added to the node's Security Group to allow the traffic.

**Steps to reproduce**
1. Create a k8s ClusterIP service
2. Create an NLB and an IP target group at AWS
3. Create a TargetGroupBinding to link (1) and (2)

**Expected outcome**
A working binding between the NLB target group and the ClusterIP service.

**Actual outcome**
The binding does not work without additional manual steps, because SG rules are not created.

**Environment**
* AWS Load Balancer controller version: v2.4.0
* EKS 1.21

**Additional Context**:
When creating the NLB using aws-load-balancer-controller, by annotating a `LoadBalancer` service, the SG rules are automatically created on the SG of the nodes to allow the traffic. However, this does not happen when creating the TargetGroupBinding ourselves.

**Comment by kishorj** [comment]
@jbg, you will have to specify the `spec.networking` in the TargetGroupBinding resource you manually create. For example:

```
spec:
  ipAddressType: ipv4
  networking:
    ingress:
    - from:
      - ipBlock:
          cidr: 10.10.0.0/16
      ports:
      - port: 80
        protocol: TCP
```
