### ISSUE TITLE
How to create rules for specific listener?

### ISSUE THREAD

**Issue by rmarra** [kubernetes-sigs/aws-load-balancer-controller#2590]
I'm provisioning an ALB Ingres that listens on port 443 and 9090, but all the traffic rules that I create are created for all ports and I have to manually delete them. How could I create rules for specific listener?

OBS: my alb is going to handle GRPC and HTTP requests

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.grpc-traffic: |
      {"type":"forward","forwardConfig":{"targetGroups":[{"serviceName":"istio","servicePort":"grpc"}]}}
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP2
    alb.ingress.kubernetes.io/certificate-arn: {{ arn-cert }}
    alb.ingress.kubernetes.io/conditions.grpc-traffic: |
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "content-type", "values":["application/grpc"]}}]
    alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
    alb.ingress.kubernetes.io/healthcheck-port: status-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":9090}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
  name: istio-ingress-alb
  namespace: istio-system
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          serviceName: grpc-traffic
          servicePort: use-annotation
        path: /
        pathType: Prefix
      - backend:
          serviceName: istio
          servicePort: http2
        path: /
        pathType: Prefix

```
