### ISSUE TITLE
Different Ingress status.loadBalancer output when using kubernetes.io/ingress.class annotation or ingressClassName field

### ISSUE THREAD

**Issue by rkosyk-dh-nf** [kubernetes-sigs/aws-load-balancer-controller#2592]
**Describe the bug**

When using kubernetes.io/ingress.class annotation in the Ingress configuration getting ALB dns name (**hostname**) in the status.loadBalancer output

kubectl get ingress testapp -o yaml
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-06fb8e9aca63cb670,subnet-08d47cc39015f5858,subnet-0b02e10d5cca58c5e
    alb.ingress.kubernetes.io/target-type: instance
    kubernetes.io/ingress.class: alb
  name: testapp
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: testapp
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - hostname: k8s-default-testapp-fecabe0a85-1861535460.us-east-1.elb.amazonaws.com
```
When using new field ingressClassName instead of annotation  in the Ingress configuration getting kubernetes node IP address (**ip**) in the Ingress status.loadBalancer output

kubectl get ingress testapp -o yaml
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-06fb8e9aca63cb670,subnet-08d47cc39015f5858,subnet-0b02e10d5cca58c5e
    alb.ingress.kubernetes.io/target-type: instance
  name: testapp
  namespace: default
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: testapp
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - ip: 10.100.92.62
```

**Steps to reproduce**

Configure ingress using kubernetes.io/ingress.class annotation, then configure ingress using field ingressClassName

**Expected outcome**

In both cases Ingress status.loadBalancer output should return **hostname**

**Environment**

* AWS Load Balancer controller version: 2.4.1
* Kubernetes version: 1.21
* Using EKS (yes/no), eks.5

**Additional Context**:

aws-load-balancer-controller has been installed using helm chart
