### ISSUE TITLE
ValidationError IngressClassParams loadBalancerAttributes

### ISSUE THREAD

**Issue by Apollorion** [kubernetes-sigs/aws-load-balancer-controller#2595]
**Describe the bug**
I have 3 things complaining to me that `loadBalancerAttributes` is an `unknown field`

I have the following IngressClassParam:
```yaml
apiVersion: elbv2.k8s.aws/v1beta1
kind: IngressClassParams
metadata:
  name: stage-alb
spec:
  group:
    name: stage-alb
  scheme: internet-facing
  loadBalancerAttributes:
    - key: access_logs.s3.enabled
      value: "true"
    - key: access_logs.s3.bucket
      value: joey-access-logs-bucket
    - key: access_logs.s3.prefix
      value: access-logs/staging
```

When I try to apply via `kubectl apply -f ingress-class.yaml` I get the following error:
```
error: error validating "ingress-class.yaml": error validating data: ValidationError(IngressClassParams.spec): unknown field "loadBalancerAttributes" in aws.k8s.elbv2.v1beta1.IngressClassParams.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

When gitops/flux tries to apply it, I get:
```
IngressClassParams/stage-alb dry-run failed, error: failed to create typed patch object: .spec.loadBalancerAttributes: field not declared in schema
```

and on my repo, Im using kubeconform to validate yaml, it complains:
```
ingress-class.yaml - IngressClassParams stage-alb is invalid: For field spec: Additional property loadBalancerAttributes is not allowed
```

**Environment**

* AWS Load Balancer controller version
latest as of today - just upgraded from 2.3.1 to 2.4.1

* Kubernetes version
1.20
* Using EKS (yes/no), if so version?
yes, platform version eks.3
