### ISSUE TITLE
Support for both TCP_UDP protocols when creating NLB

### ISSUE THREAD

**Issue by dmavrommatis** [kubernetes-sigs/aws-load-balancer-controller#2597]
**Is your feature request related to a problem?**
I am trying to setup a service that listens on the same port for TCP and UDP traffic. 
Kubernetes complains about MixedProtol error if you try to mix TCP and UDP ports on the same service manifest if it's type `LoadBalancer` but switching it to `NodePort` seems that confuses `aws-loadbalancer-controller` and it creates an NLB for one port only.

I was wondering if it's possible to either create 2 services, one for TCP and one for UDP, that share the same NLB or if there is already a way to do this through a single service.

**Describe the solution you'd like**
In a perfect scenario the best solution would be like this:
```
apiVersion: v1
kind: Service
metadata:
  name: example
  labels:
    app: example
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-subnets: {{ .subnets }}
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: {{ .eipAllocations }}
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: example
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53
      name: tcp-example
    - protocol: UDP
      port: 53
      targetPort: 53
      name: udp-example
```
Edit:
Applying the above service manifest errors with the following:
```
{"level":"error","ts":1648769567.0426252,"logger":"controller-runtime.manager.controller.service","msg":"Reconciler error","name":"example-external-udp","namespace":"example","error":"ResourceInUse: The allocation IDs are not available for use\n\tstatus code: 400, request id: xxx"}
```
