### ISSUE TITLE
Is it possible to do token based auth?

### ISSUE THREAD

**Issue by genieai-vikas** [kubernetes-sigs/aws-load-balancer-controller#2599]
I am using aws-load-balancer-controller with our K8s cluster. The ALB type we were using is internal but now I am planning to change it to external.

Usecase: Trying to create an external ALB to access the frontend microservice but with some kind of auth. Like if the request has a specific token then only access the UI otherwise reject it. Is it possible to do token-based auth

I looked into this issue but didn't get a clear solution:
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/874

**Comment by M00nF1sh** [comment]
it's not possible as alb itself don't support it

**Comment by genieai-vikas** [comment]
@M00nF1sh Someone posted this link on slack channel. 

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-update-rules.html

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/restrict-access-to-load-balancer.html#restrict-alb-route-based-on-header

I haven't tried these but he suggested that I can do it with a  header condition rule in alb. Do you know if it will work? if not then I'll have to see for some different option. Thanks for helping

**Comment by M00nF1sh** [comment]
@genieai-vikas 
It's possible to create a rule that matches header value with the conditions annotation: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#conditions

it's not token based auth tbh, but might work depends on your case.

**Comment by genieai-vikas** [comment]
@M00nF1sh Tested with the annotation you suggested. It's semi-working. This is the ingress I used

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingressScheme }}
    alb.ingress.kubernetes.io/group.name: qa
    alb.ingress.kubernetes.io/actions.redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.SUPERDRAFTER_CERTIFICATE_ARN }}"
    alb.ingress.kubernetes.io/inbound-cidrs: {{ .Values.ipWhiteList }}
    alb.ingress.kubernetes.io/ssl-redirect: '443' 
    alb.ingress.kubernetes.io/conditions.frontend-svc: |
      [{"Field":"http-header","HttpHeaderConfig":{"HttpHeaderName": "dummy", "Values":["fRfTsgyeh3qWeDFG"]}}]

spec:
  rules:
    - host: {{ .Values.domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  name: use-annotation
```
When I don't pass the header I see `HTTP ERROR 404` but when I pass the header pages load but giving me this error "Backend action does not exist"

I can confirm the service I provided `frontend-svc` is there because when  I remove `alb.ingress.kubernetes.io/conditions.frontend-svc` page opens up. Any suggestion on how to fix this error `Backend action does not exist`
