### ISSUE TITLE
Ingress unable to select subnets based on `Name` tag

### ISSUE THREAD

**Issue by johnnyhuy** [kubernetes-sigs/aws-load-balancer-controller#2612]
**Describe the bug**

Unable to select subnets based on subnet `Name` tag as stated in the [documentation](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#subnets). However, we're still able to use the `subnet-...` subnet ID.

![image](https://user-images.githubusercontent.com/27847622/163736407-a9f43af1-2d1b-4717-9c04-16f309df28b2.png)

We aren't using subnet auto-discovery.

Error:

```
Failed build model due to couldn't find all subnets, nameOrIDs: [...], found: 0
```

**Steps to reproduce**

Create an ingress resource with the `alb.ingress.kubernetes.io/subnets` annotation

Example:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example
  namespace: example
  annotations:
    alb.ingress.kubernetes.io/subnets: MyVpcA, MyVpcB, MyVpcC
    ...
spec:
  ingressClassName: alb
  ...

```

**Expected outcome**

Subnets to be selected based on the value of the subnets `Name` tag.

**Environment**

* AWS Load Balancer controller version `v1.24.0`
* Kubernetes version `1.21`
* EKS `eks.6`
