### ISSUE TITLE
ALB Ingress paths match rule not same as Ingress specification

### ISSUE THREAD

**Issue by haorenfsa** [kubernetes-sigs/aws-load-balancer-controller#2614]
**Describe the bug**
ALB Ingress paths match machanism not same as Ingress specification:
According ingress [official docs](https://kubernetes.io/docs/concepts/services-networking/ingress/) states the match rule of `Prefix` as:  

Kind | Path(s) | Request path(s) | Matches?
-- | -- | -- | --
... | ... | ... | ...
Prefix | /, /aaa | /aaa/ccc | Yes, matches /aaa prefix

But ALB actually matches the rule in front:
- when given paths order `/`,`/aaa` matches `/` prefix
- when given paths order `/aaa`,`/` matches `/aaa` prefix

**Steps to reproduce**

prepare 2 nginx service `service-a` & `service-b`

create ingress of ALB with spec:
```
spec:
  rules:
  - host: somehost
    http:
      paths:
      - backend:
          service:
            name: service-a
            port:
              number: 80
        path: /
        pathType: Prefix
      - backend:
          service:
            name: service-b
            port:
              number: 80
        path: /b
        pathType: Prefix
```

curl `http://somehost/b`, you'll found access log in A

**Expected outcome**
Access log should be found in B

**Environment**

* AWS Load Balancer controller version: `1.4.0`
* Kubernetes version: `1.21.5`
* Using EKS (yes/no), if so version? yes, `v1.21.5-eks-9017834`

**Additional Context**:
