### ISSUE TITLE
Cannot change health check endpoint

### ISSUE THREAD

**Issue by blackheaven** [kubernetes-sigs/aws-load-balancer-controller#2615]
**Describe the bug**
Even when `alb.ingress.kubernetes.io/healthcheck-path` set, the health-check is still done on `/`

**Steps to reproduce**

Create an ingress controller such as:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: my-namespace
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/healthcheck-path: /_health
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: "..."
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    external-dns.alpha.kubernetes.io/hostname: "example.com"

    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: default

spec:
  rules:
  - host: "example.com"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: my-product
              port:
                number: 80
```

**Expected outcome**
It should hit `/_healthz`

**Environment**

* AWS Load Balancer controller version: aws-load-balancer-controller-1.2.6 / v2.2.3
* Kubernetes version: 1.19
* Using EKS (yes/no): yes / eks.7

**Additional Context**:
