### ISSUE TITLE
ALB controller doesn't play nice with custom certutil issuers?

### ISSUE THREAD

**Issue by meyerkev** [kubernetes-sigs/aws-load-balancer-controller#2623]
**Describe the bug**
I had a custom issuer getting weekly origin certs from Cloudflare and then I switched to using this controller to setup ALB's and the ALB controller cannot use the custom-issued certs.  

**Steps to reproduce**

Using a custom Helm Chart
Install ALB Controller on the EKS cluster

My ingress.yaml

```
# Source: palolo-app/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: palolo-app
  labels:
    helm.sh/chart: palolo-app-0.1.0
    app.kubernetes.io/name: palolo-app
    app.kubernetes.io/instance: palolo-app
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    # This should not be required.  
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:796723948741:certificate/85944099-22a1-48bd-b343-f8b1a98c54db
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-name: palolo-alpha
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    cert-manager.io/issuer: prod-issuer
    cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
    cert-manager.io/issuer-kind: OriginIssuer
  namespace: palolo-alpha
spec:
  ingressClassName: alb
  tls:
    - hosts:
        - "alpha.palolo.com"
      secretName: palolo-com-tls
  rules:
    - host: "alpha.palolo.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: palolo-app
                port:
                  number: 443
```

When I push this with the cert arn, it works. 

When I push it without the cert arn, the logs say: 

```
Events:
  Type     Reason             Age                 From                       Message
  ----     ------             ----                ----                       -------
  Normal   CreateCertificate  48m                 cert-manager-ingress-shim  Successfully created Certificate "palolo-com-tls"
  Warning  FailedBuildModel   37m (x18 over 48m)  ingress                    Failed build model due to ingress: palolo-alpha/palolo-app: no certificate found for host: alpha.palolo.com

**Expected outcome**
I want the AWS controller to pick up my k8s secret origin cert issued by Cloudflare on the Cloudflare controller in the palolo-com-tls secret and then use that to run the webserver.  And not require an arn.  
```  

I double-checked the secret and there is in fact an origin cert in there and in other contexts it does work.  

**Environment**

* AWS Load Balancer controller version - v2.4.1
* cert-manager - v1.8.0
* Kubernetes version - 1.22
* Using EKS (yes/no), if so version?  Yes, eks.1

```
NAME                        	NAMESPACE   	REVISION	UPDATED                             	STATUS  	CHART                             	APP VERSION
aws-load-balancer-controller	kube-system 	1       	2022-04-22 11:16:53.996107 -0400 EDT	deployed	aws-load-balancer-controller-1.4.1	v2.4.1
cert-manager                	cert-manager	3       	2022-04-21 18:28:24.347837 -0400 EDT	deployed	cert-manager-v1.8.0               	v1.8.0
palolo-app                  	palolo-alpha	67      	2022-04-22 18:35:59.678256 -0400 EDT	deployed	palolo-app-0.1.0                  	0.1.0
```

**Additional Context**:
None
