### ISSUE TITLE
No good story for http->https redirects when using a HTTP2 backend

### ISSUE THREAD

**Issue by paul-civitas** [kubernetes-sigs/aws-load-balancer-controller#2632]
The general instructions for creating a http->https redirect with the ALB controller are thus:

```
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:***:certificate/***
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/scheme: internet-facing
```

What this does is creates the paths for both 80 and 443. But then in front of the 80 one it puts a redirect in front.

However if you have a HTTP2 backend, then it can't create a port 80 path directing http traffic to a HTTP2 backend. So it will freak out and say it couldn't build the model then it won't add the redirect. So this doesn't work for creating a redirect if you have a HTTP2 backend.
