### ISSUE TITLE
Echoserver example alb returning 404

### ISSUE THREAD

**Issue by kaykhancheckpoint** [kubernetes-sigs/aws-load-balancer-controller#2637]
Hi friends i have installed the aws-alb-load-balancer-controller v2.4. 

I have followed the guide to create the example echoserver. https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/examples/echo_server/

Everything was successfull and the controller created the ingress which i can see in my aws dashboard.

However when i make a simple get request to the `generated dns name` i expect to get a 200 response? but im getting a 404.

![image](https://user-images.githubusercontent.com/65535942/166435192-1893ad3a-b494-4aeb-bb96-04a2114d419a.png)

```
apiVersion: v1
kind: Namespace
metadata:
  name: echoserver
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echoserver
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: echoserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: echoserver
spec:
  selector:
    matchLabels:
      app: echoserver
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: k8s.gcr.io/e2e-test-images/echoserver:2.5
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoserver
  namespace: echoserver
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
spec:
  ingressClassName: alb
  rules:
    - host: echoserver.example.com
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: echoserver
                port:
                  number: 80
```

 **kubectl logs -f echoserver-5978c8d744-qsfwt -n echoserver**
```
Generating self-signed cert
Generating a RSA private key
.+++++
.......+++++
writing new private key to '/certs/privateKey.key'
-----
Starting nginx
2022/05/03 09:00:37 [alert] 10#10: detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
2022/05/03 09:00:37 [error] 10#10: lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
        no field package.preload['resty.core']
        no file './resty/core.lua'
        no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core/init.lua'
        no file '/usr/share/lua/5.1/resty/core.lua'
        no file '/usr/share/lua/5.1/resty/core/init.lua'
        no file '/usr/share/lua/common/resty/core.lua'
        no file '/usr/share/lua/common/resty/core/init.lua'
        no file './resty/core.so'
        no file '/usr/local/lib/lua/5.1/resty/core.so'
        no file '/usr/lib/lua/5.1/resty/core.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/usr/lib/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so')
nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
        no field package.preload['resty.core']
        no file './resty/core.lua'
        no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core/init.lua'
        no file '/usr/share/lua/5.1/resty/core.lua'
        no file '/usr/share/lua/5.1/resty/core/init.lua'
        no file '/usr/share/lua/common/resty/core.lua'
        no file '/usr/share/lua/common/resty/core/init.lua'
        no file './resty/core.so'
        no file '/usr/local/lib/lua/5.1/resty/core.so'
        no file '/usr/lib/lua/5.1/resty/core.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/usr/lib/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so')
10.0.4.56 - - [03/May/2022:09:00:43 +0000] "GET / HTTP/1.1" 200 484 "-" "ELB-HealthChecker/2.0"
10.0.3.87 - - [03/May/2022:09:00:43 +0000] "GET / HTTP/1.1" 200 484 "-" "ELB-HealthChecker/2.0"
10.0.3.147 - - [03/May/2022:09:00:43 +0000] "GET / HTTP/1.1" 200 487 "-" "ELB-HealthChecker/2.0"
10.0.5.168 - - [03/May/2022:09:00:43 +0000] "GET / HTTP/1.1" 200 487 "-" "ELB-HealthChecker/2.0"
10.0.4.56 - - [03/May/2022:09:00:45 +0000] "GET / HTTP/1.1" 200 484 "-" "ELB-HealthChecker/2.0"
10.0.3.147 - - [03/May/2022:09:00:45 +0000] "GET / HTTP/1.1" 200 487 "-" "ELB-HealthChecker/2.0"
10.0.3.87 - - [03/May/2022:09:00:45 +0000] "GET / HTTP/1.1" 200 484 "-" "ELB-HealthChecker/2.0"
10.0.5.168 - - [03/May/2022:09:00:45 +0000] "GET / HTTP/1.1" 200 487 "-" "ELB-HealthChecker/2.0"
10.0.4.56 - - [03/May/2022:09:00:47 +0000] "GET / HTTP/1.1" 200 484 "-" "ELB-HealthChecker/2.0"
```
**curl -o - -I http://k8s-echoserv-echoserv-901d6d7507-763981020.eu-west-2.elb.amazonaws.com**

```
HTTP/1.1 404 Not Found
Server: awselb/2.0
Date: Tue, 03 May 2022 10:08:13 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Connection: keep-alive
```

I'm not sure if this is a bug or just mis-configuration on my part. In the future i intend to add the `external-dns` but right now i just wanted to see if i could get a 200 from the generated dns.

I'm not sure if this is a problem with the echoserver example so i tried deploying my own example service/deployment/ingress. Again the controller creates the ingress but im not able to access the `/health` endpoint which i know should return a 200. I instead just get a 404.

**Environment**

* AWS Load Balancer controller version 2.4
* Kubernetes version: 1.22
* Using EKS (yes/no), if so version? yes latest

update:

Works when i use my own custom domain
