### ISSUE TITLE
Controller creates TargetGroup, but doesn't register any instances

### ISSUE THREAD

**Issue by aokomorowski** [kubernetes-sigs/aws-load-balancer-controller#2653]
**Describe the bug**
I'm working on setting up a small k3s cluster with AWS integration as a proof of concept. My cluster currently is a single EC2 instance running k3s binary - I don't use AWS VPC CNI. I've installed AWS LB Controller using the official Helm chart from the EKS Chart repository. Then I created a service (type: NodePort) and exposed it with Ingress. The controller creates the LB, creates the SG and a Target Group, but it doesn't register my EC2 instance as a target in the Target Group and it doesn't attach the SG to the instance. 

**Steps to reproduce**
Here's how I deploy the service and the ingress:
```
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "nginx"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/healthcheck-path: '/'
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "nginx"
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

**Expected outcome**
EC2 instance should be registered automatically with the NodePort of the service.

**Environment**

* AWS Load Balancer controller version: amazon/aws-alb-ingress-controller:v2.4.1
* Kubernetes version: k3s v1.23.6+k3s1
* Using EKS (yes/no), if so version? no

**Additional Context**:
Have mercy, I'm running out of ideas.
