### ISSUE TITLE
No ALPN Policy assigned to AWS Load Balancer

### ISSUE THREAD

**Issue by tleish** [kubernetes-sigs/aws-load-balancer-controller#2656]
**Describe the bug**
Create a new service of with a network load balancer, it creates an AWS Load Balancer with all the options except the ALPN Policy.

**Steps to reproduce**
Create a new service of with the following load balancer options

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-alpn-policy: HTTP2Preferred
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:.....
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  externalTrafficPolicy: "Local"
  ports:
    - name: "http-80"
      port: 80
      protocol: TCP
      targetPort: http
    - name: "https-443"
      port: 443
      protocol: TCP
      targetPort: https
  type: LoadBalancer
```

Check the AWS Web Console EC2 > Load Balancers > [New Load Balancer] > Listeners (tab) > TLS : 443 Security Policy = N/A.

**Expected outcome**
ALPN policy assigned to new LoadBalancer

**Environment**

* AWS Load Balancer controller version ?
* Kubernetes version 1.22.6
* Using EKS (yes/no), if so version? yes, 1.23.3

**Additional Context**:

The service is created through [haproxy-ingress](https://haproxy-ingress.github.io/docs/getting-started/).

What do I need to add in order to assign the ALPN policy?
