### ISSUE TITLE
Receiving 502 bad gateway when refreshing on a specific path

### ISSUE THREAD

**Issue by kaykhancheckpoint** [kubernetes-sigs/aws-load-balancer-controller#2661]
Hi friends i have an issue with my ingress. This is a frontend application 

- if i navigate to `staging.acme.com` it works 
- if i click a button that takes me `/dashboard` it works
- now im on the page `staging.acme.com/dashboard` if i refresh the page i get a `502 bad gateway` error

Any idea what is happening here? 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: staging-ingress
  namespace: staging
  annotations:
    alb.ingress.kubernetes.io/group.name: "acme-prod"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:redacted:certificate/<redacted>,arn:aws:acm:us-east-2:redacted:certificate/<redacted>
    alb.ingress.kubernetes.io/tags: Environment=prod,Team=dev
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '300'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=acme-aws-ingress-logs,access_logs.s3.prefix=prod-ingress
spec:
  ingressClassName: alb
  rules:
    - host: staging.acme.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: web-data-staging
                port:
                  number: 8080
```

![image](https://user-images.githubusercontent.com/65535942/170247318-8e39a9ee-fb0c-4d76-b6ed-b8425fe700fb.png)

![image](https://user-images.githubusercontent.com/65535942/170247487-638bef37-74a4-49b4-8bad-f8ba7f07e6c5.png)

I'm using the latest version of `aws-load-balancer-controller`
