### ISSUE TITLE
IPv6 target groups enforced in dual-stack environment

### ISSUE THREAD

**Issue by akunszt** [kubernetes-sigs/aws-load-balancer-controller#2668]
**Describe the bug**
We are in the long-term process to support IPv6 in our clusters. We prepared all of our Services to use PreferDualStack and hoped that the next release of aws-vpc-cni will support that. It didn't. It supports IPv4 or IPv6 but not both - aka dual-stack. As we can't do the migration in one huge step we postponed it.
After upgrading aws-loadbalancer-controller we noticed that it can't create Ingresses - but can reconcile existing ones though - with this error message.

```
Failed build model due to ingress: prometheus/prometheus-apps: unsupported IPv6 configuration, lb not dual-stack
``` 

We checked the code and it looks when you use `ipFamilyPolicy: PreferDualStack` the controller try to enforce to create a dual-stack ALB and - we assume - IPv6 only TargetGroup.
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/0ad294b07eed49116a7dd19ab096f16197c38763/pkg/ingress/model_build_target_group.go#L228-L240

This won't work as aws-vpc-cni doesn't support dual-stack mode the ALB/TG won't be able to reach the Pod's IP at all.

We tried to set the `alb.ingress.kubernetes.io/ip-address-type` to `ipv4` but that didn't help - also it's a bit unclear what does that annotation actually does.

We also tried to set the `service.beta.kubernetes.io/aws-load-balancer-ip-address-type` to `ipv4` on the service too, without any luck.

**Steps to reproduce**
Create a Service like this:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: mynamespace
spec:
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: myapp
  type: ClusterIP
```
Use this as a backend in an Ingress, for example:
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect","RedirectConfig":{"Protocol":
      "HTTPS","Port": "443","StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:....
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/security-groups: sg-xxxxx
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  name: myingress
  namespace: mynamespace
spec:
  rules:
  - host: myhost.mydomain.tld
    http:
      paths:
      - backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
        path: /
        pathType: Prefix
      - backend:
          service:
            name: myservice
            port:
              name: http
        path: /
        pathType: Prefix
```

**Expected outcome**
The Ingress and related resources are properly created.

There should be an annotation or any other configuration setting which tells the `aws-loadbalancer-controller` what protocol use when it faces a dual-stack service. Enforce IPv6 target groups only for IPv6-only backend services, enforce IPv4 target groups only for IPv4-only backend services and let the user choose when it's not obvious.

**Environment**

* AWS Load Balancer controller version: 2.4.2
* Kubernetes version: 1.22.9
* Using EKS (yes/no), if so version?: no

**Additional Context**:
This can be workaround by manually removing the IPv6 address from clusterIPs array, removing the ipFamilies array and set the ipFamilyPolicy to SingleStack but it's a tedious work if you have many Services.

**Comment by MarvinCai** [comment]
I am having similar issue. I am trying to create a LoadBalancer service in a ipv6 only EKS cluster, getting similar error `"error":"unsupported IPv6 configuration, lb not dual-stack"`. I am able to get it working by adding this annotation `"service.beta.kubernetes.io/aws-load-balancer-ip-address-type": 'dualstack'` to the service according to this doc: https://aws.amazon.com/blogs/containers/amazon-eks-launches-ipv6-support
Full manifest looks like:
```
apiVersion: v1
kind: Service
metadata:
  name: my-lb
  annotations:
    "external-dns.alpha.kubernetes.io/hostname": 'xxxxx'
    "service.beta.kubernetes.io/aws-load-balancer-type": 'external'
    "service.beta.kubernetes.io/aws-load-balancer-nlb-target-type": 'ip'
    "service.beta.kubernetes.io/aws-load-balancer-scheme": 'internet-facing'
    "service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol": 'http'
    "service.beta.kubernetes.io/aws-load-balancer-healthcheck-port": '8080'
    "service.beta.kubernetes.io/aws-load-balancer-ip-address-type": 'dualstack'
spec:
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    aa: bb
  sessionAffinity: None
  type: LoadBalancer
```
