### ISSUE TITLE
Merge ALB rules by the same host

### ISSUE THREAD

**Issue by michaelkoro** [kubernetes-sigs/aws-load-balancer-controller#2678]
**Is your feature request related to a problem?**
We would like to be able to merge rules in the ingress resource, on the ALB level.

For example, when creating the following - 

```
spec:
  rules:
    - http:
        paths:
          - path: /test1
            pathType: ImplementationSpecific
            backend:
              service:
                name: service_name
                port:
                  number: 80
          - path: /test2
            pathType: ImplementationSpecific
            backend:
              service:
                name: service_name
                port:
                  number: 80
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: service_name
                port:
                  number: 80
```
We want the controller to merge the two paths in the first rule, and create one rule in the ALB.
We are aware of the `conditions` annotation, but unfortunately working with it dynamically is very complicated.
Is there an easier way?

**Comment by kishorj** [comment]
@michaelkoro, we can optimize in limited situations - for consecutive rules so as to honor the ingress group order. Also the current ALB limit is max 5 conditions per rule.

Are you hitting the rules quotas or have other concerns?

/kind feature

**Comment by acgs771126** [comment]
+1, maybe this feature can prevent hit AWS ELB listener rule api throttle

**Comment by benjefferies** [comment]
+1 would be great to see this in v2.6.0

**Comment by henryzhao95** [comment]
+1, would love to see multiple hostnames with same backing service grouped together!

```
spec:
  ingressClassName: group1
  rules:
    - host: bar.api.internal
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: awesome-service
              port:
                number: 443
    - host: foo.api.internal
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: awesome-service
              port:
                number: 443
```
