### ISSUE TITLE
Cannot exceed 10 minutes idle connections

### ISSUE THREAD

**Issue by blackheaven** [kubernetes-sigs/aws-load-balancer-controller#2681]
**Describe the bug**
Despite configuring all timeout attributes (see `ingress.yaml` below), I cannot keep a connection idle for more then 10 minutes.

**Steps to reproduce**

* Set up the controller
* Install a long running HTTP server (in my case [mercure.rocks](https://artifacthub.io/packages/helm/mercure/mercure), a SSE server)
* Setup the `ingress.yaml` below
* Try a get on the long/idling endpoint (eg. `/.well-known/mercure`)

**Expected outcome**
It should timeout after a longer time (here, 4000s)

**Environment**

* AWS Load Balancer controller version: aws-load-balancer-controller-1.2.6 /  v2.2.3
* Kubernetes version: v1.21.9
* Using EKS: yes, v1.21.9-eks-14c7a48

**Additional Context**:
`ingress.yaml` content:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: updates-ingress
  namespace: mercure
  annotations:
    # argocd.argoproj.io/sync-options: Validate=false
    # argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    # create AWS Application LoadBalancer
    kubernetes.io/ingress.class: alb
    # external type
    alb.ingress.kubernetes.io/scheme: internet-facing
    # AWS Certificate Manager certificate's ARN
    alb.ingress.kubernetes.io/certificate-arn: arn...
    # open ports 80 and 443 
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    # redirect all HTTP to HTTPS
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    # Fix long connections (https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#custom-attributes)
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=4000
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true, idle_timeout.timeout_seconds=4000
    alb.ingress.kubernetes.io/auth-session-timeout: '86400'
    # ExternalDNS settings: https://rtfm.co.ua/en/kubernetes-update-aws-route53-dns-from-an-ingress/
    external-dns.alpha.kubernetes.io/hostname: sse.example.org

    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: default

spec:
  rules:
  - host: sse.example.org
    http:
      paths:
        - path: /.well-known/mercure
          pathType: Exact
          backend:
            service:
              name: mercure
              port:
                number: 80
```
