### ISSUE TITLE
Question: External resource IPs not being added to targetgroup

### ISSUE THREAD

**Issue by jt-sh** [kubernetes-sigs/aws-load-balancer-controller#2683]
Hello, I know this is maybe a bit unorthodox as I'm trying to use the ALB controller to create an ingress for an external service. 

Trying to put AmazonMQ (rabbitmq) behind an ingress to get a custom domain and auth. My approach has been to get the IPs from the provided UI URI and create an `Endpoint` with the external IPs, attach that to a service, then create an ingress of type IP in hopes that it would add the external IPs from the Endpoint to the target group. Everything creates as expected except the targets. The IPs for MQ are internal VPC IPs.

**Example Config**

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-port: '443'
    alb.ingress.kubernetes.io/auth-type: oidc
    alb.ingress.kubernetes.io/auth-idp-oidc: '{"issuer":"https://accounts.google.com","authorizationEndpoint":"https://accounts.google.com/o/oauth2/v2/auth","tokenEndpoint":"https://oauth2.googleapis.com/token","userInfoEndpoint":"https://www.googleapis.com/oauth2/v3/userinfo","secretName":"secret"}'
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-scope: 'email profile'
    alb.ingress.kubernetes.io/auth-session-cookie: Cookie
    alb.ingress.kubernetes.io/auth-session-timeout: '28800'
  name: rabbit
spec:
  rules:
  - host: rabbit.example.com
    http:
      paths:
      - backend:
          service:
            name: rabbit
            port:
              number: 443
        path: /*
        pathType: ImplementationSpecific
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: rabbit
subsets:
  - addresses:
      - ip: 10.3.0.1
      - ip: 10.3.0.2
      - ip: 10.3.0.3
    ports:
      - port: 443

```

**Expected outcome**
Take the IPs from the Endpoint and add them as targets to the targetGroup.

**Environment**

* AWS Load Balancer controller version - 2.4.0
* Kubernetes version - 1.21
* Using EKS (yes/no), if so version? - Yes
