### ISSUE TITLE
HTTPS listeners not created / annotation options seemingly ignored

### ISSUE THREAD

**Issue by derytim** [kubernetes-sigs/aws-load-balancer-controller#2687]
**Describe the bug**
I have recently upgraded from the `aws-ingress-controller` to `aws-load-balancer-controller`
I have an ingress config that won't create listeners that aren't default.

Here's my config with sensitive info redacted:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-service
  labels:
    app: my-service
  annotations:
    alb.ingress.kubernetes.io/listenPorts: '[{"HTTP":80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/loadBalancerAttributes: idle_timeout.timeout_seconds=600,deletion_protection.enabled=false
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/sslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/tags: Name=My Service
    alb.ingress.kubernetes.io/targetType: ip

spec:
  ingressClassName: alb
  rules:
    - host: my-service.my-host.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: my-service-backend
                port:
                  name: http
    - host: my-service.real-domain.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: my-service-backend
                port:
                  name: http
```
**Steps to reproduce**

When I attempt to apply this config, the aws-lb-controller pod logs show the error `"error":"listener does not exist for SSLRedirect port: 443"`
If I remove the `ssl-redirect` annotation, a load balancer is created, but only has listeners on HTTP port 80.

If I change the annotation `alb.ingress.kubernetes.io/listenPorts: '[{"HTTP":80}, {"HTTPS":443}]'` to only contain `{"HTTPS":443}`, the LB still only contains HTTP port 80 listeners, and the aws-lb-controller pod logs don't show any errors.

If I add the annotation `alb.ingress.kubernetes.io/certificate-arn` with a certificate ARN, the controller will add only HTTPS port 443 listeners, even if I specify `alb.ingress.kubernetes.io/listenPorts: '[{"HTTP":80}]'` or `alb.ingress.kubernetes.io/ssl-redirect: "443"` (in conjunction with listenPorts `'[{"HTTP":80}, {"HTTPS":443}]'` annotation).

Just for kicks and grins, I also attempted to add additional HTTP and HTTPS ports to the listenPorts config `8080, 8443`, and those listeners also weren't created.

**Expected outcome**
Applying the above config should create an ALB with HTTP port 80 and HTTPS port 443 listeners, with the HTTP listeners redirected to HTTPS port 443.

**Environment**

* AWS Load Balancer controller version - 2.4.1
* Kubernetes version - 1.20
* Using EKS (yes/no), if so version? yes, eks.6

**Additional Context**:
I have a second ALB controlled by the same lb controller, with a similar config, and it works as expected wrt HTTP/HTTPS listeners created and HTTPS redirects working.
