### ISSUE TITLE
NLB: External IP pending with type: LoadBalancer

### ISSUE THREAD

**Issue by ONordander** [kubernetes-sigs/aws-load-balancer-controller#2689]
**Describe the bug**
Creating a service of type LoadBalancer doesn't update the external IP of the service.
The LoadBalancer is successfully created and I can reach my service, but the `status.loadBalancer.ingress` of the service is never updated.

**Steps to reproduce**
Create service:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: proxy_protocol_v2.enabled=true
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
  name: test-svc
  namespace: nginx
spec:
  type: LoadBalancer
  ports:
    - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: nginx
```

**Expected outcome**
The status of the service should be updated.

**Environment**

* AWS Load Balancer controller version v2.4.1
* Kubernetes version v1.22
* Using EKS (yes/no), if so version? Yes

**Additional Context**:
Not using AWS CNI, using Cilium. Everything looks fine in the logs and events, nothing out of the ordinary.
I tried changing the service from `LoadBalancer` -> `NodePort` and then the status is updated correctly, but unfortunately I can only use the LoadBalancer type.
