### ISSUE TITLE
Backend app & healthcheck using different protocol versions

### ISSUE THREAD

**Issue by kncesarini** [kubernetes-sigs/aws-load-balancer-controller#2694]
**Describe the bug**
We have a kong ingress controller (in EKS) sitting behind an ALB. The controller is listening on port 80 using http/2 as it's routing gRPC traffic. It additionally has its health check, using http/1.1, on port 10254.

It doesn't seem to be possible to reconcile these differences currently. When I set

alb.ingress.kubernetes.io/backend-protocol-version: HTTP2

the health check fails (Target.FailedHealthChecks). When I change this to HTTP1, the health check works, but the controller doesn't.

**Steps to reproduce**

Using this sample ingress definition (with a backend service "kong-proxy" listening on port 80 using http2, and port 10254 using http/1.1)

`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP2
    alb.ingress.kubernetes.io/certificate-arn: **your certificate arn**
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/healthcheck-port: "10254"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip
  name: kong-ingress
  namespace: kong
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: kong-proxy
            port:
              number: 80
        path: /
        pathType: Prefix`

**Expected outcome**
Health check can use a different protocol version than the backend

**Environment**

* AWS Load Balancer controller version v2.4.0
* Kubernetes version v1.22.6
* Using EKS (yes/no), if so version? yes eks.2

**Comment by kishorj** [comment]
@kncesarini, I see you specified the healthcheck port/protocol/path manually and is different from the traffic port, it should have worked. I'm not familiar with kong-ingress proxy. Would you be able to post the model for your ingress group? And on your worker node running your application, could you check the requests to the health check port from the ALB?

**Comment by kishorj** [comment]
@kncesarini, since we've not heard back for a while, I'm closing the issue. If you have further concerns, feel free to reach out to us.

**Comment by McPatate** [comment]
Hello, I'm having the same issue when trying to deploy grafana tempo to EKS.

I would like the traffic to be routed via GRPC to my pods (so HTTP2 traffic IIUC), but my healthcheck be HTTP1.x, on the same backend, path & port.

Currently, I'm getting `400`s by tempo with the following logs:
```
xx.xx.xx.xx - - [28/Nov/2022:18:44:39 +0000]  400 "PRI * HTTP/2.0" 158 "-" "-" "-"
xx.xx.xx.xx - - [28/Nov/2022:18:44:39 +0000]  400 "PRI * HTTP/2.0" 158 "-" "-" "-"
xx.xx.xx.xx - - [28/Nov/2022:18:44:39 +0000]  400 "PRI * HTTP/2.0" 158 "-" "-" "-"
```

It seems it would be useful to have a `alb.ingress.kubernetes.io/healthcheck-protocol-version` the same way there is a `alb.ingress.kubernetes.io/backend-protocol-version` annotation.

My ingress:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-name: my-alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  name: tempo-gateway
  namespace: tempo
spec:
  rules:
  - host: some.host
    http:
      paths:
      - backend:
          service:
            name: tempo-gateway
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - some.host
```
