### ISSUE TITLE
Incorrect IP range set by LB controller for internal NLB

### ISSUE THREAD

**Issue by tanvp112** [kubernetes-sigs/aws-load-balancer-controller#2699]
**Describe the bug**

The IP range added by AWS LB Controller for the internal NLB does not cover the provisioned internal LB's IP. As a result, connection from the internal NLB to the registered target on EKS cluster is blocked.

**Steps to reproduce**

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - name: http
      containerPort: 80
---
  apiVersion: v1
  kind: Service
  metadata:
    name: nginx-lb
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
  spec:
    type: LoadBalancer
    selector:
      run: nginx
    ports:
    - name: http
      port: 8080
      targetPort: http
```

The internal NLB was provisioned successfully:

![image](https://user-images.githubusercontent.com/57385114/174613731-1c8fbb19-b525-4cc0-860d-55edad262ec9.png)

Target registered successfully:

![image](https://user-images.githubusercontent.com/57385114/174613933-9344cf54-01e8-45a6-ac69-b3ab5f6da3d0.png)

Now, exec into a pod and resolve the internal NLB DNS name result to:

![image](https://user-images.githubusercontent.com/57385114/174616250-d99ac750-4cb0-47df-a743-8d25f598193d.png)

**Noticed that the resolved internal NLB IP is NOT in the IP range added by LB controller**:

![image](https://user-images.githubusercontent.com/57385114/174614354-fb8d10bd-606f-44d7-94c4-c4cbf3d81073.png)

10.236.32.0/19 range is **10.236.32.1 to 10.236.63.254** that does not cover the internal NLB IP (**10.236.67.52**), this means the internal NLB will not able to reach the registered target IP **10.236.84.139** as the security group will block it, right? As a result, `curl` with the internal NLB DNS has failed but when `curl` directly to the target IP succeeded.

**Expected outcome**

The IP range added by AWS LB controller needs to ensure it covers the internal NLB IP.

* AWS Load Balancer controller version

2.4.2

* Using EKS (yes/no), if so version?

1.22
