### ISSUE TITLE
deletion_protection Issue when using IngressGroup

### ISSUE THREAD

**Issue by chjtwork** [kubernetes-sigs/aws-load-balancer-controller#2706]
**Describe the bug**
I upgraded the aws-load-balancer-controller version from 2.2 to 2.4.2 and get this problem.
It‘s about the ALB's deletion protection when using IngressGroup.

**Steps to reproduce**
We use the IngressGroup to make multi ingresses using the same ALB.
And we set `alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true` to turn on ALB's delete protection on aws console.
So the Ingress config file will be like this
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test001
  annotations:
    alb.ingress.kubernetes.io/group.name: test
    alb.ingress.kubernetes.io/group.order: '100'
    alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
```
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test002
  annotations:
    alb.ingress.kubernetes.io/group.name: test
    alb.ingress.kubernetes.io/group.order: '200'
    alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
````

In Version 2.2, if I want to delete one ingress，I can delete it directly (eg: kubectl delete ing test002), and the alb rule of test002 will also be deleted normally.
But in Version 2.4, the command (kubectl delete ing test002) will get stuck, the Ingress object will not be deleted, and I get the error log in the aws-load-balancer-controller
`{"level":"error","ts":1656066288.795328,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"test","namespace":"","error":"deletion_protection is enabled, cannot delete the ingress: test002"}`

So when using IngressGroup, how to delete some ingress within the IngressGroup, just like deleting a part of the alb rules and keeping the deletion protection turned on.

And I think `alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true` is an ALB Level attribute. 
If I try to set different values on different Ingress of the same IngressGroup, it will get the error log like `{"level":"error","ts":1656310200.3805873,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"test","namespace":"","error":"conflicting attributes deletion_protection.enabled: true | false"}`

**Environment**

* AWS Load Balancer controller 2.4.2
* EKS 1.21

**Additional Context**:
