### ISSUE TITLE
`serviceAccount.create` not used when installing with CDK helm provider

### ISSUE THREAD

**Issue by chalford** [kubernetes-sigs/aws-load-balancer-controller#2707]
**Describe the bug**

When add `aws-load-balancer-controller` to a cluster with the EKS CDK construct, the `serviceAccount.create` and `serviceAccount.name` values seem to be ignored when Helm deploys the chart. This may be a bug with the CDK / CDK Helm provider, but need to check that the problem isn't with the Helm chart. I think the CDK Helm Provider uses `upgrade` to install charts.

This can be seen by inspecting the `serviceAccountName` of the aws-load-balancer-controller deployment, which will be set to something different to the `serviceAccount.name` value, or, if you happen to set the service account name to the same name as the chart release, you should get an error when helm tries to create a service account of the same name as your existing one.

**Steps to reproduce**

Add the following CDK (this is in TypseScript) to an EKS Cluster construct:

```
    cluster.addHelmChart('AWSLoadBalancerController', {
      chart: 'aws-load-balancer-controller',
      repository: 'https://aws.github.io/eks-charts',
      namespace: 'kube-system',
      createNamespace: false,
      version: 'v1.4.2',
      values: {
        clusterName: cluster.clusterName,
        'serviceAccount.create': false,
        'serviceAccount.name': 'an-existing-service-account',
        region: cluster.env.region,
        vpcId: cluster.vpc.vpcId,
        'image.repository':
          '602401143452.dkr.ecr.eu-west-2.amazonaws.com/amazon/aws-load-balancer-controller',
      },
    });
```

Run `cdk deploy`.

**Expected outcome**

aws-load-balancer-controller should be deployed, and, with these values, a service account should not be created, and the deployment's service account name should point to the already existing service account.

**Environment**

* AWS Load Balancer controller version: 2.4.2 / Helm chart 1.4.2
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version? Yes, version `eks.7`

**Additional Context**:

**Comment by kishorj** [comment]
@chalford, is there a dry run option with CDK? If so, what does the spec look like?

**Comment by chalford** [comment]
It doesn't look particularly useful, I'm afraid:
```
esstestclusterchartAWSLoadBalancerControllerD0C1C04D:
    Type: Custom::AWSCDK-EKS-HelmChart
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - awscdkawseksKubectlProviderNestedStackawscdkawseksKubectlProviderNestedStackResourceA7AEBA6B
          - Outputs.EssStackCdkStackawscdkawseksKubectlProviderframeworkonEvent0614268BArn
      ClusterName:
        Ref: esstestclusterC714547C
      RoleArn:
        Fn::GetAtt:
          - esstestclusterCreationRole4DC8A812
          - Arn
      Release: kesstestclusterchartawsloadbalancercontrollerd192d827
      Chart: aws-load-balancer-controller
      Version: v1.4.2
      Values:
        Fn::Join:
          - ""
          - - '{"clusterName":"'
            - Ref: esstestclusterC714547C
            - '","serviceAccount.create":false,"serviceAccount.name":"aws-load-balancer-controller","region":"eu-west-2","vpcId":"'
            - Ref: esstestclusterDefaultVpc52E86EFD
            - '","image.repository":"602401143452.dkr.ecr.eu-west-2.amazonaws.com/amazon/aws-load-balancer-controller"}'
      Namespace: kube-system
      Repository: https://aws.github.io/eks-charts
    DependsOn:
      - esstestclusterKubectlReadyBarrier91665D33
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: EssStackCdkStack/ess-test-cluster/chart-AWSLoadBalancerController/Resource/Default
```

I'm planning on testing the installation of the chart manually with `helm upgrade` instead of `install`, to see if I can replicate the problem.
