### ISSUE TITLE
Ingress path is not working on AWS ALB

### ISSUE THREAD

**Issue by git4suvendu** [kubernetes-sigs/aws-load-balancer-controller#2713]
**Describe the bug**
I am using an EKS cluster on Fargate and deployed AWS Load Balancer Controller for ingress. Using a dummy application (taken Nginx image) deployed one service. Just for the test, I am trying to access the same service from 3 different ingress paths: / and /foo/ and /bar/

AWS is successfully provisioning an ALB while ingress kubernetes object is getting deployed. I am able to access the dummy application (Nginx homepage) by hitting external ALB on path '/'.

http://alb-dns/ # it's opening the Nginx homepage But http://alb-dns/foo/ and http://alb-dns/bar/ are throwing "404 Not Found" error.

Please refer for more details # https://stackoverflow.com/questions/72836842/kubernetes-ingress-with-aws-alb-controller

**Steps to reproduce**
- Deploy EKS
- Deploy AWS LB Controller
- Deploy Kubernetes Manifests

**Expected outcome**
AWS ALB should redirect to Nginx homepage on the three Ingress paths ('/' and '/foo' and '/bar')

**Environment**

**AWS Load Balancer controller version:**  Helm chat version 1.4.2
**Kubernetes version:**  2.0
**Using EKS (yes/no), if so version?:** Yes, Version 1.22
`  required_providers {
    aws        = ">= 3.13.0"
    local      = ">= 1.4"
    random     = ">= 2.1"
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.0"
    }
    helm       = ">= 1.4.1"
  }
}`

**Additional Context**:

**Kubernetes Manifests**

```
---
# Source: game-app/templates/game-app-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ns-fargate-app
  labels:
    app.kubernetes.io/name: sample-game-app
```

```
---
# Source: game-app/templates/game-app-service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: ns-fargate-app
  name: game-app-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: sample-game-app

```
```
---
# Source: game-app/templates/game-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns-fargate-app
  name: sample-game-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-game-app
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample-game-app
    spec:
      containers:
      - image: public.ecr.aws/nginx/nginx:1.21
        imagePullPolicy: Always
        name: sample-game-app
        ports:
        - containerPort: 80
```
        

```
# Source: game-app-ingress/templates/game-app-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ns-fargate-app
  name: game-app-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - http:
        paths:
        - path: /foo/
          pathType: Prefix
          backend:
            service:
                name: game-app-service
                port:
                   number: 80
        - path: /bar/
          pathType: Prefix
          backend:
            service:
                name: game-app-service
                port:
                   number: 80
        - path: /
          pathType: Prefix
          backend:
            service:
                name: game-app-service
                port:
                   number: 80

```
