### ISSUE TITLE
swapping subnet position works

### ISSUE THREAD

**Issue by tooptoop4** [kubernetes-sigs/aws-load-balancer-controller#2715]
my k8s ingress object definition had:
```
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: redact
    alb.ingress.kubernetes.io/group.name: infra-apps
    alb.ingress.kubernetes.io/healthcheck-path: /swaggerui/
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=4000
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/security-groups: redacty,redactz
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/subnets: subnet-redact1,subnet-redact2,subnet-redact3
    alb.ingress.kubernetes.io/tags: redact
    alb.ingress.kubernetes.io/target-type: instance
    external-dns.alpha.kubernetes.io/alias: "true"
    external-dns.alpha.kubernetes.io/hostname: redact
```

load-balancer controller pod logs showing:
```
{"level":"info","ts":1656988783.3797832,"logger":"controllers.ingress","msg":"creating loadBalancer","stackID":"infra-apps","resourceID":"LoadBalancer"}
{"level":"error","ts":1656988783.5488162,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"infra-apps","namespace":"","error":"InvalidSubnet: Not enough IP space available in subnet-redact1. ELB requires at least 8 free IP addresses in each subnet.\n\tstatus code: 400, request id: 46redact"}
{"level":"debug","ts":1656988783.5488386,"logger":"controller-runtime.manager.events","msg":"Warning","object":{"kind":"Ingress","namespace":"argocd","name":"argocd-ingress","uid":"c6redact","apiVersion":"networking.k8s.io/v1","resourceVersion":"54739886"},"reason":"FailedDeployModel","message":"Failed deploy model due to InvalidSubnet: Not enough IP space available in subnet-redact1. ELB requires at least 8 free IP addresses in each subnet.\n\tstatus code: 400, request id: 46redact"}
```

then i changed the order of values in subnets tag like so:
```
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: redact
    alb.ingress.kubernetes.io/group.name: infra-apps
    alb.ingress.kubernetes.io/healthcheck-path: /swaggerui/
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=4000
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/security-groups: redacty,redactz
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/subnets: subnet-redact2,subnet-redact1,subnet-redact3
    alb.ingress.kubernetes.io/tags: redact
    alb.ingress.kubernetes.io/target-type: instance
    external-dns.alpha.kubernetes.io/alias: "true"
    external-dns.alpha.kubernetes.io/hostname: redact
```

and the pod logs started showing successful creation of my loadbalance and listeners.
i also verified that subnet-redact1 was still full.

so i think rather than me manually changing different positions, can the code try each subnet rather than exiting out if the first is lacking IP addresses?
