### ISSUE TITLE
Loadbalancer service type with internal annotation creates public loadbalancer

### ISSUE THREAD

**Issue by FarhadF** [kubernetes-sigs/aws-load-balancer-controller#2737]
Service:

```
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: test
  type: LoadBalancer

```
Please note the annotations: [documentation](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/annotations/#lb-scheme)

Controller version: ```aws-load-balancer-controller:v2.4.2```

The resulting loadbalancer is external instead of internal. From aws console:  ```Scheme: internet-facing```
