### ISSUE TITLE
Service Type.Target Group Binding Settings Issues with ClusterIP.

### ISSUE THREAD

**Issue by oliverpark999** [kubernetes-sigs/aws-load-balancer-controller#2741]
**Describe the bug**
A concise description of what the bug is.

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version -> latest
* Kubernetes version
* Using EKS (yes/no), if so version? yes/1.22

**Additional Context**:

Hello,
I have deployed Deployment, Service, and Ingress as follows.
If you deploy Target Group Binding as [IP] type and check AWS Load Balancer Controller Log, the error continues to occur.
I'm wasting hours on this issue.
Binding works well when deployed as [Service.Type.NodePort], but an error is occurring when deployed as [ClusterIP].
What kind of problem?

```
apiVersion: v1
kind: Namespace
metadata:
  name: sample-ns
---
apiVersion: v1
kind: Service
metadata:
  name: service-sample-nginx
  namespace: sample-ns
  labels:
    app: sample-nginx
spec:
  selector:
    app: sample-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: sample-ns
  labels:
    app: sample-nginx
spec:
  selector:
    matchLabels:
      app: sample-nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: sample-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.2
          ports:
            - containerPort: 80
```

```
apiVersion: elbv2.k8s.aws/v1alpha1
kind: TargetGroupBinding
metadata:
  name: sample-tgb
  namespace: sample-ns
spec:
  serviceRef:
    name: service-sample-nginx
    port: 80
  targetGroupARN: <tg arn>
  targetType: ip
  networking:
    ingress:
      - from:
          - securityGroup:
              groupID: <sg>
        ports:
          - protocol: TCP
```

Error: 
```
{"level":"info","ts":1658997332.596294,"msg":"registering targets","arn":"arn:aws:elasticloadbalancing:xxxxx2:targetgroup/xxx-tg/1d6ec858739afd26","targets":[{"AvailabilityZone":null,"Id":"10.xx.xx.xx","Port":80},{"AvailabilityZone":null,"Id":"10.xx.xx.xx","Port":80},{"AvailabilityZone":null,"Id":"10.xx.xx.xx","Port":80}]}
{"level":"error","ts":1658997332.624734,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Reconciler error","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","name":"sample-tgb","namespace":"sample-ns","error":"ValidationError: Instance ID '10.xx.xx.xx' is not valid\n\tstatus code: 400, request id: 3473ee79-3xx.xxxx.xx0c210fd1"}
```
