### ISSUE TITLE
Targets aren't registered until ALB ingress controller pods are restarted

### ISSUE THREAD

**Issue by dusansusic** [kubernetes-sigs/aws-load-balancer-controller#2755]
**Describe the bug**

In our particular case, we have 2 deployments, 2 services, and 1 ingress rule.
We are using the A/B deployment type where we update annotation to:
- Service/deployment A is receiving 100% of the traffic
- deploy B and wait until readiness gates are passing
- update annotation to forward 100% of traffic to go to service/deployment B

From this:
```
"alb.ingress.kubernetes.io/actions.backend-svcs" : jsonencode({ "type" : "forward", "forwardConfig" : { "targetGroups" : [{ "serviceName" : "a-svc", "servicePort" : 443, "weight" : 0 }, { "serviceName" : "b-svc", "servicePort" : 443, "weight" : 100 }] } })
```

We update it to:

```
"alb.ingress.kubernetes.io/actions.backend-svcs" : jsonencode({ "type" : "forward", "forwardConfig" : { "targetGroups" : [{ "serviceName" : "a-svc", "servicePort" : 443, "weight" : 100 }, { "serviceName" : "b-svc", "servicePort" : 443, "weight" : 0 }] } })
```

And this work as expected. The problematic part is that we have occasional situations where readiness gates won't pass until we restart ingress controller pods and wait until these are up again. After pod restart, the readiness gate passes correctly. 

**Steps to reproduce**
Unclear how to reproduce, it just stops working. Logs are full of messages:
```
2022/08/06 22:00:00 http: TLS handshake error from 10.20.211.122:47690: EOF
2022/08/07 01:52:00 http: TLS handshake error from 10.20.211.122:40552: EOF
2022/08/07 04:29:00 http: TLS handshake error from 10.20.211.122:49710: EOF
2022/08/07 06:26:00 http: TLS handshake error from 10.20.211.122:42996: EOF
```

**Expected outcome**
Readiness gate is passing without restarting ALB ing controller 

**Environment**

* AWS Load Balancer controller version: 2.4.1 installed with helm, crds installed befored each helm upgrade.
* Kubernetes version: 1.22
* Using EKS (yes/no), if so version? Yes, 1.22

**Comment by kishorj** [comment]
@dusansusic, would you be able to share the controller logs? You can email them to k8s-alb-controller-triage AT amazon.com

**Comment by dusansusic** [comment]
@kishorj logs are sent to given mail. Thanks!

**Comment by dusansusic** [comment]
It just happened again. Described one of the pods and caught this:

```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-08-15T10:55:29Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-08-15T10:55:29Z"
    message: corresponding condition of pod readiness gate "target-health.elbv2.k8s.aws/k8s-default-xxxxxxxx-09a1b04b59"
      does not exist.
    reason: ReadinessGatesNotReady
    status: "False"
```
