### ISSUE TITLE
ALB Rule order

### ISSUE THREAD

**Issue by ngoyal16** [kubernetes-sigs/aws-load-balancer-controller#2763]
**Describe the bug**
If there are 2 ingress objects in EKS with following specs

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-1
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/group.name: g1
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: example-1-svc
                port:
                  name: http


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-2
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/group.name: g1
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /abc/
            pathType: Prefix
            backend:
              service:
                name: example-2-svc
                port:
                  name: http
```

above spec is creating rules in alb with following order

rule1:   host:example.com   path: /*  ->  example-1-svc
rule2:   host:example.com   path: abc or abc/*   ->    example-2-svc

**Expected outcome**
expected rule order should be 

rule1:   host:example.com   path: abc or abc/*   ->    example-2-svc
rule2:   host:example.com   path: /*  ->  example-1-svc

**Environment**

* AWS Load Balancer controller version : v2.4.3
* Kubernetes version : 1.22
* Using EKS (yes/no), if so version?  1.22
