### ISSUE TITLE
Ingress is not created when provisioning ALB controller and Ingress through terraform.

### ISSUE THREAD

**Issue by OHsechun** [kubernetes-sigs/aws-load-balancer-controller#2768]
**Describe the bug**
When I provisioning EKS, ALB Controller and Ingress, below error occurs. (helm chart version 1.4.4, not until 1.4.3)
```
Internal error occurred: failed calling webhook "vingress.elbv2.k8s.aws": Post "[https://aws-load-balancer-webhook-service.kube-system.svc:443/validate-networking-v1beta1-ingress?timeout=10s](https://aws-load-balancer-webhook-service.kube-system.svc/validate-networking-v1beta1-ingress?timeout=10s)": dial tcp 10.0.x.x:9443: connect: connection refused
```

I read issue about this error message, but that was not my case. (https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2462)
Because I already added rule for cluster security group to access eks-node security group through 1025-65535 port.

Just one suspicious thing I think is that terraform helm_release resource's argument 'wait' (default true) is not applied ALB webhook service. So terraform kubernetes_ingress resource provisioning started even though ALB webhook service was not up.

When applying remaining resource provisioning with "terraform apply", no error occurs. (when first applying, ALB Controllers were deployed well, so applying again will create only Ingress)

**Steps to reproduce**

When there are already vpc and eks, start below terraform resource provisioning.
```
resource "helm_release" "alb_controller" {
  name       = "alb-ingress-controller"
  repository = "https://aws.github.io/eks-charts"
  namespace  = "kube-system"
  chart      = "aws-load-balancer-controller"
  version = "1.4.4"

  values = [
    "${file("${path.module}/helm-values/alb-controller/values.yaml")}"
  ]

  set {
    name  = "clusterName"
    value = "{your_cluster_name}"
  }

  set {
    name  = "vpcId"
    value = "{your_vpc_id}"
  }

  set {
    name  = "region"
    value = "{your_region}"
  }

  set {
    name  = "serviceAccount.name"
    value = "{your_service_account_name}"
    type  = "string"
  }

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = "{your_service_account_iam_role_arn}"
    type  = "string"
  }
}

resource "kubernetes_ingress" "test_ingress" {
  wait_for_load_balancer = true
  metadata {
    name = "test-ingress"
    namespace = "{your_namespace}"
    annotations = {
      "kubernetes.io/ingress.class" = "alb"
      "alb.ingress.kubernetes.io/security-groups" = "{your_alb_security_group_id}"
      "alb.ingress.kubernetes.io/tags" = "Name=test-ingress"
      "alb.ingress.kubernetes.io/scheme" = "internet-facing"
      "alb.ingress.kubernetes.io/target-group-attributes" = "stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=300"
      "alb.ingress.kubernetes.io/listen-ports" = <<JSON
[
  {"HTTP": 80},
  {"HTTPS": 443}
]
JSON
      "alb.ingress.kubernetes.io/ssl-policy" = "ELBSecurityPolicy-TLS-1-2-2017-01"
      "alb.ingress.kubernetes.io/certificate-arn" = "{your_cert_arn}"
    }
    labels = {
      app = "test-ingress"
    }
  }
  spec {
    backend {
      service_name = "test-service"
      service_port = 80
    }

    rule {
      host = "{your_ingress_domain_name}"
      http {
        path {
          path = "/*"
          backend {
            service_name = "test-service"
            service_port = 80
          }
        }
      }
    }
  }

  depends_on = [
    helm_release.alb_controller
  ]
}
```

**Expected outcome**
Without errors, Ingress is created as same with chart version 1.4.3.

**Environment**
Terraform v1.1.4

* AWS Load Balancer controller version : 2.4.3 (helm chart 1.4.4)
* Kubernetes version : 1.21
* Using EKS (yes/no), if so version? yes (1.21)

**Additional Context**:

**Comment by kishorj** [comment]
@OHsechun, could you confirm whether the ALB got provisioned as expected when  you apply the remaining resource with with "terraform apply"? It is possible the controller is starting up and not ready to serve the webhook. What is the delay you observe?

**Comment by duchoa2015** [comment]
I'm having the same problem but in my case I deploy the helm chart pointing out the values.yml that should be used.

```
➜  manifest git:(master) ✗ kubectl apply -f ingress.yml 
Error from server (InternalError): error when creating "ingress.yml": Internal error occurred: failed calling webhook "vingress.elbv2.k8s.aws": the server could not find the requested resource
```


Here is my values.yml to do helm install 

```
# Default values for aws-load-balancer-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 602401143452.dkr.ecr.sa-east-1.amazonaws.com/amazon/aws-load-balancer-controller
  tag: v2.4.2
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# The name of the Kubernetes cluster. A non-empty value is required
clusterName: ug-eks-dev

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    iam.amazonaws.com/role: dev-aws-load-balancer-controller-role
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
  # Automount API credentials for a Service Account.
  automountServiceAccountToken: true

rbac:
  # Specifies whether rbac resources should be created
  create: true

podSecurityContext:
  fsGroup: 65534

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  allowPrivilegeEscalation: false

# ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass
priorityClassName: system-cluster-critical

podAnnotations:
  iam.amazonaws.com/role: dev-aws-load-balancer-controller-role

# Enable cert-manager
enableCertManager: false

# The ingress class this controller will satisfy. If not specified, controller will match all
# ingresses without ingress class annotation and ingresses of type alb
ingressClass: alb

# To use IngressClass resource instead of annotation, before you need to install the IngressClass resource pointing to controller.
# If specified as true, the IngressClass resource will be created.
createIngressClassResource: false

# The AWS region for the kubernetes cluster. Set to use KIAM or kube2iam for example.
region: sa-east1

# keepTLSSecret specifies whether to reuse existing TLS secret for chart upgrade
keepTLSSecret: false

livenessProbe:
  failureThreshold: 2
  httpGet:
    path: /healthz
    port: 61779
    scheme: HTTP
  initialDelaySeconds: 30
  timeoutSeconds: 10

hostNetwork: false
```

I downloaded the policies and created them via terraform.

`https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/main/docs/install/iam_policy.json`


When I use the same policy and create the IAM Service Account using the steps below, the ingress is created normally. I noticed that the only difference is that with the commands below a role is created linking the OIDC to the role's trust relationship.

```bash
$ eksctl utils associate-iam-oidc-provider --region=sa-east-1 --cluster=ug-eks-dev --approve

$ eksctl create iamserviceaccount \
--cluster=CLUSTER_NAME\
--namespace=kube-system \
--name=aws-load-balancer-controller \
--attach-policy-arn= here Im poiting to policy created by terraform \
--override-existing-serviceaccounts \
--approve

$ eksctl get iamserviceaccount --cluster ug-eks-dev --name aws-load-balancer-controller --namespace kube-system

$ helm repo add eks https://aws.github.io/eks-charts

$ helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
--set clusterName=CLUSTER_NAME\
--set serviceAccount.create=false \
--set region=REGION \
--set vpcId=VPC_ID \
--set serviceAccount.name=aws-load-balancer-controller \
--version 1.3.3 \
--namespace kube-system
```

The controllers are running but they don't create any target groups or make any changes to my AWS hosted ALB.

Here some logs from my controllers

```
{"level":"info","ts":1660778637.2536073,"msg":"version","GitVersion":"v2.4.2","GitCommit":"77370be7f8e13787a3ec0cfa99de1647010f1055","BuildDate":"2022-05-24T22:33:27+0000"}                                 ││ {"level":"info","ts":1660778637.336609,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}                                                                    ││ {"level":"info","ts":1660778637.3457322,"logger":"setup","msg":"adding health check for controller"}                                                                                                         ││ {"level":"info","ts":1660778637.3458135,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-v1-pod"}                                                                           ││ {"level":"info","ts":1660778637.3459122,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}                                         ││ {"level":"info","ts":1660778637.3459709,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}                                       ││ {"level":"info","ts":1660778637.3460464,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-networking-v1-ingress"}                                                          ││ {"level":"info","ts":1660778637.3461006,"logger":"setup","msg":"starting podInfo repo"}                                                                                                                      ││ {"level":"info","ts":1660778639.3463001,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}                                                                             ││ {"level":"info","ts":1660778639.346514,"logger":"controller-runtime.webhook.webhooks","msg":"starting webhook server"}                                                                                       ││ I0817 23:23:59.346454       1 leaderelection.go:243] attempting to acquire leader lease kube-system/aws-load-balancer-controller-leader...                                                                   ││ {"level":"info","ts":1660778639.3474605,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}                                                                                   ││ {"level":"info","ts":1660778639.3476636,"logger":"controller-runtime.webhook","msg":"serving webhook server","host":"","port":9443}                                                                          ││ {"level":"info","ts":1660778639.347736,"logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}                                                                                       ││ I0817 23:24:14.562617       1 leaderelection.go:253] successfully acquired lease kube-system/aws-load-balancer-controller-leader                                                                             ││ {"level":"info","ts":1660778654.5629084,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Starting EventSource","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBi ││ nding","source":"kind source: /, Kind="}                                                                                                                                                                     ││ {"level":"info","ts":1660778654.5629475,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Starting EventSource","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBi ││ nding","source":"kind source: /, Kind="}                                                                                                                                                                     ││ {"level":"info","ts":1660778654.562953,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Starting EventSource","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBin ││ ding","source":"kind source: /, Kind="}                                                                                                                                                                      ││ {"level":"info","ts":1660778654.5629578,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Starting EventSource","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBi ││ nding","source":"kind source: /, Kind="}                                                                                                                                                                     ││ {"level":"info","ts":1660778654.562966,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Starting Controller","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBind ││ ing"}
```
