### ISSUE TITLE
Failed to use TargetGroupBinding in EKS

### ISSUE THREAD

**Issue by andrewkwok2022** [kubernetes-sigs/aws-load-balancer-controller#2769]
I want to adopt TargetGroupBinding from AWS Load Balancer Controller to bind my existing target group. However, after trying to apply the below yaml file several times, I still cannot bind the target group.

**tgb.yaml** 

```
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  namespace: fargate-api-dev
  name: k8s-co1-dev
  labels:
    ingress.k8s.aws/stack: api-dev
spec:
  serviceRef:
    name: k8s-co1-dev
    port: 4001
  targetGroupARN: arn:aws:elasticloadbalancing:region:accountid:targetgroup/targetGroupName/b6db5c4683441902
  targetType: ip
```

**ingress.yaml**

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: fargate-api-dev
  name: k8s-co1-dev
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: fargate-api-dev
    alb.ingress.kubernetes.io/group.name: api-dev
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 4001}]'
    alb.ingress.kubernetes.io/subnets: subnet-A, subnet-B, subnet-C
    alb.ingress.kubernetes.io/security-groups: sg-A, sg-B
    alb.ingress.kubernetes.io/healthcheck-path: /healthCheck
    alb.ingress.kubernetes.io/success-codes: '200'

spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k8s-co1-dev
                port:
                  number: 4001
```

The system preferred to create its own target group rather than followed my tgb.yaml.

```
$ k get targetgroupbinding
NAME                               SERVICE-NAME   SERVICE-PORT   TARGET-TYPE   AGE
k8s-co1-dev                        k8s-co1-dev    4001           ip            3h6m
k8s-fargatea-k8sco1de-cc5c487714   k8s-co1-dev    4001           ip            3h7m
```

Both targetgroupbindings show the same event by using `kubectl describe targetgroupbinding` command

```
Events:
  Type    Reason                  Age                  From                Message
  ----    ------                  ----                 ----                -------
  Normal  SuccessfullyReconciled  55s (x4 over 2m58s)  targetGroupBinding  Successfully reconciled
```

I have also checked the log in aws-load-balancer-controller, no error log was found.

I used helm to install aws-load-balancer-controller. I noticed that the TargetGroupBinding CRDs are needed to install before helm upgrade and I did that. So what is the possible solution for this problem? 

Thank you 

* AWS Load Balancer controller version 2.4.2
* Kubernetes version 1.22
* Using EKS (yes/no), if so version? 1.22
