### ISSUE TITLE
not authorized

### ISSUE THREAD

**Issue by kennedy-dan** [kubernetes-sigs/aws-load-balancer-controller#2796]
I installed the aws load balancer in my kube-system namespace. I was given 2 pods  kubectl get pods -n kube-system
```
NAME                                           READY   STATUS    RESTARTS   AGE
aws-load-balancer-controller-b59598568-r8kss   1/1     Running   0          16d
aws-load-balancer-controller-b59598568-ttrcr   1/1     Running   0          16d
```
when i logged the first pod, I got no error, but when i log the second pod i got this error

```
 kubectl logs -n  kube-system aws-load-balancer-controller-b59598568-ttrcr
{"level":"info","ts":1661530054.6011205,"msg":"version","GitVersion":"v2.4.3","GitCommit":"6d3e976e3f60dc4588c01bad036d77c127a68e71","BuildDate":"2022-08-09T20:57:15+0000"}
{"level":"info","ts":1661530054.6310318,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1661530054.634033,"logger":"setup","msg":"adding health check for controller"}
{"level":"info","ts":1661530054.6341336,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-v1-pod"}
{"level":"info","ts":1661530054.634261,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
{"level":"info","ts":1661530054.634346,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
{"level":"info","ts":1661530054.6344583,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-networking-v1-ingress"}
{"level":"info","ts":1661530054.634535,"logger":"setup","msg":"starting podInfo repo"}
{"level":"info","ts":1661530056.6347249,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1661530056.634846,"logger":"controller-runtime.webhook.webhooks","msg":"starting webhook server"}
I0826 16:07:36.635052       1 leaderelection.go:243] attempting to acquire leader lease kube-system/aws-load-balancer-controller-leader...
{"level":"info","ts":1661530056.6351433,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":1661530056.635842,"logger":"controller-runtime.webhook","msg":"serving webhook server","host":"","port":9443}
{"level":"info","ts":1661530056.636086,"logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
E0906 01:43:12.046826       1 leaderelection.go:325] error retrieving resource lock kube-system/aws-load-balancer-controller-leader: Unauthorized
```

If i go to the dns url http://k8s-kerberos-factory-****6.us-east-1.elb.amazonaws.com/login, I get the login page, but when i try to log in I get : **http://api.k8s-kerberos-factory-4412a642d6-123.us-east-1.elb.amazonaws.com/login net::ERR_NAME_NOT_RESOLVED**

my deployment.yaml

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: factory
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    # kubernetes.io/ingress.class: nginx
spec:
  rules:
  - 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: factory
            port: 
              number: 80
  - host:
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: factory
            port: 
              number: 8082

```
when i checked my health checks i got Health checks failed with these codes: [401], which i assume is referring to this pod aws-load-balancer-controller-b59598568-ttrcr
