### ISSUE TITLE
Controller does not create target group without specifying "certificate-arn" annotation

### ISSUE THREAD

**Issue by useownyxis** [kubernetes-sigs/aws-load-balancer-controller#2799]
Hello, I got a problem with using aws-lb-controller. I'm trying to provide access to EKS cluster via Ingress Rules.

My setup:
  ```
Kubernetes version: 1.21
  aws-load-balancer-controller(installed via Helm):
    Chart: aws-load-balancer-controller-1.3.3
    AppVersion: v2.3.1
```

My idea was to setup "base" ingress rule which should setup LB with general attributes (like ingress rules, certification-arn, group.name, ssl-redirect and so on) and then deploy application's helm chart with application's ingress rule with the same group.name and target group attributes(target-type, backend-protocol, healthcheck path+port+protocol). Then controller should group this rules by group.name and add paths to ALB and create target group for this application. 
Firstly I deployed "base" ingress rule.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: base-ingress
  namespace: my-namespace
  annotations:
    alb.ingress.kubernetes.io/group.name: my-groupname
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/inbound-cidrs: <whitelist of ip addresses>
    alb.ingress.kubernetes.io/certificate-arn: <ACM certificate ARN>
    alb.ingress.kubernetes.io/load-balancer-attributes: <ALB attributes>
    alb.ingress.kubernetes.io/actions.response-404: >
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"404","messageBody":"Not found"}}
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: response-404
            port:
              name: use-annotation
```
And this step works, it created ALB, attached certificate and attributes I need. Then I want to create ingress rule to my app with same group.name
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: my-namespace
  annotations:
    alb.ingress.kubernetes.io/group.name: my-groupname
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: '/'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    alb.ingress.kubernetes.io/success-codes: '200'
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /my-path
        pathType: Prefix
        backend:
          service:
            name: my-app
            port:
              number: 8080
```
And it also work from k8s perspective, controller handled with resource, attached it to my-groupname(I've verified that by controller's logs). When I get this ingress it seem like it works.
```
✗ kubectl get ingress -n my-namespace
NAME                            CLASS          HOSTS      ADDRESS                              PORTS   AGE
base-ingress                    alb             *         my-alb.eu-west-1.elb.amazonaws.com   80      17h
app-ingress                     alb             *         my-alb.eu-west-1.elb.amazonaws.com   80      120m
```
**BUT** controller has not created Target Group and not modified ALB's paths. (No logs in k8s controller's pod about that and no AWS resources). 
 And fact is that when I added alb.ingress.kubernetes.io/certificate-arn annotation(same as in base ingress) to **app ingress** then it works fine(created target group and binding for it). 
 **Expected behaviour:** controller should groups rules by group.name and should create Target groups and bindings to ingress rules without duplication certificate-arn (as I see in docs that it should merge this values, certificate of base-ingress and None of app-ingress).
 **Current behaviour:** controller groups rules by group.name, but doesn't create Target groups without specifying alb.ingress.kubernetes.io/certificate-arn to additional ingress rules with the same group.name.
 
Please feel free to ask me logs, source code and other additional information you need.
