### ISSUE TITLE
Cannot use HTTP health check with gRPC Backend Version

### ISSUE THREAD

**Issue by lamebear** [kubernetes-sigs/aws-load-balancer-controller#2804]
**Describe the bug**
I am unable to create an ALB Ingress with the backend protocol set to GRPC and the health check protocol set to HTTP. The controller givers me the following error:

```
{"level":"error","ts":1663261428.6244795,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"test","namespace":"","error":"ValidationError: Health check matcher GRPC code '200' must be within '0-99' inclusive\n\tstatus code: 400, request id: e8c54cc5-1bd8-4342-906b-7b49dc1807ed"}
```

**Steps to reproduce**

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: 'test-alb'
    alb.ingress.kubernetes.io/group.name: test
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: "8080"
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/certificate-arn: <arn>
    alb.ingress.kubernetes.io/wafv2-acl-arn: <arn>
  name: test-alb
  namespace: default
spec:
  ingressClassName: alb
  rules:
  - host: test.my-domain.dev
    http:
      paths:
      - backend:
          service:
            name: my-service
            port:
              number: 9090
        path: /
        pathType: Prefix
```

**Expected outcome**

I would expect for the load balancer to be created with health checks reachable over HTTP

**Environment**

* AWS Load Balancer controller version: v2.4.2
* Kubernetes version: v1.22.11-eks-18ef993
* Using EKS (yes/no), if so version? yes, assuming platform version: eks.5
