### ISSUE TITLE
load-balancer-source-ranges does not add 0.0.0.0/0 by default

### ISSUE THREAD

**Issue by StefanTUI** [kubernetes-sigs/aws-load-balancer-controller#2806]
**Describe the bug**
A security group entry of source 0.0.0.0/0 was not added to the worker-sg, which results in ERR_EMPTY_RESPONSE errors when 
service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled is set to true.

**Steps to reproduce**
Deploy NLB with the following service yml
```
---
kind: Service
apiVersion: v1
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "redacted"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.3.0
  name: ingress-nginx-controller
  namespace: ingress-nginx-internal-dev

spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      appProtocol: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  type: LoadBalancer
```

**Expected outcome**
According to the [load-balancer-source-ranges documentation](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/annotations/#lb-source-ranges) a security group entry of source 0.0.0.0/0 should be added to the worker-sg if the IPAddressType is "ipv4" (which is default)

**Environment**
TEST

* AWS Load Balancer controller version: 2.4.3
* Kubernetes version: 1.22
* Using EKS (yes), if so version? 1.22

**Additional Context**:
We could solve this by adding the following to the above mentioned yml file:
```
spec:
  loadBalancerSourceRanges:
    - "0.0.0.0/0"
 ```

This results in the following security group entry:
```
Protocol Port    Source    Description
TCP      31907   0.0.0.0/0 elbv2.k8s.aws/targetGroupBinding=shared
```

This would also be the expected entry with with the mentioned documentation.
