### ISSUE TITLE
ALB Controller not creating Target Groups for Istio Ingress Service

### ISSUE THREAD

**Issue by mkkatica** [kubernetes-sigs/aws-load-balancer-controller#2807]
**Describe the bug**
I'm trying to setup an ALB in front of the Istio Ingress Gateway service. For some reason, when provisioning the listener and setting up the rules, the controller creates fixed response 503 rules for the specified path instead of a rule pointing to a target group. I am able to create ALB ingresses to other services correctly.

**Steps to reproduce**
Ingress Definition:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/security-groups: sg-xxxx
    alb.ingress.kubernetes.io/subnets: subnet-xxxx,subnet-xxxx,subnet-xxxx
    alb.ingress.kubernetes.io/target-type: instance
  name: istio-ingressgateway-alb-ingress
  namespace: istio-ingress
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: istio-ingressgateway
            port:
              number: 80
        path: /
        pathType: Prefix
```
Istio Service:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: istio-ingress
    meta.helm.sh/release-namespace: istio-ingress
  labels:
    app: istio-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-ingress
    app.kubernetes.io/version: 1.15.0
    helm.sh/chart: gateway-1.15.0
    istio: ingress
  name: istio-ingress
  namespace: istio-ingress
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.20.207.17
  clusterIPs:
  - 172.20.207.17
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: status-port
    nodePort: 32515
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    nodePort: 30977
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 32019
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: istio-ingress
    istio: ingress
  sessionAffinity: None
  type: LoadBalancer
```
**Expected outcome**
Expect a load balancer created, and the listener on port 80 for the load balancer to forward "/" to a target group pointing to the nodeports of the service.

**Environment**

* AWS Load Balancer controller version: v2.4.2
* Kubernetes version: 1.2.2
* Using EKS (yes/no), if so version? eks.5

**Additional Context**:
Ingress Controller Logs:
```
{"level":"info","ts":1663345091.8612401,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"istio\",\"resources\":{}}"}
{"level":"info","ts":1663345092.2107456,"logger":"controllers.ingress","msg":"deleting loadBalancer","arn":"arn:aws:elasticloadbalancing:us-east-1:xxxxx:loadbalancer/app/k8s-istio-dce0bc0b1e/6c1b54aa19e1f8cc"}
{"level":"info","ts":1663345092.3066335,"logger":"controllers.ingress","msg":"deleted loadBalancer","arn":"arn:aws:elasticloadbalancing:us-east-1:xxxxx:loadbalancer/app/k8s-istio-dce0bc0b1e/6c1b54aa19e1f8cc"}
{"level":"info","ts":1663345092.306704,"logger":"controllers.ingress","msg":"successfully deployed model","ingressGroup":"istio"}
{"level":"info","ts":1663345303.6726043,"logger":"controllers.ingress","msg":"SG configured via annotation","LB SGs":["sg-xxxxx"],"backend SG":null}
{"level":"info","ts":1663345303.672826,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"istio-ingress/istio-ingressgateway-alb-ingress\",\"resources\":{\"AWS::ElasticLoadBalancingV2::Listener\":{\"80\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":80,\"protocol\":\"HTTP\",\"defaultActions\":[{\"type\":\"fixed-response\",\"fixedResponseConfig\":{\"contentType\":\"text/plain\",\"statusCode\":\"404\"}}]}}},\"AWS::ElasticLoadBalancingV2::ListenerRule\":{\"80:1\":{\"spec\":{\"listenerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::Listener/80/status/listenerARN\"},\"priority\":1,\"actions\":[{\"type\":\"fixed-response\",\"fixedResponseConfig\":{\"contentType\":\"text/plain\",\"messageBody\":\"Backend service does not exist\",\"statusCode\":\"503\"}}],\"conditions\":[{\"field\":\"path-pattern\",\"pathPatternConfig\":{\"values\":[\"/*\"]}}]}}},\"AWS::ElasticLoadBalancingV2::LoadBalancer\":{\"LoadBalancer\":{\"spec\":{\"name\":\"k8s-istioing-istioing-xxxxx\",\"type\":\"application\",\"scheme\":\"internal\",\"ipAddressType\":\"ipv4\",\"subnetMapping\":[{\"subnetID\":\"subnet-xxxxx\"},{\"subnetID\":\"subnet-xxxxx\"},{\"subnetID\":\"subnet-xxxxx\"}],\"securityGroups\":[\"sg-xxxxx\"]}}}}}"}
{"level":"info","ts":1663345303.9549134,"logger":"controllers.ingress","msg":"creating loadBalancer","stackID":"istio-ingress/istio-ingressgateway-alb-ingress","resourceID":"LoadBalancer"}
{"level":"info","ts":1663345304.5739024,"logger":"controllers.ingress","msg":"created loadBalancer","stackID":"istio-ingress/istio-ingressgateway-alb-ingress","resourceID":"LoadBalancer","arn":"arn:aws:elasticloadbalancing:us-east-1:xxxxx:loadbalancer/app/k8s-istioing-istioing-c0c32569e0/d63a5786cb98fbf4"}
{"level":"info","ts":1663345304.6263354,"logger":"controllers.ingress","msg":"creating listener","stackID":"istio-ingress/istio-ingressgateway-alb-ingress","resourceID":"80"}
{"level":"info","ts":1663345304.6954856,"logger":"controllers.ingress","msg":"created listener","stackID":"istio-ingress/istio-ingressgateway-alb-ingress","resourceID":"80","arn":"arn:aws:elasticloadbalancing:us-east-1:xxxxx:listener/app/k8s-istioing-istioing-c0c32569e0/d63a5786cb98fbf4/3f67bb004fd1a10a"}
{"level":"info","ts":1663345304.7558112,"logger":"controllers.ingress","msg":"creating listener rule","stackID":"istio-ingress/istio-ingressgateway-alb-ingress","resourceID":"80:1"}
{"level":"info","ts":1663345304.830925,"logger":"controllers.ingress","msg":"created listener rule","stackID":"istio-ingress/istio-ingressgateway-alb-ingress","resourceID":"80:1","arn":"arn:aws:elasticloadbalancing:us-east-1:xxxxx:listener-rule/app/k8s-istioing-istioing-c0c32569e0/d63a5786cb98fbf4/3f67bb004fd1a10a/0677cd1cb5a9a866"}
{"level":"info","ts":1663345304.9466803,"logger":"controllers.ingress","msg":"successfully deployed model","ingressGroup":"istio-ingress/istio-ingressgateway-alb-ingress"}
```
