### ISSUE TITLE
Why does AWS LB Controller delete the load balancer when a target is deregistred?

### ISSUE THREAD

**Issue by winterrobert** [kubernetes-sigs/aws-load-balancer-controller#2814]
We are trying to expose Keycloak (using the Keycloak operator) through this ingress:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /auth/health/live
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}, {"HTTP": 8080}, {"HTTPS": 8443}]'    
    alb.ingress.kubernetes.io/certificate-arn: xxxx
  labels:
    app: keycloak
  name: keycloak-ingress
spec:
  ingressClassName: alb
  tls:
  - hosts:
    - '{{ .Values.keycloak.hostname }}'
  
  rules:
  - http:
      paths:
      - backend:
          service:
            name: keycloak-service
            port:
              number: 8443
        path: /
        pathType: ImplementationSpecific
```

This is what our AWS LB Controller does when one of our three keycloak pods is deleted (`kubectl delete pod keycloak-0`):

1: Deregisters the target (pod with ip 10.103.9.62) - this seems intuitive
```
{"level":"info","ts":1663938421.350132,"msg":"deRegistering targets","arn":"arn:aws:elasticloadbalancing:eu-west-1:xx:targetgroup/k8s-keycloak-keycloak-56ea148d7b/0f4b6813c1be126d","targets":[{"AvailabilityZone":"eu-west-1a","Id":"10.103.9.62","Port":8443}]}
{"level":"info","ts":1663938421.4012036,"msg":"deRegistered targets","arn":"arn:aws:elasticloadbalancing:eu-west-1:x:targetgroup/k8s-keycloak-keycloak-56ea148d7b/0f4b6813c1be126d"}
```

2: Deletes the load balancer - this seems harsh
```
{"level":"info","ts":1663938421.6561663,"logger":"controllers.ingress","msg":"deleting loadBalancer","arn":"arn:aws:elasticloadbalancing:eu-west-1:x:loadbalancer/app/k8s-keycloak-keycloak-a5bde81292/bb86575bed927905"}
{"level":"info","ts":1663938421.79802,"logger":"controllers.ingress","msg":"deleted loadBalancer","arn":"arn:aws:elasticloadbalancing:eu-west-1:x:loadbalancer/app/k8s-keycloak-keycloak-a5bde81292/bb86575bed927905"}
```

3: Deletes the target group and the two remaining targets:
```
{"level":"info","ts":1663938421.798107,"logger":"controllers.ingress","msg":"deleting targetGroupBinding","targetGroupBinding":{"namespace":"keycloak","name":"k8s-keycloak-keycloak-56ea148d7b"}}
{"level":"info","ts":1663938421.834552,"msg":"deRegistering targets","arn":"arn:aws:elasticloadbalancing:eu-west-1:x:targetgroup/k8s-keycloak-keycloak-56ea148d7b/0f4b6813c1be126d","targets":[{"AvailabilityZone":"eu-west-1a","Id":"10.103.29.184","Port":8443},{"AvailabilityZone":"eu-west-1a","Id":"10.103.53.103","Port":8443},{"AvailabilityZone":"eu-west-1a","Id":"10.103.9.62","Port":8443}]}
```

I would expect it would do (1) then call it a day. What have I done wrong?
