### ISSUE TITLE
Error while configuring annotations for OIDC authentication in ALB

### ISSUE THREAD

**Issue by shivakumar5** [kubernetes-sigs/aws-load-balancer-controller#2819]
**Describe the bug**
I have added all the required oidc annotations in ingress like below:

```  
annotations: 
    alb.ingress.kubernetes.io/auth-type: 'oidc'
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-scope: 'openid'
    alb.ingress.kubernetes.io/auth-session-cookie: 'AWSELBAuthSessionCookie'
    alb.ingress.kubernetes.io/auth-session-timeout: '604800'    
    alb.ingress.kubernetes.io/auth-idp-oidc: '{"issuer":"issuer","authorizationEndpoint":"aendpoint","tokenEndpoint":"tendpoint","userInfoEndpoint":"uendpoint","secretName":"oidc-secret"}'
```
but I'm getting the error as "**ingress  Failed deploy model due to InternalFailure:  status code: 500, request id: d25fe190-0c80-4c0e-a65c-8447f5a10ee8"**

Also, If I go to ALB via aws console, listener rules are not showing up, it ll be blank as below:
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/45067113/192288402-f015e0b3-06c7-446c-8038-45b822fd347a.png">

And, If I add the oidc authentication manually with all the details, then my application works perfectly fine.

So, I think this might be an issue with annotations configuration.

**Steps to reproduce**
Configure OIDC using annotations

**Environment**

* AWS Load Balancer controller version: 2.2.4
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version? Yes, 1.21

**Additional Context**:
