### ISSUE TITLE
TargetGroupBinding for NLB and IP TG (protocol: UDP)

### ISSUE THREAD

**Issue by oleg-ku-32768** [kubernetes-sigs/aws-load-balancer-controller#2829]
Sort of follow up to [the closed issue](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2582):
It's pretty much same setup, except protocol is UDP, not TCP.
It shouldn't matter, I guess.
But it doesn't work and I don't know how troubleshoot it...

```
$ kubectl version --short
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.22.13-eks-15b7512

$ helm list -n kube-system
NAME                         NAMESPACE   REVISION STATUS   CHART                              APP VERSION
aws-load-balancer-controller kube-system        1 deployed aws-load-balancer-controller-1.4.5 v2.4.4    
```

There are 2 target-groups and with corresponding target group bindings and services:

```
$ kubectl get targetgroupbindings -o wide --context eks-dev
NAME                 SERVICE-NAME SERVICE-PORT TARGET-TYPE
eks-dev-vpn-udp-1194 openvpn  1194 instance
dev-vpn-udp-1194     openvpn1 1194 ip      
```

* TGs are NOT configured as listeners on NLB
* It seems, it doesn't make any difference.

```
$ kubectl get service -o wide --context eks-dev
openvpn  NodePort  10.100.69.77  <none> 1194:30934/UDP app.kubernetes.io/name=openvpn
openvpn1 ClusterIP 10.100.64.237 <none> 1194/UDP       app.kubernetes.io/name=openvpn1
```

**NodePort-tgb.yaml**
```
# NodePort
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: eks-dev-vpn-udp-1194
spec:
  serviceRef:
    name: openvpn # route traffic to the openvpn service
    port: 1194 # What port should be here 1194:30934/UDP?
  targetGroupARN: arn:aws:elasticloadbalancing:us-west-2::targetgroup/eks-dev-vpn-udp-1194/498ff12da99bc955
  ipAddressType: ipv4
  networking:
    ingress:
    - from:
      - ipBlock:
          cidr: 0.0.0.0/0
      ports:
      - port: 1194 # What port should be here 1194:30934/UDP?
        protocol: UDP
```

**ClusterIP-tgb.yaml**
```
# ClusterIP
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: dev-vpn-udp-1194
spec:
  serviceRef:
    name: openvpn1 # route traffic to the openvpn service
    port: 1194
  targetGroupARN: arn:aws:elasticloadbalancing:us-west-2::targetgroup/dev-vpn-udp-1194/9814042a1d0354ce
  ipAddressType: ipv4
  networking:
    ingress:
    - from:
      - ipBlock:
          cidr: 0.0.0.0/0
      ports:
      - port: 1194
        protocol: UDP
```

Current behavior:
1. All k8s nodes get registered in "instance TG"
`eks-dev-vpn-udp-1194 openvpn 1194 instance`
with port **30934** as in 
`openvpn NodePort 10.100.69.77 <none> 1194:30934/UDP app.kubernetes.io/name=openvpn`
and there are corresponding messages in output:
`kubectl logs -n kube-system deployment.apps/aws-load-balancer-controller`
It does update k8s nodes SG to allow port/protocol in TargetGroupBinding networking

Questions:
A. Who is responsible for setting the port **30934** in TargetGroupBinding networking, me or aws-load-balancer-controller?
B. What port should be used TargetGroupBinding serviceRef?

2. Nothing is registered in "ip TG"
`openvpn1 ClusterIP 10.100.64.237 <none> 1194/UDP app.kubernetes.io/name=openvpn1`
and NO mention of "ip TG" in kubectl logs...

I would prefer to use ClusterIP, since there is NO port mapping as in NodePort.
I've no idea how to troubleshoot it.
