### ISSUE TITLE
Creating internal IPv6 ip-target NLB in public subnet results in broken target group

### ISSUE THREAD

**Issue by johngmyers** [kubernetes-sigs/aws-load-balancer-controller#2848]
**Describe the bug**

In an IPv6 cluster with public dual-stack subnets, when a `Service` specifies the creation of an internal load balancer with target-type "ip", LBC will create an NLB with a non-working target group. The resulting NLB will get stuck in "Provisioning" state and all targets will be stuck in "Initial" state.

**Steps to reproduce**
1. Create an IPv6 kOps cluster with "public" topology.
2. Apply the following manifest:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: tls-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: dualstack
spec:
  selector:
    app: tls-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tls-app
  template:
    metadata:
      labels:
        app: tls-app
        product: cloud15
        team: cloud15
    spec:
      containers:
        - name: tls-app
          image: gcr.io/k8s-staging-ingressconformance/echoserver:v20220815-e21d1a4
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
```

**Expected outcome**

I would expect an error to be logged and the NLB to not be created.

Arguably kOps should not have annotated the Subnet with "kubernetes.io/role/internal-elb", but the Subnet is usable for IPv4 NLBs of type "instance".

**Environment**

* AWS Load Balancer controller version: main branch
* Kubernetes version: 1.23.0
* Using EKS (yes/no), if so version? Not using EKS

**Additional Context**:

CloudTrail shows that the AssignIpv6AddressesRequest call from AWSServiceRoleForElasticLoadBalancing fails with a Server.InternalError error code.
