### ISSUE TITLE
Docs: apiVersion outdated

### ISSUE THREAD

**Issue by luis02lopez** [kubernetes-sigs/aws-load-balancer-controller#2851]
**Describe the bug**
Hello, in the [docs](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/) is being used the apiVersion `extensions/v1beta1` but this is now deprecated, should be `networking.k8s.io/v1`

Additionally, other parts of the YAML have an old configuration, for example:

```
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: forward-multiple-tg
              servicePort: use-annotation
```

Should be now:

```
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
                name: targets
                port:
                  name: use-annotation
```

* AWS Load Balancer controller version:  `2.2`
* Kubernetes version: `1.2.3`
* Using EKS (yes/no), if so version? yes, eks.2

**Additional Context**:

Annotation in example: `alb.ingress.kubernetes.io/actions.forward-multiple-tg`
