### ISSUE TITLE
Readiness gate reports wrong status

### ISSUE THREAD

**Issue by hmeerlo** [kubernetes-sigs/aws-load-balancer-controller#2857]
**Describe the bug**
I have enabled pod readiness gates on one of my deployments. But the pod never start receiving traffic because one of the conditions stays on false. This is 'Health checks' condition which has reason `Target.FailedHealthChecks`. This looks ok except that when I check with the targetgroup in AWS it says that the targets are all healthy (which they are). Without the readiness gates this all works, it only started failing after enabling the readiness gates. So no changes in health checks or NLB settings or whatever.

**Steps to reproduce**
Describe on my failing pod:
```
kubectl get pod athom-cloud-homey-1 -o yaml | grep -B7 'type: target-health'
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: null
    message: Target registration is in progress
    reason: Elb.RegistrationInProgress
    status: "True"
    type: target-health.elbv2.k8s.aws/k8s-default-athomclo-fd31669904
  - lastProbeTime: null
    lastTransitionTime: null
    message: Initial health checks in progress
    reason: Elb.InitialHealthChecking
    status: "True"
    type: target-health.elbv2.k8s.aws/k8s-default-athomclo-226c95b632
  - lastProbeTime: null
    lastTransitionTime: null
    message: Health checks failed
    reason: Target.FailedHealthChecks
    status: "False"
    type: target-health.elbv2.k8s.aws/k8s-default-athomclo-736d557daf
```
![Screenshot 2022-10-28 at 10 18 09](https://user-images.githubusercontent.com/448150/198539558-ba36af98-9e41-47a2-b591-efd1ce402799.png)

**Expected outcome**
I expect the pod to become Ready and start serving traffic. 

**Environment**

* AWS Load Balancer controller version: 2.4.2
* Kubernetes version: 1.23
* Using EKS (yes/no), if so version? : Yes, does it have a version??

**Additional Context**:
