### ISSUE TITLE
readinessProbe success ,the req data has not been switched to the new pod

### ISSUE THREAD

**Issue by enjoycx** [kubernetes-sigs/aws-load-balancer-controller#2861]
**config**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-webserver
  namespace: prod-webserver
  labels:
    app: prod-webserver
spec:
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: prod-webserver
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0    
  template:
    spec:
      containers:
      - name: prod-webserver
        env:
        - name: CONFIGPATH
          value: /
        image: <IMAGE>:<IMAGE_TAG>
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 300
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 30
        readinessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - /postStart.sh
          preStop:
            exec:
              command:
                - /bin/sh
                - /preStop.sh
        name: prod-webserver
        resources:
          limits:
            cpu: 500m
            memory: 1200Mi
          requests:
            cpu: 250m
            memory: 1200Mi
      terminationGracePeriodSeconds: 70
```
**description**
After the ready probe takes effect, the traffic should be switched to the new pod immediately. However, the current situation is that the traffic is still requested in the old pod. When the pod stops, the traffic arrives in the new pod, causing 502 bad gateways
