### ISSUE TITLE
Ingess get shows wrong port number instead of one created via annotation

### ISSUE THREAD

**Issue by uklg** [kubernetes-sigs/aws-load-balancer-controller#2864]
Added mulitiple listeners to a single ALB via sequential ingress applies.

Visible in console and accessible via browser. 

(works as expected but bug in kubectl output:

```
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: my-group
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 83}, {"HTTPS": 443}]'
```
Added  another ingress without the listen ports annotation as well.

Buggy response ports shows 80 in both entries but in AWS console it is 80 and 83 present in listeners list.

```
kubectl get ingress -A


NAMESPACE   NAME           CLASS   HOSTS   ADDRESS   PORTS   AGE
game-2048   ingress-2048   alb     *                 80      81m
game-2048   ingress-2049   alb     *                 80      91s
```

v1.23.9-eks-ba74326
aws-load-balancer-controller/v2.4.4
