### ISSUE TITLE
Service NLB health check timeout annotation is ignored.

### ISSUE THREAD

**Issue by project0** [kubernetes-sigs/aws-load-balancer-controller#2898]
**Describe the bug**
When creating a new NLB the health check interval timeout is not used and is set to the same value as the interval. The given timeout is ignored.
**Steps to reproduce**

Create a service with both annotations:
`service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "6"`
`service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "2"`

full example: 

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: testapp
  namespace: lbtest
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4 # dualstack
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: "preserve_client_ip.enabled=true,deregistration_delay.timeout_seconds=60,deregistration_delay.connection_termination.enabled=true"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8080"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /healthz
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "6"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "3"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: testapp
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
```
**Expected outcome**
Targetgroup should have set the timeout to 2

**Environment**

* AWS Load Balancer controller version: v2.4.5
* Kubernetes version : 1.24
* Using EKS (yes/no), if so version? : EKS

**Additional Context**:
relevant logs do not mention the timeout at all
```json
{"level":"info","ts":1669650128.2872295,"logger":"controllers.service","msg":"successfully built model","model":"{\"id\":\"lbtest/testapp\",\"resources\":{\"AWS::ElasticLoadBalancingV2::Listener\":{\"443\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":443,\"protocol\":\"TCP\",\"defaultActions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/lbtest/testapp:443/status/targetGroupARN\"}}]}}]}},\"80\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":80,\"protocol\":\"TCP\",\"defaultActions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/lbtest/testapp:80/status/targetGroupARN\"}}]}}]}}},\"AWS::ElasticLoadBalancingV2::LoadBalancer\":{\"LoadBalancer\":{\"spec\":{\"name\":\"k8s-lbtest-testapp-7fe20b9a75\",\"type\":\"network\",\"scheme\":\"internet-facing\",\"ipAddressType\":\"ipv4\",\"subnetMapping\":[{\"subnetID\":\"subnet-064655098f57ab6fe\"},{\"subnetID\":\"subnet-09f79e32b2baab717\"},{\"subnetID\":\"subnet-0b9c5fc0581bc6f58\"}]}}},\"AWS::ElasticLoadBalancingV2::TargetGroup\":{\"lbtest/testapp:443\":{\"spec\":{\"name\":\"k8s-lbtest-testapp-a043ce8c19\",\"targetType\":\"ip\",\"port\":1,\"protocol\":\"TCP\",\"ipAddressType\":\"ipv4\",\"healthCheckConfig\":{\"port\":8080,\"protocol\":\"HTTP\",\"path\":\"/healthz\",\"intervalSeconds\":6,\"healthyThresholdCount\":2,\"unhealthyThresholdCount\":2},\"targetGroupAttributes\":[{\"key\":\"deregistration_delay.connection_termination.enabled\",\"value\":\"true\"},{\"key\":\"deregistration_delay.timeout_seconds\",\"value\":\"60\"},{\"key\":\"preserve_client_ip.enabled\",\"value\":\"true\"},{\"key\":\"proxy_protocol_v2.enabled\",\"value\":\"false\"}]}},\"lbtest/testapp:80\":{\"spec\":{\"name\":\"k8s-lbtest-testapp-48ffc732c6\",\"targetType\":\"ip\",\"port\":1,\"protocol\":\"TCP\",\"ipAddressType\":\"ipv4\",\"healthCheckConfig\":{\"port\":8080,\"protocol\":\"HTTP\",\"path\":\"/healthz\",\"intervalSeconds\":6,\"healthyThresholdCount\":2,\"unhealthyThresholdCount\":2},\"targetGroupAttributes\":[{\"key\":\"deregistration_delay.connection_termination.enabled\",\"value\":\"true\"},{\"key\":\"deregistration_delay.timeout_seconds\",\"value\":\"60\"},{\"key\":\"preserve_client_ip.enabled\",\"value\":\"true\"},{\"key\":\"proxy_protocol_v2.enabled\",\"value\":\"false\"}]}}},\"K8S::ElasticLoadBalancingV2::TargetGroupBinding\":{\"lbtest/testapp:443\":{\"spec\":{\"template\":{\"metadata\":{\"name\":\"k8s-lbtest-testapp-a043ce8c19\",\"namespace\":\"lbtest\",\"creationTimestamp\":null},\"spec\":{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/lbtest/testapp:443/status/targetGroupARN\"},\"targetType\":\"ip\",\"serviceRef\":{\"name\":\"testapp\",\"port\":443},\"networking\":{\"ingress\":[{\"from\":[{\"ipBlock\":{\"cidr\":\"0.0.0.0/0\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":\"https\"}]},{\"from\":[{\"ipBlock\":{\"cidr\":\"10.0.36.0/22\"}},{\"ipBlock\":{\"cidr\":\"10.0.40.0/22\"}},{\"ipBlock\":{\"cidr\":\"10.0.32.0/22\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":8080}]}]},\"ipAddressType\":\"ipv4\"}}}},\"lbtest/testapp:80\":{\"spec\":{\"template\":{\"metadata\":{\"name\":\"k8s-lbtest-testapp-48ffc732c6\",\"namespace\":\"lbtest\",\"creationTimestamp\":null},\"spec\":{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/lbtest/testapp:80/status/targetGroupARN\"},\"targetType\":\"ip\",\"serviceRef\":{\"name\":\"testapp\",\"port\":80},\"networking\":{\"ingress\":[{\"from\":[{\"ipBlock\":{\"cidr\":\"0.0.0.0/0\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":\"http\"}]},{\"from\":[{\"ipBlock\":{\"cidr\":\"10.0.36.0/22\"}},{\"ipBlock\":{\"cidr\":\"10.0.40.0/22\"}},{\"ipBlock\":{\"cidr\":\"10.0.32.0/22\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":8080}]}]},\"ipAddressType\":\"ipv4\"}}}}}}}"}
{"level":"info","ts":1669650223.1065917,"logger":"controllers.service","msg":"successfully built model","model":"{\"id\":\"lbtest/testapp\",\"resources\":{\"AWS::ElasticLoadBalancingV2::Listener\":{\"443\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":443,\"protocol\":\"TCP\",\"defaultActions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/lbtest/testapp:443/status/targetGroupARN\"}}]}}]}},\"80\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":80,\"protocol\":\"TCP\",\"defaultActions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/lbtest/testapp:80/status/targetGroupARN\"}}]}}]}}},\"AWS::ElasticLoadBalancingV2::LoadBalancer\":{\"LoadBalancer\":{\"spec\":{\"name\":\"k8s-lbtest-testapp-7fe20b9a75\",\"type\":\"network\",\"scheme\":\"internet-facing\",\"ipAddressType\":\"ipv4\",\"subnetMapping\":[{\"subnetID\":\"subnet-064655098f57ab6fe\"},{\"subnetID\":\"subnet-09f79e32b2baab717\"},{\"subnetID\":\"subnet-0b9c5fc0581bc6f58\"}]}}},\"AWS::ElasticLoadBalancingV2::TargetGroup\":{\"lbtest/testapp:443\":{\"spec\":{\"name\":\"k8s-lbtest-testapp-a043ce8c19\",\"targetType\":\"ip\",\"port\":1,\"protocol\":\"TCP\",\"ipAddressType\":\"ipv4\",\"healthCheckConfig\":{\"port\":8080,\"protocol\":\"HTTP\",\"path\":\"/healthz\",\"intervalSeconds\":6,\"healthyThresholdCount\":2,\"unhealthyThresholdCount\":2},\"targetGroupAttributes\":[{\"key\":\"deregistration_delay.connection_termination.enabled\",\"value\":\"true\"},{\"key\":\"deregistration_delay.timeout_seconds\",\"value\":\"60\"},{\"key\":\"preserve_client_ip.enabled\",\"value\":\"true\"},{\"key\":\"proxy_protocol_v2.enabled\",\"value\":\"false\"}]}},\"lbtest/testapp:80\":{\"spec\":{\"name\":\"k8s-lbtest-testapp-48ffc732c6\",\"targetType\":\"ip\",\"port\":1,\"protocol\":\"TCP\",\"ipAddressType\":\"ipv4\",\"healthCheckConfig\":{\"port\":8080,\"protocol\":\"HTTP\",\"path\":\"/healthz\",\"intervalSeconds\":6,\"healthyThresholdCount\":2,\"unhealthyThresholdCount\":2},\"targetGroupAttributes\":[{\"key\":\"deregistration_delay.connection_termination.enabled\",\"value\":\"true\"},{\"key\":\"deregistration_delay.timeout_seconds\",\"value\":\"60\"},{\"key\":\"preserve_client_ip.enabled\",\"value\":\"true\"},{\"key\":\"proxy_protocol_v2.enabled\",\"value\":\"false\"}]}}},\"K8S::ElasticLoadBalancingV2::TargetGroupBinding\":{\"lbtest/testapp:443\":{\"spec\":{\"template\":{\"metadata\":{\"name\":\"k8s-lbtest-testapp-a043ce8c19\",\"namespace\":\"lbtest\",\"creationTimestamp\":null},\"spec\":{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/lbtest/testapp:443/status/targetGroupARN\"},\"targetType\":\"ip\",\"serviceRef\":{\"name\":\"testapp\",\"port\":443},\"networking\":{\"ingress\":[{\"from\":[{\"ipBlock\":{\"cidr\":\"0.0.0.0/0\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":\"https\"}]},{\"from\":[{\"ipBlock\":{\"cidr\":\"10.0.36.0/22\"}},{\"ipBlock\":{\"cidr\":\"10.0.40.0/22\"}},{\"ipBlock\":{\"cidr\":\"10.0.32.0/22\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":8080}]}]},\"ipAddressType\":\"ipv4\"}}}},\"lbtest/testapp:80\":{\"spec\":{\"template\":{\"metadata\":{\"name\":\"k8s-lbtest-testapp-48ffc732c6\",\"namespace\":\"lbtest\",\"creationTimestamp\":null},\"spec\":{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/lbtest/testapp:80/status/targetGroupARN\"},\"targetType\":\"ip\",\"serviceRef\":{\"name\":\"testapp\",\"port\":80},\"networking\":{\"ingress\":[{\"from\":[{\"ipBlock\":{\"cidr\":\"0.0.0.0/0\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":\"http\"}]},{\"from\":[{\"ipBlock\":{\"cidr\":\"10.0.36.0/22\"}},{\"ipBlock\":{\"cidr\":\"10.0.40.0/22\"}},{\"ipBlock\":{\"cidr\":\"10.0.32.0/22\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":8080}]}]},\"ipAddressType\":\"ipv4\"}}}}}}}"}
```
