### ISSUE TITLE
China Region - Access Denied

### ISSUE THREAD

**Issue by rosscdh** [kubernetes-sigs/aws-load-balancer-controller#2900]
hi there, just a report in the hope that its something obvious that ive missed;

**Describe the bug**
aws lbc should work in china region

**Steps to reproduce**

setup for china
add the env var for region
update images to pull from cn repo

**Expected outcome**
NLB gets deployed

**Environment**

* AWS Load Balancer controller version
2.4.3

* Kubernetes version

* Using EKS (yes/no), if so version?
v1.21.14

**Additional Context**:

Role deployed using: Updated for CN `:aws-cn:`

curl -o iam-policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.2.1/docs/install/iam_policy.json

```
{"level":"error","ts":1669735499.2716851,"logger":"controller-runtime.manager.controller.service","msg":"Reconciler error","name":"my-app-nlb-v3-service","namespace":"demo-cn-css","error":"UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: cfd950a2-bea6-4d83-83b8-83a7f1d9af88"}
```

pod updated with region (in multiple ways)
```
  containers:
    - args:
        - '--cluster-name=nonprod-eks-cn-a-1'
        - '--aws-region=cn-northwest-1'
      env:
        - name: AWS_REGION
          value: cn-northwest-1
        - name: AWS_DEFAULT_REGION
          value: cn-northwest-1
        - name: AWS_ROLE_ARN
          value: >-
            arn:aws-cn:iam::xxxxxxxxxxx:role/eksctl-nonprod-eks-cn-a-1-addon-iamserviceac-Role1-MF98VH0X66M0
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
```
