### ISSUE TITLE
Reordering of ingress rules (#2409) breaks existing functionality 

### ISSUE THREAD

**Issue by jschmidt1-godaddy** [kubernetes-sigs/aws-load-balancer-controller#2903]
**Describe the bug**
A concise description of what the bug is.
PR #2409 removes the ability to use an ImplementationSpecific path type to route a longer URL with a wildcard to a different destination than a Prefix path type with a shorter URL.

**Steps to reproduce**

Here is an example of the relevant portion of the ingress config:
````
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.ingressHostname }}
      http:
        paths:
          - path: /v1/resources/*/serviceOne
            pathType: ImplementationSpecific
            backend:
              service:
                name: serviceOne
                port: 
                  number: 8000
          - path: /v1/resources
            pathType: Prefix
            backend:
              service:
                name: serviceTwo
                port: 
                  number: 8000
```

After v2.4.3, all requests are routed to serviceTwo, even if the ImplementationSpecific path is longer than the Prefix path. This violates [Kubernetes ingress documentation](https://kubernetes.io/docs/concepts/services-networking/ingress/#multiple-matches).

**Expected outcome**
A concise description of what you expected to happen.
Prior to v2.4.3, requests with the suffix `/serviceOne` were routed to serviceOne, and requests without the `/serviceOne` suffix were routed to serviceTwo.

In order to achieve the expected behavior for multiple matches (the aim of the original PR), it seems that the length of the path should be considered before reordering based on path type (even if the type is ImplementationSpecific).

**Environment**

* AWS Load Balancer controller version 2.4.3
* Kubernetes version 1.21
* Using EKS (yes/no), if so version? yes, 1.21

**Additional Context**:
I've tried workarounds to this problem via actions/conditions annotations, but am running into the problem that the wildcard matching done by the listener includes the `/service` as part of wildcard matching, so all requests are sent to serviceOne.
