### ISSUE TITLE
Ingress port 443 to different `targetPort` keeps resetting

### ISSUE THREAD

**Issue by khteh** [kubernetes-sigs/aws-load-balancer-controller#2913]
**Describe the bug**
Different port number between `Ingress` and `Service`, the `Service` endpoints keep resetting, so are the ALB targets in the target group. What do I miss?

`Service`:
```
apiVersion: v1
kind: Service
metadata:
  name: svc-kibana
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  ports:
    - name: kibana
      protocol: TCP
      port: 443
      targetPort: 5601
  clusterIP: None # Headless
```
`Ingress`:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: kyberlife
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    #kubernetes.io/ingress.class: alb - Not needed when ingressClassName is used below
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:<account>:certificate/<guid>
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=300
    alb.ingress.kubernetes.io/auth-session-cookie: kyberlife
    alb.ingress.kubernetes.io/auth-session-timeout: "3600"
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "20"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "10"
    alb.ingress.kubernetes.io/healthy-threshold-count: "3"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
    alb.ingress.kubernetes.io/success-codes: "200"
  labels:
    app: ingress
spec:
  ingressClassName: alb
    - host: kibana.kyberlife.io
      http:
        paths:
          - backend:
              service:
                name: svc-kibana
                port:
                  number: 443
            pathType: Prefix
            path: /
```
**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version: 2.4.5
* Kubernetes version: 1.24
* Using EKS (yes/no), if so version? yes. `eksctl 0.120.0`

**Additional Context**:
