### ISSUE TITLE
TLS handshake errorr

### ISSUE THREAD

**Issue by pmichna** [kubernetes-sigs/aws-load-balancer-controller#2914]
**Describe the bug**
I get the following errors in aws-load-balancer-controller pods:
```
http: TLS handshake error from 172.16.128.63:37094: EOF
http: TLS handshake error from 172.16.116.101:58040: EOF
```

This happens even if there are no ALB Ingresses (nor NLB Services) handled by the controller. This happens on an AWS EKS cluster that is pretty big (~100 nodes, 13k pods). I created two clusters with the same config but with no load deployed there I don't have such errors there.

**Steps to reproduce**
Install AWS Load Balancer controller via Helm chart ver. 1.4.6 with the following values:
```yaml
resources:
  requests:
    cpu: 100m
    memory: 1Gi
  limits:
    cpu: 200m
    memory: 1Gi

nodeSelector:
  type: privileged

tolerations:
  - key: privileged
    operator: Exists
    effect: NoExecute

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule

replicaCount: 2

podDisruptionBudget:
  minAvailable: 1

region: us-east-1

vpcId: <REDACTED>

image:
  repository:  602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon/aws-load-balancer-controller

clusterName: <REDACTED>

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: <REDACTED>
    name: aws-load-balancer-controller
```

**Expected outcome**
No TLS handshake errors.

**Environment**

* AWS Load Balancer controller version - 2.4.5 (Helm chart version 1.4.6)
* Kubernetes version - EKS 1.23
