### ISSUE TITLE
ALB with HTTP/2 websocket errors.

### ISSUE THREAD

**Issue by khteh** [kubernetes-sigs/aws-load-balancer-controller#2917]
**Describe the bug**
Running a ASP.Net Core 7 web application behind ALB in EKS cluster bumps into the following error seen in chrome debugger:
```
Error: Failed to start the transport 'WebSockets': Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.
```
Running the same application on my local development host does not have this error at all.

The ALB ingress has the following annotation:
```
alb.ingress.kubernetes.io/target-type: ip
alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60
alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=600
```
and the following kubernetes `Service`:
```
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 300
```

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version: 2.4.5
* Kubernetes version: 1.24
* Using EKS (yes/no), if so version? yes. `eksctl 0.120.0`

**Additional Context**:

**Comment by kishorj** [comment]
@khteh, for websockets support :
- ensure ingress has rule for the initial request path to the websocket
- configure larger idle timeout (default is 60 seconds), or setup heartbeat from the application layer

**Comment by khteh** [comment]
![Screenshot from 2022-12-15 09-08-39](https://user-images.githubusercontent.com/3871483/207748664-b84d17eb-37f5-4159-a661-d45afae3040d.png)

**Comment by khteh** [comment]
> * ensure ingress has rule for the initial request path to the websocket
```
    - host: myapp.com
      http:
        paths:
          - backend:
              service:
                name: svc-myapp
                port:
                  number: 443
            pathType: Prefix
            path: /*
```
> * configure larger idle timeout (default is 60 seconds), or setup heartbeat from the application layer
Done.

Why does it change to `wss://` scheme? Is that the root cause?
