### ISSUE TITLE
[Error]: Using Multiple PodSecurityGroups --> Expect exactly one securityGroup tagged with...

### ISSUE THREAD

**Issue by armenr** [kubernetes-sigs/aws-load-balancer-controller#2922]
**Describe the bug**
Following the points mentioned in other (similar) issues, I am struggling to get a working ALB while using multiple PodSecurityGroups for a deployment + service.

**Steps to reproduce**

1. "cluster" security group does NOT possess the `kubernetes.io/cluster/${name}` tag - "worker/node" security group is the *only* security group that DOES possess the tag:

```
  # module.eks.aws_security_group.cluster[0] will be created
  + resource "aws_security_group" "cluster" {
      + arn                    = (known after apply)
      + description            = "EKS cluster security group"
      + egress                 = (known after apply)
      + id                     = (known after apply)
      + ingress                = (known after apply)
      + name                   = "my-cluster-eks"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name" = "my-cluster-eks"
        }
      + tags_all               = {
          + "my-org:app"     = "my-org"
          + "my-org:billing" = "devops"
          + "my-org:contact" = "ops@my-org.net"
          + "my-org:env"     = "my-cluster"
          + "my-org:owner"   = "devops"
          + "my-org:project" = "dev"
          + "Name"       = "my-cluster-eks"
          + "terraform"  = "yes"
        }
      + vpc_id                 = "vpc-REDACTED_VPC"
    }

  # module.eks.aws_security_group.node[0] will be created
  + resource "aws_security_group" "node" {
      + arn                    = (known after apply)
      + description            = "EKS node shared security group"
      + egress                 = (known after apply)
      + id                     = (known after apply)
      + ingress                = (known after apply)
      + name                   = "my-cluster-eks-node"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name"                         = "my-cluster-eks-node"
          + "karpenter.sh/discovery"       = "my-cluster"
          + "kubernetes.io/cluster/my-cluster" = "owned"
        }
      + tags_all               = {
          + "my-org:app"                       = "my-org"
          + "my-org:billing"                   = "devops"
          + "my-org:contact"                   = "ops@my-org.net"
          + "my-org:env"                       = "my-cluster"
          + "my-org:owner"                     = "devops"
          + "my-org:project"                   = "dev"
          + "Name"                         = "my-cluster-eks-node"
          + "karpenter.sh/discovery"       = "my-cluster"
          + "kubernetes.io/cluster/my-cluster" = "owned"
          + "terraform"                    = "yes"
        }
      + vpc_id                 = "vpc-REDACTED_VPC"
    }
```
2. ALB Ingress config (argoCD):
```
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/backend-protocol: HTTPS
      alb.ingress.kubernetes.io/certificate-arn: <MY_CERTIFICATE_ARN>
      alb.ingress.kubernetes.io/group.name: main
      alb.ingress.kubernetes.io/load-balancer-name: <SOME_NAME>
      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
```

**Expected outcome**
A concise description of what you expected to happen.

1..Load Balancer Controller does *not* throw an error
2. Load Balancer Controller automatically adds a security group *rule* to the  `module.eks.aws_security_group.node` security group
3. Load Balancer Controller successfully serves traffic through the ingress

**Environment**

* AWS Load Balancer controller version - v2.4.5
* Kubernetes version - 1.24
* Using EKS (yes/no), if so version? Yes --> 1.24

**Additional Context**:
The documentation is unclear to the reader when they are unfamiliar with the caveats and nuances of using multiple PodSecurityGroups + Load Balancer Controller...it would be nice to have a clearer documentation (and maybe an example) of how to work with ALB Ingresses + pods with multiple SGs attached to the ENI via PodSecurityGroups
