### ISSUE TITLE
nlb and target group is not removed after service successfully removed

### ISSUE THREAD

**Issue by FarhadF** [kubernetes-sigs/aws-load-balancer-controller#2924]
**Describe the bug**
aws loadbalancer controller did not remove nlb on service removal. Service got removed from the kubernetes cluster successfully. 

Targets got deregistered successfully. 
```
{"level":"info","ts":1670859906.0783424,"msg":"deRegistered targets","arn":"arn:aws:elasticloadbalancing:xxx:xxx:targetgroup/xxx/xxx"}
```

No  errors in controller logs.

**Steps to reproduce**
create a service with loadbalancer type with annotations:
```
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: external
              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
              service.beta.kubernetes.io/aws-load-balancer-scheme: internal
```
**Expected outcome**
the loadbalancer and target groups removed as well

**Environment**
EKS 
* AWS Load Balancer controller version
2.4
* Kubernetes version
1.21
* Using EKS (yes/no), if so version?
yes
**Additional Context**:
