### ISSUE TITLE
Addded a new subnet, didn't get attached to my ALB

### ISSUE THREAD

**Issue by mbonica1990** [kubernetes-sigs/aws-load-balancer-controller#2930]
**Describe the bug**
I was running an ALB managed by the aws-load-balancer controller. After it was set up, I created a new subnet (so I could use more AZs), and tagged it; however, the ALB didn't start using it.

**Steps to reproduce**
1. Create three subnets, each in a unique AZ
2. Tag them `kubernetes.io/role/internal-elb = 1`
3. Deploy an Ingress like this:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/certificate-arn: TEST
    alb.ingress.kubernetes.io/healthcheck-path: /ping
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-policy: TEST
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/tags: TEST
  labels:
    redacted
  name: TEST
  namespace: TEST
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: TEST
            port:
              number: 443
        path: /*
        pathType: ImplementationSpecific
```
4. The ALB comes up, using those three subnets.

5. Add a fourth subnet in a fourth AZ, also tagged `kubernetes.io/role/internal-elb = 1`.

The new subnet does not get added to the ALB.

**Expected outcome**
I expected the ALB to start using the new subnet automatically. Instead, I had to add it by hand.

**Environment**

* AWS Load Balancer controller version
2.4.4
* Kubernetes version
1.22
* Using EKS (yes/no), if so version?
1.22
eks.6

**Additional Context**:
