### ISSUE TITLE
How to get client IP instead of node IP in EKS pods

### ISSUE THREAD

**Issue by genieai-vikas** [kubernetes-sigs/aws-load-balancer-controller#2944]
**Describe the bug**
I want the client(source) IP to pass it into the pod so nodeJS can use it but as the request are coming from ALB I am getting node IP instead of the client(source) IP inside the pod.

**Steps to reproduce**
This is my ingress file
```

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "testapp.frontend.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingressScheme }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.eks_cluster }}
    alb.ingress.kubernetes.io/actions.redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.external.ACM_CERTIFICATE_ARN }},{{ .Values.external.ANONYMISER_CERTIFICATE_ARN }},{{ .Values.external.testapp_CERTIFICATE_ARN }}"
    alb.ingress.kubernetes.io/inbound-cidrs: {{ .Values.ipWhiteList }}
    alb.ingress.kubernetes.io/ssl-redirect: '443' 
    {{- if (ne .Values.env_name "app") }}
    alb.ingress.kubernetes.io/conditions.{{ template "testapp.frontend.fullname" . }}: |
      [{"Field":"http-header","HttpHeaderConfig":{"HttpHeaderName": "SecurityToken", "Values":["dddtdehd3qwdddeawd"]}}]
    {{- end }}

spec:
  rules:
    - host: {{ .Values.domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "testapp.frontend.fullname" . }}
                port:
                  number: 4200
```

**Expected outcome**
To get the client IP inside the pod

**Environment**

* AWS Load Balancer controller version: 2.4.4
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version? yes, version 1.21

**Additional Context**:

I tried using  `externalTrafficPolicy: local` as mentioned here:
https://stackoverflow.com/questions/69679735/preserve-sourceip-address-in-kubernetes-and-distribute-the-load
