### ISSUE TITLE
ClientSecret won't be set or be configured properly.

### ISSUE THREAD

**Issue by 0xF4D3C0D3** [kubernetes-sigs/aws-load-balancer-controller#2946]
**Describe the bug**
aws-load-balancer-controller sets clientId but not clientSecret or is misconfigured.

I'm trying to setup OIDC listener like
```yaml
...
    annotations:
      ...
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/auth-type: 'oidc'
      alb.ingress.kubernetes.io/auth-scope: openid email https://www.googleapis.com/auth/admin.directory.group.readonly
      alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
      alb.ingress.kubernetes.io/auth-idp-oidc: '{
          "Issuer": "https://accounts.google.com",
          "AuthorizationEndpoint": "https://accounts.google.com/o/oauth2/v2/auth",
          "TokenEndpoint": "https://oauth2.googleapis.com/token",
          "UserInfoEndpoint": "https://openidconnect.googleapis.com/v1/userinfo",
          "secretName": "consoleme"
        }'
...
```

all the other properties are set properly but clientSecret won't be set or be misconfigured.
(I'm not sure because it's always shown empty in AWS console)

I also already set RBAC to make aws-load-balancer-controller can be able to access the secret containing clientId and clientSecret.
In the first place, if aws-load-balancer-controller can't access the secret it couldn't set clientId but it set properly so I think RBAC is ok.

I logged aws-load-balancer-controller with debug level but couldn't find anything else.

---

The reason I think that clientSecret is the problem is that configuring listener from aws-load-balancer-controller gives 561 error(due to wrong or empty clientSecret) but configuring listener in the aws console is fine. So I think aws-load-balancer-controller can't set clientSecret properly.

**Environment**
- I have a secret named consoleme in the same namespace with above ingress.
- clientId and ClientSecret in the secret are encoded with base64.
- RBAC for accessing the secret is configured ( if it were misconfigured it couldn't set clientId neither I guess )

* AWS Load Balancer controller version: 2.4.4
* Kubernetes version: 1.23
* Using EKS (yes/no), if so version?: yes, eks.5
