### ISSUE TITLE
health check interval minimum is 5s and not 6s

### ISSUE THREAD

**Issue by matti** [kubernetes-sigs/aws-load-balancer-controller#2951]
**Describe the bug**

specifying
```
service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: 2
service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: 5
```

will cause  `ValidationError: Health check interval must be greater than the timeout.`

but

```
service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: 2
service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: 6
```

Works

**Steps to reproduce**

```yaml
apiVersion: v1
kind: Service
metadata:
  name: test-lb-1
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: dualstack
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8080"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "6"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: deregistration_delay.timeout_seconds=31,deregistration_delay.connection_termination.enabled=true,stickiness.enabled=false,load_balancing.cross_zone.enabled=true
spec:
  type: LoadBalancer
  selector:
    app: whoami
  ports:
    - name: http
      port: 80
      targetPort: 8000
```

**Expected outcome**

Interval value of 5s should work:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/3893/210081014-4fc4b2b7-319d-4447-a372-ba5bb481521d.png">

**Environment**

* AWS Load Balancer controller version

`602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.4.3`

* Kubernetes version

1.24

* Using EKS (yes/no), if so version?

yes, 1.24

**Additional Context**:
