### ISSUE TITLE
Deployment on another namespace than kube-system

### ISSUE THREAD

**Issue by littlejo** [kubernetes-sigs/aws-load-balancer-controller#2957]
**Describe the bug**

I would like to use another namespace than kube-system for aws load balancer controller and load balancer is not created

**Steps to reproduce**

**Expected outcome**

Creation of load balancer and target groups. If i roll back on kube-system, it works directly.

**Environment**

* AWS Load Balancer controller version: v2.4.4
* Kubernetes version: 1.24
* Using EKS (yes/no), if so version? yes
* nginx ingress controller version: v1.4.0

**Additional Context**:

annotations:
```
        service.beta.kubernetes.io/aws-load-balancer-name: aaa
        service.beta.kubernetes.io/aws-load-balancer-type: "external"
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
        service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses: 
        service.beta.kubernetes.io/aws-load-balancer-subnets: private-subnet-lb-1a, private-subnet-lb-1b
```

events:

```
  Normal   EnsuringLoadBalancer  18m                  service-controller  Ensuring load balancer
  Warning  FailedDeployModel     4m54s (x2 over 11m)  service             Failed deploy model due to Internal error occurred: failed calling webhook "vtargetgroupbinding.elbv2.k8s.aws": failed to call webhook: Post "https://aws-load-balancer-webhook-service.load-balancer.svc:443/validate-elbv2-k8s-aws-v1beta1-targetgroupbinding?timeout=10s": context deadline exceeded
```

* load-balancer is the namespace where i deploy aws-load-balancer.
