### ISSUE TITLE
ALB - Impossibile configure default Rule

### ISSUE THREAD

**Issue by quadrinho** [kubernetes-sigs/aws-load-balancer-controller#2966]
**Describe the bug**
It is impossible to configure the default Rule of an ALB created using alb annotations

**Steps to reproduce**

I try to install argocd application and configure the ingress:

```
    ingress:
      enabled: true
      ingressClassName: "alb"
      annotations:
         alb.ingress.kubernetes.io/load-balancer-name: argocd2
         alb.ingress.kubernetes.io/target-type: ip
         alb.ingress.kubernetes.io/scheme: internal
         alb.ingress.kubernetes.io/backend-protocol: HTTP
         alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
         alb.ingress.kubernetes.io/healthcheck-port: traffic-port
         alb.ingress.kubernetes.io/healthcheck-path: /
         alb.ingress.kubernetes.io/healthcheck-interval-seconds: '60'
         alb.ingress.kubernetes.io/success-codes: 200-399
         alb.ingress.kubernetes.io/unhealthy-threshold-count: '5'
         alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=30,load_balancing.algorithm.type=least_outstanding_requests,stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=180
         alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-2016-08"
         alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
         alb.ingress.kubernetes.io/group.name: "argo-alb-private"
         alb.ingress.kubernetes.io/group.order: "1"
```

I have tried to configure the default application using different configurations:

```
         alb.ingress.kubernetes.io/actions.default-rule: >
           {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"200","messageBody":"OK"}}

      extraPaths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: default-rule
              port:
                name: use-annotation

```

and also this one:

```
      extraPaths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ssl-redirect
              port:
                name: use-annotation
```

**Expected outcome**
The Default rule should not be a fixed response 404

![image](https://user-images.githubusercontent.com/48757909/211559247-ab1a9625-027b-4fec-8fd5-7a7aae0325b9.png)

**Environment**

* AWS Load Balancer controller version --> 2.4
* Kubernetes version --> 1.23
* Using EKS (yes/no), if so version? EKS 1.23

**Additional Context**:

**Comment by kishorj** [comment]
@quadrinho, you can configure the default rule via the ingress `spec.defaultBackend` attribute. For example:
```
spec:
  defaultBackend:
    service:
      name: default-rule
      port:
        name: use-annotation
```

If you don't configure default backend, controller configures a default 404 rule.

**Comment by quadrinho** [comment]
> @quadrinho, you can configure the default rule via the ingress `spec.defaultBackend` attribute. For example:
> 
> ```
> spec:
>   defaultBackend:
>     service:
>       name: default-rule
>       port:
>         name: use-annotation
> ```
> 
> If you don't specify a default backend, the controller configures a default 404 rule.

Hello @kishorj,

i have tried but it seems the field defaultBackend is unknown:

`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0]): unknown field "defaultBackend" in io.k8s.api.networking.v1.HTTPIngressPath, ValidationError(Ingress.spec.rules[0].http.paths[0]): missing required field "backend" in io.k8s.api.networking.v1.HTTPIngressPath]`

Can you help me on that?

**Comment by kishorj** [comment]
@quadrinho, your ingress manifest seems incorrect, would you be able to post the entire manifest?

**Comment by quadrinho** [comment]
> @quadrinho, your ingress manifest seems incorrect, would you be able to post the entire manifest?

hello @kishorj 

i am trying to deploy argocd chart. Below the template of the ingress:


```
{{- if .Values.server.ingress.enabled -}}
{{- $serviceName := include "argo-cd.server.fullname" . -}}
{{- $servicePort := ternary .Values.server.service.servicePortHttps .Values.server.service.servicePortHttp .Values.server.ingress.https -}}
{{- $paths := .Values.server.ingress.paths -}}
{{- $extraPaths := .Values.server.ingress.extraPaths -}}
{{- $pathType := .Values.server.ingress.pathType -}}
apiVersion: {{ include "argo-cd.apiVersion.ingress" . }}
kind: Ingress
metadata:
{{- if .Values.server.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.server.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if and .Values.server.ingressGrpc.isAWSALB .Values.server.ingressGrpc.enabled }}
    alb.ingress.kubernetes.io/conditions.{{ template "argo-cd.server.fullname" . }}-grpc: |
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "Content-Type", "values":["application/grpc"]}}]
  {{- end }}
{{- end }}
  name: {{ template "argo-cd.server.fullname" . }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
    {{- if .Values.server.ingress.labels }}
    {{- toYaml .Values.server.ingress.labels | nindent 4 }}
    {{- end }}
spec:
  {{- if eq (include "argo-cd.apiVersion.ingress" $) "networking.k8s.io/v1" }}
  {{- with .Values.server.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- end }}
  rules:
  {{- if .Values.server.ingress.hosts }}
    {{- range $host := .Values.server.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          {{- if $extraPaths }}
          {{- toYaml $extraPaths | nindent 10 }}
          {{- end }}
          {{- range $p := $paths }}
          {{- if and $.Values.server.ingressGrpc.isAWSALB $.Values.server.ingressGrpc.enabled }}
          - path: {{ $p }}
            {{- if eq (include "argo-cd.apiVersion.ingress" $) "networking.k8s.io/v1" }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if eq (include "argo-cd.apiVersion.ingress" $) "networking.k8s.io/v1" }}
              service:
                name: {{ template "argo-cd.server.fullname" $ }}-grpc
                port:
                  {{- if kindIs "float64" $servicePort }}
                  number: {{ $servicePort }}
                  {{- else }}
                  name: {{ $servicePort }}
                  {{- end }}
              {{- else }}
              serviceName: {{ template "argo-cd.server.fullname" $ }}-grpc
              servicePort: {{ $servicePort }}
              {{- end }}
            {{- end }}
          - path: {{ $p }}
            {{- if eq (include "argo-cd.apiVersion.ingress" $) "networking.k8s.io/v1" }}
            pathType: {{ $pathType }}
            {{- end }}
            backend:
              {{- if eq (include "argo-cd.apiVersion.ingress" $) "networking.k8s.io/v1" }}
              service:
                name: {{ $serviceName }}
                port:
                  {{- if kindIs "float64" $servicePort }}
                  number: {{ $servicePort }}
                  {{- else }}
                  name: {{ $servicePort }}
                  {{- end }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
          {{- end -}}
    {{- end -}}
  {{- else }}
    - http:
        paths:
          {{- if $extraPaths }}
          {{- toYaml $extraPaths | nindent 10 }}
          {{- end }}
          {{- range $p := $paths }}
          - path: {{ $p }}
            {{- if eq (include "argo-cd.apiVersion.ingress" $) "networking.k8s.io/v1" }}
            pathType: {{ $pathType }}
            {{- end }}
            backend:
              {{- if eq (include "argo-cd.apiVersion.ingress" $) "networking.k8s.io/v1" }}
              service:
                name: {{ $serviceName }}
                port:
                  {{- if kindIs "float64" $servicePort }}
                  number: {{ $servicePort }}
                  {{- else }}
                  name: {{ $servicePort }}
                  {{- end }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
          {{- end -}}
  {{- end -}}
  {{- if .Values.server.ingress.tls }}
  tls:
    {{- toYaml .Values.server.ingress.tls | nindent 4 }}
  {{- end -}}
{{- end -}}

```

I don't see nothing incorrect.

Here the yaml of the ingress:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.default-rule: |
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"200","messageBody":"OK"}}
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:XXXXXXX:certificate/XXXXXXXXXXXXXXXXXXXX
    alb.ingress.kubernetes.io/group.name: argo-alb-private
    alb.ingress.kubernetes.io/group.order: "1"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "60"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=XXXXXXXXXX,access_logs.s3.prefix=argocd
    alb.ingress.kubernetes.io/load-balancer-name: argocd2
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/security-groups: sg-XXXXXXXXXXXXXX
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-2016-08
    alb.ingress.kubernetes.io/success-codes: 200-399
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=30,load_balancing.algorithm.type=least_outstanding_requests,stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=180
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "5"
    meta.helm.sh/release-name: argo-cd
    meta.helm.sh/release-namespace: argocd
  finalizers:
  - group.ingress.k8s.aws/argo-alb-private
  generation: 1
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-5.14.1
  name: argo-cd-argocd-server
  namespace: argocd
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: argo-cd-argocd-server
            port:
              number: 80
        path: /
        pathType: Prefix



```
Naturally in the ingress above there isn't "defaultBackend" because it doesn't work

Below the values used to create the ingress:

```
    ingress:
      enabled: true
      ingressClassName: "alb"
      annotations:
         alb.ingress.kubernetes.io/security-groups: sg-XXXXXXXXXXXXXX
         alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=XXXXXXXXXXXXXXX,access_logs.s3.prefix=argocd
         alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:XXXXXXXXXXXXXX:certificate/XXXXXXXXXXXXXXXXX
         alb.ingress.kubernetes.io/load-balancer-name: argocd2
         alb.ingress.kubernetes.io/target-type: ip
         alb.ingress.kubernetes.io/scheme: internal
         alb.ingress.kubernetes.io/backend-protocol: HTTP
         alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
         alb.ingress.kubernetes.io/healthcheck-port: traffic-port
         alb.ingress.kubernetes.io/healthcheck-path: /
         alb.ingress.kubernetes.io/healthcheck-interval-seconds: '60'
         alb.ingress.kubernetes.io/success-codes: 200-399
         alb.ingress.kubernetes.io/unhealthy-threshold-count: '5'
         alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=30,load_balancing.algorithm.type=least_outstanding_requests,stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=180
         alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-2016-08"
         #alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
         alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
         alb.ingress.kubernetes.io/group.name: "argo-alb-private"
         alb.ingress.kubernetes.io/group.order: "1"
         alb.ingress.kubernetes.io/actions.default-rule: >
           {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"200","messageBody":"OK"}}

      hosts:
       - XXXX-XXX-XXXX
      https: false
      extraPaths:
        - path: /
          pathType: Prefix
          defaultBackend:
            service:
              name: default-rule
              port:
                name: use-annotation
```
 

Can you help me?
