### ISSUE TITLE
Removing Ingress deletes ALB rules with the same host even if they were not created by that Ingress

### ISSUE THREAD

**Issue by SimPlat** [kubernetes-sigs/aws-load-balancer-controller#2978]
**Describe the bug**
Removing ingress deletes ALB rules with the same host name even if they were not created by that specific ingress.

**Steps to reproduce**
1. Add a rule to the ALB (with or without path)
2. Deploy the Ingress using the same host as the above rule and a different sub-path
3. 
```
ALB Rules:
- Created by Ingress
   1. example.com/A -> Deployment's target group
   2. example.com/B -> Deployment's target group
- Pre-existing ALB rules
   3. example.com/ -> Pre-existing target group
   4. example.com/C -> Pre-existing target group
```
5. Deleting Ingress will delete the subpath rules (as expected) but also the pre-existing rules as well.

**Expected outcome**
- Deleting the Ingress should only delete the rules created by the ALB and not the pre-existing rules.

**Environment**
* **AWS Load Balancer controller version:** 2.4.4
* **Kubernetes version:** Client: 1.23.13 + Server: 1.24.8
* **EKS Version:** eks.3
* **Eksctl Version:** 0.123.0

**Additional Context**:
Ingress Helm values:
```
ingress:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: ****
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'    
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP    
    kubernetes.io/ingress.allow-http: "false"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: alb_name
    alb.ingress.kubernetes.io/group.name: alb_group
    alb.ingress.kubernetes.io/success-codes: "200"
  hosts:
    - host: example.com
      paths:
        - path: /A
          pathType: Prefix
        - path: /B
          pathType: Prefix
```
