### ISSUE TITLE
Unable to deploy GRPC application with ALB

### ISSUE THREAD

**Issue by DLesage25** [kubernetes-sigs/aws-load-balancer-controller#2980]
**Describe the bug**
I have a GRPC application running on an EKS cluster. I have set up the AWS Load Balancer Controller, and have configured an ingress as follows:

Ingress.yml
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: staging-grpc-ingress
  namespace: staging
  annotations:
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - host: grpc-staging.domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grpc-service
                port:
                  number: 50051

``` 

The `grpc-service` referenced above is configured as follows:
```
apiVersion: v1
kind: Service
metadata:
  name: grpc-service
spec:
  type: ClusterIP
  ports:
    - port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    app: grpc-app
```

Additionally, I've created an alias A record on R53 that points to the DNS name of the load balancer created above, but I am unable to connect to `grpcs://grpc-staging.domain.com:443` or any port for that matter.

**Steps to reproduce**

**Expected outcome**
Expected the GRPC application to be exposed correctly on port 443.

**Environment**

* AWS Load Balancer controller version 2.4.0
* Kubernetes version 1.24
* Using EKS (yes/no), if so version? 1.24

**Additional Context**:
I can see the ALB created  and the target group with 1 healthy listener and set to `HTTP: 50051` and protocol `gRPC`, but as soon as I make a request it deregisters targets and registers back a few minutes later.
