### ISSUE TITLE
Path based routing with AWS controller and gunicorn not work

### ISSUE THREAD

**Issue by pilchita** [kubernetes-sigs/aws-load-balancer-controller#3016]
I’m trying to deploy several applications using the AWS driver and gunicorn in a Kubernetes cluster in EKS.

This is my setup:

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: backend-apps
  name: default-http-backend
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/group.name: backend-apps
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
spec:
  rules:
    - http:
        paths:
        - path: /app01
          pathType: Prefix
          backend:
            service:
              name: app01
              port:
                number: 8004
        - path: /app02
          pathType: Prefix
          backend:
            service:
              name: app02
              port: 
                number: 8003
        - path: /app03
          pathType: Prefix
          backend:
            service:
              name: app03
              port:
                number: 8006
        - path: /
          pathType: Prefix
          backend:
            service:
              name: app00
              port:
                number: 8001
        - path: /booking-service
          pathType: Prefix
          backend:
            service:
              name: booking-service
              port:
                number: 8005
```

Each backend is configured this way, I leave an example:

```

---
apiVersion: v1
kind: Service
metadata:
  name: app01
  namespace: backend-apps
  labels:
    app: app01
  annotations:
spec:
  type: NodePort
  selector:
    app: app01
  ports:
   - name: http
     targetPort: 8004
     port: 8004
     protocol: TCP

```
Each deployment listens on its port:

```
        ports:
         - name: http
           containerPort: 8004
           protocol: TCP

```

When I do the tests inside a pod of the same namespace, I mean to make a curl with the corresponding payload the response of the application is expected but when I make a request to the dns of the Amazon balancer I see this error:

```

http 2023-01-31T16:08:13.651715Z app/x-xxxxx-xxx/xxxx 10.54.171.250:49510 10.41.11.222:31521 0.001 0.008 0.000 404 404 2546 331 "POST http://x.x.x:80/booking-service/create-booking HTTP/1.1" "curl/7.77.0" - - arn:aws:elasticloadbalancing:x-x-x:xxxx:targetgroup/k8s-xxx-bookings-f1744e9171/06c7c2cf86463bf0 "Root=1-63d93ced-1f04c4a716c9df8738db5316" "-" "-" 2 2023-01-31T16:08:13.642000Z "forward" "-" "-" "10.41.11.222:31521" "404" "-" "-"

```

For some reason it is not working as appropriate the redirection by the path from the AWS balancer.

I have read the documentation of Amazon and Kubernetes without finding any indication of where the problem may be so requested your help.

UPDATE:

This is work fine:
```
  - host: adapters-prod-booking.aws.aaaaaa.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: booking-service
            port:
              number: 8005
```

this is not work
```
  - host: adapters-prod.aws.aaaaa.com
    http:
      paths: 
      - path: /app01
        pathType: Prefix
        backend:
          service:
            name: app01
            port:
              number: 8004
      - path: /app02
        pathType: Prefix
        backend:
          service:
            name: app02
            port: 
              number: 8003
      - path: /app03
        pathType: Prefix
        backend:
          service:
            name: app03
            port:
              number: 8006
      - path: /booking-service
        pathType: Prefix
        backend:
          service:
            name: booking-service
            port:
              number: 8005
```
