### ISSUE TITLE
The Service "openvpn-nlb" is invalid: may not contain more than 1 protocol when type is 'LoadBalancer'

### ISSUE THREAD

**Issue by oleg-ku-32768** [kubernetes-sigs/aws-load-balancer-controller#3019]
Getting weird error below, is it a bug in my yaml?
```
The Service "openvpn-nlb" is invalid: 
spec.ports: 
Invalid value: []core.ServicePort {
  core.ServicePort {
    Name:"https", 
    Protocol:"TCP",
    AppProtocol:(*string)(nil),
    Port:443,
    TargetPort:intstr.IntOrString {
      Type:0,
      IntVal:443,
      StrVal:""
    }, 
    NodePort:32554
  }, 
  core.ServicePort {
    Name:"udp-1194",
    Protocol:"UDP",
    AppProtocol:(*string)(nil),
    Port:1194,
    TargetPort:intstr.IntOrString { 
      Type:0,
      IntVal:1194,
      StrVal:""
    },
    NodePort:31690
  }
}
: may not contain more than 1 protocol when type is 'LoadBalancer'
```
Is it k8s service **when type is 'LoadBalancer'** limitation?
NLB supports TCP and UDP at the same time.
No doubt, aws-load-balancer-controller supports it too.
It must be error in my yaml, but I cannot find it...
```
apiVersion: v1
kind: Service
metadata:
  name: openvpn-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: openvpn-2

    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4

    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0d9167d0a438b3304, subnet-08e646467a72b7605

    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "80"

    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: deregistration_delay.timeout_seconds=15
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: deregistration_delay.connection_termination.enabled=true
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
spec:
  selector:
    app: openvpn
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  ports:
    - name: https
      port: 443
      protocol: TCP
    - name: udp-1194
      port: 1194
      protocol: UDP
```
