### ISSUE TITLE
Failing to create condition and action for fix response

### ISSUE THREAD

**Issue by aidan-melen** [kubernetes-sigs/aws-load-balancer-controller#3020]
**Describe the bug**

I want to restrict the loadbalancer so that it only forwards to the service for all GET and HEAD http method requests. I also want to explicitly have a fixed response for all POST, PUT, and DELETE http method requests.

The following manifest:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ...
    alb.ingress.kubernetes.io/conditions.my-service: '[{"field":"http-request-method","httpRequestMethodConfig":{"Values":["GET","HEAD"]}}]'
...
spec:
  ingressClassName: alb
  rules:
  - host.example.com
    http:
      paths:
      - backend:
          service:
            name: my-service
            port:
              number: 8083
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - host.example.com
status:
  loadBalancer:
    ingress:
    - hostname: internal-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXX.elb.amazonaws.com
```

configured these rules:

<img width="967" alt="Screen Shot 2023-02-02 at 8 00 24 PM" src="https://user-images.githubusercontent.com/54326778/216515343-915ced02-c4e2-4e7f-b918-693b202f4f14.png">

In this configuration, it will only allow GET and HEAD requests. However, it will return the default action response (404 not found) for POST, PUT, DELETE requests. 

I tested the next change by manually adding a fixed response rule in the console such that POST, PUT, and DELETE condition redirects to a fixed response: `401 Client Error: Unauthorized`:

<img width="974" alt="Screen Shot 2023-02-02 at 9 48 59 PM" src="https://user-images.githubusercontent.com/54326778/216516096-3ebb59e9-635a-4f14-9e14-8b59db26fb55.png">

After testing, this configuration works as expected. Now trying to implement this with `condition` and `action` annotations seems impossible because `path` is required by the spec.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ...
    alb.ingress.kubernetes.io/conditions.my-service: '[{"field":"http-request-method","httpRequestMethodConfig":{"Values":["GET","HEAD"]}}]'
    alb.ingress.kubernetes.io/conditions.unauthorized: '[{"field":"http-request-method","httpRequestMethodConfig":{"Values":["POST","PUT", "DELETE"]}}]'
    alb.ingress.kubernetes.io/action.unauthorized: '{"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"401","messageBody":"401 Client Error: Unauthorized"}}'
...
spec:
  ingressClassName: alb
  rules:
  - host.example.com
    http:
      paths:
      - backend:
          service:
            name: my-service
            port:
              number: 8083
        path: /
        pathType: Prefix
  - http:
      paths:
      - backend:
          service:
            name: unauthorized
            port:
              name: use-annotation
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - host:example.com
status:
  loadBalancer:
    ingress:
    - hostname: internal-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXX.elb.amazonaws.com
```

I get this new rule:

<img width="1013" alt="Screen Shot 2023-02-02 at 10 01 24 PM" src="https://user-images.githubusercontent.com/54326778/216516635-5dcc60d9-fa4a-4942-811c-f10f4573a68b.png">

The other thing that is off is that the fix response is a 503 and not the 401 that was configured in the action annotation. I am guessing this is because the `unauthorized` service doesn't exist so that is what the operator is returning.

Despite this, I can still perform GET, HEAD http method requests, however, no the POST, PUT, DELETE fixed response is not right.

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version: v2.4.4
* Kubernetes version: 1.23
* Using EKS (yes), if so version? eks.5

**Additional Context**:

I realize I could use AWS Incognito or some other authentication mechanism, but the k8s application already has basic auth enabled and another service feels like overkill. I just want to create a readonly endpoint by restricting http method requests and redirecting fixed responses
