### ISSUE TITLE
a new NLB with a name that's used before, overrides the existing NLB configurations

### ISSUE THREAD

**Issue by eslam-gomaa** [kubernetes-sigs/aws-load-balancer-controller#3027]
**Describe the bug**
A concise description of what the bug is.

> a new NLB with a name that's used before, overrides the existing NLB configurations .. making the currently used port not reachable.

**Steps to reproduce**

create 2 NLBs with the same name

**Expected outcome**
A concise description of what you expected to happen.

> Should fail if the the NLB's name is already used.

**Environment**

> Creating NLBs with K8s LoadBalancer services.

* AWS Load Balancer controller version: v2
* Kubernetes version
* Using EKS (yes/no), if so version?

**Additional Context**:

> More about my use case; 
- I created a new set of NLBs (with the same name of existing NLBs) 
- that overriden the existing NLBs configurations, resulting in making the NLBs not reachable on the preconfigured port anymore.

> In the screenshoot, both the highlighted K8s svc LBs have the same names, but only listening on the new service port "9096" .. making "9095" not reachable. 

![image](https://user-images.githubusercontent.com/33789516/216921281-7ceecda9-2ab5-469f-9efc-0aaed928b925.png)

**Comment by eslam-gomaa** [comment]
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2533 related

**Comment by M00nF1sh** [comment]
/kind bug
we should check whether ELBv2 CreateLoadBalancer API returns an existing LB's ARN when create a new LB with the  existing LB's name but different settings. 
And if that's the case, when using the LB name feature(or we always do the validation), we should check whether a existing LB exists with same name and validate the tags.

**Comment by rdcarrera** [comment]
Hi everyone,

I find myself in the same situation of being able to reuse the NLB with multiple services. I need to expose approximately 1800 services from my EKS cluster, and for orchestrating these services, I have a wrapper that manages the creation of deployments and services for them.

If the integration with NLB were similar to ALB's, I would only need to integrate with the Kubernetes API, which would make the management of everything very convenient. Otherwise, I would need to integrate with the AWS API to manage the creation of NLBs, target groups, associate the target group bindings, and so on.

After analyzing the code, I have noticed that the loop responsible for cleaning up the old listeners is located in:

- pkg/deploy/elbv2/listener_synthesizer.go (lines 61-65)

```
matchedResAndSDKLSs, unmatchedResLSs, _ := matchResAndSDKListeners(resLSs, sdkLSs)
// for _, sdkLS := range unmatchedSDKLSs {
// 	if err := s.lsManager.Delete(ctx, sdkLS); err != nil {
// 		return err
// 	}
// }

```
By commenting out the loop and build the controller, I have managed to reuse the NLB as expected. However, I would prefer a solution that does not break future updates or the correct functionality of the controller.

Thank you,
Best regards!

**Comment by elamaran11** [comment]
Im running in to same issue. Hope this is fixed soon

**Comment by yoonhyunwoo** [comment]
There seems to be no problem at the moment, so I think we can close this issue.
When I previously attempted to create a second Kubernetes Service of type LoadBalancer using the same NLB name but with different port configurations, the following error occurred:
```
apiVersion: v1
kind: Service
metadata:
  name: example-nlb-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-name: "my-custom-nlb"
spec:
  type: LoadBalancer
  selector:
    app: app-v1
  ports:
    - port: 9095
      targetPort: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-v1
  template:
    metadata:
      labels:
        app: app-v1
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: example-nlb-service-2
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-name: "my-custom-nlb"
spec:
  type: LoadBalancer
  selector:
    app: app-v2
  ports:
    - port: 9096
      targetPort: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-v2
  template:
    metadata:
      labels:
        app: app-v2
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
```
When applying the second Service (example-nlb-service-2), I received the following error:
```
{"level":"error","ts":"2025-05-17T10:13:03Z","msg":"Reconciler error","controller":"service","namespace":"default","name":"example-nlb-service-2","reconcileID":"b3b1d12a-5f12-4b6d-89da-2d4a2587eb55","error":"operation error Elastic Load Balancing v2: CreateLoadBalancer, https response error StatusCode: 400, RequestID: 6375c362-2556-4466-9689-c3b0dc838a47, DuplicateLoadBalancerName: A load balancer with the same name 'my-custom-nlb' exists, but with different settings"}
```
If there was anything incorrect during testing, please let me know.
