### ISSUE TITLE
Question: Multiple Listeners to the same targetPort?

### ISSUE THREAD

**Issue by yuvalshi0** [kubernetes-sigs/aws-load-balancer-controller#3030]
I have a `LoadBalancer`, and I want both ports 8080 and port 8081 to be forwarded to same `targetPort` (8082, for example), how can this be done?

**Comment by yuvalshi0** [comment]
I managed to do so with this yml, the port names should be different:
```yml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "grpc"
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
      targetPort: {{ .Values.port }}
      name: http
    - port: 1212
      protocol: TCP
      targetPort: {{ .Values.port }}
      name: grpc
...
```
