### ISSUE TITLE
Custom ICMP - IPv4 rule created for SG

### ISSUE THREAD

**Issue by tculp** [kubernetes-sigs/aws-load-balancer-controller#3031]
**Describe the bug**
I am creating an NLB for my service and I'm seeing a Custom ICMP - IPv4 rule created. The service I am creating is as followed:

```
apiVersion: v1
kind: Service
metadata:
  name: gitlab-runner-session-server
  namespace: "gitlab-runner"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
    service.beta.kubernetes.io/aws-load-balancer-name: gitlab-runner-session-server
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
    service.beta.kubernetes.io/aws-load-balancer-type: external
  labels:
    app: gitlab-runner
    chart: gitlab-runner-0.49.0
    release: "gitlab-runner"
    heritage: "Helm"
spec:
  selector:
    app: gitlab-runner
    release: "gitlab-runner"
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 8093
```

<img width="885" alt="Screen Shot 2023-02-06 at 3 40 48 PM" src="https://user-images.githubusercontent.com/19711877/217080410-95f307fc-8080-4c81-bcbd-1e447a88437a.png">

Is there any way to avoid this rule being created? Security policies often dislike ICMP access to resources.

Also see: https://gitlab.com/gitlab-org/charts/gitlab/-/issues/1596

**Steps to reproduce**
I am having difficulty reproducing.

**Expected outcome**
No Custom ICMP rule, or be able to disable it.

**Environment**

* AWS Load Balancer controller version: 2.4.0
* Kubernetes version: 1.24
* Using EKS (yes/no), if so version? Yes, latest

**Additional Context**:
