### ISSUE TITLE
annotation service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "false" does not work

### ISSUE THREAD

**Issue by vumdao** [kubernetes-sigs/aws-load-balancer-controller#3041]
**Describe the bug**
I set annotation `service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "false"` in my NLB service but the controller still add IP CIDR to the EKS Security Group

```
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "false"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: app-nlb
spec:
  loadBalancerSourceRanges:
    - 10.0.0.0/8
```

Logs: https://gist.github.com/vumdao/c655c8d494850cda3a17fa1619c3f295

**Steps to reproduce**
Create NLB service with the annotation and check the security group 

**Expected outcome**
The controller does not add any IP to SG except the `loadBalancerSourceRanges`

* AWS Load Balancer controller version v2.4.6
* Kubernetes version 1.24
* Using EKS v1.24
