### ISSUE TITLE
kubernetes.io/ingress.class and ingressClassName at the same time

### ISSUE THREAD

**Issue by yasinlachiny** [kubernetes-sigs/aws-load-balancer-controller#3054]
**Describe the bug**

If we have an ingress 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingtest
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internal
spec:
  ingressClassName: test
```
And also define the scheme as `internet-facing` in `IngressClassParams`

What is the expected behavior in this situation?

Right now it will deploy ALB with scheme `internal` and ignores `IngressClass`
I mean which one has priority? 
* AWS Load Balancer controller version
Built from main branch
* Kubernetes version
1.22
* Using EKS (yes/no), if so version?
1.22
**Additional Context**:
