### ISSUE TITLE
Question: one NLB with multiple listeners with different protocols, fully managed from k8s/YAML?

### ISSUE THREAD

**Issue by utkarsh079** [kubernetes-sigs/aws-load-balancer-controller#3057]
**Describe the bug**
I am trying to create multiple listeners with NLB with annotation `service.beta.kubernetes.io/aws-load-balancer-type: nlb` and ssl-cert. What I need is to create one listener with TLS and other ones with just TCP. But all the listeners are coming up with TLS.

```
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<>"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
```

**Environment**
* Kubernetes version - 1.21
* Using EKS (yes/no) - EKS 1.21

**Additional Context**:
