### ISSUE TITLE
Helm chart 1.4.8 indicates `aws-load-balancer-controller` is version `v2.4.7` in the labels but the image remains on `v2.4.2`

### ISSUE THREAD

**Issue by OliverRC** [kubernetes-sigs/aws-load-balancer-controller#3077]
**Describe the bug**
Helm chart 1.4.8 indicates `aws-load-balancer-controller` is version `v2.4.7` in the labels but the image remains on `v2.4.2`

**Steps to reproduce**
Previously had installed `v1.4.2` which added deployment on `v2.4.2`.

Following:
https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html

```
helm repo add eks https://aws.github.io/eks-charts
```

```
helm repo update
```

```
helm upgrade aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system
```

**Expected outcome**
Expected to see deployment progress with updated pods on new `v2.4.7` image

**Environment**

* Helm chart version = 1.4.8
* AWS Load Balancer controller version = v2.4.7
* Kubernetes version = 1.23
* EKS = yes

**Additional Context**:

```
 helm upgrade aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --dry-run
```

```
# Source: aws-load-balancer-controller/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  labels:
    helm.sh/chart: aws-load-balancer-controller-1.4.8
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: aws-load-balancer-controller
    app.kubernetes.io/version: "v2.4.7"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-load-balancer-controller
      app.kubernetes.io/instance: aws-load-balancer-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aws-load-balancer-controller
        app.kubernetes.io/instance: aws-load-balancer-controller
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: aws-load-balancer-controller
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: aws-load-balancer-tls
      securityContext:
        fsGroup: 65534
      containers:
      - name: aws-load-balancer-controller
        args:
        - --cluster-name=my-cluster
        - --ingress-class=alb
        - --aws-region=af-south-1
        - --aws-vpc-id=vpc-....
        command:
        - /controller
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        image: "877085696533.dkr.ecr.af-south-1.amazonaws.com/amazon/aws-load-balancer-controller:v2.4.2"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        ports:
        - name: webhook-server
          containerPort: 9443
          protocol: TCP
        - name: metrics-server
          containerPort: 8080
          protocol: TCP
        resources:
          {}
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /healthz
            port: 61779
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 10
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - aws-load-balancer-controller
              topologyKey: kubernetes.io/hostname
      priorityClassName: "system-cluster-critical"
```
