### ISSUE TITLE
Respects Single AZ Whitelist of ELB in v2

### ISSUE THREAD

**Issue by hitsub2** [kubernetes-sigs/aws-load-balancer-controller#3082]
**Is your feature request related to a problem?**
If we got a whitelist of single az of ELB, the v2 controller does not respects that, according to the document:

<p>
At least two subnets in different Availability Zones. The AWS Load Balancer Controller chooses one subnet from each Availability Zone. When multiple tagged subnets are found in an Availability Zone, the controller chooses the subnet whose subnet ID comes first lexicographically. Each subnet must have at least eight available IP addresses.
</p>

Currently error comes up from the v2 controller

```json
{"level":"error","ts":1677568163.5564663,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"ingress-default","namespace":"default","error":"subnets count less than minimal required count: 1 < 2"}
```

**Describe the solution you'd like**
Maybe adding a flag to turn off the check and respects the whitelist.

**Describe alternatives you've considered**
 Adding another annotation of the non-target subnet, for example, **subnet-0987654321** .

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: ingress-default
 annotations:
   alb.ingress.kubernetes.io/scheme: internet-facing
   alb.ingress.kubernetes.io/target-type: ip
   alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=10
   alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
   alb.ingress.kubernetes.io/backend-protocol: HTTP
   alb.ingress.kubernetes.io/subnets: subnet-123456789,subnet-0987654321
```
