### ISSUE TITLE
security group rules not created with nlb

### ISSUE THREAD

**Issue by rrey** [kubernetes-sigs/aws-load-balancer-controller#3087]
**Describe the bug**

It is more of a support request since I got things working properly on different environments.
I am facing a deployment with following annotations:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: SomeKey=SomeVal
    service.beta.kubernetes.io/aws-load-balancer-name: istio-external-ingress
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
    service.beta.kubernetes.io/aws-load-balancer-type: external
```

nlb is properly created but targets were not healthy. We realised that the security group rules were not created in the pod sg and we had to create them manually to have things working properly.

I check the logs of the controller and I have no error appearing, here are the last logs:
```
{"level":"info","ts":1677767993.8420088,"logger":"controllers.service","msg":"successfully deployed model","service":{"namespace":"istio-system","name":"istio-external-ingress"}}
```
The preceding log contains the model with several arns that would like to avoid posting.
I saw other issue talking about having 2 sg on the eni, but they report an error in the controller which I don't have.

Would you have any hint around possible reasons that could lead to the sg rules not created ?

**Environment**

* AWS Load Balancer controller version : `v2.4.6` through Helm chart `1.4.7`
* Kubernetes version : `EKS 1.23`
* Using EKS (yes/no), if so version? `EKS 1.23`
