### ISSUE TITLE
Service with type NodePort/ClusterIP creates NLB with valid service annotations

### ISSUE THREAD

**Issue by ib-ak** [kubernetes-sigs/aws-load-balancer-controller#3094]
**Describe the bug**
Service with NodePort/ClusterIP type should not create NLB.

**Steps to reproduce**

1. Create a NodePort or ClusterIP Service with valid annotations

```
apiVersion: v1
kind: Service
metadata:
 annotations:
  service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /ready
  service.beta.kubernetes.io/aws-load-balancer-name: my-new-nlb
  service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
  service.beta.kubernetes.io/aws-load-balancer-scheme: internal
  service.beta.kubernetes.io/aws-load-balancer-type: external
 name: service-my-nodeport-service
spec:
 type: NodePort
 ports:
 - name: http
   port: 80
   protocol: TCP
   targetPort: http
 selector:
  target: app
```

**Expected outcome**
3. NodePort service gets created with no Load Balancer

**Environment**

* AWS Load Balancer controller version 2.4
* Kubernetes version 1.24
* Using EKS (yes/no), if so version?

**Additional Context**:

Output
```
kubectl -n test describe svc service-my-nodeport-service 
Name:                     service-my-nodeport-service
Namespace:                test
Labels:                   <none>
Annotations:              service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /ready
                          service.beta.kubernetes.io/aws-load-balancer-name: my-new-nlb
                          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
                          service.beta.kubernetes.io/aws-load-balancer-scheme: internal
                          service.beta.kubernetes.io/aws-load-balancer-type: external
Selector:                 target=app
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       172.20.221.57
IPs:                      172.20.221.57
LoadBalancer Ingress:     my-new-nlb-xyz.elb.us-west-2.amazonaws.com
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  30623/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                  Age   From     Message
  ----    ------                  ----  ----     -------
  Normal  SuccessfullyReconciled  19s   service  Successfully reconciled
```
