### ISSUE TITLE
Cannot deploy TargetGroupBinding

### ISSUE THREAD

**Issue by SomaGallai** [kubernetes-sigs/aws-load-balancer-controller#3099]
**Describe the bug**
When trying to deploy the TargetGroupBinding in a cluster it fails with the following error code:
```bash
Error from server (InternalError): error when creating "tgb.yaml": Internal error occurred: failed calling webhook "mtargetgroupbinding.elbv2.k8s.aws": failed to call webhook: Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding?timeout=10s": context deadline exceeded
``` 
I have looked at the previous tickets with the same error code, but none of them seemed to be the same as this one, the load-balancer-controller is running and accessible, the pods are able to communicate with it properly. The security groups of the cluster should be setup correctly as well allowing all form of internal communication and outbound while limiting inbound to only the necessary.   
**Steps to reproduce**
By running: `kubectl apply --namespace=service-namespace -f tgb.yaml`
Where` tgb.yaml` is the default example of TargetGroupBinding:
```yaml
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: my-tgb
spec:
  serviceRef:
    name: awesome-service # route traffic to the awesome-service
    port: 80
  targetGroupARN: <arn-to-targetGroup>
```
  
**Expected outcome**
TargetGroupBinding gets deployed.

**Environment**

* AWS Load Balancer controller version: `helm.sh/chart=aws-load-balancer-controller-1.4.6`
* Kubernetes version: `app.kubernetes.io/version=v2.4.5`
* Using EKS (yes/no), if so version? `yes, eks.1`

**Additional Context**:
