### ISSUE TITLE
ClientSecret is not set correctly for OIDC authentication

### ISSUE THREAD

**Issue by riita10069** [kubernetes-sigs/aws-load-balancer-controller#3107]
**Describe the bug**

I want to use an external IdP to authenticate to the ALB.
For this purpose, we have created the following manifest.
(ingress and secret were created.)

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-1:0000000:certificate/xxxxxxxxxxxxxxxxx"
    alb.ingress.kubernetes.io/auth-type: oidc
    alb.ingress.kubernetes.io/auth-idp-oidc: '{"issuer":"https://example.com","authorizationEndpoint":"https://example.com/auth2/v1/authorize","tokenEndpoint":"https://example.com/api/oauth2/v2/token","userInfoEndpoint":"https://example.com/api/oauth2/v1/userinfo","secretName":"oidc-secret"}'
    alb.ingress.kubernetes.io/group.name: 'sample-alb'
    alb.ingress.kubernetes.io/group.order: '1'
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
---
apiVersion: v1
data:
  clientID: cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxIKN75Dxo= # base64 encoded
  clientSecret: YXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxK  # base64 encoded
kind: Secret
metadata:
  name: oidc-secret
type: Opaque
```

The created ALB does indeed have the rules set as configured, but the authentication does not go through.

The following error was displayed in the browser
**561 Authentication Error**

The only possible cause is clientSecret, so I tried to override only the clientSecret item on the AWS Management Concole, and it works correctly.

However, this is not IaC.
This may be a problem on the Load Balancer Controller side.

**Environment**

* AWS Load Balancer controller version v2.4.5
* Kubernetes version v1.24
* Using EKS (yes/no), if so version? yes, v1.24
