### ISSUE TITLE
Add support for external target groups

### ISSUE THREAD

**Issue by devopsmash** [kubernetes-sigs/aws-load-balancer-controller#3132]
Today we are using the managed Amazon MQ (Rabbitmq) in order to work with message broker.
Due to security reasons, I must use it without "Public accessibility". This means that if I want to expose the rabbitmq console dashboard I'll have to create a **target group**, attach the **Amazon MQ** Internal **private IP** to the **target group**, and then to attach the **target group** to an **Application load balancer**.

The thing is that I already have an ALB for my eks, and I would like to save costs by using the same ALB for my **Amazon MQ** target group.

There is any way to create an external target groups which created manually and are not part of the EKS, so the ALB ingress controller will attach this target group to the same ALB that it already has been created?

**Comment by kishorj** [comment]
@dsaydon90, you can use ingress-group to share same ALB across multiple ingress resources. If your targets are k8s pods then it is straightforward to create appropriate ingress rules to forward the traffic. If your target group is external, you could use the actions annotation `alb.ingress.kubernetes.io/actions.${action-name}`, live doc https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#actions to forward to your specific target group ARN.

For example, here is the ingress snippet:
```
  annotations:
    alb.ingress.kubernetes.io/actions.forward-single-tg: >
      {"type":"forward","targetGroupARN": "arn-of-your-target-group"}
...
  rules:
     - http:
         paths:
          - path: /path1
            pathType: Exact
            backend:
              service:
                name: forward-single-tg
                port:
                  name: use-annotation

```
