### ISSUE TITLE
Creating an ingress with mismatched annotations and backend service names creates global 503 routing path

### ISSUE THREAD

**Issue by JamesWojewoda** [kubernetes-sigs/aws-load-balancer-controller#3140]
I have an ingress with a service that has not yet been created yet. The pathing is set up, and normally it creates a listener  that routes to a 503 error for a specific header with the following config (this makes sense due to the service not existing). However, when I have an annotation with header conditions with a service backend with accidental mismatched names as such (technically in this case its an independent condition and backend because the names don't match:
```
    alb.ingress.kubernetes.io/conditions.foo: |
      [
        {
          "field": "http-header",
          "httpHeaderConfig": {
            "httpHeaderName": "model-name",
            "values": [
              "execute-order66"
            ]
          }
        }
      ]

```
```
      - backend:
          service:
            name: foo-wrong
            port:
              number: 50051
        pathType: ImplementationSpecific
```

It seems to create a listener on the AWS side with an overriding global path that auto routes to 503s (causing issues with the rest of the listeners)
<img width="1201" alt="Screenshot 2023-04-05 at 9 21 03 AM" src="https://user-images.githubusercontent.com/1399346/230093092-a88dcd11-c896-430d-9486-2674fa4ba2b2.png">

Understandably we can catch this type of user error in a Pull request, but is there a way to prevent this from happening?
