### ISSUE TITLE
Shared security group has no inbound rules causing all traffic to be blocked

### ISSUE THREAD

**Issue by junglie85** [kubernetes-sigs/aws-load-balancer-controller#3176]
**Describe the bug**

Setting `alb.ingress.kubernetes.io/inbound-cidrs` I expect the security group to allow inbound traffic. The inbound rules for the "Managed SecurityGroup for LoadBalancer" are updated but there does not seem to be a way to update "Shared Backend SecurityGroup for LoadBalancer": its inbound rules remain empty. I'm having to manually edit this SG to enable inbound traffic.

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version: 2.5.2
* Kubernetes version 1.26
* Using EKS (yes/no), if so version? 1.26

**Additional Context**:

**Comment by M00nF1sh** [comment]
@junglie85 
the `Shared Backend SecurityGroup for LoadBalancer` is supposed to have empty inbound rules.
The ALB have two security group attached: "Managed SecurityGroup for LoadBalancer" and "Shared Backend SecurityGroup for LoadBalancer". And the worker nodes is configured to allow traffic from `Shared Backend SecurityGroup for LoadBalancer`.
The sole purpose of "Shared Backend SecurityGroup for LoadBalancer" is to associate traffic from ALB to be with this security group, thus it's allowed by worker nodes, by design it should contain empty inbound rules.

**Comment by junglie85** [comment]
@M00nF1sh if the `Shared Backend SecurityGroup for LoadBalancer` is supposed to be empty, I don't understand what is missing in my config to allow traffic to reach the nodes:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard
  annotations:
    kubernetes.io/ingress.class: alb
    cert-manager.io/cluster-issuer: letsencrypt-staging
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/inbound-cidrs: 1.2.3.4/24
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 80}, {"HTTPS": 443}]'
spec:
  rules:
    - host: kuard.domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kuard
                port:
                  number: 443
  tls:
    - hosts:
        - kuard.domain.com
      secretName: kuard-tls
```

Currently, it is only able to reach the nodes if I add `Allow all traffic from source 1.2.3.4/24`  to `Shared Backend SecurityGroup for LoadBalancer` ingress rules.
