### ISSUE TITLE
Fails to use ACME TLS certificate and uses default HTTPS listener certificate instead

### ISSUE THREAD

**Issue by junglie85** [kubernetes-sigs/aws-load-balancer-controller#3178]
When I create an ingress with an ACME issued TLS certificate, it's not being applied and instead the ALB is using the default ACM generated certificate on the HTTPS listener for the domain instead.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard
  annotations:
    kubernetes.io/ingress.class: alb
    cert-manager.io/cluster-issuer: letsencrypt-staging
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/inbound-cidrs: 1.2.3.4/24
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 80}, {"HTTPS": 443}]'
spec:
  rules:
    - host: kuard.domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kuard
                port:
                  number: 443
  tls:
    - hosts:
        - kuard.domain.com
      secretName: kuard-tls
```

What annotations need to be set or configuration applied when deploying the load balancer controller to prevent this behaviour and use the ACME certificate?
