### ISSUE TITLE
AWS LB Controller does not update NLB tags when additional resource tags annotation value is changed

### ISSUE THREAD

**Issue by eolatham** [kubernetes-sigs/aws-load-balancer-controller#3181]
**Describe the bug**
Could be related to https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3157

AWS LB Controller does not update NLB tags when `service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags` annotation value is changed on the LoadBalancer Service.

It seems that although annotation changes trigger AWS LB Controller to reconcile Services again, the reconciliation that occurs after annotation changes is not a "full" reconciliation; the controller appears to verify that the NLB exists, but doesn't update the NLB's configuration with the annotation value changes.

**Steps to reproduce**

1. Create a LoadBalancer Service with the `service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags` annotation set to some value (i.e.`key=value`)
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: key=value
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "30"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: test
  namespace: default
spec:
  ports:
  - name: test
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: test
  type: LoadBalancer
```
3. Wait for the Service to be reconciled by the AWS LB Controller and the NLB to be created (this could take a couple of minutes)
4. Verify that the tags specified in the `service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags` annotation were correctly applied to the NLB (this can be done in the AWS console)
5. Edit the Service and change the value of the `service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags`  annotation to something else (i.e. `key=othervalue`)
```sh
kubectl annotate svc test --overwrite service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags="key=value"
```
7. Wait for the Service to be reconciled again (this should take just a couple of seconds)
8. See that the changes in the `service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags`  annotation are not applied to the existing NLB

**Expected outcome**
After updating the `service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags` annotation value on a LoadBalancer Service managed by the AWS LB Controller, the effective NLB tags in AWS should be updated to match the new annotation value.

**Environment**

* AWS Load Balancer controller version: **v2.4.4**
* Kubernetes version: **v1.24**
* Using EKS (yes/no), if so version? **Yes**
