### ISSUE TITLE
unable to resolve at least one subnet

### ISSUE THREAD

**Issue by pranavnateri** [kubernetes-sigs/aws-load-balancer-controller#3212]
**Describe the bug**
i have installed aws load balancer controller using helm chart. However, i am getting the below error.
`{"level":"error","ts":"2023-05-26T08:35:07Z","msg":"Reconciler error","controller":"service","object":{"name":"grpc-ingressgateway","namespace":"istio-system"},"namespace":"istio-system","name":"grpc-ingressgateway","reconcileID":"3e7af4a6-6605-4596-84dc-8c0ce70032c2","error":"unable to resolve at least one subnet"}`

Please note that i have the tags in all of my subnets(both private and public)
<img width="842" alt="image" src="https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/48081553/3ce9c0b3-f4af-4dc6-9234-ebd4cdbc519e">

Also, ALB controller points to the correct cluster name and VPC. 
```
containers:
      - args:
        - --cluster-name=intr-dev-eks-eu-west-1
        - --ingress-class=alb
        - --aws-region=eu-west-1
        - --aws-vpc-id=vpc-0b3f9a142f4370b89
        image: public.ecr.aws/eks/aws-load-balancer-controller:v2.5.2
```
        
But still its not discovering the subnets. Not sure what is the issue. Please help       

**Steps to reproduce**
Install AWS LOAD BALANCER CONTROLLER

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version
v2.5.2
* Kubernetes version
1.26
* Using EKS (yes/no), if so version?
yes, 1.26

**Additional Context**:

**Comment by oliviassss** [comment]
@pranavnateri can you double check if these subnets are under the vpc `vpc-0b3f9a142f4370b89` as assigned in your args. And also the available IP address should be more than 8 in your subnets.
Ref: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/release-2.5/pkg/networking/subnet_resolver.go#LL442C3-L442C3

**Comment by KaimingWan** [comment]
I met the same problem. Does any one have some idea?

**Comment by oliviassss** [comment]
@Vad1mo Thanks for the detailed info. The error log indicates the controller failed to resolve subnets, so I think it might be some transition issue when you deleted and recreated the NLB as initially. The best practice, as suggested in our live doc, would be assigning the same number of subnets via annotation ```service.beta.kubernetes.io/aws-load-balancer-subnets```,  as the number of EIPs assigned. For more reference you can check: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/guide/service/annotations/#eip-allocations

**Comment by taylorshaulis** [comment]
I had the same problem. Brand new EKS cluster with chart 1.5.3 and getting "unable to resolve at least one subnet".

I did not have the required tags for auto discovery as documented here https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/deploy/subnet_discovery/

After setting the required tags I deleted the pods to force a reload and the NLBs were created without issue.

**Comment by Vad1mo** [comment]
@oliviassss I am wondering why autodiscovery isn't working in that case, we have 2 public and 2 private subnets. All nodes are in the private subnets. IMHO it should work, why the need to add the subnets as well?

**Comment by Vad1mo** [comment]
We found out what caused the issue: It was a combination configuration change with the breaking change in the application v. 2.5 

It seems now to be mandatory to set:
`service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing`

**Comment by tommyasai** [comment]
I encountered the following error: `"error":"unable to resolve at least one subnet"`. This issue was present for some of my services even though I properly configured the subnet discovery as per the official guide: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/deploy/subnet_discovery/. Only one of my service and load balancer was successfully created by the way.

I have managed to work around the issue by explicitly defining the subnets using `service.beta.kubernetes.io/aws-load-balancer-subnets`. However, I find it odd that auto-discovery didn't work. Here is my current working configuration:
```
service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
service.beta.kubernetes.io/aws-load-balancer-name: "xxx"
service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-a, subnet-b,subnet-c
```
Thanks @Vad1mo for the hint.

If anyone could shed light on why the auto-discovery did not work, that would be very helpful.

- helm chart version: v1.5.5
- app version: v2.5.4

**Comment by johngmyers** [comment]
For those encountering this error message, I would suggest looking in CloudTrail for the `DescribeSubnets` call that LBC is issuing.

**Comment by ktibi** [comment]
Hello.

thanks @johngmyers , I found a cloudtrail log. Don't know why but I need to add the tag kubernetes.io/role/elb + kubernetes.io/role/internal-elb.

Maybe now, kubernetes.io/role/elb is for all.

**Comment by johngmyers** [comment]
@ktibi https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/subnet_discovery/

**Comment by ktibi** [comment]
@johngmyers Yes I read the doc but the internal tag no working.

When I check cloudtrail, I can see the request : 
```
"requestParameters": {
        "subnetSet": {},
        "filterSet": {
            "items": [
                {
                    "name": "vpc-id",
                    "valueSet": {
                        "items": [
                            {
                                "value": "vpc-05a203815139e1dc8"
                            }
                        ]
                    }
                },
                {
                    "name": "tag:kubernetes.io/role/elb",
                    "valueSet": {
                        "items": [
                            {},
                            {
                                "value": "1"
                            }
                        ]
                    }
                }
            ]
        }
    },
```
But the ingress definition is : 
```
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: >-
      arn:aws:acm:eu-west-1:1XXXXXXXXX:certificate/XXXXXXXXXXXXXXXXXXXXXXXXXX
    alb.ingress.kubernetes.io/healthcheck-path: /service/rest/v1/status
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    external-dns.alpha.kubernetes.io/hostname: XXXXX.XXXXXX.com
    kubernetes.io/ingress.class: alb
    meta.helm.sh/release-name: XXXX
    meta.helm.sh/release-namespace: default
```
