### ISSUE TITLE
Conflicting SSL policies on ingresses in an ingress group should be a warning rather than an error

### ISSUE THREAD

**Issue by tomelliff** [kubernetes-sigs/aws-load-balancer-controller#3262]
**Describe the bug**
I'm unsure if this is a bug or an intentional design decision (and so wanting of a feature request to change the behaviour instead) but I thought I'd raise it as a bug because I have steps to reproduce the issue.

If two ingresses share the same ingress group and set conflicting SSL policies via the `alb.ingress.kubernetes.io/ssl-policy` annotation, the load balancer controller begins throwing errors and is unable to manage the ingress group (no new ingresses created, updated or even deleted) until the SSL policies are aligned across all of the ingresses.

**Steps to reproduce**
1. Setup a cluster with the ALB controller configured and without using the [`sslPolicy` ingress class parameter](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/guide/ingress/ingress_class/#specsslpolicy)
2. Apply the following manifests in order to set up a deployment and service
```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: load-balancer-controller-test
    name: load-balancer-controller-test
  name: load-balancer-controller-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer-controller-test
  labels:
    app.kubernetes.io/name: load-balancer-controller-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-controller-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-controller-test
    spec:
      containers:
      - name: http-echo-8080
        image: hashicorp/http-echo
        command: ["/http-echo", "-listen=:8080", "-text='hello on 8080'"]
        ports:
          - containerPort: 8080
            name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-controller-test
  name: load-balancer-controller-test
  namespace: load-balancer-controller-test
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: load-balancer-controller-test
```
3. Apply this ingress manifest to create an ALB with the default SSL policy of `ELBSecurityPolicy-2016-08`:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/group.name: load-balancer-controller-test
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-redirect: "443"
  labels:
    app.kubernetes.io/name: load-balancer-controller-test-a
  name: load-balancer-controller-test-a
  namespace: load-balancer-controller-test
spec:
  ingressClassName: alb
  rules:
  - host: load-balancer-controller-test-a.example.com # TODO: Replace this with a domain you control
    http:
      paths:
      - backend:
          service:
            name: load-balancer-controller-test
            port:
              number: 8080
        path: /
        pathType: Prefix

```
4. Apply this ingress manifest to add a target group to the ALB and set the SSL policy of `ELBSecurityPolicy-TLS13-1-2-Res-2021-06`:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/group.name: load-balancer-controller-test
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-Res-2021-06
  labels:
    app.kubernetes.io/name: load-balancer-controller-test-b
  name: load-balancer-controller-test-b
  namespace: load-balancer-controller-test
spec:
  ingressClassName: alb
  rules:
  - host: load-balancer-controller-test-b.example.com # TODO: Replace this with a domain you control
    http:
      paths:
      - backend:
          service:
            name: load-balancer-controller-test
            port:
              number: 8080
        path: /
        pathType: Prefix

```
5. Apply this ingress manifest with a different SSL policy set to see the AWS load balancer controller begin to throw errors and be stuck in a broken state and observe that the ingress is not created and a target group is not created:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/group.name: load-balancer-controller-test
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10
  labels:
    app.kubernetes.io/name: load-balancer-controller-test-a
  name: load-balancer-controller-test-c
  namespace: load-balancer-controller-test
spec:
  ingressClassName: alb
  rules:
  - host: load-balancer-controller-test-c.example.com # TODO: Replace this with a domain you control
    http:
      paths:
      - backend:
          service:
            name: load-balancer-controller-test
            port:
              number: 8080
        path: /
        pathType: Prefix

```
6. Apply this ingress manifest to see that other ingresses that match the SSL policy of the ALB are also not created:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/group.name: load-balancer-controller-test
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-Res-2021-06
  labels:
    app.kubernetes.io/name: load-balancer-controller-test-d
  name: load-balancer-controller-test-d
  namespace: load-balancer-controller-test
spec:
  ingressClassName: alb
  rules:
  - host: load-balancer-controller-test-d.example.com # TODO: Replace this with a domain you control
    http:
      paths:
      - backend:
          service:
            name: load-balancer-controller-test
            port:
              number: 8080
        path: /
        pathType: Prefix

```

You can also swap step 5 for patching the first ingress with `kubectl patch ingress -n load-balancer-controller-test load-balancer-controller-test-a --patch-file ingress-a-patch.yml` and this patch to observe the same behaviour when an ingress in the group is updated to a mismatched SSL policy:
```yaml
metadata:
  annotations:
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10
```

The logs thrown look like this:

```
{"level":"error","ts":"2023-06-28T13:10:16Z","msg":"Reconciler error","controller":"ingress","object":{"name":"load-balancer-controller-test"},"namespace":"","name":"load-balancer-controller-test","reconcileID":"571718e7-ddbd-4177-a9e8-05cdd4caa694","error":"failed to merge listenPort config for port: 443: conflicting sslPolicy, load-balancer-controller-test/load-balancer-controller-test-b: ELBSecurityPolicy-FS-1-2-Res-2020-10 | load-balancer-controller-test/load-balancer-controller-test-b: ELBSecurityPolicy-TLS13-1-2-Res-2021-06"}
```

Other updates also fail to apply to the ingresses in the ingress group such as this health check update applied with `kubectl patch ingress -n load-balancer-controller-test load-balancer-controller-test-b --patch-file ingress-b-patch.yml`:

```yaml
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /foo
```

If you either remove the ingress with the mismatched SSL policy, remove the SSL policy annotation from the ingress, or align them then the AWS load balancer controller will resume managing changes to these ingresses in the group.

Alternatively, if you set the `sslPolicy` ingress class parameter then the AWS load balancer controller will ignore the `alb.ingress.kubernetes.io/ssl-policy` annotation and just set all the load balancers of that ingress class to use the SSL policy defined there.

**Expected outcome**
I'd expect to see warnings in the logs so you can see that they're mismatched and the ALB controller can't merge these (although the current log line as shown above doesn't help you easily spot the issue because the same ingress name is used multiple times - that's covered in https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3125) but otherwise the ALB load balancer controller should continue to manage the ingress group as normal.

**Environment**

* AWS Load Balancer controller version v2.5.3 via the 1.5.4 Helm chart
* Kubernetes version 1.24
* Using EKS (yes/no), if so version? 1.24

**Additional Context**:
This isn't the worst thing in the world because we're now changing tack and introducing the SSL policy via the ingress class instead. However, it did cause us to spend a lot of time head scratching why ingresses weren't being created or updated after we updated some of the ingresses in an ingress group and raised support ticket 13031568301.

Right now, it's not particularly feasible to use the `alb.ingress.kubernetes.io/ssl-policy` annotation with ingress groups because you leave the ingresses in the group in an unmanaged state until you can roll out the changes to all of the ingresses in the group.
