### ISSUE TITLE
Overrideable default tags

### ISSUE THREAD

**Issue by sosheskaz** [kubernetes-sigs/aws-load-balancer-controller#3273]
**Is your feature request related to a problem?**
I would like the ability to set global, overrideable default tags for Ingresses. i.e., "by default it should have this tag, but the `Ingress` annotation may override that default setting.

**Describe the solution you'd like**
In order of preference:
1. Breaking change: make --default-tags controller flags lower priority than tags supplied via annotation, and replace the old functionality with `--global-tags`
2. Add a new `--overrideable-default-tags` controller flag which has the weakest priority in tag merging.
3. Add a default-tags field to ingress class which has weaker priority than the annotation in tag merging.

**Describe alternatives you've considered**
Mutating admission webhooks

**Comment by sosheskaz** [comment]
If I am understanding you correctly, then no that would not work for me. The behavior I want is "Set this tag to this value **only** if the ingress itself did not specify a replacement value". Let's say I have 3 Ingresses, `alpha` `bravo` `charlie`.

```yaml
---
kind: Ingress
metadata:
  name: alpha
  annotations:
    alb.ingress.kubernetes.io/tags: MyTag=alpha
---
kind: Ingress
metadata:
  name: bravo
  annotations:
    alb.ingress.kubernetes.io/tags: MyTag=bravo
---
kind: Ingress
metadata:
  name: charlie
  annotations: {}
```

My desired behavior is that all of them should have `MyTag: MyValue` by default, _unless_ they override it. So I would expect the tags for each resource, given these manifests, to be:

```yaml
alpha:
  MyTag: alpha
bravo:
  MyTag: bravo
charlie:
  MyTag: MyValue
```

If I set `--default-tags=MyTag=MyValue`, then the resulting tags would be:
```yaml
alpha:
  MyTag: MyValue
bravo:
  MyTag: MyValue
charlie:
  MyTag: MyValue
```
which is not what I want. The given solution may work if I ran a load balancer controller _for each ingress_, but maintaining that would be worse than the problem I am currently having.
