### ISSUE TITLE
Allow for custom certificates generated from cert manager to be used by the webook

### ISSUE THREAD

**Issue by jooh-lee** [kubernetes-sigs/aws-load-balancer-controller#3284]
**Is your feature request related to a problem?**
We have a Private CA and would like to use that as the trust anchor to secure all communication. With the current implementation, when enabling the cert-manager feature, the helm chart creates a hardcoded self signed certificate.

**Describe the solution you'd like**
Some way for us to turn off the self signed certificate creation and allow us to load in our certificates issued via our CA via cert-manager

**Describe alternatives you've considered**
None

**Comment by kishorj** [comment]
@jooh-lee, you can enable the cert-manager in helm values during installation/upgrade. If cert manager is enabled, helm does not create the self-signed certificate.

**Comment by jooh-lee** [comment]
```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "aws-load-balancer-controller.namePrefix" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "aws-load-balancer-controller.labels" . | indent 4 }}
spec:
  selfSigned: {}
 ```
 it creates that but we cant control the spec of the issuer or anything
