### ISSUE TITLE
Custom Header Listener Condition

### ISSUE THREAD

**Issue by kimberleyhallifax** [kubernetes-sigs/aws-load-balancer-controller#3307]
**Is your feature request related to a problem?**

This is a partial security issue. I've got AWS CloudFront setup in front of my AWS EKS ALB provisioned by a Helm chart. I use a number of these annotations but can't seem to find an annotation to add listener rule conditions to check custom headers on viewer requests. This is a well known and advised practice endorsed by AWS to restrict access to ALBs: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/restrict-access-to-load-balancer.html

An example of such a condition in `terraform` would be:

```
resource "aws_alb_listener_rule" "app" {
  listener_arn = aws_alb_listener.app.arn
  priority     = 1

  action {
    type             = "forward"
    target_group_arn = aws_alb_target_group.app.id
  }

  condition {
    http_header {
      http_header_name = "Secret-Header"
      values           = ["hs(gbk#8286#3ls&8"]
    }
  }
}
```

>Note: The secret value above is not in use.

**Describe the solution you'd like**

I'd like an annotation to generate listener conditions for custom headers.

**Describe alternatives you've considered**

As far as I know there isn't another solution for this in AWS. Origin Access Identities (OAIs) can be used for S3 origins, but this isn't available for ALB origins.

**Comment by kimberleyhallifax** [comment]
Hey can I please get a response on this?

**Comment by radiantstatic** [comment]
+1 on this - this seems like a well documented use case in AWS that I also am trying to find a solution for

**Comment by radiantstatic** [comment]
@kimberleyhallifax - it appears that this functionality may be possible via the condition and action annotations - I am doing some testing now:

- https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/ingress/annotations/#actions
- https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/ingress/annotations/#conditions

**Comment by radiantstatic** [comment]
@kimberleyhallifax - I went ahead and tested and found that the following worked. I essentially created duplicate path entry and had the rules pass through in order:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: ingress
  annotations:
    alb.ingress.kubernetes.io/actions.valid-request: >
      {"type":"forward","forwardConfig":{"targetGroups":[{"serviceName":"my-service-name","servicePort":"http","weight":100}],"targetGroupStickinessConfig":{"enabled":true,"durationSeconds":200}}}
    alb.ingress.kubernetes.io/conditions.valid-request: >
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "X-Cloudfront-Header", "values":["MY-CLOUDFRONT-SECRET-HEADER"]}}]
    alb.ingress.kubernetes.io/actions.response-401: >
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"application/json","statusCode":"401","messageBody":"Unauthorized. You are not permitted to view this resource."}}
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: valid-request
                port:
                  name: use-annotation
          - path: /
            pathType: Prefix
            backend:
              service:
                name: response-401
                port:
                  name: use-annotation
```
