### ISSUE TITLE
Target does not registered with NLB controlled by LBC with different clusterName between kubernetes

### ISSUE THREAD

**Issue by DingGGu** [kubernetes-sigs/aws-load-balancer-controller#3319]
**Describe the bug**
A concise description of what the bug is.

Currently, My cluster has a different name from the Kubernetes cluster and the LBC `--clusterName` value.

I know this is abnormal configurations, but If I change LBC's clusterName, LBC will try replace all ALB and NLB.
As you know, replacing ALB and NLB can impact end-users DNS TTL.
I don't want the LB deployed to the end-users to be recreated.

One things, ALB does not matter difference of k8s' clusterName and LBC's args `--clusterName`.
However, NLB does not register in target-group.

When I create NLB with `target-type: instance`, Error logs appeared in LBC.
```
expect exactly one securityGroup tagged with kubernetes.io/cluster/$LBC_CLUSTER_NAME for eni eni-xxx, got: [] (clusterName: $LBC_CLUSTER_NAME)
```
None of the instances are registered to the target group.

If I set service annotation with `service.beta.kubernetes.io/aws-load-balancer-target-node-labels`, than logs just appear Successfully Build Model. However, None of the instances are registered to the target group too.

**Steps to reproduce**

```
apiVersion: v1
kind: Service
metadata:
  name: 
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-target-node-labels: 'some=node-label'
```

Set difference kubernetes' cluster name and LBC's `--clusterName`

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version
2.5.3
* Kubernetes version
1.24.16
* Using EKS (yes/no), if so version?
no

**Additional Context**:

Since I had to restore the service immediately, I removed the services-related resources from mutatingwebhookconfiguration so that the kubernetes in-tree controller can control the service again.

I wonder what criteria the service is in-tree or LBC is in charge of nlb.
