### ISSUE TITLE
Tags list to allow comma with optional space separated values

### ISSUE THREAD

**Issue by NickLarsenNZ** [kubernetes-sigs/aws-load-balancer-controller#3336]
**Is your feature request related to a problem?**

I have a number of tags to apply to the managed resources, and doing all on a single line becomes rather unreadable, eg:

```yml
metadata:
  annotations:
    alb.ingress.kubernetes.io/tags: example.com/cluster=cluster1,example.com/environment=nonprod,example.com/variant=variant1,example.com/tenant=customer1,example.com/otherlabel=primary
```

So I opted for YAML multiline string with newline chomping, like so:

```yml
metadata:
  annotations:
    alb.ingress.kubernetes.io/tags: >-
      example.com/cluster=cluster1,
      example.com/environment=nonprod,
      example.com/variant=variant1,
      example.com/tenant=customer1,
      example.com/otherlabel=primary
```

However, that renders to a single line but with newlines replaced with spaces:

```yml
metadata:
  annotations:
    alb.ingress.kubernetes.io/tags: example.com/cluster=cluster1, example.com/environment=nonprod, example.com/variant=variant1, example.com/tenant=customer1, example.com/otherlabel=primary
```

The code which splits the tags by commas is called here:

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/35126b27da1a41f2e7a67713a50c6997375a3b4a/pkg/annotations/parser.go#L130C34-L136

**Describe the solution you'd like**

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/35126b27da1a41f2e7a67713a50c6997375a3b4a/pkg/annotations/parser.go#L185-L196

Modify the `splitCommaSeparatedString` (possibly rename it to make it clear) to remove any spaces after commas.

**Describe alternatives you've considered**

None
