### ISSUE TITLE
Is it possible to define different healthcheck protocol for a Service exposing two or more NodePorts ?

### ISSUE THREAD

**Issue by hajdukda** [kubernetes-sigs/aws-load-balancer-controller#3346]
Let's say we have a Service:
```
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  selector:
    some: selector
```

It will create two target groups -> one for port 443 and one for port 80, how to set a different healthcheck for them ?
