### ISSUE TITLE
Deployment of TargetGroupBinding fails with InvalidParameterValue: vpc-id

### ISSUE THREAD

**Issue by phmcder** [kubernetes-sigs/aws-load-balancer-controller#3352]
I have an existing Application Load balancer, Target Group and EKS cluster. When I try to apply a TargetGroupBinding using kubectl I get the following error

'Failed cleanup due to InvalidParameterValue: vpc-id status code: 400'

I am at a loss on how to investigate this further.

We have a similar cluster were we have used ingress attributes to declare the target group configuration and that seems to work fine.

**Environment**

* AWS Load Balancer controller version: 2.6.0
* Kubernetes version: 1.2.7
* Using EKS (yes/no), if so version? eks.4

We are running the eks on a private vpc using private vpc links to access service such as "elasticloadbalancing.e-west-2.amazonaws.com"

**Comment by oliviassss** [comment]
@phmcder, hi, would you be able to share more info like how you apply the TGB and the manifest?

**Comment by phmcder** [comment]
Thanks for getting back to me @oliviassss 

Here is my configuration.

This is the yaml for my EKS deployed service (hashicorp vault is the service I am trying to access but get the same with all my other services)
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: vault
    meta.helm.sh/release-namespace: vault
  creationTimestamp: "2023-08-23T17:31:14Z"
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.25.0
  name: vault
  namespace: vault
  resourceVersion: "844052"
  uid: 48b77b76-f717-4344-b600-14d225e5b656
spec:
  clusterIP: XXX.XXX.XXX.XXX
  clusterIPs:
  - XXX.XXX.XXX.XXX
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 8200
    protocol: TCP
    targetPort: 8200
  - name: https-internal
    port: 8201
    protocol: TCP
    targetPort: 8201
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
    component: server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

This is the AWS TargetGroup that I had created before deploying the EKS cluster
```json
{
    "TargetGroups": [
        {
            "TargetGroupArn": "arn:aws:elasticloadbalancing:eu-west-2:XXXXXXXXXXXX:targetgroup/vault/28220f6e1c435ace",
            "TargetGroupName": "vault",
            "Protocol": "HTTPS",
            "Port": 8200,
            "VpcId": "vpc-0907f84c3869fb5c8",
            "HealthCheckProtocol": "HTTPS",
            "HealthCheckPort": "traffic-port",
            "HealthCheckEnabled": true,
            "HealthCheckIntervalSeconds": 30,
            "HealthCheckTimeoutSeconds": 5,
            "HealthyThresholdCount": 3,
            "UnhealthyThresholdCount": 3,
            "HealthCheckPath": "/v1/sys/init",
            "Matcher": {
                "HttpCode": "200,401"
            },
            "LoadBalancerArns": [
                "arn:aws:elasticloadbalancing:eu-west-2:XXXXXXXXXXXX:loadbalancer/app/eks-cluster/32ecf168d212643f"
            ],
            "TargetType": "ip",
            "ProtocolVersion": "HTTP1",
            "IpAddressType": "ipv4"
        }
    ]
}
```

And this is the targetgroup binding I am using to link the two
```yaml
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  creationTimestamp: "2023-08-24T16:11:48Z"
  finalizers:
  - elbv2.k8s.aws/resources
  generation: 1
  name: vault
  namespace: vault
  resourceVersion: "1284985"
  uid: f9576495-b923-45fe-8910-dbf144978867
spec:
  ipAddressType: ipv4
  serviceRef:
    name: vault
    port: 8200
  targetGroupARN: arn:aws:elasticloadbalancing:eu-west-2:XXXXXXXXXXXX:targetgroup/vault/28220f6e1c435ace
  targetType: ip
```
And this is the error that prints at regular internals from the ALB controller
```json
{
    "level": "error",
    "ts": "2023-08-25T12:05:11Z",
    "msg": "Reconciler error",
    "controller": "targetGroupBinding",
    "controllerGroup": "elbv2.k8s.aws",
    "controllerKind": "TargetGroupBinding",
    "TargetGroupBinding": {
        "name": "mongodb",
        "namespace": "hyperion-mongodb"
    }
    "namespace": "hyperion-mongodb",
    "name": "mongodb",
    "reconcileID": "6b7b80da-c92a-42cc-b693-977f37db136b",
    "error": "InvalidParameterValue: vpc-id\n\tstatus code: 400, request id: 5ab6a474-5b36-4586-9949-91e63b1ab289"
}
```

Let me know if you need anything else

**Comment by phmcder** [comment]
I'm still struggling with this? Anyone have any ideas why I'm getting the vpc-id InvalidParameterValue error?

**Comment by M00nF1sh** [comment]
@phmcder 
Did you use the same vpc for your cluster & your targetGroup?
Did you override the `aws-vpc-id` controller flag in the controller's deployment YAML? (by default it's auto-inferred from ec2 metadata, but if you specified a wrong value above error can occur)

The logs for this case seems didn't provide enough information, which is something we should improve. 
To help us debug, would you help query your cloudtrail logs looking for the request with id"e478db1-1260-4160-81cf-13d630526b3e" to see which call the controller is trying to make

**Comment by phmcder** [comment]
Thanks @M00nF1sh 
Turns out the issue was down to a typeo. After looking at the AWS logs we found the error was being raised during the call to describe DecsribeSecurityGroups. Below is a summary of the log entry
```yaml
{
    "eventVersion": "1.08",
    "eventTime": "2023-08-31T07:22:18Z",
    "eventSource": "ec2.amazonaws.com",
    "eventName": "DescribeSecurityGroups",
    "awsRegion": "eu-west-2",
    "userAgent": "elbv2.k8s.aws/v2.6.0 aws-sdk-go/1.44.294 (go1.20.5; linux; amd64)",
    "errorCode": "Client.InvalidParameterValue",
    "errorMessage": "vpc-id",
    "requestParameters": {
        "securityGroupSet": {},
        "securityGroupIdSet": {},
        "filterSet": {
            "items": [
                {
                    "name": "tag:kubernetes.io/cluster/eks-cluster",
                    "valueSet": {
                        "items": [
                            {
                                "value": "owned"
                            },
                            {
                                "value": "shared"
                            }
                        ]
                    }
                },
                {
                    "name": "vpc-id",
                    "valueSet": {
                        "items": [
                            {
                                "value": "arn:aws:ec2:eu-west-2:XXXXXXXXXXX:vpc/vpc-0907f84c3869fb5c8"
                            }
                        ]
                    }
                }
            ]
        }
    },
    "responseElements": null,
    "eventType": "AwsApiCall",
    "managementEvent": true
}
```

The VPC ID in the request should have been just the vpc id vpc-0907f84c3869fb5c8  and not the ARN of the VPC. Back tracking from there I found my terraform code was setting the VPC-ID to the ARN via Helm value `vpcId` in the ALB Controller helm chart. Changing this from the ARN of the VPC to the VPC-ID fixed my problem.

Thank for the help everyone and if anyone wants to add code to raise an error message for badly formatted vpcId values, be my guest ;0)
