### ISSUE TITLE
support for AWS Network Load Balancer attaching sec groups in upcoming version like 2.7 

### ISSUE THREAD

**Issue by emad-ramlawi** [kubernetes-sigs/aws-load-balancer-controller#3354]
**Is your feature request related to a problem?**
Will version 2.7 of 

https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/service/nlb/#security-group
support the recent change of 

Network Load Balancer now supports security groups:

https://aws.amazon.com/about-aws/whats-new/2023/08/network-load-balancer-supports-security-groups/#:~:text=Network%20Load%20Balancers%20(NLB)%20now,centrally%20enforce%20access%20control%20policies

**Describe the solution you'd like**
```
nlb.ingress.kubernetes.io/security-groups: sg-xxxx, nameOfSg1, nameOfSg2
```
just like we have one for
```
alb.ingress.kubernetes.io/security-groups: sg-xxxx, nameOfSg1, nameOfSg2
```

**Describe alternatives you've considered**
NA

**Comment by emad-ramlawi** [comment]
btw it seems this is supported with newest release but can we get the correct way to implement

**Comment by emad-ramlawi** [comment]
hi again,

so i used 2 options jus to test, i tried each separately too 

    **service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: sg-065410bec37ed3be8**
    **service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-065410bec37ed3be8**

then i deleted the ingress/LB from aws and re-created and everytime I create it no Sec group is registered 

![image](https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/42615994/f44736fa-a60f-4a4b-8bd4-bc297f21133e)

Do note im using k8s 1.24


```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kots.io/app-slug: dash-enterprise
    networking.gke.io/load-balancer-type: ""
    **service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: sg-065410bec37ed3be8**
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    **service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-065410bec37ed3be8**
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.7.0
    helm.sh/chart: ingress-nginx-4.6.0
    kots.io/app-slug: dash-enterprise
    kots.io/backup: velero
  name: ingress-nginx-controller
  namespace: plotly-system
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: 22-tcp
    port: 22
    protocol: TCP
    targetPort: 22-tcp
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  type: LoadBalancer
```
