### ISSUE TITLE
Ability to use Security Group Name and/or tags in alb.ingress.kubernetes.io/security-groups annotation

### ISSUE THREAD

**Issue by Aleksei-Poliakov** [kubernetes-sigs/aws-load-balancer-controller#3359]
**Is your feature request related to a problem?**
Currently one has to have an existing security group in order to define an ALB using aws-load-balancer-controller. It's not a problem if you create a SG using something like terraform upfront, but makes it impossible to manage everything in kubernetes, for example using AWS Controller for Kubernetes, when **both** security group **and** application load balancer are created from kubernetes.
This is very similar to this request https://github.com/aws/amazon-vpc-resource-controller-k8s/issues/20#issuecomment-1260705399 where CustomNetworking/SecurityGroupsForPods definition should integrate with ACK in a first class way.

**Describe the solution you'd like**
Ideally one should be able to specify security group name or other selector, something like:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
#  alb.ingress.kubernetes.io/security-groups: sg-0a1b22ee11d38943f # this already exists
    alb.ingress.kubernetes.io/security-groups-names: my-cool-app-alb-sg
````
