### ISSUE TITLE
Setting the idle_timeout.timeout_seconds parameter does not work

### ISSUE THREAD

**Issue by mgledi** [kubernetes-sigs/aws-load-balancer-controller#3363]
**Describe the bug**
Setting the idle_timeout.timeout_seconds parameter does not work. 

**Steps to reproduce**
We tried to update an existing alb first. 
We then tried to recreate an alb with the following attributes. 
```
...
ingressClassParams:
  create: true
  name: alb
  spec:
    group:
      name: common
    ipAddressType: dualstack
    loadBalancerAttributes:
    - key: idle_timeout.timeout_seconds
      value: "3600"
    scheme: internet-facing
    tags:
    - key: Environment
      value: ue2
    - key: Name
      value: dtmr-plat-ue2-dev
    - key: Namespace
      value: dtmr
    - key: Stage
      value: dev
    - key: Tenant
      value: plat
...
```

**Expected outcome**
The idle_timeout in the attributes tab when configuring EKS should contain 120s. 

**Environment**

* AWS Load Balancer controller version: 1.5.5
* Kubernetes version: 1.25
* Using EKS (yes/no), if so version? yes

**Additional Context**:
We are using cloudposse's component to manage EKS: 1.25
