### ISSUE TITLE
ALS CLB blocks hostPort usage of later installed Pods

### ISSUE THREAD

**Issue by david-freistrom** [kubernetes-sigs/aws-load-balancer-controller#3385]
**Describe the bug**
AWS Loadbalancer Controller blocks other deployments to use hostPort. Pods with hostNetwork: true and a hostPort set to 10261 or 10271 or any other in between for webhooks cannot be used. If I delete AWS LBC the other Pods becaomes ready.

**Steps to reproduce**

Install Helm of AWS LBC with the follworing values:
```yaml
serviceAccount:
  create: true
  name: aws-lbc
  annotations:
    "eks.amazonaws.com/role-arn" : "arn:aws:iam::12345:role/aws-lbs-irsa"
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  allowPrivilegeEscalation: false
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
clusterName: test
region: eu-central-1
vpcId: vpc-123456778
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
serviceMonitor:
  enabled: true
  namespace: monitoring
enableServiceMutatorWebhook: false
ingressClassConfig:
  default: true
disableRestrictedSecurityGroupRules: true
```

Then install ExternalSecrets Operator wity the values:
```yaml
concurrent: 5
serviceAccount:
  name: external-secrets
  create: true
  annotations: 
    "eks.amazonaws.com/role-arn" : "arn:aws:iam::12345:role/external-secrets-irsa"
resources:
  requests:
    cpu: 128m
    memory: 32Mi
  limits:
    cpu: 512m
    memory: 128Mi
serviceMonitor:
  enabled: true
webhook:
  **hostNetwork: true**
  **port: 10261**
  resources:
    requests:
      cpu: 128m
      memory: 32Mi
    limits:
      cpu: 512m
      memory: 128Mi
certController:
  resources:
    requests:
      cpu: 128m
      memory: 32Mi
    limits:
      cpu: 512m
      memory: 128Mi
``` 

**Expected outcome**

ExternalSecrets Webhook Pod becmes ready

**Environment**

EKS 1.27 
OS: linux (amd64)
OS Image: Bottlerocket OS 1.14.3 (aws-k8s-1.27)
Kernel version: 5.15.117
Container runtime: containerd://1.6.20+bottlerocket
Kubelet version: v1.27.3-eks-6f07bbc

* AWS Load Balancer controller version

Helm version: "1.6.0"
Controller: v2.6

* Kubernetes version
YES
EKS 1.27 

**Additional Context**:
When I install ExternalSecrets first and after AWS LBC installation restart the webhook pod from external-secrets it's all ready.
