### ISSUE TITLE
listen-ports annotation is mandatory for IngressGroup to work

### ISSUE THREAD

**Issue by AzaxSyndrom** [kubernetes-sigs/aws-load-balancer-controller#3395]
Hello ! 

**Describe the bug**
When creating 2 ingress inside a ingressGroup. The first one has all the Exclusive and some Merge annotation to create the ALB and the explicit IngressGroup. 
The second ingress contains only group.name & group.order annotation.

```
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/group.name: "{{ .Release.Namespace }}-external-ingress-group"
    alb.ingress.kubernetes.io/group.order: '2'
```
The load balancer controller do not create nor TargetGroup nor the rule into the ALB.  Nothing is shown into the log. It just output the model as info log.

if you add the listen-ports annotation (already configured in the First Ingress)

`alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'`

The controller create the TG and the rule. 

**Steps to reproduce**

**Expected outcome**
Listen-ports should not be mandatory or the controller should logs an Error that there is no listen-ports specified for the ingress rules. 

**Environment**

* AWS Load Balancer controller version : 2.6.1
* Kubernetes version : 1.27
* Using EKS (yes/no), if so version? no

**Additional Context**:

**Comment by oliviassss** [comment]
@AzaxSyndrom, hi, `alb.ingress.kubernetes.io/listen-ports` is merged across ingress group, and we allow users to define different ports per ingress. Most annotations will only apply to the path in that single ingress. Would you be able to share the spec of your second ingress?

**Comment by AzaxSyndrom** [comment]
Hi, 

**main ingress :** 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Namespace }}-{{ .Values.env }}-external"
  namespace: default
  labels:
    app: "{{ .Release.Namespace }}-{{ .Values.env }}-external"
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.alb.acmArn }}"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/load-balancer-name: "alb-{{ .Release.Namespace }}-{{ .Values.env }}-external"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01
    alb.ingress.kubernetes.io/tags: >-
      ingress.k8s.aws/resource=LoadBalancer,
      elbv2.k8s.aws/cluster="{{ .Values.clusterName }}"
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/group.name: "{{ .Release.Namespace }}-{{ .Values.env }}-external-ingress-group"
spec:
  ingressClassName: alb
```

**Second ingress for group :** 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Namespace }}-{{ .Chart.Name }}-{{ .Values.env }}-external"
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /uaa/login
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/group.name: "{{ .Release.Namespace }}-{{ .Values.env }}-external-ingress-group"
    alb.ingress.kubernetes.io/group.order: '20'
    external-dns.alpha.kubernetes.io/hostname: "oauth.{{ ternary "dev.aws" "paws" ( eq .Values.env "dev" ) }}.intelcia.com"
    external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
spec:
  ingressClassName: alb
```
  
 like this it works. 
 But if i remove the listen-ports from the second ingress, nothing is created into the load balancer. Since that annotation is merge it should use that value by default since it's in the main ingress.
