### ISSUE TITLE
Supports other certificates for HTTPS connection?

### ISSUE THREAD

**Issue by jslouisyou** [kubernetes-sigs/aws-load-balancer-controller#3401]
**Is your feature request related to a problem?**
A description of what the problem is. For example: I'm frustrated when [...]

Hello, forks.
I'm trying to expose L7 LoadBalancer - ALB by using aws-load-balancer-controller with supporting HTTPS connection.
When I try to create ALB with registered domain (eg. `*.example.com`) in Route53 and registered certificates in AWS ACM, ALB works well.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: whoami
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:xxxxx:certificate/xxxxxxx
    external-dns.alpha.kubernetes.io/hostname: test.example.com
spec:
  ingressClassName: alb
  rules:
   - host: test.example.com
     http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami
            port:
              number: 443
```

But when I try to expose ALB like below without any explicit certificates annotation (of course this domain and certificate are not registered in AWS Route53 and ACM) then Ingress can't be created even if secret exists in namespace too.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: whoami
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
spec:
  ingressClassName: alb
  tls:
  - hosts:
    - test.example.com
    secretName: test-example-tls
  rules:
  - host: test.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami
            port:
              number: 443

```
```
Events:
  Type     Reason            Age                   From     Message
  ----     ------            ----                  ----     -------
  Warning  FailedBuildModel  7m38s (x18 over 18m)  ingress  Failed build model due to ingress: default/whoami: no certificate found for host: test.example.com
```

In this case, Does aws-load-balancer-controller supports other certificates besides AWS ACM?

**Describe the solution you'd like**
A description of what you want to happen.

Successfully creates ALB with other certificates explicitly added in `spec.tls` field.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.
