### ISSUE TITLE
Pod readiness gate does not work on aws load balancer controller 2.6.1

### ISSUE THREAD

**Issue by kahirokunn** [kubernetes-sigs/aws-load-balancer-controller#3403]
**Describe the bug**
Pod readiness gate does not work on aws load balancer controller 2.6.1

I created a Pod and then created Ingress, but I have deleted the Pod many times since then, but it does not have readinessGates.

```
k get po -A -oyaml | grep -A5 readinessGates
```

empty response.

I have searched the aws load balancer controller issue but could not find the cause. 😢 
How can I get it to function properly?
Thx.

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version
* Kubernetes version
* Using EKS (yes/no), if so version?

**Additional Context**:

The following is a little masking, but it is information about the environment.

flags

```
- --cluster-name=test
- --ingress-class=alb
- --aws-region=ap-northeast-1
- --enable-pod-readiness-gate-inject=true
- --metrics-bind-addr=0.0.0.0:31080
- --log-level=debug
- --webhook-bind-port=xxxxx
```

Mutating webhooks will be delivered.

log

```json
{
  "level": "debug",
  "ts": "2023-09-27T08:24:40Z",
  "logger": "controller-runtime.webhook.webhooks",
  "msg": "received request",
  "webhook": "/mutate-v1-pod",
  "UID": "44d6549a-74da-49d8-87eb-687cd7a5ca3c",
  "kind": "/v1, Kind=Pod",
  "resource": {
    "group": "",
    "version": "v1",
    "resource": "pods"
  }
}
```

yamls

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: aws-load-balancer-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/version: v2.6.1
    argocd.argoproj.io/instance: aws-load-balancer-controller
    helm.sh/chart: aws-load-balancer-controller-1.6.1
  name: aws-load-balancer-webhook
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: XXXXXXX
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /mutate-v1-pod
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mpod.elbv2.k8s.aws
  namespaceSelector:
    matchExpressions:
    - key: elbv2.k8s.aws/pod-readiness-gate-inject
      operator: In
      values:
      - enabled
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - aws-load-balancer-controller
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: XXXXXXX
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /mutate-v1-service
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mservice.elbv2.k8s.aws
  namespaceSelector: {}
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - aws-load-balancer-controller
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - services
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: XXXXXXX
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mtargetgroupbinding.elbv2.k8s.aws
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - elbv2.k8s.aws
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - targetgroupbindings
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
```

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-port: "xxxxx"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=hogehoge,access_logs.s3.prefix=hogehoge-test1-default-alb-access-log,idle_timeout.timeout_seconds=3600
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/subnets: subnet-xxx,subnet-yyy,subnet-zzz
    alb.ingress.kubernetes.io/target-type: instance
  finalizers:
  - ingress.k8s.aws/resources
  name: gw-000000000000
  namespace: test
spec:
  defaultBackend:
    service:
      name: gw-000000000000
      port:
        name: http
  ingressClassName: alb
  rules:
  - host: hoge.example.com
    http:
      paths:
      - backend:
          service:
            name: gw-000000000000-contour-envoy
            port:
              name: http
        path: /
        pathType: Prefix
  - host: fuga.example.com
    http:
      paths:
      - backend:
          service:
            name: gw-000000000000-contour-envoy
            port:
              name: http
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - hostname: xxxxx.ap-northeast-1.elb.amazonaws.com
```

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    elbv2.k8s.aws/pod-readiness-gate-inject: enabled
    kubernetes.io/metadata.name: test
  name: test
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.kubernetes.io/topology-mode: auto
  labels:
    app.kubernetes.io/component: default-backend
    app.kubernetes.io/instance: gw-000000000000
    app.kubernetes.io/name: gw-000000000000
    app.kubernetes.io/part-of: ingress
    app.kubernetes.io/version: x.x.x
  name: gw-000000000000
  namespace: test
spec:
  clusterIP: xxxxxx
  clusterIPs:
  - xxxxxx
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: yyyyy
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/component: default-backend
    app.kubernetes.io/instance: gw-000000000000
    app.kubernetes.io/name: gw-000000000000
    app.kubernetes.io/part-of: ingress
    app.kubernetes.io/version: x.x.x
  sessionAffinity: None
  type: NodePort
```

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.kubernetes.io/topology-mode: auto
  labels:
    app.kubernetes.io/component: envoy
    app.kubernetes.io/instance: gw-000000000000
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: contour
    app.kubernetes.io/version: 1.26.0
    argocd.argoproj.io/instance: gw-000000000000
    helm.sh/chart: contour-13.0.0
    networking.knative.dev/ingress-provider: contour
  name: gw-000000000000-contour-envoy
  namespace: test
spec:
  clusterIP: xxxxxx
  clusterIPs:
  - xxxxxx
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: yyyyy
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: yyyyy
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: envoy
    app.kubernetes.io/instance: gw-000000000000
    app.kubernetes.io/name: contour
  sessionAffinity: None
  type: NodePort
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.cilium.proxy-visibility: <Egress/53/UDP/DNS>
  labels:
    app.kubernetes.io/component: default-backend
    app.kubernetes.io/instance: gw-000000000000
    app.kubernetes.io/name: gw-000000000000
    app.kubernetes.io/part-of: ingress
    app.kubernetes.io/version: x.x.x
    pod-template-hash: 64488678d9
  name: gw-000000000000-64488678d9-drtgp
  namespace: test
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: gw-000000000000-64488678d9
    uid: 80ac6396-8553-4912-8617-e70cff3a2917
spec:
  containers:
  - image: nginx:1.25.1
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-m5wzw
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-xxxxxx.ap-northeast-1.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-m5wzw
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-09-27T08:33:26Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-09-27T08:33:28Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-09-27T08:33:28Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-09-27T08:33:26Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://5330b62bfb298dc6d0bdcc0cf49a0d1051f7082bf3bddeac9efdb01777d0f4de
    image: docker.io/library/nginx:1.25.1
    imageID: docker.io/library/nginx@sha256:67f9a4f10d147a6e04629340e6493c9703300ca23a2f7f3aa56fe615d75d31ca
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-09-27T08:33:27Z"
  hostIP: 10.0.30.13
  phase: Running
  podIP: 10.224.130.161
  podIPs:
  - ip: 10.224.130.161
  qosClass: Burstable
  startTime: "2023-09-27T08:33:26Z"
```
