### ISSUE TITLE
'service.beta.kubernetes.io/aws-load-balancer-ssl-ports' annotation doesn't seems to work as expected

### ISSUE THREAD

**Issue by yagelkt** [kubernetes-sigs/aws-load-balancer-controller#3414]
**Describe the bug**
I'm trying to create NLB with ssl certificate with port 443, for my apisix service.

This is the ArgoCd app for the Apisix:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loadbalancer-apisix
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: api-gw
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: apisix
    repoURL: https://charts.apiseven.com
    targetRevision: v2.1.0
    helm:
      releaseName: apisix
      values: |
        service:
          type: LoadBalancer
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tls 
            service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Environment=Prod
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-north-1:..........
```

This app creates NLB with ssl certificates, but it works on port 80.
When I added this annotation:
`
service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
`
It doesn't seems to do anything (still creates only port 80).

any idea why?

**Environment**

* AWS Load Balancer controller version
v2.6.0

* Kubernetes version
eks 1.27
