### ISSUE TITLE
Ingress doesnt reconcile even with NodeType service InvalidParameter: 1 validation error(s) found.\n- minimum field value of 1, CreateTargetGroupInput.Port.\n

### ISSUE THREAD

**Issue by kasvith** [kubernetes-sigs/aws-load-balancer-controller#3420]
**Describe the bug**
Ingress doesn't reconcile even service has a `NodeType` 

```
InvalidParameter: 1 validation error(s) found.\n- minimum field value of 1, CreateTargetGroupInput.Port.\n
```

**Steps to reproduce**
- Deploy a service with NodePort
- Try to expose it with Ingress

**Expected outcome**
- It should work

**Environment**

* AWS Load Balancer controller version: 2.6
* Kubernetes version: 1.28
* Using EKS (yes/no), if so version?: 1.28

**Additional Context**:

My Ingress is for argocd

```yml
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP2 #This tells AWS to send traffic from the ALB using HTTP2. Can use GRPC as well if you want to leverage GRPC specific features
  labels:
    app: argogrpc
  name: argogrpc
  namespace: argocd
spec:
  ports:
    - name: "443"
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    # Use this annotation (which must match a service name) to route traffic to HTTP2 backends.
    alb.ingress.kubernetes.io/conditions.argogrpc: |
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "Content-Type", "values":["application/grpc"]}}]
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: apps
    alb.ingress.kubernetes.io/certificate-arn: <<redacted>>
    alb.ingress.kubernetes.io/target-type: instance
  name: argocd
  namespace: argocd
spec:
  ingressClassName: alb
  rules:
    - host: argocd.example.com
      http:
        paths:
          - path: /
            backend:
              service:
                name: argogrpc
                port:
                  number: 443
            pathType: Prefix
          - path: /
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
            pathType: Prefix
  tls:
    - hosts:
        - argocd.example.com
```

Error
```json
{
  "level": "error",
  "ts": "2023-10-05T18:10:29Z",
  "msg": "Reconciler error",
  "controller": "ingress",
  "object": {
    "name": "apps"
  },
  "namespace": "",
  "name": "apps",
  "reconcileID": "a78585cd-17d3-402f-8391-4f85ca06596f",
  "error": "InvalidParameter: 1 validation error(s) found.\n- minimum field value of 1, CreateTargetGroupInput.Port.\n"
}
```

Logs

```json
{
  "id": "apps",
  "resources": {
    "AWS::EC2::SecurityGroup": {
      "ManagedLBSecurityGroup": {
        "spec": {
          "groupName": "k8s-apps-53be320dfa",
          "description": "[k8s] Managed SecurityGroup for LoadBalancer",
          "ingress": [
            {
              "ipProtocol": "tcp",
              "fromPort": 443,
              "toPort": 443,
              "ipRanges": [
                {
                  "cidrIP": "0.0.0.0/0"
                }
              ]
            }
          ]
        }
      }
    },
    "AWS::ElasticLoadBalancingV2::Listener": {
      "443": {
        "spec": {
          "loadBalancerARN": {
            "$ref": "#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN"
          },
          "port": 443,
          "protocol": "HTTPS",
          "defaultActions": [
            {
              "type": "fixed-response",
              "fixedResponseConfig": {
                "contentType": "text/plain",
                "statusCode": "404"
              }
            }
          ],
          "certificates": [
            {
              "certificateARN": "<<redacted>>"
            }
          ],
          "sslPolicy": "ELBSecurityPolicy-2016-08"
        }
      }
    },
    "AWS::ElasticLoadBalancingV2::ListenerRule": {
      "443:1": {
        "spec": {
          "listenerARN": {
            "$ref": "#/resources/AWS::ElasticLoadBalancingV2::Listener/443/status/listenerARN"
          },
          "priority": 1,
          "actions": [
            {
              "type": "forward",
              "forwardConfig": {
                "targetGroups": [
                  {
                    "targetGroupARN": {
                      "$ref": "#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/argocd/argocd-argogrpc:443/status/targetGroupARN"
                    }
                  }
                ]
              }
            }
          ],
          "conditions": [
            {
              "field": "http-header",
              "httpHeaderConfig": {
                "httpHeaderName": "Content-Type",
                "values": [
                  "application/grpc"
                ]
              }
            },
            {
              "field": "host-header",
              "hostHeaderConfig": {
                "values": [
                  "argocd.example.com"
                ]
              }
            },
            {
              "field": "path-pattern",
              "pathPatternConfig": {
                "values": [
                  "/*"
                ]
              }
            }
          ]
        }
      },
      "443:2": {
        "spec": {
          "listenerARN": {
            "$ref": "#/resources/AWS::ElasticLoadBalancingV2::Listener/443/status/listenerARN"
          },
          "priority": 2,
          "actions": [
            {
              "type": "forward",
              "forwardConfig": {
                "targetGroups": [
                  {
                    "targetGroupARN": {
                      "$ref": "#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/argocd/argocd-argocd-server:443/status/targetGroupARN"
                    }
                  }
                ]
              }
            }
          ],
          "conditions": [
            {
              "field": "host-header",
              "hostHeaderConfig": {
                "values": [
                  "argocd.example.com"
                ]
              }
            },
            {
              "field": "path-pattern",
              "pathPatternConfig": {
                "values": [
                  "/*"
                ]
              }
            }
          ]
        }
      }
    },
    "AWS::ElasticLoadBalancingV2::LoadBalancer": {
      "LoadBalancer": {
        "spec": {
          "name": "k8s-apps-70e984890c",
          "type": "application",
          "scheme": "internet-facing",
          "ipAddressType": "ipv4",
          "subnetMapping": [
            {
              "subnetID": "subnet-033a262bc3f7df933"
            },
            {
              "subnetID": "subnet-068b5178b17c1a6d6"
            }
          ],
          "securityGroups": [
            {
              "$ref": "#/resources/AWS::EC2::SecurityGroup/ManagedLBSecurityGroup/status/groupID"
            },
            "sg-06f80ede99f54cc68"
          ]
        }
      }
    },
    "AWS::ElasticLoadBalancingV2::TargetGroup": {
      "argocd/argocd-argocd-server:443": {
        "spec": {
          "name": "k8s-argocd-argocdse-8bf850292e",
          "targetType": "instance",
          "port": 0,
          "protocol": "HTTPS",
          "protocolVersion": "HTTP1",
          "ipAddressType": "ipv4",
          "healthCheckConfig": {
            "port": "traffic-port",
            "protocol": "HTTPS",
            "path": "/",
            "matcher": {
              "httpCode": "200"
            },
            "intervalSeconds": 15,
            "timeoutSeconds": 5,
            "healthyThresholdCount": 2,
            "unhealthyThresholdCount": 2
          }
        }
      },
      "argocd/argocd-argogrpc:443": {
        "spec": {
          "name": "k8s-argocd-argogrpc-a536bf3a0d",
          "targetType": "instance",
          "port": 32010,
          "protocol": "HTTPS",
          "protocolVersion": "HTTP2",
          "ipAddressType": "ipv4",
          "healthCheckConfig": {
            "port": "traffic-port",
            "protocol": "HTTPS",
            "path": "/",
            "matcher": {
              "httpCode": "200"
            },
            "intervalSeconds": 15,
            "timeoutSeconds": 5,
            "healthyThresholdCount": 2,
            "unhealthyThresholdCount": 2
          }
        }
      }
    },
    "K8S::ElasticLoadBalancingV2::TargetGroupBinding": {
      "argocd/argocd-argocd-server:443": {
        "spec": {
          "template": {
            "metadata": {
              "name": "k8s-argocd-argocdse-8bf850292e",
              "namespace": "argocd",
              "creationTimestamp": null
            },
            "spec": {
              "targetGroupARN": {
                "$ref": "#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/argocd/argocd-argocd-server:443/status/targetGroupARN"
              },
              "targetType": "instance",
              "serviceRef": {
                "name": "argocd-server",
                "port": 443
              },
              "networking": {
                "ingress": [
                  {
                    "from": [
                      {
                        "securityGroup": {
                          "groupID": "sg-06f80ede99f54cc68"
                        }
                      }
                    ],
                    "ports": [
                      {
                        "protocol": "TCP",
                        "port": 0
                      }
                    ]
                  }
                ]
              },
              "ipAddressType": "ipv4"
            }
          }
        }
      },
      "argocd/argocd-argogrpc:443": {
        "spec": {
          "template": {
            "metadata": {
              "name": "k8s-argocd-argogrpc-a536bf3a0d",
              "namespace": "argocd",
              "creationTimestamp": null
            },
            "spec": {
              "targetGroupARN": {
                "$ref": "#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/argocd/argocd-argogrpc:443/status/targetGroupARN"
              },
              "targetType": "instance",
              "serviceRef": {
                "name": "argogrpc",
                "port": 443
              },
              "networking": {
                "ingress": [
                  {
                    "from": [
                      {
                        "securityGroup": {
                          "groupID": "sg-06f80ede99f54cc68"
                        }
                      }
                    ],
                    "ports": [
                      {
                        "protocol": "TCP",
                        "port": 32010
                      }
                    ]
                  }
                ]
              },
              "ipAddressType": "ipv4"
            }
          }
        }
      }
    }
  }
}
```
