### ISSUE TITLE
Multiple Ports  for same underlying service 

### ISSUE THREAD

**Issue by brickpattern** [kubernetes-sigs/aws-load-balancer-controller#3433]
Environment: EKS
Version of ALB used: latest

If the underlying service has more than one ports exposed, should I be mapping each port to a different path ?  Or how should O define. For eg. my-clusterip-service  has ports 7000, 7001, 9042, 9142 etc. 

My desired outcome is to map the ports  1:1 as-is to the underlying service. 

Q- can same path / be used for all ports
Q - Can i specify multiple ports and target ports  for a given path?

```
---
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      namespace: myns
      name: my-ingress
      annotations:
        alb.ingress.kubernetes.io/scheme: internal
        alb.ingress.kubernetes.io/target-type: ip
    spec:
      ingressClassName: alb
      rules:
        - http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: my-clusterip-service
                  port:
                    number: 9042
            - path: /cqlssl
              pathType: Prefix
              backend:
                service:
                  name: my-clusterip-service
                  port:
                    number: 9142    
```
