### ISSUE TITLE
The SSL Policy parameter in the ingressClassParams definition has no effect

### ISSUE THREAD

**Issue by zalejus** [kubernetes-sigs/aws-load-balancer-controller#3438]
**Describe the bug**
Maybe it's not a bug but more my question. I set up IngressClass and IngressClassParams to change SSL Policy for my load balancer to ELBSecurityPolicy-FS-1-2-Res-2020-10 but I still have the default one set (ELBSecurityPolicy-2016-08) in one cluster. I have two almost the same kubernetes clusters - the same versions and so on and so forth. In one of them such property changes Security Policy, and in the other it doesn't. What could be the reason for this behavior? How can I investigate this case deeper?

**Steps to reproduce**
My defonitions:
```
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: IngressClassParams
metadata:
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
  name: alb
spec:
  sslPolicy: "ELBSecurityPolicy-FS-1-2-Res-2020-10"

---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
  name: alb
spec:
  controller: ingress.k8s.aws/alb
  parameters:
    apiGroup: elbv2.k8s.aws
    kind: IngressClassParams
    name: alb
```
In kubernetes everything looks fine:
```
$ kubectl describe ingressclassparams alb
Name:         alb
Namespace:    
Labels:       app.kubernetes.io/name=aws-load-balancer-controller
              kustomize.toolkit.fluxcd.io/name=static-alb-controller
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  <none>
API Version:  elbv2.k8s.aws/v1beta1
Kind:         IngressClassParams
Metadata:
  Creation Timestamp:  2023-05-29T22:04:25Z
  Generation:          2
  Resource Version:    141781006
  UID:                 b54456f0-ae32-48d8-a000-09d3c47d96a8
Spec:
  Ssl Policy:  ELBSecurityPolicy-FS-1-2-Res-2020-10
Events:        <none>

$ kubectl describe ingressclass alb
Name:         alb
Labels:       app.kubernetes.io/name=aws-load-balancer-controller
              kustomize.toolkit.fluxcd.io/name=static-alb-controller
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  <none>
Controller:   ingress.k8s.aws/alb
Parameters:
  APIGroup:  elbv2.k8s.aws
  Kind:      IngressClassParams
  Name:      alb
Events:      <none>
```

**Expected outcome**
To my mind it should change like with ingress annotation.
(e.g. alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10
However, I think that this parameter should be part of global configuration so that I don't want to use annotation in some specific ingress to change this global behavior.

**Environment**

* AWS Load Balancer controller version v2.5.4
* Kubernetes version 1.28
* Using EKS (yes/no), if so version?

**Additional Context**:
