### ISSUE TITLE
Controller fails to finish applying status to Ingress objects when WAF checks fail

### ISSUE THREAD

**Issue by myoung34** [kubernetes-sigs/aws-load-balancer-controller#3445]
**Describe the bug**

When using the ALB controller with permissions for ec2:* and elasticloadbalancing:* IAM permissions It should create an ALB just fine

If you do not give it waf:* permissions the controller will happily create the ALB but will fail on 

* `shield:GetSubscriptionState`
* `wafv2:GetWebACLForResource`

and fail to update the Ingress object with the Address (required for external-dns)

The default values for `enableWaf` and `enableWafv2` are true which is not clear, not expected and causes the controller to fail to update the Ingress even though it can create the ALB.

**Steps to reproduce**

Using this kustomize:
```
  helmCharts:
  - name: aws-load-balancer-controller
    releaseName: aws-load-balancer-controller
    namespace: aws-load-balancer-controller
    #includeCRDs: true
    version: 1.6.1
    repo: https://aws.github.io/eks-charts
    valuesInline:
      clusterName: teleport-ue1
      replicaCount: 1
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::11111111111:role/foo-alb_controller
```
where `foo-alb_controller` IAM has permissions:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "ec2:*",
                "elasticloadbalancing:*"
            ],
            "Resource": [
              "*"
            ]
        }
    ]
}
```

Ingress:

```
$ kubectl -n teleport get ingress
NAME             CLASS    HOSTS                                                             ADDRESS   PORTS     AGE
teleport-proxy   <none>   teleport.test.ue1.redact.net                    80, 443   3h59m
```

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:1111111111:certificate/b6ab7fdf-4951-451b-a0ae-78a456aceb60
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=350
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: sg-0ff870c9cf388f98d,sg-062aababa986f19a9
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/subnets: subnet-09a8cfb107f3e694c,subnet-0cf3788c86d0beecc
    alb.ingress.kubernetes.io/success-codes: 200,301,302
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: teleport.test.ue1.redact.net.
    kubernetes.io/ingress.class: alb
  name: teleport-proxy
  namespace: teleport
spec:
  rules:
  - host: teleport.test.ue1.redact.net
    http:
      paths:
      - backend:
          service:
            name: teleport
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - teleport.test.ue1.redact.net
status:
  loadBalancer: {}
```

As you can see the status never gets updated:

```
status:
  loadBalancer: {}
```

The controller logs:

```
{"level":"info","ts":"2023-10-19T14:52:42Z","logger":"controllers.ingress","msg":"successfully built model","model":"...snipped"}
                                                      
 {"level":"error","ts":"2023-10-19T14:52:42Z","logger":"controllers.ingress","msg":"unable to determine AWS Shield subscription state, skipping AWS shield reconciliation","error":"AccessDeniedException: User: arn:aws:sts::1111111111:assumed-role/teleport-alb_controller/1697727143424788697 is not authorized to perform: shield:GetSubscriptionState on resource: arn:aws:shield::1111111111:subscription/* because no identity-based policy allows the shield:GetSubscriptionState action"}                  {"level":"error","ts":"2023-10-19T14:52:44Z","msg":"Reconciler error","controller":"ingress","object":{"name":"teleport-proxy","namespace":"teleport"},"namespace":"teleport","name":"teleport-proxy","reconcileID":"e0068806-a166-43b1-8128-a5a6d2f4b1c6","error":"AccessDeniedException: User: arn:aws:sts::1111111111:assumed-role/teleport
-alb_controller/1697727143424788697 is not authorized to perform: wafv2:GetWebACLForResource on resource: arn:aws:wafv2:us-east-1:1111111111:regional/webacl/*/* because no identity-based policy allows the wafv2:GetWebACLForResource action\n\tstatus code: 400, request id: eea87ddf-9032-4747-b41f-0eb99b6bf578"}
```

This is very unclear as to why the Address stays blank. I was able to finally find an unvoted stack overflow very far into searching that hinted to disable waf/wafv2 and the controller would work

```
    enableWaf: false
    enableWafv2: false
```

After applying that:

```
kubectl -n teleport get ingress
NAME             CLASS    HOSTS                                                             ADDRESS                                                                  PORTS     AGE
teleport-proxy   <none>   teleport.test.ue1.redact.net   k8s-teleport-teleport-1111111111-979246774.us-east-1.elb.amazonaws.com   80, 443   13h
```

This is unexpected as it would seem:

* waf/waf2 likely should not be defaulted to `true` since this is not related directly to creating an ALB and should be purposefully turned on as it requires more IAM permissions
* The controller should spit out the exception if waf/wafv2 are enabled but still be able to update the status of the ingress **if** nothing from waf or shield was required, returned, assigned, or annotated (here even though it was on none of my ingress annotations desired waf or shield behavior and failed for those calls)

**Expected outcome**

* if waf/wafv2 are enabled the controller should still be able to update the status with the information it does have, especially if waf/shield is not annotated as desired
* waf/wafv2 should possibly default to false or documented better

**Environment**

* AWS Load Balancer controller version 1.6.1
* Kubernetes version 1.26
* Using EKS (yes/no), if so version? yes, 1.26

**Additional Context**:
