### ISSUE TITLE
[Feature Request] Can we have a way to specify a port for the sourceIpConfig condition?

### ISSUE THREAD

**Issue by maiconrocha** [kubernetes-sigs/aws-load-balancer-controller#3459]
**Is your feature request related to a problem?**
IHAC with the following use case:

  External customers connect to the ALB created by the Ingress Controller through an NLB, and if the requests
  are coming from Source Ips of the NLB ENIs, requests needs to be allowed on Port 80 and be forward to specific service

  Basically: Client -> External ALB -> Internal NLB -> Internal ALB managed by Ingress Controller -> Port 80 if source-ip match specific values

  Internal Customers needs to be redirect to port 443 on the ALB managed by the Ingress Controller

  Basically: Client -> Internal ALB managed by Ingress Controller -> Redirect to port 443

However, it seems is not currently possible to achieve this use case with current annotations:

  When the SSL Redirect rule is applied, as the doc states:

  "ssl-redirect is exclusive across all Ingresses in IngressGroup.

  Once defined on a single Ingress, it impacts every Ingress within IngressGroup."

  alb.ingress.kubernetes.io/ssl-redirect: "443" 

And when applying the rules to sourceIpConfig, there is currently no way to apply the condition to only port 80:

alb.ingress.kubernetes.io/conditions.test: >
      [{"field":"source-ip","sourceIpConfig,":{"values":["XX.X.XX.XXX/32", "XX.X.XX.XXX/32"]}}]
alb.ingress.kubernetes.io/actions.test: >
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"200","messageBody":"Query has NLB as origin"}}

**Describe the solution you'd like**
So the ask is, can we have a way to specify a port for the sourceIpConfig condition? And also a priority order for the ssl-redirect
So customer can achieve their use case for external customer, when they will though the following conditions:

Is the source IP from the list sourceIpConfig for the port 80?
  If yes, traffic goes to HTTP
  Otherwise, traffic goes to HTTPS

Customer ALB Ingress Controller Version is: 2.4.3
I checked the newer versions and this feature still not available from my research. 

**Describe alternatives you've considered**
Creating two separate ALB managed by ALB Ingress Controller, one having the source-ip condition for port 80 and not performing SSL redirects, one having SSL redirects to forward all trafic to HTTPS.

**Comment by maiconrocha** [comment]
I tried applying the following config as an example:

```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: alb
spec:
  controller: ingress.k8s.aws/alb
---
apiVersion: v1
kind: Namespace
metadata:
  name: example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: example
  name: deployment-example1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: example1
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example1
    spec:
      containers:
      - image: public.ecr.aws/l6m2t8p7/docker-2048:latest
        imagePullPolicy: Always
        name: example1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: example
  name: service-example1
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: example1
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: example
  name: deployment-example2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: example2
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example2
    spec:
      containers:
      - image: public.ecr.aws/l6m2t8p7/docker-2048:latest
        imagePullPolicy: Always
        name: example2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: example
  name: service-example2
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: example2
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: example
  name: ingress1
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/conditions.service-example1: >
      [{"field":"source-ip","sourceIpConfig":{"values":["XX.XX.XX.XX/32", "XX.XX.XX.XX/32"]}}]
    alb.ingress.kubernetes.io/actions.service-example1: >
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"200","messageBody":"Query has NLB as origin"}}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/group.name: g1
    alb.ingress.kubernetes.io/group.order: '10'
spec:
  ingressClassName: alb
  rules:
    - host: service-example1.example.com
      http:
        paths:
        - backend:
            service:
              name: service-example1
              port:
                name: http
          path: /service-example1
          pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: example
  name: ingress2
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: g1
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm<Region>:<account.:certificate/XXXXXXX
    alb.ingress.kubernetes.io/group.order: '20'
spec:
  ingressClassName: alb
  rules:
    - host: service-example2.example.com
      http:
        paths:
        - backend:
            service:
              name: service-example2
              port:
                name: http
          path: /service-example2
          pathType: Prefix
```

I noticed when applying the ingress1 first, rules for the port 80 were properly created:
![Screenshot 2023-10-30 at 8 58 00 am](https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/16223299/e793b3a6-cdee-4970-a395-ee1cfce63860)

However, when applying the ingress2, which has the ssl-redirect rule, it add a default action which redirects to HTTPS, and then deletes any other existent rules.
![Screenshot 2023-10-30 at 9 04 33 am](https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/16223299/f2bca7c9-f4bf-46b2-9856-debf25d814db)

I understand this is by design, as documented here:
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#ssl-redirect
Once enabled SSLRedirect, every HTTP listener will be configured with a default action which redirects to HTTPS, other rules will be ignored.

Hence this feature request to change this behaviour to allow ssl-redirect to coexist with other existent rules for listener on port 80.
