### ISSUE TITLE
The aws-load-balancer-security-groups annotation does not add the given SGs to backend SG

### ISSUE THREAD

**Issue by igoratencompass** [kubernetes-sigs/aws-load-balancer-controller#3469]
**Describe the bug**
According to the docs https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/service/nlb/#security-group we should be able to use custom SGs starting from controller version 2.6. This is not working properly for me, the following annotation:

```
annotations:
   service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
   service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-0fxxxxxxxxxxxxx15"
   service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "true"
```
results to `sg-0fxxxxxxxxxxxxx15` being attached to the NLB. But in the same time another SG with empty inbound rules gets created by the controller and attached to the NLB which is unexpected. Even more, this odd SG gets whitelisted for access to the NodeGroup  SG for some (random) port range of `8082 - 32365`. This makes the TG health checks to fail and no traffic is flowing through the NLB. Only after adding the custom SG to the NodeGroup  SG manually the issue gets resolved.

**Steps to reproduce**
Nothing special just used the annotations given above.

**Expected outcome**
From the docs I was under impression the controller should automatically handle the custom SG whitelisting with the backend SG for a port range or even more specifically just the NodePort of the Listener's TargetGroup. 

**Environment**

* AWS Load Balancer controller version `2.6.1`
* Kubernetes version `1.24`
* Using EKS (yes/no), if so version? `v1.24.17-eks-f8587cb`
