### ISSUE TITLE
Wha's internal connection between target-group-attributes annotations at Ingress level and Service level?

### ISSUE THREAD

**Issue by hzzb** [kubernetes-sigs/aws-load-balancer-controller#3474]
1. target-group-attributes annotation at Ingress level is supported. https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#target-group-attributes

2. target-group-attributes  annotation at Service level is supported too. https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/annotations/#target-group-attributes

3. In my situation, there is one Ingress and several Services referenced by the one Ingress. I'd like to config different target attributes for each Service individually. Is that possible? or is it worthy to support?

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
  name: example-ingress
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: service1
          servicePort: 80
        path: /service1
      - backend:
          serviceName: service2
          servicePort: 80
        path: /service2
```
In the above Ingress definition, i would set slow_start.duration_seconds=30 for the service1 while set slow_start.duration_seconds=60 for the service2. Will it work if specifying these two different annotation values correspondingly at service1 and service2. Thanks in advance!

**Comment by oliviassss** [comment]
@hzzb, hi, I don't think this is supported right now, as the target-group-attribute annotation is just applied to all the backend svc.
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/ingress/model_build_target_group.go
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/ingress/model_build_actions.go#L114

**Comment by hzzb** [comment]
Hi @oliviassss, thanks. I walked through the code. It looks well supported  already to me. let me explain my understanding and plz free free to CWMIIW.

The overall calling flow is:
func (t *defaultModelBuildTask) buildForwardAction()
 -> func (t *defaultModelBuildTask) buildTargetGroup()
      -> func (t *defaultModelBuildTask) buildTargetGroupSpec()
           -> func (t *defaultModelBuildTask) buildTargetGroupAttributes()
Inside the implementation of the method buildTargetGroupSpec(), annotations of service and ingress will be merged together and service's annotation takes higher priority(see code at https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/ingress/model_build_target_group.go#L142). So If i don't setup ingress annotation and setup different annotations correspondingly to different services, target groups for each service will get different attributes eventually.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: service1
  annotations:
    alb.ingress.kubernetes.io/target-group-attributes: slow_start.duration_seconds=30
spec:
---
apiVersion: v1
kind: Service
metadata:
  name: service2
  annotations:
    alb.ingress.kubernetes.io/target-group-attributes: slow_start.duration_seconds=60
spec:
---
apiVersion: v1
kind: Service
metadata:
  name: service3
spec:
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
  name: example-ingress
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: service1
          servicePort: 80
        path: /service1
      - backend:
          serviceName: service2
          servicePort: 80
        path: /service2
      - backend:
          serviceName: service3
          servicePort: 80
        path: /service3
```
