### ISSUE TITLE
Document: Ingress specification sample is wrong and not matched to examples.

### ISSUE THREAD

**Issue by stdll00** [kubernetes-sigs/aws-load-balancer-controller#3476]
**Describe the bug**
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/ingress/spec/ 
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/guide/ingress/spec.md 

This Ingress is not valid at the Kubernetes API level. 

**Steps to reproduce**
Apply the yaml to some k8s server.
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "2048-ingress"
  namespace: "2048-game"
  labels:
    app: 2048-nginx-ingress
spec:
  ingressClassName: alb
  rules:
    - host: 2048.example.com
      http:
        paths:
          - path: /*
            backend:
              service:
                name: "service-2048"
                port:
                  number: 80
```
```
error: error validating "STDIN": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0]): missing required field "pathType" in io.k8s.api.networking.v1.HTTPIngressPath; if you choose to ignore these errors, turn validation off with --validate=false
```
**Expected outcome**
At least no validation error. 
**Environment**
* AWS Load Balancer controller version 
N/A, cannot apply to cluster.
* Kubernetes version 
1.26
* Using EKS (yes/no), if so version? 
yes

**Additional Context**:
