### ISSUE TITLE
Cannot sucessfully provision NLB on RKE2 cluster in AWS

### ISSUE THREAD

**Issue by aceeric** [kubernetes-sigs/aws-load-balancer-controller#3485]
**Describe the bug**
We run [RKE2](https://docs.rke2.io/) clusters in AWS. The way we do this is: 1) provision EC2 instances, 2) install RKE2 on those instances.

We would like to use the AWS LB controller to provision NLBs to route traffic to the RKE2 cluster. Unfortunately, the controller fails to populate the target group instances. (It does successfully create the NLB and listeners - so the failure is specifically associated with populating the target group.)

**Steps to reproduce**
Assumes an RKE2 cluster successfully running in AWS. Then:

Label one node:
```
kubectl label node ip-10-114-174-36.myco.org awslb=true
```
Install the LB controller:
```
cd /tmp
curl -LO https://aws.github.io/eks-charts/aws-load-balancer-controller-1.6.2.tgz
helm install\
 aws-load-balancer-controller\
 aws-load-balancer-controller-1.6.2.tgz \
 -n kube-system --set clusterName=foo
```

Next create a deployment that runs an http listener on port 80. (Steps omitted here because as you will see below this isn't really relevant because the workload is never reached by the NLB.)

Then create a `LoadBalancer` service for the controller to route traffic to the listener running in the deployment pod:
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: python-http-lb
  namespace: python-http
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-subnets: us-east-subnet-7,us-east-subnet-4
    service.beta.kubernetes.io/aws-load-balancer-target-node-labels: awslb=true
spec:
  selector:
    app: python-http
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
EOF
```

Confirm in the AWS Console that the NLB, and Listeners are created, but the Target Group is empty.

Look at the LB controller logs:
```
kubectl -n kube-system logs deploy/aws-load-balancer-controller
```

Notice:
```
{"level":"error","ts":"2023-11-15T13:32:39Z","msg":"Reconciler error","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding","TargetGroupBinding":{"name":"k8s-pythonht-pythonht-ae434494d6","namespace":"python-http"},"namespace":"python-http","name":"k8s-pythonht-pythonht-ae434494d6","reconcileID":"ff01eda7-7365-4702-a554-6bde38bf27d2","error":"providerID rke2://ip-10-114-174-36.myco.org is invalid for EC2 instances, node: ip-10-114-174-36.myco.org"}
```

Look at the RKE2-provisioned node:
```
kubectl get node ip-10-114-174-36.myco.org -oyaml
```

Snip:
```
spec:
  podCIDR: 10.42.1.0/24
  podCIDRs:
  - 10.42.1.0/24
  providerID: rke2://ip-10-114-174-36.myco.org
```
Look at: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/82301db337fa73f2b339025697c5e626f0984ceb/pkg/k8s/node_utils.go#L23

snip:
```
	if !awsInstanceIDRegex.MatchString(instanceID) {
		return "", errors.Errorf("providerID %s is invalid for EC2 instances, node: %s", providerID, node.Name)
	}
```

So in summary it appears to me that the AWS LB controller is expecting a provider ID in a specific format in the k8s node metadata that is incompatible with RKE2-generated clusters.

I *could* patch the provider in the node to make the controller happy but - I'm unsure if this would have any negative effect on RKE2 so - I'm reluctant to attempt that. Is there a better approach that I should be taking?

**Expected outcome**

`kubectl apply`ing the service on a non-EKS cluster (RKE2 in this case) enables the LB target group to be populated by the nodes that match the provided label in the service annotation (`service.beta.kubernetes.io/aws-load-balancer-target-node-labels: awslb=true`).

(P.S. same issue affects ALB)

**Environment**

* AWS Load Balancer controller version: v2.6.2 (chart version 1.6.2)
* Kubernetes version: v1.28.2
* Using EKS (yes/no), if so version? no
