### ISSUE TITLE
Allow multiple service to share the same NLB using different port

### ISSUE THREAD

**Issue by onion1984** [kubernetes-sigs/aws-load-balancer-controller#3498]
**Is your feature request related to a problem?**
I have multiple services in my cluster exposed using NLB. I would like to share the same NLB by listening on the different port.

**Describe the solution you'd like**
Allow multiple service to share the same NLB by having an annotation indicating the group.id like how ingress share the same ALB.

**Describe alternatives you've considered**
NA

**Comment by mausch** [comment]
duplicate of https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3247 ?

**Comment by tom10271** [comment]
Not 100% the same as #3247 but I am 100% demanding for the same thing as the original post does.

**Comment by shraddhabang** [comment]
@onion1984 We will be supporting this in our upcoming minor release. Meanwhile have you looked at using the [TargetGroupBinding](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/guide/targetgroupbinding/targetgroupbinding/) ?

**Comment by DevBey** [comment]
there has been two minor releases since last comment from @shraddhabang. 

can we now confirm @shraddhabang if NLB can be used for two services on different ports ?? 

if so how ??

**Comment by DevBey** [comment]
any update on this ??

**Comment by lalit4osttra** [comment]
> I am also waiting for an update for this. Its so annoying that we have to create different NLBs for different services

Is there a hard requirement to use NLB, we are using ALB to share among different services

**Comment by tom10271** [comment]
> > I am also waiting for an update for this. Its so annoying that we have to create different NLBs for different services
> 
> Is there a hard requirement to use NLB, we are using ALB to share among different services

ALB is for L7 traffics only, in fact it supports HTTP, HTTPS and WebSocket if I remember correctly. Service like MQTT cannot use ALB

**Comment by DevBey** [comment]
@tom10271 @skursadk 
can you guys please checkout some other ingress controller like nginx/kong. 

we use them for single load balancer for multiple database requiring TCP.

**Comment by skursadk** [comment]
@DevBey thank you for the suggestion. For now I've solved my issue with some manual actions. (i.e creating the NLB, creating a TargetGroupBinding for each service, etc ). But I'll keep your suggestion in my mind for the future

**Comment by DevBey** [comment]
please do check out the ingress controller, that's the industry standard way to use one NLB, for all HTTP/TCP/UDP routes. 

the differnece is 
1. aws controller just updated the AWS actual ALB with the routes. 
2. but in nginx/kong they have one NLB and the routing is done by the actual nginx controller.

**Comment by thunder-spb** [comment]
Any progress on this one?

**Comment by DevBey** [comment]
yes NLB can be shared ALB can be shared but both need separate LB's

**Comment by thunder-spb** [comment]
> yes NLB can be shared ALB can be shared but both need separate LB's

Hey @DevBey ,

The request is about have two kubernetes services with one shared NLB name via annotation. Like
```
apiVersion: v1
kind: Service
metadata:
  name: my-udp-service-1
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-name: shared-udp-nlb
spec:
  type: ClusterIP
  selector:
    app: my-udp-app-1
  ports:
    - name: udp-port-1
      port: 1234
      targetPort: 1234
      protocol: UDP
```
And
```
apiVersion: v1
kind: Service
metadata:
  name: my-udp-service-2
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-name: shared-udp-nlb
spec:
  type: ClusterIP
  selector:
    app: my-udp-app-2
  ports:
    - name: udp-port-2
      port: 5678
      targetPort: 5678
      protocol: UDP
```
And those should be under one NLB `shared-udp-nlb` with two listeners: for port `1234` and for port `5678`...

**Comment by DevBey** [comment]
yes this should work, in latest gateway release as per documentation, I haven't tested this out myself. 


what's pending is sharing single NLB for both https and tcp traffic

**Comment by thunder-spb** [comment]
> yes this should work, in latest gateway release as per documentation, I haven't tested this out myself.

I couldn't find examples for this :( And the Gateway API sill not stable... UDPRoute is alpha... 

> what's pending is sharing single NLB for both https and tcp traffic

That was implemented I believe with TCP_UDP...

> LBC now supports TCP_UDP type Listeners and TargetGroups.
TCP_UDP is a popular listener type for AWS NLB, which allows serving both TCP and UDP from the same port. We have backfilled this feature into the LBC.
You can enable this feature by specifying a service with TCP and UDP protocols on the same port.
In order to enable the feature, please enable the LBC feature flag EnableTCPUDPListener or specify individual services to enable the feature by using the annotation service.beta.kubernetes.io/aws-load-balancer-enable-tcp-udp-listener

**Comment by sergey-safarov** [comment]
I have tested the annotation
```yaml
annotations:
  service.beta.kubernetes.io/aws-load-balancer-type: external
  service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
  service.beta.kubernetes.io/aws-load-balancer-name: shared-udp-nlb
```
and found this does not work.
In the logs I error
> {"level":"error","ts":"2025-11-29T21:29:15Z","msg":"Reconciler error","controller":"service","namespace":"envoy-gateway-system","name":"nlb-internal","reconcileID":"a91412de-0db5-46a6-addc-dedf2b7b4c50","error":"operation error Elastic Load Balancing v2: CreateLoadBalancer, https response error StatusCode: 400, RequestID: c654390c-319a-4da2-ba01-be5feb25941f, DuplicateLoadBalancerName: A load balancer with the same name 'shared-udp-nlb' exists, but with different settings"}
