### ISSUE TITLE
Error from server (NotFound): ingresses.networking.k8s.io

### ISSUE THREAD

**Issue by noamgreen** [kubernetes-sigs/aws-load-balancer-controller#3504]
**Describe the bug**

Hi, i am not sure who to describe the issues but the controller create the ALB but after some time "Error from server (NotFound): ingresses.networking.k8s.io. " ALB ARN " not found 

k describe ing internal-XXXXXXXXXXXX.us-east-1.elb.amazonaws.com

Error from server (NotFound): ingresses.networking.k8s.io "internal-XXXXXXXXXXXX.us-east-1.elb.amazonaws.com" not found

i am not sure why its happened, no error in the logs .
after testing restart the service will generate this error its just lost the connection to the ALB like its not there 
i checked int the aws dashboard and the ALB is there the controller not see it ... 
 
 

* AWS Load Balancer controller version = 1.6.2
* Kubernetes version = 1.27
* Using EKS = yes 

```
replicaCount: 1
image:
  repository: public.ecr.aws/eks/aws-load-balancer-controller
  tag: v2.6.2
  pullPolicy: IfNotPresent
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::XXXXXXXX:role/dev-aws-lb-controller"
  name: dev-aws-lb-controller
  automountServiceAccountToken: true
  imagePullSecrets:

rbac:
  create: true

podSecurityContext:
  fsGroup: 65534


securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  allowPrivilegeEscalation: false

terminationGracePeriodSeconds: 10

priorityClassName: system-cluster-critical

configureDefaultAffinity: true

enableCertManager: false

clusterName: myeks

cluster:
    dnsDomain: cluster.local

ingressClass: alb

ingressClassParams:
  create: true
  name:
createIngressClassResource: true

region: us-east-1

vpcId: vpc-XXXXXXXXXXXXX

defaultTargetType: instance

enablePodReadinessGateInject:

logLevel: debug

# webhookTLS specifies TLS cert/key for the webhook
webhookTLS:
  caCert:
  cert:
  key:

keepTLSSecret: true

livenessProbe:
  failureThreshold: 2
  httpGet:
    path: /healthz
    port: 61779
    scheme: HTTP
  initialDelaySeconds: 30
  timeoutSeconds: 10
hostNetwork: false
clusterSecretsPermissions:
  allowAllSecrets: false

ingressClassConfig:
  default: false

enableServiceMutatorWebhook: false

```
