### ISSUE TITLE
ValidationError: Action type 'authenticate-cognito' must be one of 'redirect,fixed-response,forward,authenticate-oidc'

### ISSUE THREAD

**Issue by lunderhage** [kubernetes-sigs/aws-load-balancer-controller#3517]
**Describe the bug**
Unable to enable cognito authentication on load balancer.

**Steps to reproduce**
Create an ingress like this:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoserver
  namespace: echoserver
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
    external-dns.alpha.kubernetes.io/hostname: mydomain.com
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '443'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/authenicate-cognito: authenticate-oidc
    alb.ingress.kubernetes.io/auth-scope: openid
    alb.ingress.kubernetes.io/auth-session-timeout: "3600"
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn":"arn:aws:cognito-idp:eu-north-1:1234567890123:userpool/eu-north-1_xxYYXXxxYYxx","UserPoolClientId":"xxxxxxxxxxxxxxx","UserPoolDomain":"mydomain.auth.eu-north-1.amazoncognito.com"}'
spec:
  ingressClassName: alb
  rules:
     - host: echoserver.magicwindow.se
       http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: echoserver
                port:
                  number: 80
```

**Expected outcome**
Ingress is reconciled without errors and I am using cognito for authentication.

**Environment**

* AWS Load Balancer controller version 2.6.2
* Kubernetes version 1.28 
* Using EKS (yes/no), if so version? Yes, v1.28.3-eks-e71965b

**Additional Context**: Basically exactly the same problem as [#2434](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2534), but according to [List of AWS Services Available by Region](https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/), cognito is now supposed to be available in eu-north-1.
