### ISSUE TITLE
question: only expose a subset of ports 

### ISSUE THREAD

**Issue by dprotaso** [kubernetes-sigs/aws-load-balancer-controller#3543]
Is there a way to have a K8s Service with type=LoadBalancer with several ports defined (`80`,`443`) but then only have the NLB expose a single service port `443`.

The idea here is to have the NLB do TLS termination - but it's ok for traffic in the cluster to use port `80` when hitting that K8S service using the cluster local domain

**Comment by oliviassss** [comment]
@dprotaso, hi, you mean you want to specify both `80` and `443` in the annotation, but in svc spec, you only want port `443`? Would this manifest work for you?
```
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "80"
spec:
  ports:
    - name: port
      port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
```

**Comment by dprotaso** [comment]
Would the above mean that TLS termination happens on 443 and then traffic is forwarded to port 80?

**Comment by oliviassss** [comment]
@dprotaso, yeah, so right now all the ports specified in the annotations `service.beta.kubernetes.io/aws-load-balancer-ssl-ports` need to be in the service spec too, otherwise the controller will error out. So I'm not aware of a feasible way to only expose a subset of ports.

**Comment by dprotaso** [comment]
I guess to confirm if I don't specify port `80` in `service.beta.kubernetes.io/aws-load-balancer-ssl-ports` would the LB still expose port 80 because it's in the Service's port list?

As a concrete example - which ports would the LB expose to the internet for the given service (apologies I don't have a handy AWS account to verify this myself)

```yaml
apiVersion: v1
kind: Service
metadata:
  name: envoy
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "..."
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 8080
    name: http
    protocol: TCP
  - port: 443
    targetPort: 8080
    name: http
    protocol: TCP
  selector:
    app: envoy
  type: LoadBalancer
```
