### ISSUE TITLE
Support ALB as target group type

### ISSUE THREAD

**Issue by lbsn** [kubernetes-sigs/aws-load-balancer-controller#3553]
**Is your feature request related to a problem?**
What I'm trying to achieve is something like [this](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/application-load-balancer-target.html)

I have the following resources and I'd like the controller to create a Network Load Balancer (`my-svc-lb`) and an Application Load Balancer (`my-ingress-lb`) with `my-svc-lb` routing traffic to `my-ingress-lb`:

```
apiVersion: v1
kind: Service
metadata:
  name: my-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: my-svc-lb
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: 'instance'
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/instance: my-pod
    app.kubernetes.io/name: my-pod
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-name: my-ingress-lb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip
  name: my-ingress
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: my-svc
            port:
              name: http
        path: /
        pathType: Prefix
```
But there is currently no way to define `aws-load-balancer-nlb-target-type` with a value different from `ip` or `instance`.

**Describe the solution you'd like**
Let `service.beta.kubernetes.io/aws-load-balancer-nlb-target-type` to allow for the additional value `alb`. I'm not sure how the target ALB should be specified, maybe through an additional annotation?

**Describe alternatives you've considered**
I'd be happy to know if there is some workaround to achieve this, beside using AWS console or CLI.
