### ISSUE TITLE
big jump in versions

### ISSUE THREAD

**Issue by FernandoMiguel** [kubernetes-sigs/aws-load-balancer-controller#3554]
**Describe the bug**
Previous versions of the chart were like:
```
version: 1.6.0
appVersion: v2.6.2
```
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/5e07dced064969588164c60cd493ce7921e913da/helm/aws-load-balancer-controller/Chart.yaml#L4C1-L5C19

but the latest 2.7.0 is:
```
version: 2.7.0
appVersion: v2.7.0
```
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/ed00c8199179b04fa2749db64e36d4a48ab170ac/helm/aws-load-balancer-controller/Chart.yaml#L4

I didn't immediately find a reason for this change.

Also, when I added this new version to our test argo, it failed to pull the chart
```
apiVersion: v2
name: aws-load-balancer-controller
description: AWS Load Balancer Controller Helm chart for Kubernetes
type: application

# The chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

home: https://github.com/aws/eks-charts
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
keywords:
  - eks
  - alb
  - load balancer
  - ingress
  - nlb

sources:
  - https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases
  - https://github.com/aws/eks-charts/releases?q=aws-load-balancer-controller&expanded=true
  - https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/helm/aws-load-balancer-controller/Chart.yaml
  - https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller

dependencies:
  - name: aws-load-balancer-controller
    version: ~v2.7
    repository: https://aws.github.io/eks-charts
```

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): `helm dependency build` failed exit status 1: Error: can't get a valid version for repositories aws-load-balancer-controller. Try changing the version constraint in Chart.yaml
```

* AWS Load Balancer controller version
* Kubernetes version
* Using EKS (yes/no), if so version? 1.27
