### ISSUE TITLE
s3 bucket creation name

### ISSUE THREAD

**Issue by lifeofmoo** [kubernetes-sigs/aws-load-balancer-controller#3563]
Hello,

Can someone help explain how the following is derived and what would I need to do to change it to another value.

Using this Annotation I am able to get S3 logs.

```
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=myorg-dev-loadbalancer-log-bucket

```

> AWSLogs/xxxxxxxxxx/elasticloadbalancing/eu-west-1/2023/08/30/xxxxxxxx_elasticloadbalancing_eu-west-1_app.k8s-ping-pingfeda-d2cc6a04df.181cc947fc4ccd46_20230830T0830Z_172.21.89.86_ym80j8sr.log.gz

I need to rename the log files to make the distinction clearer between some PingFed apps we use. 

From *ping-pingfeda* to *pingfed-authgw*

> E.g.:
> 99999999_elasticloadbalancing_eu-west-1_app.k8s-**ping-pingfeda**-d2cc6a04df.181cc947fc4ccd46_20230830T0830Z_172.21.89.86_ym80j8sr.log.gzInfo → 
> 99999999_elasticloadbalancing_eu-west-1_app.k8s-**pingfed-authgw**-d2cc6a04df.181cc947fc4ccd46_20230830T0830Z_172.21.89.86_ym80j8sr.log.gzInfo

**How is the value "ping-pingfeda" being derived?**

Stripped out version of the full deployment is below!

```
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: pingfed-authentication-gateway
    app.kubernetes.io/name: pingfed-authentication-gateway
    costcentre: ping
    project: ping
    team: access
  name: pingfed-authentication-gateway
  namespace: ping
---
apiVersion: v1
data:
  application.yaml: |
    spring:
      application:
        name: pingfed-authentication-gateway

    server:
      port: 8080

    client:
      base-url: https://pingfed-authentication-gateway.myorggroup.com
      timeout:
        connection: 2000
        read: 3000
    ---
    spring:
      config:
        activate:
          on-profile: dev
kind: ConfigMap
metadata:
  name: pingfed-authentication-gateway-config-8kkt7c4dg4
  namespace: ping
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pingfed-authentication-gateway
    app.kubernetes.io/name: pingfed-authentication-gateway
    costcentre: ping
    project: ping
    team: access
  name: pingfed-authentication-gateway
  namespace: ping
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: pingfed-authentication-gateway
    app.kubernetes.io/name: pingfed-authentication-gateway
    costcentre: ping
    project: ping
    team: access
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pingfed-authentication-gateway
    app.kubernetes.io/name: pingfed-authentication-gateway
    costcentre: ping
    project: ping
    team: access
  name: pingfed-authentication-gateway
  namespace: ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingfed-authentication-gateway
      app.kubernetes.io/name: pingfed-authentication-gateway
      costcentre: ping
      project: ping
      team: access
  template:
    metadata:
      labels:
        app: pingfed-authentication-gateway
        app.kubernetes.io/name: pingfed-authentication-gateway
        costcentre: ping
        project: ping
        team: access
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pingfed-authentication-gateway
              topologyKey: topology.kubernetes.io/zone
            weight: 100
      containers:
      - args:
        - -Dspring.profiles.active=dev
        - -jar
        - pingfed-authentication-gateway.jar
        command:
        - java
        image: xxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com/pingfed-authentication-gateway:0.61
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        name: pingfed-authentication-gateway
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 1.5Gi
        volumeMounts:
        - mountPath: /app/config/application.yaml
          name: config
          subPath: application.yaml
        - mountPath: /opt/appdynamics
          name: appd-agent-repo
      securityContext:
        runAsUser: 1001
      serviceAccountName: pingfed-authentication-gateway
      tolerations:
      - effect: NoSchedule
        key: nodetype
        operator: Exists
      volumes:
      - configMap:
          name: pingfed-authentication-gateway-config-8kkt7c4dg4
        name: config
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.pingfed-authentication-gateway-login-redirect: '{"Type":
      "redirect", "RedirectConfig": {"Protocol": "HTTPS", "Path": "/index.html", "Port":
      "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:xxxxxxxx:certificate/xxxxxxxxx
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/inbound-cidrs: 172.26.0.0/16
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=myorg-dev-loadbalancer-log-bucket
    alb.ingress.kubernetes.io/load-balancer-name: k8s-pingfed-auth-gateway
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/tags: app=pingfed-authentication-gateway
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=3600
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: pingfed-authentication-gateway.myorggroup.com
  labels:
    app: pingfed-authentication-gateway
  name: pingfed-authentication-gateway-ingress
  namespace: ping
spec:
  ingressClassName: alb
  rules:
  - host: pingfed-authentication-gateway.myorggroup.com
    http:
      paths:
      - backend:
          service:
            name: pingfed-authentication-gateway-login-redirect
            port:
              name: use-annotation
        path: /
        pathType: ImplementationSpecific
      - backend:
          service:
            name: pingfed-authentication-gateway
            port:
              number: 80
        path: /*
        pathType: ImplementationSpecific

```
