### ISSUE TITLE
There are too long delay between controller UPDATE operation and ModifyRule action. (which is causing downtime) 

### ISSUE THREAD

**Issue by nessa829** [kubernetes-sigs/aws-load-balancer-controller#3588]
**Describe the bug**
A concise description of what the bug is.

- We are using argo-rollout / canary strategy / ingress with ALB configuration in AWS EKS environment.
- **When i trigger a new image sync before the rollout canary deployment is complete, downtime occurs.** (This is not a typical deployment process, but sometimes it happens)
- As i analyzed and followed up the argo rollout code and the actual remaining rollout logs, it progresses as follows.: 

1. As soon as synchronized, rollout detects new canary  (2024-02-22T01:32:14Z UTC) 
2. Change service selector to new canary from old canary (2024-02-22T01:32:14Z UTC) 
3. Change canary hash value of rollout status to new canary (2024-02-22T01:32:14Z UTC) 
4. Change ingress weight from 50:50 to 100:0 (because new canary is not ready) (2024-02-22T01:32:14Z UTC) 
5. delete old canary  (2024-02-22T01:32:14Z UTC) 

- I was curious that 5xx errors occurred even though the ingress weight was changed to 100:0. 
- so I analyzed the lb-controller log as well, and found that an **update operation** request was received at almost the same time.
```
{"level":"debug","ts":"**2024-02-22T01:32:14Z**","logger":"validating_handler","msg":"validating webhook request","request":{"uid":"1b140c2d-b347-46aa-9f2b-5efe2528a3da","kind":{"group":"networking.k8s.io","version":"v1","kind":"Ingress"},"resource":{"group":"networking.k8s.io","version":"v1","resource":"ingresses"},"requestKind":{"group":"networking.k8s.io","version":"v1","kind":"Ingress"},"requestResource":{"group":"networking.k8s.io","version":"v1","resource":"ingresses"},"name":"internal-alb-ingress-init-ingress-canary","namespace":"service-sre-test","operation":"UPDATE","userInfo":{"username":"system:serviceaccount:argo-rollouts:argo-rollouts-redated","uid":"722a51d6-484b-4fd6-9d78-b0df5aeca6d7","groups":["system:serviceaccounts","system:serviceaccounts:argo-rollouts","system:authenticated"],"extra":{"authentication.kubernetes.io/pod-name":["argo-rollouts-redated"],"authentication.kubernetes.io/pod-uid":["0be3d23e-8bd7-4698-b510-845b48a85cf4"]}},"object":{"kind":"Ingress","apiVersion":"networking.k8s.io/v1","metadata":{"name":"internal-alb-ingress-init-ingress-canary","namespace":"service-sre-test","uid":"cbfbaa01-768a-45f7-9cda-3e9bff7f571d","resourceVersion":"278711068","generation":4,"creationTimestamp":"2023-10-19T07:07:54Z","labels":{"app.kubernetes.io/name":"internal-alb-ingress-init-ingress-canary","argocd.argoproj.io/instance":"alpha-sre-test"},"annotations":{"alb.ingress.kubernetes.io/actions.sre-test-root":"{\"Type\":\"forward\",\"ForwardConfig\":{\"TargetGroups\":[{\"ServiceName\":\"sre-test-canary\",\"ServicePort\":\"80\",\"Weight\":0},{\"ServiceName\":\"sre-test-stable\",\"ServicePort\":\"80\",\"Weight\":100}]}}","alb.ingress.kubernetes.io/conditions.sre-test-root":"[{\"field\":\"host-header\",\"hostHeaderConfig\":{\"values\":[redated]}}]\n","alb.ingress.kubernetes.io/group.name":"internal-service","alb.ingress.kubernetes.io/healthcheck-path":"/hello","alb.ingress.kubernetes.io/listen-ports":"[{\"HTTP\": 8080}]","alb.ingress.kubernetes.io/load-balancer-name":"ingress-internal-alb","alb.ingress.kubernetes.io/scheme":"internal","alb.ingress.kubernetes.io/subnets":"redated","alb.ingress.kubernetes.io/target-group-attributes":"deregistration_delay.timeout_seconds=40","alb.ingress.kubernetes.io/target-type":"ip","kubectl.kubernetes.io/last-applied-configuration":"...


{"level":"debug","ts":"2024-02-22T01:32:14Z","logger":"validating_handler","msg":"validating webhook response","response":{"Patches":null,"uid":"","allowed":true,"status":{"metadata":{},"code":200}}}


{"level":"debug","ts":"2024-02-22T01:32:14Z","logger":"controller-runtime.webhook.webhooks","msg":"wrote response","webhook":"/validate-networking-v1-ingress","code":200,"reason":"","UID":"1b140c2d-b347-46aa-9f2b-5efe2528a3da","allowed":true}

{"level":"debug","ts":"2024-02-22T01:32:14Z","logger":"controller-runtime.webhook.webhooks","msg":"received request","webhook":"/mutate-v1-pod","UID":"9c41e46c-b6b9-40aa-b20f-de3e2c802d68","kind":"/v1, Kind=Pod","resource":{"group":"","version":"v1","resource":"pods"}}
```

- However, the actual ModifyRule action to change weight triggered only after about 1 minute and 10 seconds. (From, Cloudtrail logs. February 22, 2024, 1:33:23 UTC) 
- After that, when new canary is ready, it changes to 50:50 again.

Ultimately, the problem seems to be that there is a time difference between the lb-controller's update operation request for weight change and the actual lb listner rule modification api.

I don't see any other errors in lb -controller logs, or limitation related issue. 

**Steps to reproduce**
as above. 

**Expected outcome**
A concise description of what you expected to happen.

no downtime when weight changed. 

**Environment**
- LB controller version  : aws-load-balancer-controller:v2.6.2
- alb annotation / ingress settings
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/conditions.sre-test-root: >
      [{"field":"host-header","hostHeaderConfig":{"values":["domain-info"]}}]
    alb.ingress.kubernetes.io/group.name: internal-service
    alb.ingress.kubernetes.io/healthcheck-path: /hello
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8080}]'
    alb.ingress.kubernetes.io/load-balancer-name: ingress-internal-alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/subnets: 'subnet-info'
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=40
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app.kubernetes.io/name: internal-alb-ingress-init-ingress-canary
    argocd.argoproj.io/instance: alpha-sre-test
  name: internal-alb-ingress-init-ingress-canary
  namespace: service-sre-test
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - backend:
              service:
                name: sre-test-root
                port:
                  name: use-annotation
            path: /
            pathType: Prefix

```

* AWS Load Balancer controller version
aws-load-balancer-controller:v2.6.2
* Kubernetes version
1.27
* Using EKS (yes/no), if so version?
Yes, 1.27

**Additional Context**:
