### ISSUE TITLE
Pod READINESS GATES shows 1/1 only after Restart 

### ISSUE THREAD

**Issue by vgokul984** [kubernetes-sigs/aws-load-balancer-controller#3603]
Currently we are using AWS LB Controller 2.5.4 and EKS Version 1.24 while deploying New application using helm-chart the readiness Gates show none once after the pod restarted it shows as 1/1 on the readiness gates. during the new deployments it creates the ingress load balancer pod comes 1/1 ready everything is fine apart from Readiness Gates.

**Expected outcome**
During the New deployments the readiness gates should be 1/1  

**Environment**

* AWS Load Balancer controller version: 2.5.4
* Kubernetes version:
* Using EKS (yes/no), if so version? yes/1.24

**Additional Context**:
Service.yaml
```
  apiVersion: v1
  kind: Service
  metadata:
    annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/readiness
      meta.helm.sh/release-name: test-service
      meta.helm.sh/release-namespace: default
    labels:
      app: test-service
      app.kubernetes.io/managed-by: Helm
    name: test-service
    namespace: default
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: test-service
    sessionAffinity: None
    type: ClusterIP
```
ingress.yaml
```
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: "40"
      alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/readiness
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "30"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/tags: DiscountTag=1234
      alb.ingress.kubernetes.io/target-type: ip
      external-dns.alpha.kubernetes.io/aws-region: us-east-1
      external-dns.alpha.kubernetes.io/hostname: test.com
      external-dns.alpha.kubernetes.io/set-identifier: test-service-us-east-1
      kubernetes.io/ingress.class: alb
      meta.helm.sh/release-name: test-service
      meta.helm.sh/release-namespace: default
    labels:
      app: test-service
      app.kubernetes.io/managed-by: Helm
    name: test-service
    namespace: default
  spec:
    rules:
    - http:
        paths:
        - backend:
            service:
              name: test-service
              port:
                number: 80
          path: /*
          pathType: ImplementationSpecific
    tls:
    - hosts:
      - test.com
```
