### ISSUE TITLE
Documentation missing for using EKS Pod Identities

### ISSUE THREAD

**Issue by e6c31d** [kubernetes-sigs/aws-load-balancer-controller#3613]
The [v2.7.0 release](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.7.0) mentions that "Support for [EKS pod identities](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html)" was added. However, there's no documentation about how to use it. The [installation guide](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/deploy/installation/#configure-iam) has instructions for IRSA and node IAM policies, but not for EKS pod Identities.

**Comment by krishk8s** [comment]
Has any one implemented ALBC with pod identity ?

**Comment by flipcc** [comment]
This will give you an AWS EKS cluster that uses up-to-date stuff (IPv6 instead of IPv4 and pod-identity instead of IRSA), has nodes in private subnets and comes with an AWS LBC deployed. For testing it uses echoserver. It is sparse on sources, because I build it from AWS documentation bits and pieces and therefore their docs are your best help.

Here we go ..

## EKS cluster

```sh
eksctl create cluster -f example-cluster.yaml
export EKS_CLUSTER_NAME=$(eksctl get clusters | awk '$1 ~ /poc/ { print $1 }')
```

## LBC

```sh
export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
export LBC_LATEST_VERSION=$(curl -sL https://api.github.com/repos/kubernetes-sigs/aws-load-balancer-controller/releases/latest | jq -r '.tag_name')
export LBC_POLICY_NAME=eks_poc_lbc_iam_policy
export LBC_SERVICE_ACCOUNT_NAME=eks-poc-lbc-service-account  # must be a valid RFC 1123 name

# configure permission stuff
curl -o lbc-iam-policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/$LBC_LATEST_VERSION/docs/install/iam_policy.json
export LBC_POLICY_ARN=$(aws iam create-policy \
    --policy-name $LBC_POLICY_NAME \
    --policy-document file://lbc-iam-policy.json \
    --output text \
    --query Policy.Arn)
cat > lbc-service-account.yaml <<EOF
apiVersion: v1
kind: ServiceAccount
metadata:
  name: $LBC_SERVICE_ACCOUNT_NAME
  namespace: kube-system
EOF
kubectl apply -f lbc-service-account.yaml
eksctl create podidentityassociation \
    --cluster=$EKS_CLUSTER_NAME \
    --namespace=kube-system \
    --service-account-name=$LBC_SERVICE_ACCOUNT_NAME \
    --permission-policy-arns=$LBC_POLICY_ARN

# install the controller
helm repo add eks https://aws.github.io/eks-charts
curl -o lbc-crds.yaml https://raw.githubusercontent.com/aws/eks-charts/master/stable/aws-load-balancer-controller/crds/crds.yaml
kubectl apply -f lbc-crds.yaml
helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=$EKS_CLUSTER_NAME --set serviceAccount.create=false --set serviceAccount.name=$LBC_SERVICE_ACCOUNT_NAME

# deploy echoserver
kubectl apply -f echoserver-namespace.yaml
kubectl apply -f echoserver-deployment.yaml
kubectl apply -f echoserver-service.yaml

# deploy ingress in dual stack mode
kubectl apply -f echoserver-ingress.yaml
kubectl logs -n kube-system --tail -1 -l app.kubernetes.io/name=aws-load-balancer-controller | grep 'echoserver\/echoserver'

# test by querying your LB
export LB_DNS_NAME=<do get it from the webUI, honestly>
curl $LB_DNS_NAME | jq .
```

## Cleanup

```sh
# remove downloaded content
rm lbc-iam-policy.json
rm lbc-service-account.yaml
rm lbc-crds.yaml

# delete K8s resources
kubectl delete -f echoserver-deployment.yaml
kubectl delete -f echoserver-service.yaml
kubectl delete -f echoserver-ingress.yaml
kubectl delete -f echoserver-namespace.yaml
helm delete aws-load-balancer-controller -n kube-system

# delete AWS EKS stuff
# manually delete policies and roles (too annoying to script)
eksctl delete cluster --name $EKS_CLUSTER_NAME --region eu-central-1
```

## Files used

[1] example-cluster.yaml
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-eks-poc
  region: eu-central-1

kubernetesNetworkConfig:
  ipFamily: IPv6

addonsConfig:
  autoApplyPodIdentityAssociations: true

addons:
  - name: eks-pod-identity-agent
    version: latest
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest

iam:
  withOIDC: true

managedNodeGroups:
  - name: mng-1-eks-poc
    labels: { role: workers }
    tags:
      nodegroup-role: worker
    instanceType: m5.large
    privateNetworking: true
```

[2] echoserver-namespace.yaml
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: echoserver
```

[3] echoserver-deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: echoserver
spec:
  selector:
    matchLabels:
      app: echoserver
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: ealen/echo-server:latest
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 80
```

[4] echoserver-service.yaml
 ```yaml
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echoserver
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: echoserver
```

[5] echoserver-ingress.yaml
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoserver
  namespace: echoserver
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ip-address-type: dualstack
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: echoserver
      port:
        number: 80
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echoserver
                port:
                  number: 80
```
