### ISSUE TITLE
AWS NLB - Proxy Protocol v2 NOT enabled in existing NLB created bythe ingress-nginx

### ISSUE THREAD

**Issue by utkarsh079** [kubernetes-sigs/aws-load-balancer-controller#3619]
**Describe the bug**
I have an existing NLB created by ingress-nginx controller. Now I have a requirement to enable proxy protocol v2 in order to get source IPs. I have added an annotation to the same ingress-nginx's configuration and can see the same in annotation in service. But the NLB is unchanged. I have aws-load-balancer-controller running in cluster
```
annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "ssl"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<Redacted>"
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "2000"
      domainName: "public.kube.develop.vortexa.com"
      service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
```
**Steps to reproduce**
Create an NLB with nginx-ingress controller and then try to enable proxy-protocol v2 with annotation.
**Expected outcome**
Proxy protocol v2 should be enabled in NLB

**Environment**

* AWS Load Balancer controller version: 2.7.1
* Kubernetes version: 1.25
* Using EKS (yes/no), if so version? EKS 1.25
