### ISSUE TITLE
Allowed certificate arn list doesn't work

### ISSUE THREAD

**Issue by kimxogus** [kubernetes-sigs/aws-load-balancer-controller#3626]
**Describe the bug**
A concise description of what the bug is.
As [specifying allowed certificate arns for certificate discovery](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3591), I tested in our test environment.

After specified acm cert arn in `certDiscovery.allowedCertificateAuthorityARNs` in helm chart(I checked it's set in deployment args too), cert discovery begun to fail in every ingresses.
I tried below, and they all failed with the same error message as below
- specifying `*.our.domain`, `subdomain.our.domain`, `our.domain` in `spec.tls.hosts` in ingress (acm has all these domain subjects)
- not specifying `spec.tls.hosts` at all

error message
```
  Normal   SuccessfullyReconciled  4m48s (x2 over 6m19s)  ingress  Successfully reconciled
  Warning  FailedBuildModel        14s (x16 over 2m58s)   ingress  Failed build model due to ingress:ns/ingress: no certificate found for host: our.domain
  Warning  FailedBuildModel        11s                    ingress  Failed build model due to ingress: ns/ingress: no certificate found for host: *.our.domain
```

After removing `--allowed-certificate-authority-arns` arg from the deploy, cert discovery worked again.

**Steps to reproduce**
- Specify `certDiscovery.allowedCertificateAuthorityARNs` in helm chart or `--allowed-certificate-authority-arns` arg.

**Expected outcome**
A concise description of what you expected to happen.
Cert discovery works using allowed acm certificate arns only.

**Environment**

* AWS Load Balancer controller version 2.7.2 (with helm chart version 1.7.2 in eks-charts)
* Kubernetes version `v1.28.6-eks-508b6b3`
* Using EKS (yes/no), if so version? `v1.28.6-eks-508b6b3`

**Additional Context**:

**Comment by shraddhabang** [comment]
@the-technat Would you be able to take a look at this issue? Seems like a bug introduced from your [PR](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3591). Tagging you since you have a good knowledge around it and if you know anything about it. 

@kimxogus We will also try to reproduce this issue on our side. Thank you for raising this concern.

**Comment by the-technat** [comment]
I'll take a look.

**Comment by the-technat** [comment]
@kimxogus Could you share an example ingress config that you used to try the CA filter?

From what I can see specifying `spec.tls.hosts` doesn't necessarily break cert discovery, so I'm not sure where to look for a relation. Also that cert discovery didn't worked at all in your environment seems strange.

Just to be sure: have you manually verified that the CA ARN you passed to the flag is the ARN referenced in a matching certificate in ACM as CA ARN? Otherwise it would be expected that he doesn't find any certificate matching the domain, since there's no issued with the CA you specified.

**Comment by kimxogus** [comment]
@the-technat Specifying `spec.tls.hosts` is irrelevant to this issue. It didn't work when I didn't specified that too.

Here are details.
I've set 2 acm arns for `--allowed-certificate-authority-arns`, ACM A and ACM B
- ACM A's domain
    - `*.a.domain`
    - `a.domain`
    - `*.b.domain`
    - `b.domain`
- ACM B's domain
    - `*.b.domain`
    - `b.domain`
    
And ingress,
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: sg-ids
    alb.ingress.kubernetes.io/subnets: subnet-ids
    alb.ingress.kubernetes.io/target-type: ip
  name: my-ingress
  namespace: my-ns
spec:
  ingressClassName: alb
  rules:
  - host: foo.a.domain
    http:
      paths:
      - backend:
          service:
            name: my-svc
            port:
              number: my-port
        path: /
        pathType: Prefix
```

Now I have an error log `"error":"ingress: my-ingress/my-ns: no certificate found for host: foo.a.domain`
