### ISSUE TITLE
nginx ingress controller service pending with aws loadbalancer controller

### ISSUE THREAD

**Issue by simonyerro** [kubernetes-sigs/aws-load-balancer-controller#3627]
**Describe the bug**
When I try to deploy nginx ingress controller after having an aws load balancer controller deployed, the ingress-nginx-controller service will stay in pending state

I get:
```
Warning | FailedBuildModel | Failed build model due to unable to resolve at least one subnet (0 match VPC and tags: [kubernetes.io/role/internal-elb])
```
the warning disappear when I set: `EnableServiceController: false` on the aws loadbalancer controller
but the load balancer service from nginx will still be pending without any warning this time

If I try to deploy the nginx ingress controller alone or before the aws load balancer controller, the service is working fine.

**Steps to reproduce**
* Deploy an aws loadbalancer controller:
```
  - name: aws-load-balancer-controller
    namespace: kube-system
    chart: eks/aws-load-balancer-controller
    version: 1.7.1
    values:
      - clusterName: {{ .Values.clusterName }}
        region: {{ .Values.region }}
        vpcId: {{ .Values.vpcId }}
        serviceAccount:
          create: false
          name: aws-load-balancer-controller
        defaultTags:
          managedBy: helm/charts/aws-load-balancer-controller
          VantaNoAlert: {{ .Values.env }} alb managed by EKS
```
* Deploy an nginx ingress controller
```
- name: ingress-nginx
    namespace: addons
    chart: ingress-nginx/ingress-nginx
    version: 4.10.0
    values:
      - controller:
          replicaCount: 1
          service:
            externalTrafficPolicy: "Local"
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
```

**Expected outcome**
The nginx ingress controller service shouldn't be in pending state

**Environment**

* AWS Load Balancer controller version 2.7.1 (with helm chart version 1.7.1)
* Kubernetes version 1.29
* Using EKS (yes/no), if so version? v1.29.1-eks-508b6b3

**Additional Context**:
