### ISSUE TITLE
question: 

### ISSUE THREAD

**Issue by kylebisley** [kubernetes-sigs/aws-load-balancer-controller#3632]
Hey All, 
Asking here hoping someone can at least point me where to start. 
I'm using `aws-load-balancer-controller` to provision a `NLB service `that is directing traffic at `nginx `inside my cluster. This has been necessitated by some client architectural oddities I'll not go into (Normally I'd just use an `ALB `and be on my way)

The `NLB `needs to listen on two specific ports with `HTTP `(the firewalls forward my traffic on non-standard ports) lets call the ports `7777 `and `7778`. I cannot figure out how to get the `aws-load-balancer-controller` to provision listeners on those non-standard ports. I've tested it creating them manually and it works as intended but the `7777 `and `7778` listeners get removed by the `ALB `eventually.

With an ALB I'd use the annotation [alb.ingress.kubernetes.io/listen-ports](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/guide/ingress/annotations/) but I can't find a similar annotation or configuration option in the NLB/service [documentation](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/guide/service/annotations/).

I'm close to abandoning the aws-load-balancer-controller at this point but frankly would struggle with how to get my traffic into my pods without its special sauce. 

Any direction on this would be very much appreciated. 

I'd happily create an update for the docs to codify this guidance if it's thought to be appropriate. Would love to save someone else my troubles.

**Comment by shraddhabang** [comment]
Hello @kylebisley ,

Have tried using this configuration to expose [multiple ports](https://kubernetes.io/docs/concepts/services-networking/service/#multi-port-services) for your service on NLB
```
apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external 
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
  namespace: my-namespace
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - name: http
      port: 80
      targetPort: 7777
    - name: https
      port: 443
      targetPort: 7778
```
