### ISSUE TITLE
No rules attached to the security group  

### ISSUE THREAD

**Issue by dev-travelex** [kubernetes-sigs/aws-load-balancer-controller#3652]
**Describe the bug**
I am using Terraform + Helm to deploy applications to EKS Fargate. Below are my `ingress` values. The load balancer gets created and targets are reporting healthy. However, the application url gives 504 as there's no inbound rule for port 443 created to allow incoming traffic. The HTTPS:443 in listener shows `unreachable`.
I have even added `alb.ingress.kubernetes.io/inbound-cidrs: 0.0.0.0/0`, but that didn't create the rule either.

```
ingress:
  className: "alb"
  defaultBackend:
    service:
      name: bliss-app
      port:
        number: 8443
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/group.name: ${target_infra}
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "60"
    alb.ingress.kubernetes.io/healthcheck-path: "/BankNotesWeb/css/menu.css"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/inbound-cidrs: 0.0.0.0/0
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/success-codes: 200-499
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.order: "0"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/certificate-arn: ${acm_arn}
  finalizers:
    - group.ingress.k8s.aws/${app_env}    
```

**Steps to reproduce**
Run a Java Tomcat web application behind the load balancer created by the ingress controller using the above ingress details.
 
**Expected outcome**
The inbound rule should be open to 0.0.0.0/0 for port 443.

**Environment**

* AWS Load Balancer controller version : v2.7.0 
* Kubernetes version : 1.28
* Using EKS (yes/no), if so version? Yes, eks.11
