### ISSUE TITLE
TargetGroupBinding using port instead of nodePort when service is of type NodePort

### ISSUE THREAD

**Issue by joelmarty** [kubernetes-sigs/aws-load-balancer-controller#3689]
**Describe the bug**
On one hand I have an ALB with a target group of type `instance` for the port 30081.

On the other hand I have a `NodePort` service defined as follows:
```yaml
metadata:
  name: my-service
spec:
  ports:
    - name: http-port
      nodePort: 30081
      port: 1080
      targetPort: 1080
  type: NodePort
```

And I am using the following `TargetGroupBinding` to connect both:
```yaml
spec:
  serviceRef:
    name: my-service
    port: 30081
  targetGroupARN: <my-arn>
  targetType: instance
```

The TargetGroupBinding resource produces an event "backend not found: unable to find port 30081 on service my-service" and the targets are not registered.

**Steps to reproduce**
See previous section

**Expected outcome**
Since the service is of type "NodePort", then the controller should use the service's nodePort and successfully reconcile state.

**Environment**

* AWS Load Balancer controller version: 2.6.1
* Kubernetes version: 1.24.17-eks-0766bb9
* Using EKS (yes), if so version? 

**Additional Context**:

The documentation is not clear on how nodeport services should be registered and that "requirement" is not visible anywhere. I am assuming it is a bug because of that: either in the controller or in the doc.

**Comment by wweiwei-li** [comment]
Hey, the port used in serviceRef should be the port of the service. So in your case,  you should set the service port as 3081
Example of how it works. 

```
---
# App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace:  your-namespace
  name: your-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: your-app
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: your-app
    spec:
      containers:
        - image: # app image
          imagePullPolicy: Always
          name: your-app
          ports:
            - containerPort: 3081
---
# Service
apiVersion: v1
kind: Service
metadata:
  namespace:  your-namespace
  name: your-service
spec:
  ports:
    - port: 3081
      targetPort: 3081
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: your-app
---
# TargetGroupBinding
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: your-targetgroupbinding
  namespace: your-namespace
spec:
  serviceRef:
    name: your-service
    port: 3081
  targetGroupARN: ARN of your instance TG with port 3081
```

**Comment by TBBle** [comment]
> I get that it is how it works, but shouldn't this requirement to have the same port for service's `port` and `nodePort` be documented somewhere ?

There's not a requirement that port and nodePort be the same, the requirement is that the `TargetGroupBinding.serviceRef.port` matches the `Service.ports.port`, so that the `TargetGroupBinding` can find the Service object. You don't need to hard-code the `nodePort` at all, as you can see in https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3689#issuecomment-2113697953. The AWS LB Controller will look up the current (specified or dynamically assigned) `nodePort` value if it needs to, although it's possible to set up the system so the NodePort is not needed at all, AFAIR.

i.e. in your original example, slightly modified
```yaml
metadata:
  name: my-service
spec:
  ports:
    - name: http-port
      nodePort: 30081
      port: 1080
      targetPort: 1090
  type: NodePort
```

the correct `TargetGroupBinding` port should be 1080, not 30081 or 1090. i.e.

```yaml
spec:
  serviceRef:
    name: my-service
    port: 1080
  targetGroupARN: <my-arn>
  targetType: instance
```

This is because the ServiceReference is used to _identify_ a given Service and a port in that service in order to fetch the details it needs (nodePort, port, depending on your network and NLB setup); it doesn't just blindly send traffic to that port number.

You could also use the port's name, if you prefer, both for easier readability, and to illustrate that this doing a lookup in the Service.

```yaml
spec:
  serviceRef:
    name: my-service
    port: http-port
  targetGroupARN: <my-arn>
  targetType: instance
```
