### ISSUE TITLE
External load balancer via targetGroupARN does not modify the security group to allow traffic from load balancer 

### ISSUE THREAD

**Issue by prakashbalaji** [kubernetes-sigs/aws-load-balancer-controller#3703]
**Describe the bug**
The pods are getting registered to the targetGroupARN specified correctly but the. security groups in the nodes are not adjusted to allow the traffic from the load balancer. Even specifically passing security group with ingress annotation is not helping. 

Is this an bug here? if this is not a bug what is the correct way to adjust the node security group to allow traffic from load balancer for external load balancer. 

**Steps to reproduce**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
            - containerPort: 80        
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-app
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /index.html    
spec:
  type: ClusterIP
  selector:
    app: nginx-app
  ports:
    - port: 80
      targetPort: 80
---

apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: nginx-manual-tg
spec:
  serviceRef:
    name: nginx-service
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-west-2:<AWS_ACCOUNT_ID>:targetgroup/nginx-manual-tg/<HASH>
```

**Expected outcome**
Should security group of node be adjusted to allow traffic from load balancer for external load balancer?

**Environment**

AWS Load Balancer controller version : v2.7.2
Kubernetes version v1.29.3-eks-adc7111
Using EKS (yes/no), if so version? yes - v1.29.3-eks-adc7111

**Additional Context**:

For cases when the load balancer is created by the controller, the node security groups are adjusted correctly to allow traffic from load balancer.
