### ISSUE TITLE
AWS LB Controller doesn't recognize remaining certificates as Listener Certificates for SNI

### ISSUE THREAD

**Issue by 3-commerce** [kubernetes-sigs/aws-load-balancer-controller#3720]
**Describe the bug**
I use Istio Ingress Gateway v1.21.2 in my EKS for ingress traffic. The aws load balancer version is v2.7.2.
I have 2 ACM certs in AWS Console and want to add the second cert as Listener Certificates for SNI in port 443. However, my second domain that paired for second cert is not recognizing the ssl.

**Steps to reproduce**

- Install Istio Gateway v1.21.2 via Istio Operator
- Install AWS LB Controller via helm chart v1.7.2 contains AWS lb controller v2.7.2
- And then setup serviceAnnotations on istio operator ingress gateway

```
serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
          service.beta.kubernetes.io/aws-load-balancer-scheme: internal
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-3:0123456789:certificate/abcd-1234-zzzz,arn:aws:acm:ap-southeast-3:0123456789:certificate/ghij-5678-jklm
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
          service.beta.kubernetes.io/aws-load-balancer-type: external
```

**Expected outcome**
The second certs in the stringList (arn:aws:acm:ap-southeast-3:0123456789:certificate/ghij-5678-jklm) should be registered as Listener certificates for SNI. I try to add manually via AWS Web Console and i can hit my domain with ssl paired correctly to SSL.

**Environment**

* AWS Load Balancer controller version v2.7.2
* Kubernetes version v1.29
* Using EKS (yes/no), if so version? EKS, v1.29

**Additional Context**:
I don't know if this is bug or should be new features. If this is considered a new feature the serviceAnnotations will be like;

```
...
service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-3:0123456789:certificate/abcd-1111-zzzz
service.beta.kubernetes.io/aws-load-balancer-ssl-cert-sni: arn:aws:acm:ap-southeast-3:0123456789:certificate/ghij-2222-jklm, arn:aws:acm:ap-southeast-3:0123456789:certificate/uiop-3333-zzzz,arn:aws:acm:ap-southeast-3:0123456789:certificate/qwer-3333-jjjj
...
```
