### ISSUE TITLE
Cannot set the IPv6 addresses in dualstack mode during modification

### ISSUE THREAD

**Issue by witalisoft** [kubernetes-sigs/aws-load-balancer-controller#3743]
**Describe the bug**

Changing the IP Address Type to `dualstack` (via annotation `service.beta.kubernetes.io/aws-load-balancer-ip-address-type`) with a provided list of IPv6 addresses (via annotation `service.beta.kubernetes.io/aws-load-balancer-ipv6-addresses`) is not being reflected (still using the randomly selected IP from IPv6 range). AWS Console gives the option to specify the IPv6 address.  Creating instead of modifying the LoadBalancer, which works as expected.

**Steps to reproduce**

Initial Kubernetes service specification:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: test
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
  name: test
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app.kubernetes.io/name: kubernetes-ingress
  type: LoadBalancer
```

Migration to `dualstack` mode with specified IPv6 addresses

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: dualstack
    service.beta.kubernetes.io/aws-load-balancer-ipv6-addresses: <list of IPv6 addresses>
    service.beta.kubernetes.io/aws-load-balancer-name: test
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
  name: test
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app.kubernetes.io/name: kubernetes-ingress
  type: LoadBalancer
```

**Expected outcome**

IPv6 addresses specified in annotation `service.beta.kubernetes.io/aws-load-balancer-ipv6-addresses` should be taken in a `dualstack` mode.

**Environment**

* AWS Load Balancer controller version

2.8.0

* Kubernetes version

v1.27

* Using EKS (yes/no), if so version?

v1.27.13-eks-3af4770

**Additional Context**:

I haven't found any references during the update process to make it possible - https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/deploy/elbv2/load_balancer_manager.go#L88
