### ISSUE TITLE
Helm: explicitly add envFrom to the deployment template

### ISSUE THREAD

**Issue by huonguyenlt** [kubernetes-sigs/aws-load-balancer-controller#3768]
**Problem**
To add an environment variable by config map or secret, I must write the key `envFrom` twice in the `values.yaml `file. 
For example
```
envFrom:
    envFrom:
        - secretRef:
             name: my-secret
```
Also, the example provided in the `values.yaml `file is not correct. If use `valueFrom`, we need to 1. give the variable `name` and 2. give the `key` to choose a specific variable from the configmap. Example:
```
env:
        # Define the environment variable
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: special-config
              # Specify the key associated with the value
              key: special.how
```

**Suggested Solution**
Update the helm template so the user only writes the `envFrom` key one. 
Update the example in the `values.yaml `file
