### ISSUE TITLE
[Question] Manually set a rule in the ALB

### ISSUE THREAD

**Issue by RobinFrcd** [kubernetes-sigs/aws-load-balancer-controller#3782]
Hi,
I'd like to manually add a rule to an ALB managed by the controller. I've seen related issues like https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3763, but not sure about the conclusion.
Is there a way, with tags or something else, to ask the controller **not to delete a rule I've created manually**. I have a service running outside EKS, on an EC2 instance, that I want to expose through the ALB.

Thank you very much !

**Comment by wweiwei-li** [comment]
Our controller by design will delete resources you created manually. We will suggest not doing manual modification on it.

**Comment by wweiwei-li** [comment]
Same issue ad :  https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3763

**Comment by MartinEmrich** [comment]
@RobinFrcd you can have aws-load-balancer-controller create the rule for you, like this:

````
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ec2-service
  annotations:
    alb.ingress.kubernetes.io/group.name: whatever
    alb.ingress.kubernetes.io/group.order: "123"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.forward-my-ec2: >
      {"type":"forward","targetGroupARN": "<arn-of-your-targetgroup>"}
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: "8000" # whatever
    alb.ingress.kubernetes.io/healthcheck-path: "/" # whatever
    alb.ingress.kubernetes.io/success-codes: "200"
spec:
  ingressClassName: alb
  rules:
    http:
      paths:
      - path: /my-service-on-ec2-whatever
        pathType: Prefix
        backend:
          service:
            name: forward-my-ec2
            port:
              name: use-annotation
````
