### ISSUE TITLE
[Feature Request] Need re-writing path

### ISSUE THREAD

**Issue by kworkbee** [kubernetes-sigs/aws-load-balancer-controller#3793]
As with the rewrite-target annotation of NGINX Ingress, I ask you to add annotation and related features to enable Path Rewrite.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-example
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-one
              port:
                number: 80
        - path: /something(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: service-two
              port:
                number: 80
```
