### ISSUE TITLE
How to add additional ACM certificate in separate Ressource?

### ISSUE THREAD

**Issue by MartinEmrich** [kubernetes-sigs/aws-load-balancer-controller#3815]
I would like to add additional ACM certificates to an existing ingress group, without editing an existing ressource (which might reside in a different namespace)

Intuitively, I should be able to add an Ingress without any rules, just adding the annotation to be merged in:

````
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: just-another-certificate
  annotations:
    alb.ingress.kubernetes.io/group.name: my-existing-ingress-group
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:000000000000:certificate/1234-5678-1234-5678-1234567890whatever
spec:
  ingressClassName: alb
  rules: []
````
Sadly, a Kubernetes Ingress object must have either a rule or a defaultBackend: https://github.com/kubernetes/kubernetes/issues/82203

My current workaround is to add a dummy rule (fixed response on an unlikely path), but this consumes one rule on the ALB.

Is there a better way I happen to have missed?
