### ISSUE TITLE
Error: unknown field "spec.certificateArn" on 2.8.2

### ISSUE THREAD

**Issue by moody-visaops** [kubernetes-sigs/aws-load-balancer-controller#3837]
**Describe the bug**
Using the spec.certificateArn in IngressClassParams results in:
```
error: unknown field "spec.certificateArn"
```

**Steps to reproduce**
Using version 2.8.2 of the alb controller. Create IngressClass and IngressClassParams with:
```
apiVersion: elbv2.k8s.aws/v1beta1
kind: IngressClassParams
metadata:
    name: alb
spec:
  scheme: internet-facing
  inboundCIDRs:
    - "XXXX/32"
  subnets:
    tags:
      VPC: 
        - "X"
  certificateArn: "XXXX"
  loadBalancerAttributes:
    - key: deletion_protection.enabled
      value: "true"
    - key: idle_timeout.timeout_seconds
      value: "3600"
    - key: access_logs.s3.enabled
      value: "true"
    - key: access_logs.s3.bucket
      value: "bucket"
```

**Expected outcome**
Using spec.certificateArn replaces the need for using the annotiation alb.ingress.kubernetes.io/certificate-arn

**Environment**

* AWS Load Balancer controller version - 2.8.2
* Kubernetes version - 1.29
* Using EKS (yes/no), if so version? yes 1.29

**Additional Context**:
