### ISSUE TITLE
Target Group Unhealthy Due to Redirect to /login?redirect=%2F - How to Set Separate Health Check Paths?

### ISSUE THREAD

**Issue by vrathore18** [kubernetes-sigs/aws-load-balancer-controller#3846]
I am using the AWS ALB Ingress controller in my EKS setup, and one of my target groups is marked as unhealthy. The reason is that when users hit the URL {{ .Values.domainName }}, they are redirected to /login?redirect=%2F, which causes the ALB health checks to fail with a 302 redirect response.

Below is the part of my Ingress configuration:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "drafter.frontend.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingressScheme }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.eks_cluster }}
    alb.ingress.kubernetes.io/actions.redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.external.ACM_CERTIFICATE_ARN }},{{ .Values.external.ANONYMISER_CERTIFICATE_ARN }},{{ .Values.external.DRAFTER_CERTIFICATE_ARN }}"
    alb.ingress.kubernetes.io/inbound-cidrs: {{ .Values.ipWhiteList }}
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  rules:
    - host: {{ .Values.domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "drafter.frontend.fullname" . }}
                port:
                  number: 4200
    - host: l.{{ .Values.domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "drafter.frontend-logger.fullname" . }}
                port:
                  number: 80
    - host: auth.{{ .Values.domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "drafter.genieauth.fullname" . }}
                port:
                  number: 80
    - host: auth.{{ .Values.anonymiser_domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "drafter.genieauth.fullname" . }}
                port:
                  number: 80
    - host: b.{{ .Values.domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "drafter.graphql-gateway.fullname" . }}
                port:
                  number: 80
    {{- if or (eq .Values.env_name "qa") (eq .Values.env_name "trialco") (eq .Values.env_name "app") }}
    - host: static.{{ .Values.domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "drafter.graphql-gateway.fullname" . }}
                port:
                  number: 80
    {{- end }}
```
The unhealthy target group corresponds to the following rule:

```
    - host: {{ .Values.domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "drafter.frontend.fullname" . }}
                port:
                  number: 4200
```
Problem:
The target group health checks fail because they receive a 302 redirect to /login?redirect=%2F, which doesn't return a 200 OK response. I understand that AWS ALB doesn't support different health check paths for each rule in a single Ingress.

Question:
How can I resolve this issue and make the target group healthy?
Is there a way to configure different health check paths for each rule within the same Ingress, or do I need to split the Ingress into separate resources for each service? What’s the best approach to handle this scenario?
Thanks!
