### ISSUE TITLE
Support reading headers values from Secrets 

### ISSUE THREAD

**Issue by ivanfoo** [kubernetes-sigs/aws-load-balancer-controller#3852]
**Is your feature request related to a problem?**
We  need to configure rule conditions based on specific Header values. However, these values can contain sensitive data so we don't want them to end up visible in plain text in the Ingress annotations. Example:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: any-namespace
  name: any-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/conditions.sensible-headers: >
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "AnySensibleHeader", "values":["AnySensibleValue"]}}]

```

**Describe the solution you'd like**
Add support to reading header values from kubernetes Secrets as it's done to configure the clientID and clientSecret when using OIDC authentication.

```yaml
alb.ingress.kubernetes.io/conditions.sensible-headers: >
  [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "AnySensibleHeader", "values":["secret://any-secret/any-key"]}}]
```

**Describe alternatives you've considered**
Load header values from AWS Services like ParameterStore or SecretsManager
