### ISSUE TITLE
Create rule and condition for http port 80 listener only

### ISSUE THREAD

**Issue by umarizulkifli** [kubernetes-sigs/aws-load-balancer-controller#3883]
**Describe the bug**
When ever I try to add rule and condition only for port 80 listener it get apply to port 443 listener too

**Steps to reproduce**

**Expected outcome**
Rule and condition apply only for port 80 not on port 443

**Environment**

* AWS Load Balancer controller version 2.8.1
* Kubernetes version 1.29
* Using EKS (yes), if so version? EKS 1.29 

**Additional Context**:
I want to add rule on port 80 listener to mitigate host header injection
I can add the rules via console but it will be deleted because it is not created by aws load balancer controller

<img width="1304" alt="image" src="https://github.com/user-attachments/assets/3fdc9360-d1d6-4039-8bbb-7b7935f67ec9">

Below is my ingress manifest

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ambassador-l7
  namespace: ambassador
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:338771224436:certificate/1e6a1d99-c7e9-498c-80e8-320ff593b983
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/healthcheck-path: "/ambassador/v0/check_alive"
    alb.ingress.kubernetes.io/healthcheck-port: "healthcheck"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/actions.host-header: >
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"301","messageBody":"Moved Permanently","responseParameters":{"headers":{"Location":"https://$host$request_uri"}}}}
    alb.ingress.kubernetes.io/actions.default: >
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"404","messageBody":"Not Found"}}
spec:
  rules:
    - host: "*.favex.io"
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: host-header
                port:
                  number: 80
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: ambassador-aws-alb-l7
                port:
                  number: 443
  defaultBackend:
    service:
      name: default
      port:
        number: 80
```
This is what aws load balancer controller created from the manifest 
port 80
<img width="1304" alt="image" src="https://github.com/user-attachments/assets/403d377f-236a-4205-bf8e-b16e7c832b90">

port 443
<img width="1304" alt="image" src="https://github.com/user-attachments/assets/898b233d-fc70-4618-8e9a-a080c1298216">
