### ISSUE TITLE
The certificate must have a fully-qualified domain name, a supported signature, and a supported key size.

### ISSUE THREAD

**Issue by uriworkaccount** [kubernetes-sigs/aws-load-balancer-controller#3890]
**Describe the bug**
I am trying to set up NLB with aws-load-balancer-controller in a private subnet.
I did so in my dev account, i tried to do the same in a prod account, but i received errors:
first of all, after tagging the relevant subnets as required (kubernetes.io/role/internal-elb=1, see picture) , it still didn't work, i got the error:
failed build model due to unable to resolve at least one subnet (0 match VPC and tags: [kubernetes.io/role/internal-elb])
so i had to manually register the subnets (see yaml), after which everything was ok.

after that, I tried to add a valid certificate, but i get the error:
The certificate must have a fully-qualified domain name, a supported signature, and a supported key size.

additionally, when recreating the resources, i had to manually delete some, as they weren't all deleted on helm uninstall.

please help.

**Steps to reproduce**

helm install, filled in the eks name.
this is the yaml for the nlb service:
```
apiVersion: v1
kind: Service
metadata:
  name: nlb-service
  namespace: ingress-controller
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"  # or "ip" for IP mode
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-subnets: xxx, xxx
    service.beta.kubernetes.io/aws-load-balancer-name: xxxx
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <arn>

spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
    #app.kubernetes.io/component: controller


```

this is the certificate:
![image](https://github.com/user-attachments/assets/ae9330d8-5a2f-4cc1-aa82-34977ed24977)

this is the listener, due take note that i can't manually add a certificate or choose a security policy.

![image](https://github.com/user-attachments/assets/cfd8fa15-801a-4719-8c8c-01b923f3304c)

these are the tags for the subnets
![image](https://github.com/user-attachments/assets/8e9d86bb-800c-41d3-8842-985b0a36c512)

screen pictures of errors:
![image](https://github.com/user-attachments/assets/d2bdc99d-106d-444c-aa47-ae458941e4f0)
![image](https://github.com/user-attachments/assets/3c0cb0f1-3546-497d-8724-d081c3613330)

**Expected outcome**
create nlb

**Environment**

* AWS Load Balancer controller version - 1.8.1
* Kubernetes version - 1.30
* Using EKS (yes/no), if so version? yes, 1.30
**Additional Context**:
