### ISSUE TITLE
Controller failed to create TargetGroup when alb.ingress.kubernetes.io/multi-cluster-target-group is "true"

### ISSUE THREAD

**Issue by pwouavre** [kubernetes-sigs/aws-load-balancer-controller#3969]
**Describe the bug**
Controller fail to create TargetGroup because of 'port' parameter set to 0 instead of 1
Controller Error : 

```json
{
  "level": "error",
  "ts": "2024-12-05T12:26:53Z",
  "msg": "Reconciler error",
  "controller": "ingress",
  "object": {
    "name": "whoami2-app",
    "namespace": "whoami"
  },
  "namespace": "whoami",
  "name": "whoami2-app",
  "reconcileID": "038cda24-09de-4ffd-b154-cbe479f25cec",
  "error": "operation error Elastic Load Balancing v2: CreateTargetGroup, https response error StatusCode: 400, RequestID: 1e0cda0a-5cc6-4674-82f0-abda792105cb, api error ValidationError: 1 validation error detected: Value '0' at 'port' failed to satisfy constraint: Member must have value greater than or equal to 1"
}
```

**Steps to reproduce**
- deploy chart aws-load-balancer-controller v1.10.1 (image app: public.ecr.aws/eks/aws-load-balancer-controller:v2.10.1)
- deploy a service in your cluster, type ClusterIP 
- deploy ingress referencing previously created service and using specific annotations : 

```yaml
apiVersion: networking.k8s.io/v1  
kind: Ingress  
metadata:  
  name: whoami2-app
  namespace: whoami
  annotations:
    alb.ingress.kubernetes.io/multi-cluster-target-group: "true"    
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/tags: Application=blue-green,Environment=DEV,terraform-aws-modules=alb
spec:
  ingressClassName: alb
  rules:
    - host: whoami2-app.663575844070.eu.aws.airliquide.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami2-app
                port:
                  number: 80
```

**Expected outcome**
Specific AWS Target Group is being created (linked CRD TargetGroupbinding should exist in cluster)

**Environment**

* AWS Load Balancer controller version: v2.10.1
* Kubernetes version : 1.31
* Using EKS (yes/no), if so version? yes

**Additional Context**:
I'm following documentation here (following https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/use_cases/multi_cluster/)
