### ISSUE TITLE
TargetGroupBinding can't be created when using Pod-Identity

### ISSUE THREAD

**Issue by ShadeCormac** [kubernetes-sigs/aws-load-balancer-controller#3972]
**Describe the bug**
As title, i'm running AWS Load balancer controller with Pod Identity, instead of IRSA and OIDC provider.
When i tried to apply a TGB, an error response returned: `error when creating "elb_target_group_binding.yaml": Internal error occurred: failed calling webhook "mtargetgroupbinding.elbv2.k8s.aws": failed to call webhook: Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding?timeout=10s"`

**Steps to reproduce**
- Create an EKS cluster
- Create an external application load balancer with provisioned listen rule and target group
- Install Pod identity addons
- Apply aws-load-balancer-controller helm chart with values:
```
clusterName: <CLUSTER_NAME>
serviceAccount:
  name: aws-load-balancer-controller
region: us-east-1
vpcId: <VPC_ID>
enableServiceMutatorWebhook: false
replicaCount: 1
hostNetwork: true
```
- Apply target group binding:
```
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: api-gateway
spec:
  serviceRef:
    name: api-gateway
    port: 30000
  targetGroupARN: <target group ARN>
  targetType: instance
  vpcID: <VPC_ID>

```

**Expected outcome**
Target Group Binding created and bind to the correct ALB / target group.

**Environment**
- aws-load-balancer-controller chart version: 1.10.1
- pod-identity addon version: v1.3.4-eksbuild.1
- CNI: AWS-VPC CNI

* AWS Load Balancer controller version: v2.10.1
* Kubernetes version: v1.30.6-eks-7f9249a
* Using EKS (yes/no), if so version? v1.30

**Additional Context**:
- The pod identity works as intended, as i deployed VPC CNI and cluster autsoscaler with Pod identity successfully.
