### ISSUE TITLE
Question about tagging listeners rules in ALB

### ISSUE THREAD

**Issue by fabgaubert** [kubernetes-sigs/aws-load-balancer-controller#3973]
Hi,

Is it possible to add tags directly to ALB listeners rules instead of the ALB or its listeners?
I need to assign a unique tag to each rule created within the ALB.

Thank you in advance for your help.

Best regards,

**Comment by shraddhabang** [comment]
Hello @fabgaubert , Unfortunately we currently don't support tagging each rule with unique tags yet. We will mark this as feature request. This can be a good first issue. We welcome any community contributions for this.

**Comment by omerap12** [comment]
> Hello @fabgaubert , Unfortunately we currently don't support tagging each rule with unique tags yet. We will mark this as feature request. This can be a good first issue. We welcome any community contributions for this.

To clarify, I’m considering adding a new annotation for this purpose since the rules field in the Ingress API spec is part of Kubernetes’ core API and can’t be modified directly to include custom fields. Here's an example of what I have in mind:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/rule-tags: |
      {
        "example.com:/api": {
          "team": "backend",
          "cost-center": "123"
        },
        "/docs": {
          "team": "docs",
          "cost-center": "456"
        }
      }
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-svc
                port:
                  number: 80
    - http:
        paths:
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: docs-svc
                port:
                  number: 80
```
what do you think?
