### ISSUE TITLE
Modify listener attributes to apply security headers

### ISSUE THREAD

**Issue by arakakivl** [kubernetes-sigs/aws-load-balancer-controller#3986]
Hi,

AWS recently featured [HTTP header modification](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/header-modification.html), which allows the modification of request or response headers, including renaming them, inserting security headers and even disabling ones. Unfortunately, in the [AWS Load Balancer Controller docs](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.11/), I couldn't find any annotation for applying any of the security headers -- is this even supported? Well, because of that, I would like to know if there's any way to apply them using the AWS Load Balancer Controller annotations.

I already tried the following annotations:
```
alb.ingress.kubernetes.io/listener-attributes.http.80: |
  headers.Strict-Transport-Security.value="max-age=31536000; includeSubDomains",
  headers.X-Content-Type-Options.value="nosniff",
  headers.X-Frame-Options.value="SAMEORIGIN",
  headers.X-XSS-Protection.value="1; mode=block"
```
```
alb.ingress.kubernetes.io/listener-attributes.http.80: routing.http.response.strict_transport_security.header_value="31536000;includeSubdomains;preload;"
```

**Comment by zac-nixon** [comment]
This is a duplicate of https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3962

**Comment by arakakivl** [comment]
> This is a duplicate of #3962

I appreciate the response. Adding the second annotation in addition to this is enough?

**Comment by kielby** [comment]
Does it also work for renaming headers?

**Comment by arakakivl** [comment]
I added the following annotations:
```
alb.ingress.kubernetes.io/listener-attributes.HTTPS-443: |
  routing.http.response.server.enabled=true
  routing.http.response.strict_transport_security.header_value="31536000;includeSubdomains;preload;"
```

It didn't worked as expected. Am I missing something?

**Comment by stem-ui** [comment]
I'm having the same issue, and also tried specifying the HSTS header through `alb.ingress.kubernetes.io/load-balancer-attributes`.

```
Warning  FailedDeployModel  1s  ingress  Failed deploy model due to ValidationError: Load balancer attribute key 'routing.http.response.strict_transport_security.header_value' is not recognized
```

**Comment by stem-ui** [comment]
@arakakivl if you got this working can you please share?

**Comment by arakakivl** [comment]
> [@arakakivl](https://github.com/arakakivl) if you got this working can you please share?

Could make it work with the following syntax:
```
alb.ingress.kubernetes.io/listener-attributes.HTTPS-443: routing.http.response.strict_transport_security.header_value=max-age=31536000;includeSubdomains;preload;,
  routing.http.response.x_content_type_options.header_value=nosniff,
  routing.http.response.content_security_policy.header_value=frame-ancestors 'none',
  routing.http.response.x_frame_options.header_value=SAMEORIGIN
```

Basically:
```
alb.ingress.kubernetes.io/listener-attributes.HTTPS-443: routing.http.response.security_header_1_in_this_format=value_of_it, routing.http.response.security_header_2_in_this_format=value_of_it
```

**Comment by casey-robertson-paypal** [comment]
The attribute list is here: https://docs.aws.amazon.com/cli/latest/reference/elbv2/modify-listener-attributes.html

**Comment by stem-ui** [comment]
Thanks @casey-robertson-paypal and @arakakivl - it turned out we were not running a new enough version of the controller.

**Comment by arakakivl** [comment]
People, I am having the following issue now: in a specific IP address of my ALB, the response headers are not being returned. Only in the two other IPs these response headers are returned.

Anyone w/ the same problem?

**Comment by colin-byrne-1** [comment]
> People, I am having the following issue now: in a specific IP address of my ALB, the response headers are not being returned. Only in the two other IPs these response headers are returned.
> 
> Any suggestions?

If that's the case, I'd imagine it's a bug with ALB, not aws-load-balancer-controller. Try setting it through the console and see if the issue persists.

**Comment by FernandoMiguel** [comment]
anyone implemented this and got:
```
* Request completely sent off
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/2 404
< date: Mon, 17 Mar 2025 14:28:42 GMT
< content-type: text/html; charset=utf-8
< content-length: 53
* Illegal STS header skipped
< strict-transport-security: 600
```
?

searching for `Illegal STS header skipped` has not turned up anything

**Comment by rhyek** [comment]
I'm trying to add the hsts response header, however I'm not seeing it added in AWS console.
The pod container is running v2.13.0:

`kubectl describe deployment/aws-load-balancer-controller -n kube-system`
```
Containers:
 aws-load-balancer-controller:
  Image:       public.ecr.aws/eks/aws-load-balancer-controller:v2.13.0
```
My ingress yaml:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: alb-ingress
  annotations:
    alb.ingress.kubernetes.io/group.name: my-default
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.certificateArn }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.wafV2WebAclArn }}
    alb.ingress.kubernetes.io/tags: IngressGenerated=true
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=300
    # enable hsts
    alb.ingress.kubernetes.io/listener-attributes.HTTPS-443: routing.http.response.strict_transport_security.header_value="31536000;includeSubdomains;preload;"
spec:
  ingressClassName: alb
...
```
Am I missing something? Thanks.

**Comment by rrachev** [comment]
Hi all,

Could someone assist me how to set the HSTS via this annotation? I tried following variants but without success:

`      alb.ingress.kubernetes.io/listener-attributes.HTTPS-443: routing.http.response.strict_transport_security.header_value=max-age="31536000;includeSubdomains;"

      alb.ingress.kubernetes.io/listener-attributes.HTTPS-443: "routing.http.response.strict_transport_security.header_value=max-age=31536000;includeSubdomains;"

      alb.ingress.kubernetes.io/listener-attributes.HTTPS-443: routing.http.response.strict_transport_security.header_value=max-age="31536000;includeSubdomains;

`
Because I am using the EKS automode I am do not know how to reach the logs.

**Comment by FernandoMiguel** [comment]
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.internal.ingress.certificateArn }}
    alb.ingress.kubernetes.io/listener-attributes.HTTPS-443: routing.http.response.strict_transport_security.header_value=max-age=60
[...]
```
@rrachev 
the logs should come from your AWS LBC controller
