### ISSUE TITLE
Nginx attributes for connecting with AWS NLB not being applied to NLB instance

### ISSUE THREAD

**Issue by Timotej979** [kubernetes-sigs/aws-load-balancer-controller#3991]
Hello :smile: 

currently I'm facing an issue regarding applying the helm chart values of a ingress-nginx controller connected to the AWS NLB using service annotations in EKS. My current values.yaml file for the nginx-ingress look like this:

```yaml
controller:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-attributes: |
        load_balancing.cross_zone.enabled=true,
        deletion_protection.enabled=true

  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  admissionWebhooks:
    createSecretJob:
      resources:
        limits:
          cpu: "100m"
          memory: "64Mi"
        requests:
          cpu: "100m"
          memory: "64Mi"
    patchWebhookJob:
      resources:
        limits:
          cpu: "100m"
          memory: "64Mi"
        requests:
          cpu: "100m"
          memory: "64Mi"
```

They look correct to me from outside, however on the `terraform apply` command of a helm release with this values the load balancer fails to enable cross zone load balancing, I managed to overcome this using an alternative annotation which still works apparently, even thou in the latest docs it is said to be deprecated. Link to the annotation: [service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.11/guide/service/annotations/#deprecated-attributes)

The issue I am specifically having is the deletion protection argument/annotation, which I would really like to have on the infrastructure.

I'm using an EKS cluster version 1.30.
Latest ingress nginx helm chart version from: https://kubernetes.github.io/ingress-nginx.

Any help would be much appreciated, even thou it seems like a really simple issue :sweat_smile:
