### ISSUE TITLE
--default-tags is overriding tags set in Ingress annotations

### ISSUE THREAD

**Issue by bytemux** [kubernetes-sigs/aws-load-balancer-controller#4005]
**Describe the bug**
--default-tags is overriding tags set in Ingress annotations

The same behaviour is reported in https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/187#issuecomment-2361414179

**Steps to reproduce**
1. Set defaultTags for aws-load-balancer-controller:
```
--default-tags=Tag1=default
```

2. Create Ingress with
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/tags: Tag1=fromannotation,Tag2=foobar
```

**Expected outcome**
ALB has tags: Tag1=fromannotation,Tag2=foobar

**Actual outcome**
ALB has tags: Tag1=default,Tag2=foobar

**Environment**

* AWS Load Balancer controller version public.ecr.aws/eks/aws-load-balancer-controller:v2.8.1
* Kubernetes version 1.30
* Using EKS (yes/no), if so version? Yes, 1.30
