### ISSUE TITLE
NLB PodReadinessGate instability

### ISSUE THREAD

**Issue by ajax-suprun-r** [kubernetes-sigs/aws-load-balancer-controller#4034]
**Describe the bug**
A concise description of what the bug is.

We are using Argo Rollout canary strategy with NLB operated on Service level, during deployment of new version first pod is missing readiness gate, second one that schedules in the same service does have readiness gate. Looks like ALB controller misses injection for the first pod.

On the screenshot you can see that the first(older) pod goes without readiness gate, next one does have readiness gate. 
![Image](https://github.com/user-attachments/assets/17146f4d-5158-4cdc-bd9b-77eb9c67f788)

**Steps to reproduce**

1. Use ArgoCD and Argo Rollouts as delivery system.
2. Use 2 replicas 
3. Configure  canary strategy with:
```
steps:
  - setWeight: 50
  - pause:
      duration: 30s
  - setWeight: 100
```
4. Make some deployment with changing app version
5. Monitor pod readiness gate status with: `kubectl get pod -l 'app.kubernetes.io/name=<app_name>' -o wide -n <namespace>`

**Expected outcome**
A concise description of what you expected to happen.
Readiness gate applies to first pod during rollout process.

**Environment**

Services types are: `LoadBalancer`

Annotations and ports configuration:

![Image](https://github.com/user-attachments/assets/6f836a76-b2f1-4add-a576-12f4550935f1)

As a result: 2 loadbalancers are being created, 2 services and 6 target group bindings

* AWS Load Balancer controller version: 2.10.1
* Kubernetes version: 1.31
* Using EKS (yes/no), if so version? eks.16

**Additional Context**:

**Comment by zac-nixon** [comment]
What is the order in which you create the deployment / (service or ingress)?

Basically, if you create the deployment first, then your initial pods could come up with no readiness gates as at creation time they were not associated to a Load Balancer. If you create the ingress or service then create the deployment then when your pods are created they are already associated to the load balancer and hence will have readiness gates attached.

These are the scenarios I tested with an NLB:

The initial pods came up with no readiness check.
1. Create deployment.
2. Create SVC that references the deployment.

The initial pods came up with a readiness check
1. Create SVC that references that deployment in (2)
2. Create deployment.

**Comment by zac-nixon** [comment]
I think I see the issue, and it relates to how Kubernetes handles eventually consistency.

I can repro the same behavior:
```
  kubectl create namespace nlb-game-2048-5
  kubectl label namespace nlb-game-2048-5 elbv2.k8s.aws/pod-readiness-gate-inject=enabled
  kubectl apply -f /tmp/svc.yaml
  kubectl apply -f /tmp/rs.yaml
```

svc.yaml
```
apiVersion: v1
kind: Service
metadata:
  namespace: nlb-game-2048-5
  name: repro
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  selector:
    tier: frontend
```

rs.yaml
```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: repro
  namespace: nlb-game-2048-5
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: public.ecr.aws/l6m2t8p7/docker-2048:latest
```

The pods come up with no readiness gates attached.


The issue is because of eventual consistency within Kubernetes and the LBC. I was able to solve this issue by adding a sleep between each command, to ensure the LBC has a correctly warmed cache before processing each operation.

```
  kubectl create namespace nlb-game-2048-5
  sleep 5
  kubectl label namespace nlb-game-2048-5 elbv2.k8s.aws/pod-readiness-gate-inject=enabled
  sleep 5
  kubectl apply -f /tmp/svc.yaml
  sleep 5
  kubectl apply -f /tmp/rs.yaml
```

I know it's not a great solution but there is some pretty serious architectural limitations at play. Can you try with some time between each of the operations?
```
