### ISSUE TITLE
ALB Listener attributes - conflict between controller and API due to data type

### ISSUE THREAD

**Issue by JoseAlvarezSonos** [kubernetes-sigs/aws-load-balancer-controller#4092]
We are trying to use the [ALB header modification](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/header-modification.html). We are specially interested in adding CORS headers since we are doing a migration from a "central gateway" for couple of services to individual ALBs to improve resiliency and performance. Nonetheless, we need CORS since most of those services are not used from the same domain. Therefore, to enabled CORS headers in the ALB, we need to add the following listener attributes according to the AWS docs:

```
routing.http.response.server.enabled: "true"
routing.http.response.access_control_allow_origin.header_value: "https://www.domain.com"
routing.http.response.access_control_allow_methods.header_value: "GET, POST, OPTIONS, PUT, DELETE"
routing.http.response.access_control_allow_headers.header_value: "Origin, X-Requested-With, Content-Type, Accept, Authorization"
```

Any help, recommendations, or any suggestions are more than welcomed 🙏  thanks in advance.

**Bug Description**

The bug is that to add those attributes we need to use the [listener-attributes annotations](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.12/guide/ingress/annotations/#listener-attributes). This annotations is defined as a stringMap, but it seems that the commas (,) from the attributes values conflict with this. I tried looking for other examples on how to pass this safely but I couldn't find any. I also tried:

```
alb.ingress.kubernetes.io/listener-attributes.HTTPS-443: routing.http.response.access_control_allow_methods.header_value=\"GET, POST, OPTIONS, PUT, DELETE\",routing.http.response.access_control_allow_origin.header_value=https://www.domain.com,routing.http.response.server.enabled=true
```

But I always get:

```
"error":"failed to parse stringMap annotation, alb.ingress.kubernetes.io/listener-attributes.HTTPS-443: routing.http.response.access_control_allow_methods.header_value=\"GET, POST, OPTIONS, PUT, DELETE\",routing.http.response.access_control_allow_origin.header_value=https://www.domain.com,routing.http.response.server.enabled=true"
```

**Steps to Reproduce**
We are using AWS Load Balancer controller version v2.11.0 being deployed with the Helm chart version 1.11.0.

Here's a template that will cause this error:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /ping
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/listener-attributes.HTTPS-443: >-
      routing.http.response.access_control_allow_methods.header_value="GET, POST, OPTIONS, PUT, DELETE",routing.http.response.access_control_allow_origin.header_value=https://www.domain.com,routing.http.response.server.enabled=true
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=60,slow_start.duration_seconds=30
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app.kubernetes.io/instance: random-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: ingress-2025.03.14-181458
  name: random-ingress
  namespace: random-namespace
spec:
  ingressClassName: alb
  rules:
    - host: www.domain.com
      http:
        paths:
          - backend:
              service:
                name: random-service
                port:
                  name: http
            path: /*
            pathType: ImplementationSpecific
```

**Expected Behavior**
To be able to add modify these attributes without an issue, and it would be nice to have more examples around this. It possible that we are using it wrong but the lack of examples it's complicated to diagnose that.

**Actual Behavior**
It fails to parse the stringMap due to the commans (,) in the attributes.

**Environment**
- AWS Load Balancer controller version: v2.11.0
- Kubernetes version: 1.32
- Using EKS (yes/no), if so version?: Yes, 1.32
- Using Service or Ingress: Ingress
- AWS region: us-east-1
- How was the aws-load-balancer-controller installed: We are using Helm with the following values:
```
image:
  repository: "account-id.dkr.ecr.us-east-1.amazonaws.com/ecr-public/eks/aws-load-balancer-controller"

clusterName: cluster-name
vpcId: vpc-id
region: us-east-1

revisionHistoryLimit: 3
resources:
  requests:
    cpu: 15m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 128Mi

defaultTargetType: ip
enableBackendSecurityGroup: true
enablePodReadinessGateInject: true
webhookNamespaceSelectors:
  - key: elbv2.k8s.aws/pod-readiness-gate-inject
    operator: In
    values:
      - enabled

serviceMonitor:
  enabled: true
  additionalLabels:
    release: prometheus

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "role-arn"

defaultTags:
  context: "random"

tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: karpenter.sh/nodepool
              operator: DoesNotExist
```

- Current state of the Controller configuration:
```
Name:                   aws-load-balancer-controller
Namespace:              kube-system
CreationTimestamp:      Mon, 10 Mar 2025 15:36:46 +0100
Labels:                 app.kubernetes.io/instance=aws-load-balancer-controller
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=aws-load-balancer-controller
                        app.kubernetes.io/version=v2.11.0
                        argocd.argoproj.io/instance=aws-load-balancer-controller
                        helm.sh/chart=aws-load-balancer-controller-1.11.0
Annotations:            deployment.kubernetes.io/revision: 2
Selector:               app.kubernetes.io/instance=aws-load-balancer-controller,app.kubernetes.io/name=aws-load-balancer-controller
Replicas:               2 desired | 2 updated | 2 total | 2 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/instance=aws-load-balancer-controller
                    app.kubernetes.io/name=aws-load-balancer-controller
  Service Account:  aws-load-balancer-controller
  Containers:
   aws-load-balancer-controller:
    Image:       account_id.dkr.ecr.us-east-1.amazonaws.com/ecr-public/eks/aws-load-balancer-controller:v2.11.0
    Ports:       9443/TCP, 8080/TCP
    Host Ports:  0/TCP, 0/TCP
    Args:
      --cluster-name=cluster-name
      --ingress-class=alb
      --aws-region=us-east-1
      --aws-vpc-id=vpc-id
      --enable-pod-readiness-gate-inject=true
      --default-tags=context=random-context
      --enable-backend-security-group=true
      --default-target-type=ip
    Limits:
      cpu:     500m
      memory:  128Mi
    Requests:
      cpu:        15m
      memory:     128Mi
    Liveness:     http-get http://:61779/healthz delay=30s timeout=10s period=10s #success=1 #failure=2
    Readiness:    http-get http://:61779/readyz delay=10s timeout=10s period=10s #success=1 #failure=2
    Environment:  <none>
    Mounts:
      /tmp/k8s-webhook-server/serving-certs from cert (ro)
  Volumes:
   cert:
    Type:               Secret (a volume populated by a Secret)
    SecretName:         aws-load-balancer-tls
    Optional:           false
  Priority Class Name:  system-cluster-critical
  Node-Selectors:       <none>
  Tolerations:          CriticalAddonsOnly op=Exists
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  aws-load-balancer-controller-58d5bb5c97 (0/0 replicas created)
NewReplicaSet:   aws-load-balancer-controller-7cd7f77544 (2/2 replicas created)
Events:          <none>
```

- Current state of the Ingress/Service configuration:
```
Name:             random-ingress
Labels:           app.kubernetes.io/instance=random-ingress
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=ingress
                  app.kubernetes.io/version=1.0.0
                  helm.sh/chart=ingress-2025.03.14-181458
Namespace:        random-namespace
Address:          random-address.us-east-1.elb.amazonaws.com
Ingress Class:    alb
Default backend:  <default>
Rules:
  Host                                                    Path  Backends
  ----                                                    ----  --------
[Rules ...]

Annotations:                                              alb.ingress.kubernetes.io/healthcheck-path: /ping
                                                          alb.ingress.kubernetes.io/listen-ports: [{"HTTPS":443}]
                                                          alb.ingress.kubernetes.io/listener-attributes.HTTPS-443:
                                                            routing.http.response.access_control_allow_headers.header_value=false,routing.http.response.access_control_allow_methods.header_value="GET...
                                                          alb.ingress.kubernetes.io/load-balancer-attributes:
                                                            idle_timeout.timeout_seconds=600,routing.http.drop_invalid_header_fields.enabled=false,routing.http.preserve_host_header.enabled=true
                                                          alb.ingress.kubernetes.io/scheme: internal
                                                          alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=60,slow_start.duration_seconds=30
                                                          alb.ingress.kubernetes.io/target-type: ip

Events:
  Type     Reason                  Age                  From     Message
  ----     ------                  ----                 ----     -------
  Warning  FailedBuildModel        56m (x8 over 56m)    ingress  Failed build model due to failed to parse stringMap annotation, alb.ingress.kubernetes.io/listener-attributes.HTTPS-443: routing.http.response.access_control_allow_methods.header_value="GET,POST,OPTIONS",routing.http.response.access_control_allow_origin.header_value=https://studio-dev-sandbox.sve.sonos.com,routing.http.response.server.enabled=true
  Warning  FailedDeployModel       54m                  ingress  Failed deploy model due to operation error Elastic Load Balancing v2: ModifyListenerAttributes, https response error StatusCode: 400, RequestID: 4b7f2662-a97c-4195-8198-eae9beaae528, api error ValidationError: The value 'GET;POST;OPTIONS' is not allowed. The value should be '*' or a comma-separated string that contains one or more methods: [GET, HEAD, POST, PUT, DELETE, CONNECT, OPTIONS, TRACE, PATCH]
  Normal   SuccessfullyReconciled  49m (x27 over 6d)    ingress  Successfully reconciled
  Warning  FailedBuildModel        31m (x3 over 31m)    ingress  Failed build model due to failed to parse stringMap annotation, alb.ingress.kubernetes.io/listener-attributes.HTTPS-443: routing.http.response.access_control_allow_headers.header_value=false,routing.http.response.access_control_allow_methods.header_value="GET\,POST\,OPTIONS\,PUT\,DELETE",routing.http.response.access_control_allow_origin.header_value=https://studio-dev-sandbox.sve.sonos.com,routing.http.response.server.enabled=true
  Warning  FailedBuildModel        7m33s (x3 over 28m)  ingress  Failed build model due to failed to parse stringMap annotation, alb.ingress.kubernetes.io/listener-attributes.HTTPS-443: routing.http.response.access_control_allow_headers.header_value=false,routing.http.response.access_control_allow_methods.header_value="GET, POST, OPTIONS, PUT, DELETE",routing.http.response.access_control_allow_origin.header_value=https://studio-dev-sandbox.sve.sonos.com,routing.http.response.server.enabled=true
```
