### ISSUE TITLE
[Feature Enhancement] Allow overriding of default webhook certificate values

### ISSUE THREAD

**Issue by usamaahmadkhan** [kubernetes-sigs/aws-load-balancer-controller#4102]
**Describe the feature you are requesting**
With `enableCertmanager: true` the helm chart creates Issuer and Certificate resource for webhook. The certificate doesn't specify `duration` and `renewBefore` and hence use the default duration of `720h` and renew after `600h`. I would like the ability to override these values whenever required.

**Motivation**
This makes certificate duration more flexible. A longer certificate duration would mean less failure points for the issuance of the certificate if certmanager fails throughout the year.

**Describe the proposed solution you'd like**
Specify the overrides for the `duration` and `renewBefore` fields in Certificate template.

Current:
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "aws-load-balancer-controller.namePrefix" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "aws-load-balancer-controller.labels" . | indent 4 }}
spec:
  dnsNames:
  - {{ template "aws-load-balancer-controller.webhookService" . }}.{{ .Release.Namespace }}.svc
  - {{ template "aws-load-balancer-controller.webhookService" . }}.{{ .Release.Namespace }}.svc.{{ .Values.cluster.dnsDomain }}
  issuerRef:
    kind: Issuer
    name: {{ template "aws-load-balancer-controller.namePrefix" . }}-selfsigned-issuer
  secretName: {{ template "aws-load-balancer-controller.webhookCertSecret" . }}
```

Proposed Change:
```yaml
# templates/webhook.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "aws-load-balancer-controller.namePrefix" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "aws-load-balancer-controller.labels" . | indent 4 }}
spec:
  dnsNames:
  - {{ template "aws-load-balancer-controller.webhookService" . }}.{{ .Release.Namespace }}.svc
  - {{ template "aws-load-balancer-controller.webhookService" . }}.{{ .Release.Namespace }}.svc.{{ .Values.cluster.dnsDomain }}
  duration: {{ .Values.webhookCertDuration | default "720h" }}           # <------ cert duration
  renewBefore: {{ .Values.webhookCertDuration | default "600h" }}   # <------ cert renewal
  issuerRef:
    kind: Issuer
    name: {{ template "aws-load-balancer-controller.namePrefix" . }}-selfsigned-issuer
  secretName: {{ template "aws-load-balancer-controller.webhookCertSecret" . }}

# values.yaml
enableCertManager: true
webhookCertDuration: ""
webhookCertRenewAfter: ""
```

**Describe alternatives you've considered**

**Contribution Intention (Optional)**

- [x] Yes, I am willing to contribute a PR to implement this feature
- [ ] No, I cannot work on a PR at this time
