### ISSUE TITLE
Service internal NLB errors with "InvalidSubnet: VPC vpc-xxx has no internet gateway" unless I add deprecated annotation

### ISSUE THREAD

**Issue by sss-ng** [kubernetes-sigs/aws-load-balancer-controller#4110]
**Bug Description**
When deploying a  k8s Service with annotations:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: ingress-nginx
    meta.helm.sh/release-namespace: ingress-nginx
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-xxx,subnet-yyy
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal ### <-----------
```
I get the following errors, and the NLB never comes up:
``` 
Warning  SyncLoadBalancerFailed  94s     service-controller  Error syncing load balancer: failed to ensure load balancer: error creating load balancer: "InvalidSubnet: VPC vpc-xxx has no internet gateway\n\tstatus code: 400, request id: ..." 
```

However, when replacing the `scheme` annotation with the deprecated `internal: true` annotation, the NLB comes right up:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: ingress-nginx
    meta.helm.sh/release-namespace: ingress-nginx
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-xxx,subnet-yyy
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true" ### <---------
```

From reading the docs, I see that `service.beta.kubernetes.io/aws-load-balancer-scheme: internal` should work, I wonder why it doesnt. Anyone have any ideas?

**Regression**
Was the functionality working correctly in a previous version ? [Yes / No]

I've noticed this issue on all versions that I've tested it on: 1.2 and 1.12 so far.

**Environment**
- AWS Load Balancer controller version: 2.12
- Kubernetes version: v1.31.6-eks-bc803b4
- Using EKS (yes/no), if so version?: v1.31.6-eks-bc803b4
- Using Service or Ingress: service 
- AWS region: us west 1
- How was the aws-load-balancer-controller installed:
  - If helm was used then please show output of `helm ls -A | grep -i aws-load-balancer-controller`
 ```
aws-load-balancer-controller            kube-system     2               2025-03-27 00:10:34.253831155 -0400 EDT deployed        aws-load-balancer-controller-1.12.0             v2.12.0
```
  - If helm was used then please show output of `helm -n <controllernamespace> get values <helmreleasename>`
```
helm -n kube-system get values aws-load-balancer-controller 

USER-SUPPLIED VALUES:
clusterName: test-cluster
enableServiceMutatorWebhook: false
podDisruptionBudget:
  maxUnavailable: 1
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws-us-gov:iam::xxx:role/alb-controller-xxxxxxxx
  name: aws-load-balancer-controller-sa
vpcId: vpc-xxxxx
--------------------
```
