### ISSUE TITLE
Is `.spec.networking.ingress` required for UDP traffic in `TargetGroupBinding`?

### ISSUE THREAD

**Issue by kumo-rn5s** [kubernetes-sigs/aws-load-balancer-controller#4146]
**Bug Description**

When creating a TargetGroupBinding with `targetType: ip` for UDP (port 53) traffic to CoreDNS, the NLB fails to route traffic unless `spec.networking.ingress` is explicitly specified.

TCP traffic (on the same port) works fine even without this field. This suggests that the `networking.ingress` field might be implicitly required for UDP traffic, but not for TCP — however, this requirement does not appear to be documented.

**Steps to Reproduce**
- Create a internal type NLB with UDP:53 listener and UDP:53 target group.
- Create a Service of type `ClusterIP` for CoreDNS (port 53 UDP).
   - **no**`spec.networking.ingress` in the TGB.
- Attempt a `dig` query to `@<nlb-dns>` for any internal DNS name.
  - Example: `dig my-app-headless.default.svc.cluster.local @<nlb-dns>`
- You will observe that: UDP does **not** work. 

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    eks.amazonaws.com/component: kube-dns
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
  name: coredns-external
  namespace: kube-system
spec:
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: coredns-udp
  namespace: kube-system
spec:
  serviceRef:
    name: coredns-external
    port: 53
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-1:123456789012:targetgroup/someid
  targetType: ip
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: coredns-metrics
  namespace: kube-system
spec:
  serviceRef:
    name: coredns-external
    port: 9153
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-1:123456789012:targetgroup/someid
  targetType: ip
```
  - dig only work when `.spec.networking` is specified like this. 

```yaml
networking:
  ingress:
    - from:
        - ipBlock:
            cidr: xxxx
      ports:
        - port: 53
          protocol: UDP
```
  - tcp:9153 works even `.spec.networking` is not specified. `curl <nlb_dns>:9153/metrics` will response.

**Expected Behavior**

UDP traffic should be allowed to reach the Pod targets when targetType: ip is specified and the TargetGroupBinding references a valid Service and port, without needing to specify spec.networking.ingress.

**Actual Behavior**

Without spec.networking.ingress, UDP traffic is dropped or never reaches the CoreDNS Pods.
This behavior is consistent and always reproducible.

**Regression**
Was the functionality working correctly in a previous version ? [Yes / No]
If yes, specify the last version where it worked as expected
No. I am not sure if this is a regression or if this behavior was always present but undocumented.

**Current Workarounds**

Explicitly define `spec.networking.ingress` in the TargetGroupBinding with a broad CIDR ( like `0.0.0.0/0`) and UDP port 53 allowed

**Environment**
- AWS Load Balancer controller version: `v2.4.7`
- Kubernetes version: `1.30`
- Using EKS (yes/no), if so version?: yes, `1.30`, platform version `eks.29`
- Using Service or Ingress: Service, with TargetGroupBinding
- AWS region: ap-northeast-1
- How was the aws-load-balancer-controller installed:
  - helmchart + argocd. no output of `helm ls -A | grep -i aws-load-balancer-controller`
  - chart version: `1.4.8`
- Current state of the Controller configuration:
  - `kubectl -n <controllernamespace> describe deployment aws-load-balancer-controller`
- Current state of the Ingress/Service configuration:
  - `kubectl describe ingressclasses`
     ```bash
    kubectl describe ingressclasses
    Name:         alb
    Labels:       app.kubernetes.io/instance=aws-load-balancer-controller
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=aws-load-balancer-controller
                  app.kubernetes.io/version=v2.4.7
                  argocd.argoproj.io/instance=dev-aws-load-balancer-controller
                  helm.sh/chart=aws-load-balancer-controller-1.4.8
    Annotations:  argocd.argoproj.io/tracking-id: dev-aws-load-balancer-controller:networking.k8s.io/IngressClass:kube-system/alb
    Controller:   ingress.k8s.aws/alb
    Events:       <none>
     ```
  - not using ingressclass, no output of ingressclass’s yaml 
  - service yaml has been provided before.

**Possible Solution (Optional)**

**Contribution Intention (Optional)**

- [x] Yes, I'm willing to submit a PR to fix this issue
- [ ] No, I cannot work on a PR at this time

**Additional Context**
