### ISSUE TITLE
LB configuraion is not working Using Gateway API

### ISSUE THREAD

**Issue by anannaya** [kubernetes-sigs/aws-load-balancer-controller#4175]
**Bug Description**

**Steps to Reproduce**

- Step-by-step guide to reproduce the bug:
- Manifests applied while reproducing the issue:
- Controller logs/error messages while reproducing the issue:

**Expected Behavior**

**Actual Behavior**

**Regression**
Was the functionality working correctly in a previous version ? [Yes / No]
If yes, specify the last version where it worked as expected

**Current Workarounds**

**Environment**
- AWS Load Balancer controller version:
- Kubernetes version:
- Using EKS (yes/no), if so version?:
- Using Service or Ingress:
- AWS region:
- How was the aws-load-balancer-controller installed:
  - If helm was used then please show output of `helm ls -A | grep -i aws-load-balancer-controller`
  - If helm was used then please show output of `helm -n <controllernamespace> get values <helmreleasename>`
  - If helm was not used, then copy/paste the exact command used to install the controller, including flags and options.
- Current state of the Controller configuration:
  - `kubectl -n <controllernamespace> describe deployment aws-load-balancer-controller`
- Current state of the Ingress/Service configuration:
  - `kubectl describe ingressclasses`
  - `kubectl -n <appnamespace> describe ingress <ingressname>`
  - `kubectl -n <appnamespace> describe svc <servicename>`

**Possible Solution (Optional)**

**Contribution Intention (Optional)**

- [ ] Yes, I'm willing to submit a PR to fix this issue
- [ ] No, I cannot work on a PR at this time

**Additional Context**

**Comment by shraddhabang** [comment]
@anannaya So excited that you are trying out Gateway API. 

to add to Zac's points, We only materialize the listeners for gateway if we find the associated routes for it and create tgs for the backends in those route to avoid creating leaking Target groups for the services which are not yet referred by any gateways.

**Comment by anannaya** [comment]
@shraddhabang @zac-nixon   Thanks a lot for responding .  I would like replicate the same ingress resources using the Gateway-api 
ALB(ingress)-->istio-ingress-gateway-pods(targets)

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:xxxxxxxxx:certificate/329884a5-f66e-48f5-a30e-677058afe898
    alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=120
    alb.ingress.kubernetes.io/load-balancer-name: anand-ingress-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Owner=anand,SpendType=COGS
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=50
    external-dns.alpha.kubernetes.io/hostname: istioalb.anand.xxxxxx.thunderhead.io
    gateway.networking.k8s.io/gateway-name: default-gateway-alb
  name: default-gateway-alb
  namespace: istio-system
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
        path: /
        pathType: Prefix
      - backend:
          service:
            name: istio-ingressgateway-alb
            port:
              number: 443
        path: /
        pathType: Prefix
```
