### ISSUE TITLE
Reconcile errors for `controller=targetGroupBinding` increased after upgrade v2.12.0 -> v2.13.0

### ISSUE THREAD

**Issue by mkilchhofer** [kubernetes-sigs/aws-load-balancer-controller#4176]
**Bug Description**
We upgraded the LBC from v2.12.0 -> v2.13.0. After this upgrade, the metric `controller_runtime_reconcile_errors_total` is now drastically increasing:

![metric `controller_runtime_reconcile_errors_total`](https://github.com/user-attachments/assets/eeadb376-135e-44c0-b7a8-211458efcb56)

If i use the PromQL `increase()` function which we use in the alert rules (see below), we see this graph after the upgrade:
![metric `controller_runtime_reconcile_errors_total` - use increase function](https://github.com/user-attachments/assets/1c93064d-fc4b-4f20-8551-9cf73696a38d)

**Steps to Reproduce**
Upgrade from v2.12.0 to v2.13.0

**Expected Behavior**

Metric looks like before

**Actual Behavior**

Metric drastically increased on all clusters

**Regression**
Was the functionality working correctly in a previous version ? [Yes / No]
Yes, with `v2.12.0` we had no alerts for this metric

**Current Workarounds**
none

**Environment**
- AWS Load Balancer controller version: **v2.13.0**
- Kubernetes version: **v1.31.7-eks-bcf3d70**
- Using EKS (yes/no), if so version?: **yes, v1.31.7-eks-bcf3d70**
- Using Service or Ingress: **both**
- AWS region: **eu-central-1**
- How was the aws-load-balancer-controller installed:
  **Via Helm + Argo CD**, values:
  ```yaml
  aws-load-balancer-controller:
    image:
      repository: <REDACTED>/eks/aws-load-balancer-controller
  
    certDiscovery:
      allowedCertificateAuthorityARNs: "arn:aws:acm-pca:eu-central-1:<REDACTED>"
  
    # The name of the Kubernetes cluster. A non-empty value is required
    clusterName: "" # Set via Argo CD Parameters
  
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "" # Set via Argo CD Parameters
  
    updateStrategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
  
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        matchLabelKeys:
          - pod-template-hash
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: aws-load-balancer-controller
  
    securityContext:
      capabilities:
        drop:
          - ALL
  
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  
    # Enable cert-manager
    enableCertManager: true
  
    region: "eu-central-1"
    enableShield: false
  
    # The address the metric endpoint binds to. (default ":8080")
    metricsBindAddr: ":8080"
  
    defaultSSLPolicy: "ELBSecurityPolicy-<REDACTED>"
  
    defaultTags:
      <REDACTED>: <REDACTED>
  
    env:
      AWS_STS_REGIONAL_ENDPOINTS: "regional"
      # For the public ACM and WAFv2 endpoint and for the global Shield endpoint
      https_proxy: <REDACTED>
      # For the "private" VPC endpoints like EC2, ELB and STS
      no_proxy: <REDACTED>,<REDACTED>,<REDACTED>,<REDACTED>,ec2.eu-central-1.amazonaws.com,elasticloadbalancing.eu-central-1.amazonaws.com,sts.eu-central-1.amazonaws.com'
  
    podDisruptionBudget:
      maxUnavailable: 1
  
    enableServiceMutatorWebhook: false
  ```

**Possible Solution (Optional)**

Either
- just ignore the metrics. Is this safe?
- downgrade to v2.12.0 again

**Contribution Intention (Optional)**

- [ ] Yes, I'm willing to submit a PR to fix this issue
- [x] No, I cannot work on a PR at this time

**Additional Context**

We use these Prometheus alert rules:

```yaml
  groups:
  - name: aws-lb-controller.rules
    rules:
    - alert: AWSLBIngressControllerReconcileErrors
      expr: increase(controller_runtime_reconcile_errors_total{controller="ingress", job="aws-load-balancer-controller"}[5m]) > 0
      for: 5m
      labels:
        severity: critical
        component: platform
        service: aws-load-balancer-controller
      annotations:
        summary: "AWS LB Ingress controller reconciliation errors"
        description: "AWS LB ingress controller has encountered errors while reconciling its state."
    
    - alert: AWSLBServiceControllerReconcileErrors
      expr: increase(controller_runtime_reconcile_errors_total{controller="service", job="aws-load-balancer-controller"}[5m]) > 0
      for: 5m
      labels:
        severity: critical
        component: platform
        service: aws-load-balancer-controller
      annotations:
        summary: "AWS LB Service controller reconciliation errors"
        description: "AWS LB Service controller has encountered errors while reconciling its state."
    
    - alert: AWSLBTargetGroupBindingControllerReconcileErrors
      expr: increase(controller_runtime_reconcile_errors_total{controller="targetGroupBinding", job="aws-load-balancer-controller"}[5m]) > 0
      for: 5m
      labels:
        severity: critical
        component: platform
        service: aws-load-balancer-controller
      annotations:
        summary: "AWS LB TargetGroupBinding controller reconciliation errors"
        description: "AWS LB TargetGroupBinding controller has encountered errors while reconciling its state." 
```

/cc @blanchardma @LinoSteffen @the-technat
