### ISSUE TITLE
Missing traffic port in TargetGroupBinding

### ISSUE THREAD

**Issue by mycrEEpy** [kubernetes-sigs/aws-load-balancer-controller#4183]
**Bug Description**

When we create a `Service` of type `LoadBalancer` with a different health check port and the SSL certificates pinned via the `service.beta.kubernetes.io/aws-load-balancer-ssl-cert` annotation, only the health check port will be added to the `TargetGroupBinding` and the traffic port is missing.

If we remove the `service.beta.kubernetes.io/aws-load-balancer-ssl-cert` annotation the traffic port is added to the `TargetGroupBinding` again.

**Steps to Reproduce**

Manifest:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8000"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /readyz
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-central-1:xxxxxxxxxx:certificate/xxxxxxxxxxxxxxx
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
  name: broken-tgb
  namespace: example
spec:
  ports:
    - appProtocol: https
      name: https
      port: 443
      protocol: TCP
      targetPort: 2443
  selector:
    app: my-app
  type: LoadBalancer
```

Resulting `TargetGroupBinding`:

```yaml
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  annotations:
    elbv2.k8s.aws/checkpoint: xxxxxxxxx
    elbv2.k8s.aws/checkpoint-timestamp: "1747302285"
  creationTimestamp: "2025-05-15T09:44:45Z"
  finalizers:
  - elbv2.k8s.aws/resources
  generation: 1
  labels:
    service.k8s.aws/stack-name: broken-tgb
    service.k8s.aws/stack-namespace: example
  name: k8s-example-brokentg-xxxxxxxxx
  namespace: example
  resourceVersion: "66269930"
  uid: xxxxxxxx
spec:
  ipAddressType: ipv4
  networking:
    ingress:
    - from:
      - securityGroup:
          groupID: sg-xxxxxxxxxx
      ports:
      - port: 8000
        protocol: TCP
  serviceRef:
    name: broken-tgb
    port: 443
  targetGroupARN: arn:aws:elasticloadbalancing:eu-central-1:xxxxxxxxxxxxx:targetgroup/k8s-example-brokentg-xxxxxx
  targetType: ip
  vpcID: vpc-xxxxxxxxxx
status:
  observedGeneration: 1
```

**Expected Behavior**

Both ports, traffic & health check are added to the `TargetGroupBinding`.

**Actual Behavior**

Only the health check port is added to the `TargetGroupBinding`.

**Regression**
Was the functionality working correctly in a previous version ?

Yes in 2.12.0, broken since 2.13.0

**Current Workarounds**

Stay on 2.12.0 or remove `service.beta.kubernetes.io/aws-load-balancer-ssl-cert` annotation.

**Environment**

- AWS Load Balancer controller version: 2.13.1
- Kubernetes version: v1.32.3-eks-bcf3d70
- Using EKS (yes/no), if so version?: Yes, v1.32.3-eks-bcf3d70
- Using Service or Ingress: Service
- AWS region: eu-central-1
- How was the aws-load-balancer-controller installed:  v2_13_1_full.yaml from Release page
- Current state of the Controller configuration:

```text
Name:                   aws-load-balancer-controller
Namespace:              kube-system
CreationTimestamp:      Mon, 27 Jan 2025 14:07:44 +0100
Labels:                 app.kubernetes.io/component=controller
                        app.kubernetes.io/name=aws-load-balancer-controller
                        env=dev
Annotations:    deployment.kubernetes.io/revision: 7
Selector:               app.kubernetes.io/component=controller,app.kubernetes.io/name=aws-load-balancer-controller
Replicas:               2 desired | 2 updated | 2 total | 2 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/component=controller
                    app.kubernetes.io/name=aws-load-balancer-controller
  Service Account:  aws-load-balancer-controller
  Containers:
   controller:
    Image:      public.ecr.aws/eks/aws-load-balancer-controller:v2.13.1
    Port:       9443/TCP
    Host Port:  0/TCP
    Args:
      --cluster-name=xxxxxxxxx
      --ingress-class=alb
      --default-ssl-policy=ELBSecurityPolicy-TLS13-1-2-Ext1-2021-06
      --enable-leader-election=true
    Limits:
      cpu:     200m
      memory:  500Mi
    Requests:
      cpu:        100m
      memory:     200Mi
    Liveness:     http-get http://:61779/healthz delay=30s timeout=10s period=10s #success=1 #failure=2
    Environment:  <none>
    Mounts:
      /tmp/k8s-webhook-server/serving-certs from cert (ro)
  Volumes:
   cert:
    Type:               Secret (a volume populated by a Secret)
    SecretName:         aws-load-balancer-webhook-tls
    Optional:           false
  Priority Class Name:  system-cluster-critical
  Node-Selectors:       <none>
  Tolerations:          <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  aws-load-balancer-controller-94fc45cbd (0/0 replicas created), aws-load-balancer-controller-bdbc8cdc5 (0/0 replicas created), aws-load-balancer-controller-7d959f8d46 (0/0 replicas created)
NewReplicaSet:   aws-load-balancer-controller-65dd7cf7f (2/2 replicas created)
Events:          <none>
```

- Current state of the Ingress/Service configuration:
  - `kubectl describe ingressclasses`:

```text
Name:         alb
Labels:       app.kubernetes.io/name=aws-load-balancer-controller
              env=dev
Controller:   ingress.k8s.aws/alb
Parameters:
  APIGroup:  elbv2.k8s.aws
  Kind:      IngressClassParams
  Name:      alb
Events:      <none>
```

  - `kubectl -n <appnamespace> describe svc <servicename>`

```text
Name:                     broken-tgb
Namespace:                example
Labels:                   <none>
Annotations:              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
                          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: true
                          service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /readyz
                          service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: 8000
                          service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http
                          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
                          service.beta.kubernetes.io/aws-load-balancer-scheme: internal
                          service.beta.kubernetes.io/aws-load-balancer-ssl-cert:
                            arn:aws:acm:eu-central-1:xxxxxxxxxxx:certificate/xxxxxxxxxxxxx
                          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
                          service.beta.kubernetes.io/aws-load-balancer-type: external
Selector:                 app=my-app
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       xxx.xxx.xxx.xxx
IPs:                      xxx.xxx.xxx.xxx
LoadBalancer Ingress:     k8s-example-brokentg-xxxxxxxx.elb.eu-central-1.amazonaws.com
Port:                     https  443/TCP
TargetPort:               2443/TCP
NodePort:                 https  31211/TCP
Endpoints:                xxx.xxx.xxx.xxx:2443
Session Affinity:         None
External Traffic Policy:  Cluster
Internal Traffic Policy:  Cluster
Events:
  Type    Reason                  Age    From                Message
  ----    ------                  ----   ----                -------
  Normal  EnsuringLoadBalancer    14m    service-controller  Ensuring load balancer
  Normal  SuccessfullyReconciled  14m    service             Successfully reconciled
  Normal  SuccessfullyReconciled  8m37s  service             Successfully reconciled
  Normal  SuccessfullyReconciled  7m28s  service             Successfully reconciled
```

**Possible Solution (Optional)**

n/a

**Contribution Intention (Optional)**
- [ ] Yes, I'm willing to submit a PR to fix this issue
- [x] No, I cannot work on a PR at this time

**Additional Context**

n/a
