### ISSUE TITLE
Ingress group with multiple conditions and actions reconcile but no rules in ALB

### ISSUE THREAD

**Issue by casey-robertson-paypal** [kubernetes-sigs/aws-load-balancer-controller#4215]
Working on an ingress consolidation project to try to reduce the number of ALBs in our AWS account

Due to old tech debt all of "dev" is a single cluster with multiple environmenment namespaces: dev,dev-1, dev-2 etc

Single DNS zone - hostnames per service per env look something like:

```
service-dev.domain.com
service-dev-1.domain.com
service-dev-2.domain.com
```

This has presented challenges because Kubernetes ingress objects only support full hostname wildcards, not partial matching.

Per this post I am attempting to do this via `conditions` and `actions` annotations: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/987#issuecomment-589820566

Current design is a "base" ingress in the `dev` namespace.  Group name annotation is set.  Then have "app" ingresses in each namespace that are part of this group.name.  The hope is to figure out some way to do pattern matching such that `*-dev.domain.com` routes to the service in the `dev` namespace; `*-dev-1.domain.com` routes to the service in the `dev-1` namespace etc.

I know the fundamental construct of Ingresses define per NS works but so far only with full FQDNs (or top level wildcards).  Current config below - looking to see what the issue might be or if it's even possible.  Currently the controller says everything reconciles but I don't end up with any rules showing up in the ALB.

Base ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-service
  namespace: dev
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    alb.ingress.kubernetes.io/group.name: dev-service
    alb.ingress.kubernetes.io/healthcheck-path: /heartbeat
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: eks-alb-external-dev
    alb.ingress.kubernetes.io/shield-advanced-protection: 'true'
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-Res-2021-06
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/subnets: REDACTED
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - host: dummy-service-retailers-dev.domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dummy-service-domain-dev
                port:
                  number: 80
```

dev app ingress - deployed to `dev` namespace:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: dev
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    alb.ingress.kubernetes.io/actions.app-dev: >-
      {"Type":"forward","ForwardConfig":{"TargetGroups":[{"ServiceName":"app","ServicePort":"80"}]}}
    alb.ingress.kubernetes.io/conditions.app-dev: >-
      [{"Field":"host-header","HostHeaderConfig":{"Values":["*-dev.domain.com"]}}]
    alb.ingress.kubernetes.io/group.name: dev-service
    alb.ingress.kubernetes.io/healthcheck-path: /heartbeat
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-dev
                port:
                  name: use-annotation
```

dev-1 app ingress - deployed to `dev-1` namespace:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: dev-1
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    alb.ingress.kubernetes.io/actions.app-dev-1: >-
      {"Type":"forward","ForwardConfig":{"TargetGroups":[{"ServiceName":"app","ServicePort":"80"}]}}
    alb.ingress.kubernetes.io/conditions.app-dev-1: >-
      [{"Field":"host-header","HostHeaderConfig":{"Values":["*-dev-1.domain.com"]}}]
    alb.ingress.kubernetes.io/group.name: dev-service
    alb.ingress.kubernetes.io/healthcheck-path: /heartbeat
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-dev
                port:
                  name: use-annotation
```
