### ISSUE TITLE
IngressClassParams not creating all listeners

### ISSUE THREAD

**Issue by larivierec-psl** [kubernetes-sigs/aws-load-balancer-controller#4218]
**Bug Description**

When using IngressClassParams, it is unable to provision both listeners.

[Listener Spec](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/release-2.13/apis/elbv2/v1beta1/ingressclassparams_types.go#L95-L102)

[IngressClassParams Spec](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/release-2.13/apis/elbv2/v1beta1/ingressclassparams_types.go#L118-L177)

It clearly shows an array, however, after provision, it only creates 1 of the two.
The purpose of the IngressClass and the IngressClassParams, is to avoid repeating the annotations all over the ingress objects, and keeping let the controller make the required standard changes.

**Steps to Reproduce**

- Step-by-step guide to reproduce the bug:
1. We use argo to apply the manifest, but it reconciles and creates the load balancer below
**Manifest**

```yaml
aws-load-balancer-controller:
  # Use hard-coded values instead of variables
  nameOverride: &name aws-lb-external-controller
  fullnameOverride: *name
  clusterName: shared-services-prod
  region: eu-west-1
  vpcId: vpc-<guid>
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::1234567890:role/aws-load-balancer-controller
  ingressClass: &type external
  loadBalancerClass: *type
  ingressClassConfig:
    default: true
  ingressClassParams:
    name: *type
    spec:
      group:
        name: *type
      scheme: internet-facing
      subnets:
        ids:
          - subnet-1
          - subnet-2
      listeners:
        - port: 80
          protocol: HTTP
        - port: 443
          protocol: HTTPS
      certificateArn:
        - arn:aws:acm:eu-west-1:1234567890:certificate/<GUID>
      loadBalancerAttributes:
        - key: deletion_protection.enabled
          value: "true"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: *name
              app.kubernetes.io/instance: aws-lb-controller-external
          topologyKey: kubernetes.io/hostname
```

- Controller logs/error messages while reproducing the issue:

Produces this:

```bash
(⎈|shared-services-prod:kube-system)➜  ami-soundboardai-llm git:(unittests) k get ingressclass external -o yaml
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  creationTimestamp: "2025-06-04T17:36:18Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: aws-lb-controller-external
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-lb-external-controller
    app.kubernetes.io/version: v2.13.2
    argocd.argoproj.io/instance: aws-lb-controller-external
    helm.sh/chart: aws-load-balancer-controller-1.13.2
  name: external
spec:
  controller: ingress.k8s.aws/alb
  parameters:
    apiGroup: elbv2.k8s.aws
    kind: IngressClassParams
    name: external
    scope: Cluster

(⎈|shared-services-prod:kube-system)➜  ami-soundboardai-llm git:(unittests) k get ingressclassparams.elbv2.k8s.aws external -o yaml
apiVersion: elbv2.k8s.aws/v1beta1
kind: IngressClassParams
metadata:
  labels:
    app.kubernetes.io/instance: aws-lb-controller-external
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-lb-external-controller
    app.kubernetes.io/version: v2.13.2
    argocd.argoproj.io/instance: aws-lb-controller-external
    helm.sh/chart: aws-load-balancer-controller-1.13.2
  name: external
spec:
  certificateArn:
  - arn:aws:acm:eu-west-1:1234567890:certificate/<GUID>
  group:
    name: external
  listeners:
  - port: 80
    protocol: HTTP
  - port: 443
    protocol: HTTPS
  loadBalancerAttributes:
  - key: access_logs.s3.enabled
    value: "true"
  - key: access_logs.s3.bucket
    value: log-bucket
  - key: access_logs.s3.prefix
    value: shared-services-prod
  - key: deletion_protection.enabled
    value: "true"
  scheme: internet-facing
  subnets:
    ids:
    - subnet-1
    - subnet-2
```

**Expected Behavior**

Should create 2 listeners attached to the load balancer that gets provisioned and / or let us add a default action. This way we can redirect traffic to the 443 port.

**Actual Behavior**

Creates the 443 HTTPS listener only.

**Current Workarounds**

Note, as a workaround, i've added these annotations to the ingress for my project and it works  
```yaml
annotations:
    alb.ingress.kubernetes.io/listen-ports: [{"HTTP": 80}, {"HTTPS": 443}]
    alb.ingress.kubernetes.io/ssl-redirect: 443
```

**Environment**
- AWS Load Balancer controller version: v2.13.2
- Kubernetes version: 1.33.0
- Using EKS (yes/no), if so version?: Yes, automode - (It's working fine with the ELBv2 CRDs) - and this aws-load-balancer-controller doesn't seem to support automode as the crds are hardcoded for ELBv2 [Reference](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/release-2.13/helm/aws-load-balancer-controller/templates/ingressclass.yaml#L12)
- Using Service or Ingress: Ingress
- AWS region: eu-west-1
- How was the aws-load-balancer-controller installed: argocd -> helm
- Current state of the Controller configuration:
  - `kubectl -n <controllernamespace> describe deployment aws-load-balancer-controller`

```text
(⎈|shared-services-prod:kube-system)➜  ami-soundboardai-llm git:(unittests) k describe deployments.apps aws-lb-external-controller
Name:                   aws-lb-external-controller
Namespace:              kube-system
CreationTimestamp:      Wed, 04 Jun 2025 13:36:18 -0400
Labels:                 app.kubernetes.io/instance=aws-lb-controller-external
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=aws-lb-external-controller
                        app.kubernetes.io/version=v2.13.2
                        argocd.argoproj.io/instance=aws-lb-controller-external
                        helm.sh/chart=aws-load-balancer-controller-1.13.2
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app.kubernetes.io/instance=aws-lb-controller-external,app.kubernetes.io/name=aws-lb-external-controller
Replicas:               2 desired | 2 updated | 2 total | 2 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/component=controller
                    app.kubernetes.io/instance=aws-lb-controller-external
                    app.kubernetes.io/name=aws-lb-external-controller
  Annotations:      prometheus.io/port: 8080
                    prometheus.io/scrape: true
  Service Account:  aws-lb-external-controller
  Containers:
   aws-load-balancer-controller:
    Image:       public.ecr.aws/eks/aws-load-balancer-controller:v2.13.2
    Ports:       9443/TCP, 8080/TCP
    Host Ports:  0/TCP, 0/TCP
    Args:
      --cluster-name=shared-services-prod
      --ingress-class=external
      --aws-region=eu-west-1
      --aws-vpc-id=vpc-<guid>
      --disable-ingress-class-annotation=true
      --default-target-type=ip
      --load-balancer-class=external
    Liveness:     http-get http://:61779/healthz delay=30s timeout=10s period=10s #success=1 #failure=2
    Readiness:    http-get http://:61779/readyz delay=10s timeout=10s period=10s #success=1 #failure=2
    Environment:  <none>
    Mounts:
      /tmp/k8s-webhook-server/serving-certs from cert (ro)
  Volumes:
   cert:
    Type:               Secret (a volume populated by a Secret)
    SecretName:         aws-lb-external-controller-tls
    Optional:           false
  Priority Class Name:  system-cluster-critical
  Node-Selectors:       <none>
  Tolerations:          <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   aws-lb-external-controller-7db96c8fd8 (2/2 replicas created)
Events:          <none>
```
- Current state of the Ingress/Service configuration:
  - `kubectl describe ingressclasses`
```bash
(⎈|shared-services-prod:kube-system)➜  ami-soundboardai-llm git:(unittests) k describe ingressclass external
Name:         external
Labels:       app.kubernetes.io/instance=aws-lb-controller-external
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=aws-lb-external-controller
              app.kubernetes.io/version=v2.13.2
              argocd.argoproj.io/instance=aws-lb-controller-external
              helm.sh/chart=aws-load-balancer-controller-1.13.2
Annotations:  <none>
Controller:   ingress.k8s.aws/alb
Parameters:
  APIGroup:  elbv2.k8s.aws
  Kind:      IngressClassParams
  Name:      external
Events:      <none>
```
  - `kubectl -n <appnamespace> describe ingress <ingressname>`
```bash
(⎈|shared-services-prod:kube-system)➜  ami-soundboardai-llm git:(unittests) k describe ingress -n atlantis atlantis
Name:             atlantis
Labels:           app=atlantis
                  argocd.argoproj.io/instance=atlantis
                  chart=atlantis-5.17.2
                  helm.sh/chart=atlantis-5.17.2
                  heritage=Helm
                  release=atlantis
Namespace:        atlantis
Address:          <EXTERNAL-ALB-URL>.amazonaws.com
Ingress Class:    external
Default backend:  <default>
Rules:
  Host                  Path  Backends
  ----                  ----  --------
  atlantis.<DOMAIN>
                        /   atlantis:80 (10.97.146.39:4141)
Annotations:            alb.ingress.kubernetes.io/listen-ports: [{"HTTP": 80}, {"HTTPS": 443}]
                        alb.ingress.kubernetes.io/ssl-redirect: 443
Events:
  Type    Reason                  Age                 From     Message
  ----    ------                  ----                ----     -------
  Normal  SuccessfullyReconciled  26m (x3 over 148m)  ingress  Successfully reconciled
```
  - `kubectl -n <appnamespace> describe svc <servicename>`
```bash
(⎈|shared-services-prod:kube-system)➜  ami-soundboardai-llm git:(unittests) k -n atlantis describe svc atlantis
Name:                     atlantis
Namespace:                atlantis
Labels:                   app=atlantis
                          argocd.argoproj.io/instance=atlantis
                          chart=atlantis-5.17.2
                          helm.sh/chart=atlantis-5.17.2
                          heritage=Helm
                          release=atlantis
Annotations:              <none>
Selector:                 app=atlantis,release=atlantis
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       172.20.80.224
IPs:                      172.20.80.224
Port:                     atlantis  80/TCP
TargetPort:               4141/TCP
NodePort:                 atlantis  31340/TCP
Endpoints:                10.97.146.39:4141
Session Affinity:         None
External Traffic Policy:  Cluster
Internal Traffic Policy:  Cluster
Events:                   <none>
```
**Contribution Intention (Optional)**

- [ ] Yes, I'm willing to submit a PR to fix this issue
- [X] No, I cannot work on a PR at this time

**Additional Context**
