### ISSUE TITLE
Subnet Discovery doesn't work for internet-facing Frontend NLB if ALB is internal

### ISSUE THREAD

**Issue by andrea-gelati** [kubernetes-sigs/aws-load-balancer-controller#4246]
**Bug Description**
Subnet Discovery doesn't work for a [Frontend NLB](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/annotations/#enable-frontend-nlb) with 'internet-facing' scheme if scheme of the related ALB instance is defined as 'internal'.

**Steps to Reproduce**
Ingress resource defines following annotations:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xxxxx
  namespace: yyyyy
  annotations:
    external-dns.alpha.kubernetes.io/hostname: alb01.example.com
    alb.ingress.kubernetes.io/load-balancer-name: alb01
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":{ "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-path: /ping
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port 
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/certificate-arn: arn_cert
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/enable-frontend-nlb: true
    alb.ingress.kubernetes.io/frontend-nlb-scheme: internet-facing
    alb.ingress.kubernetes.io/frontend-nlb-healthcheck-port: 443
    alb.ingress.kubernetes.io/frontend-nlb-healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/frontend-nlb-healthcheck-path: /ping
    kubernetes.io/ingress.class: alb
spec:
  ...
```

**Expected Behavior**
- NLB placed in the public discovered subnets
- ALB placed in the private discovered subnets

**Actual Behavior**
Both instances (NLB and ALB) are placed in the internal (private) discovered subnets,

**Current Workarounds**
Set explicit subnet ids for fronted NLB using annotation` alb.ingress.kubernetes.io/frontend-nlb-subnets`

**Environment**
- AWS Load Balancer controller version: 2.13.3
- Kubernetes version: 1.32
- Using EKS (yes/no), if so version?: yes, 1.32
- Using Service or Ingress: Ingress
