### ISSUE TITLE
The aws-load-balancer-controller-role role seems to be missing the ability to patch loadbalancerconfigurations

### ISSUE THREAD

**Issue by timothy-spencer** [kubernetes-sigs/aws-load-balancer-controller#4247]
**Bug Description**
The aws-load-balancer-controller-role role seems to be missing the ability to patch loadbalancerconfigurations.

**Steps to Reproduce**
I just updated to the latest helm chart (1.13.3) and tried re-applying all my gateway-related resources.  The first resource that I applied was one that should set up an ALB:
```
---
apiVersion: gateway.k8s.aws/v1beta1
kind: LoadBalancerConfiguration
metadata:
  name: gitlab-http-config
spec:
  scheme: internet-facing
  listenerConfigurations:
    - protocolPort: HTTP:443
```

It applies, but the lb controller logs say this:
```
{"level":"error","ts":"2025-06-26T18:16:15Z","msg":"Reconciler error","controller":"aws-lbc-loadbalancerconfiguration-controller","object":{"name":"gitlab-http-config","namespace":"gitlab2"},"namespace":"gitlab2","name":"gitlab-http-config","reconcileID":"87d46899-913e-4c3a-8471-9c1866e4b65a","error":"loadbalancerconfigurations.gateway.k8s.aws \"gitlab-http-config\" is forbidden: User \"system:serviceaccount:kube-system:aws-load-balancer-controller-sa\" cannot patch resource \"loadbalancerconfigurations\" in API group \"gateway.k8s.aws\" in the namespace \"gitlab2\""}
```

**Expected Behavior**
I expected this to apply and for there not to be errors in the logs.  I have been having problems with other things (see #4245), and it is possible that this is contributing to this, or at least masking the real problem.

**Actual Behavior**
The controller is not able to do it's job, so everything gateway related is not quite working.

**Regression**
Was the functionality working correctly in a previous version ? [Maybe]

I didn't see the log messages until I upgraded to the latest helm chart (1.13.3).  It may have been having this problem without logging in 1.13.2, and I don't think that I was having any problems in 1.10.0, though I'm pretty sure that other things were not working there.

**Current Workarounds**
I don't think there are any workarounds.

**Environment**
- AWS Load Balancer controller version: 2.13.3
- Kubernetes version: 1.33
- Using EKS (yes/no), if so version?: Yes, 1.33
- Using Service or Ingress:  Gateway
- AWS region: us-west-2
- How was the aws-load-balancer-controller installed:  We used the argocd helm app to install it with these values
```
createNamespace: true
enableCertManager: true
priorityClassName: system-cluster-critical
serviceAccount:
  create: true
  name: aws-load-balancer-controller-sa
podDisruptionBudget:
  maxUnavailable: "10%"
securityContext:
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: RuntimeDefault
tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
  - key: ondemand
    operator: Equal
    value: "true"
    effect: NoSchedule
resources:
  requests:
    cpu: 10m
    memory: 100Mi
  limits:
    memory: 100Mi
controllerConfig:
  featureGates:
    NLBGatewayAPI: true
    ALBGatewayAPI: true
```
- Current state of the Controller configuration:
```
Name:                   aws-load-balancer-controller
Namespace:              kube-system
CreationTimestamp:      Fri, 07 Jun 2024 16:34:23 -0700
Labels:                 app.kubernetes.io/instance=aws-load-balancer-controller
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=aws-load-balancer-controller
                        app.kubernetes.io/version=v2.13.3
                        argocd.argoproj.io/instance=aws-load-balancer-controller
                        helm.sh/chart=aws-load-balancer-controller-1.13.3
Annotations:            deployment.kubernetes.io/revision: 17
Selector:               app.kubernetes.io/instance=aws-load-balancer-controller,app.kubernetes.io/name=aws-load-balancer-controller
Replicas:               2 desired | 2 updated | 2 total | 2 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/instance=aws-load-balancer-controller
                    app.kubernetes.io/name=aws-load-balancer-controller
  Annotations:      kubectl.kubernetes.io/restartedAt: 2025-06-11T21:48:49Z
                    prometheus.io/port: 8080
                    prometheus.io/scrape: true
  Service Account:  aws-load-balancer-controller-sa
  Containers:
   aws-load-balancer-controller:
    Image:           public.ecr.aws/eks/aws-load-balancer-controller:v2.13.3
    Ports:           9443/TCP, 8080/TCP
    Host Ports:      0/TCP, 0/TCP
    SeccompProfile:  RuntimeDefault
    Args:
      --cluster-name=tspencertest
      --ingress-class=alb
      --aws-region=us-west-2
      --aws-vpc-id=vpc-08291ee586de1ce4e
      --feature-gates=ALBGatewayAPI=true,NLBGatewayAPI=true
    Limits:
      memory:  100Mi
    Requests:
      cpu:        10m
      memory:     100Mi
    Liveness:     http-get http://:61779/healthz delay=30s timeout=10s period=10s #success=1 #failure=2
    Readiness:    http-get http://:61779/readyz delay=10s timeout=10s period=10s #success=1 #failure=2
    Environment:  <none>
    Mounts:
      /tmp/k8s-webhook-server/serving-certs from cert (ro)
  Volumes:
   cert:
    Type:               Secret (a volume populated by a Secret)
    SecretName:         aws-load-balancer-tls
    Optional:           false
  Priority Class Name:  system-cluster-critical
  Node-Selectors:       <none>
  Tolerations:          CriticalAddonsOnly op=Exists
                        ondemand=true:NoSchedule
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  aws-load-balancer-controller-79bc9f8bd6 (0/0 replicas created), aws-load-balancer-controller-7576bdcf7b (0/0 replicas created), aws-load-balancer-controller-577c6cc4df (0/0 replicas created), aws-load-balancer-controller-6dbcc88dd7 (0/0 replicas created), aws-load-balancer-controller-796c895667 (0/0 replicas created), aws-load-balancer-controller-78589869bf (0/0 replicas created), aws-load-balancer-controller-74f66c9c6f (0/0 replicas created), aws-load-balancer-controller-5b8f876894 (0/0 replicas created), aws-load-balancer-controller-858485f84b (0/0 replicas created), aws-load-balancer-controller-8f779fccc (0/0 replicas created)
NewReplicaSet:   aws-load-balancer-controller-7dfc49c98d (2/2 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  31m   deployment-controller  Scaled up replica set aws-load-balancer-controller-7dfc49c98d from 0 to 2
```
- Current state of the Ingress/Service configuration:
```
Name:         gitlab-http-config
Namespace:    gitlab2
Labels:       argocd.argoproj.io/instance=gitlab2-extras
Annotations:  <none>
API Version:  gateway.k8s.aws/v1beta1
Kind:         LoadBalancerConfiguration
Metadata:
  Creation Timestamp:  2025-06-26T17:15:21Z
  Generation:          1
  Resource Version:    422385653
  UID:                 afc63aa4-892a-48db-bde2-c6f45d4942ef
Spec:
  Listener Configurations:
    Protocol Port:  HTTP:443
  Scheme:           internet-facing
Events:             <none>
```
**Possible Solution (Optional)**
I am pretty sure that if you add patch to https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/helm/aws-load-balancer-controller/templates/rbac.yaml#L94 that it will fix the problem.

**Contribution Intention (Optional)**
- [X] Yes, I'm willing to submit a PR to fix this issue
- [ ] No, I cannot work on a PR at this time
