### ISSUE TITLE
ALB Ingress Controller not reconciling load-balancer-attributes on ingress/service annotation update

### ISSUE THREAD

**Issue by bilby91** [kubernetes-sigs/aws-load-balancer-controller#898]
Hello,

We've been debugging a problem while updating an ingress load-balancer-attributes annotation and we think the controller is not working correctly.

When updating `alb.ingress.kubernetes.io/load-balancer-attributes` on a given ingress, the controller detects the change but doesn't reconcile the changes with the ALB. Only if the controller pods are recreated, the ALB is correctly updated.

We've been able to verify this behaviour by increasing the controller verbosity with `-v 5` and also turning on `--aws-api-debug`.

**Comment by JoaquinScript** [comment]
I just enable logging and deletion protection and the ALB is not reflecting the update.

**Comment by M00nF1sh** [comment]
Hi, which version are u using? There is known issue in older versions but should work fine in v1.1.2

**Comment by opklnm102** [comment]
@M00nF1sh Could you tell me where i can find the known issue...?

**Comment by wjrogers** [comment]
Just experienced the same problem: added `alb.ingress.kubernetes.io/load-balancer-attributes` to an existing Ingress resource, but the change was not applied to the ALB until I restarted the aws-alb-ingress-controller pod. (Thanks for that workaround.)

**Comment by nitrag** [comment]
Also seeing this:
Related?
```
 kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile targetGroups due to failed to load serviceAnnotation due to no object matching key \"master/jobservice\" in local store"  "controller"="alb-ingress-controller" "request"={"Namespace":"master","Name":"pv-ingress"}
```

**Comment by srirajan** [comment]
I'm seeing the same behaviour. Version is 1.1.2.  Restarting the pod seems to enable some of the required configuration. However, it is still not doing all I wanted. In the example below, I have a few, but it only seems to set some on every restart. Also, with access logs, I am not seeing the desired behaviour. It just seems to ignore it and not configure it.  Using --v=5 does not show much in terms of debug info. Happy to share more details if required. 

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=false
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=300
    alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
```
